== Introduction

When those who have, through the varied trials and temptations of time,
been driven nearer and nearer to the fountain of purity and love; whose course,
as it draws towards its close, shines more and more unto the perfect day,
are called home to the mansions of everlasting blessedness whilst in
the midst of the fulness of their usefulness on earth,
the church feels the loss, and amidst the sorrow that oppresses,
it oftentimes becomes the duty of the bereaved, for the benefit of survivors,
to preserve some memorial of the humble, obedient walking of the departed,
and of the faithfulness of the Lord,
whose all-sustaining presence has been with them to the end.

We would gather up such fragments as remain,
to testify of the inward exercises and outward trials,
the fervent labours and faithful dedication of our dear departed parent and brother,
Thomas Kite.
Remembering him in the varied relations of life which
he so conscientiously filled:--the sustaining husband,
the carefully concerned father, the helping brother, the sympathizing friend,
the faithful minister, we feel the poignancy of individual bereavement,
and the depth of the church`'s loss.

In the oft renewed sorrow of our hearts we could lament and weep,
but that we know that the Judge of all the earth
does everything in faithfulness and truth,
and that all is well with him, whom He hath gathered from amongst us.
We see him not, but from the habitation prepared for him in his Heavenly Father`'s house,
he calleth us, by the remembrance of his holy, humble walking amongst men,
by the recollection of his earnest travail of spirit for our everlasting welfare,
to follow him in the lowly path he trod, to blessedness and peace.
If we are faithful, his God will be our God forever and ever;
He will be our Guide even unto death.
We remember how we have heard him testify in Gospel authority, to the holy,
consoling truth, that the dedicated followers of the Lamb have the privilege of coming,
in sweet unity of feeling, even whilst on earth, "`Unto Mount Zion,
unto the city of the Living God, the heavenly Jerusalem,
and to an innumerable company of angels,
to the general assembly and church of the first-born which are written in heaven,
'`and to Jesus the Mediator of the new covenant.`"
Can we not in earnest travail of spirit seek more and more to attain this blessed unity?
With hearts tenderly touched at the remembrance of the dear
departed one--with hearts elevated with thankfulness to the
God who redeemed him from the corruptions of this world,
let us turn to the records of his life.
Therein we shall find the follies of youth and its sins manifested,
and the mercy of God in Christ Jesus which pardoned them all;
the imperfect obedience of riper years set forth, repented of and forgiven;
the faithful dedication of heart,
and the peaceful and happy end permitted by infinite
Goodness as a crown to the tribulations of life.

These pages bear testimony to many earthly blessings and
comforts showered down around the way of the pilgrim,
yet are they a record of trials and baptisms,
of a preparation,`' through sorrow for unmingled joy.

These memoirs of my dear father were prepared by his family soon after his death,
and now, after a lapse of some years,
it has been a labour of love to revise them for the press.
The revival of the memories of his earnest,
loving labours for his family has been very precious.
May the readers of this little volume be comforted and strengthened by the perusal
of these records of his fervent Christian zeal for his dear Lord and Master,
to press heavenward with the same dedication of heart.

William Kite.German-town, Philadelphia, 1883.
