== Chapter I.

[.chapter-synopsis]
* 1785-1806.
* Early Religious Impressions
* Commenced A Diary
* Yellow Fever of 1803
* Letter to his Brother Joseph
* Diary Letter from a Friend.

+++[+++Thomas Kite, the eldest son of Benjamin and Rebecca Kite, was born in Frankford,
Philadelphia, on the 16th of the Seventh month, 1785.
When he was about two years of age a cap of strong lye
being left upon a chair within his reach,
he seized it with childish eagerness, and swallowed a copious draught.
His mother, turning round, found him with the cup in his hand,
and perceived at a glance what he had clone.
She felt that an agonizing death must speedily
follow if a remedy were not instantly applied.
A moment of suspense and her eye fell upon the oil can.
With promptitude and decision, which ever marked her character,
she took the child in her arms, opened his mouth,
and poured down his throat a large draught of the oil.
Entering into combination with the lye in his stomach it changed its character, and,
in the judgment of the physician, saved the life of her first born.
Nevertheless, the effect upon his constitution was severe, and for many subsequent years,
he was weak and sickly; so much so, indeed,
as to interfere considerably with his attendance at school.
But his parents taught him early to read, for which he imbibed a taste,
and with little regular education, he acquired a large fund of general knowledge.

In 1792 his parents removed with their family to Philadelphia,
and as his health continued still unequal to the confinement of school duties,
he made long visits in the country amongst his relatives.
His strength gradually increased,
and in 1800 he was placed apprentice with
Benjamin Johnson to learn the printing business.

Respecting the early part of his life Thomas Kite thus writes:]

[.small-break]
'''

Though favoured with religious parents, my early years were marked with many follies;
yet the Lord followed me with the convictions of his Holy Spirit,
which were too often slighted.
In my fifteenth year, being placed apprentice,
I became exposed to the influence of bad example,
and the usual contaminating effects followed.
I desire that some of the transactions of those times
may fill me with humiliation and self-abhorrence,
and that I may ever retain a sense of my unspeakable obligations to the Lord Almighty,
who did not cut me off in my transgressions,
but favoured me with a powerful visitation in the seventeenth year of my age.
In one of our meetings a Friend +++[+++his uncle John Letchworth]
offered a few words in testimony, being the first time of his appearing in that line.
I could not distinguish one word he uttered,
being some distance from him in the youth`'s gallery,
yet impressions of a serious character were then made,
which never afterwards entirely left me: convictions for sin,
desires for deliverance from its guilt and power,
and that I might experience conversion to God.

After enduring for a season the dispensation of condemnation,
I believe I was favoured with the gift of repentance,
and enabled to enter into covenant with the Lord.
I gave up the society of associates who had been a snare to me;
sat alone and kept silence; endeavoured to keep a guard over my words and actions;
kept close to religious meetings, seeking to have my mind stayed upon God;
and was sometimes livingly favoured of Him, both immediately and instrumentally.

For want of greater watchfulness, I too often missed my way,
but met with merciful chastisements, and being thereby humbled,
I was again admitted to favour.

[.small-break]
'''

+++[+++Being, through Divine mercy,
thus thoroughly aroused from the state of carnal security in which he had been living,
Thomas Kite endeavoured to be faithful to the requirings of his Heavenly Father.
He became earnestly concerned to attend religious meetings,
and was conscientiously scrupulous that his master should be no sufferer by it.
Having a daily task allotted, he was enabled by diligence, and working in the evenings,
to make up his full quota,
though he not unfrequently attended other meetings than his own.
He endeavoured to be circumspect in life and conversation,
yet he had much to contend against in his natural inclinations and dispositions,
and was often brought into deep humiliation in
the retrospect of his daily walk before men.
He now sought to spend his leisure hours in the company
of those who were seeking the way to Zion.
His uncle, John Letchworth,
who was then passing through baptisms consequent on a call to the ministry,
he delighted to visit.
Mary Harper, a valuable elder of Frankford Meeting,
was also one with whom he could enjoy sweet fellowship,
and from whose counsel and religious advice he derived benefit.
One of her communications, under date of Eighth month 4th, 1802, contains this passage:]

[.embedded-content-document.letter]
--

I am informed thou art often conversant with dear uncle John Letchworth, who, I hope,
is in the road to that glorious place where there it neither sorrow nor crying.
I have often thought it would be well if the youth more generally were to spend
their leisure hours with those advanced in age and religious experience.

--

+++[+++After wading along through many spiritual depths in the summer and fall,
without attaining that stability his soul longed for, Thomas Kite concluded,
in the Twelfth month, as one means of improvement, to commence keeping a diary.
He thus explains at the opening his motives in the undertaking.]

[.small-break]
'''

"`Convinced of the necessity of watchfulness and circumspection,
I have resolved daily to pen down such events as impress my mind, that,
by a frequent review of them, under the Divine blessing, I may endeavour to improve.

Twelfth month 12th. Too willing to listen to reports to the disadvantage of my neighbours.
"`Thou shalt love thy neighbour as thyself.`"

13th. At meeting, Northern District,
thought the meeting was hurt by one or more injudicious appearances.
Nothing but what proceeds from God can gather to God.
He maketh his angels spirits and his ministers a flame of fire.

14th. Temper ruffled.
Lord give me meekness!
Soul, dost thou not endeavour to shut thy ears against the
voice of Christ when He opposes thy corrupt will?
Lord, destroy the root of self in me!
A day of weakness.

10th. At meeting: desirous of being inwardly gathered, yet too unwatchful.

16th. Preserve me, O Lord, from every taint of envy.
Evil thoughts.
How desirable is a well regulated mind,
even that state in which every thought is brought into captivity to Christ.

17th. Heard of the appearance in the ministry of a youth about as old as myself.
Made a person angry.
Preserve me, O Lord, from putting a stumbling block in another`'s way.

18th. Beware of detraction.
At three meetings, in each of which the goodness of the Lord was conspicuous.
Awake, my soul, to greater diligence, and make thy calling and election sure.

20th. At North Meeting.
Light and life mercifully afforded.
Exceeded in conversation.
Guard thy tongue.

21st. At Pine Street Meeting.
Oh for a more deep ingathering.
Thoughts wandering and unsettled.

22nd. None, however large their religious experience, are safe when off the watch.
Be thou careful, oh, my soul!
Oh, how noble the simplicity of truth!
How consistent throughout is the character of the humble-minded Christian!

[.offset]
+++[+++A few of the succeeding pages of his diary have been destroyed or lost.
The next entry found is about the close of the Third month, 1803.]

At an evening meeting light and truth prevailed
and the gospel trumpet was powerfully blown.
Lord, grant that I may finally enter into that everlasting sheep-fold of rest,
which was testified of this evening by thy servants.

Fourth month.
At a week-day meeting.
A sweet covering of solemnity.
Martha Routh encouraged the young men, and quoted the example of William Dewsbury,
a bright son of the morning, who was a weaver s apprentice.
Oh that I might experience a little of that spirit
which gathered our ancestors to the power of Truth!
Make my heart tender and thankful, O Lord, for the renewings of thy tender mercies.

Yearly Meeting.
A remarkably weighty baptizing season, on the state of Society.

Meeting for worship.
The Gospel labourers engaged on account of the youth in earnest travail of spirit.

Yearly Meeting closes, having been favoured, during the several sittings,
to experience the fatherly regards of the Holy Head of the Church.
This short testimony was revived in the conclusion: "`Jesus, having loved his own,
loved them unto the end.`"

Fifth month.
Quarterly Meeting.
The covering of solemnizing love was felt.
O Lord, convince my obdurate heart.
Meeting.
Gospel calls to the youth.
Awake, my soul!
Something of the Divine presence felt, calming and solemnizing the mind.
A severe mortification.
Oh!
Lord, withdraw me from depending on the world for consolation.

Sixth month.
Having had thoughts for some time of attending Westfield Preparative Meeting,
I accomplished it in company with dear +++_______+++. In the first meeting he was
enabled to speak of and open the prophet`'s visit to the potter`'s house;
recommending our becoming as clay in the Great Potter`'s hand,
as well as mentioning the necessary operations of forming, drying, hardening,
and passing through the furnace.
In the meeting for business he had likewise considerable pertinent advice to communicate;
and a lively meeting it was upon the whole.
Several of the youth of that meeting seem hopeful.
Having lately perceived that many of my faults seem to increase,
and the old inhabitants of the land to get the victory almost daily, I hope to endeavour,
with Divine assistance, to keep up the watch more circumspectly.
O Lord! bring every secret thought into judgment.
Purify my soul, I pray thee, if consistent with thy holy will, amen!
Tried to learn silence.

Seventh month 16th. My birth-day.
I am eighteen years old.
Oh thou eternal Creator of the world, enable me, a poor, weak worm,
yet the workmanship of thy holy hands, to solicit thee, with sincerity of heart,
for a continuance of thy manifold mercies.
Pass by my backslidings, forgive my revoltings, cleanse, purge and purify me,
in the laver of regeneration, through Jesus Christ, the Lamb immaculate,
the blessed Advocate for sinners.
Oh God!
I beseech thee, enable me implicitly to bow to thy holy direction!
Let me feel the language of "`Thy will be done,`" in the depths of my soul.
Let me be in thy hands as clay in the hands of the potter.
Preserve me from hypocrisy.
Let me not take up a rest short of the true rest,
but enable me to press forward toward the mark,
in humble hope of forgiveness through the blood of a crucified Redeemer.
And oh, my Almighty Maker, if consistent with thy will,
bring me into union and communion with thee, and the Son of thy bosom, to whom,
with thee, belongs worship, adoration and praise.
Hosanna in the highest.
Amen.

27th. O Lord, grant me to make war in righteousness against my spiritual enemies.
Ninth month.
By the admission of a new journeyman into my master`'s house,
I am exposed to much immoral conversation, swearing,
and taking the name of the Most High in vain.
From observing my many backslidings, even of late,
though favoured to see my conduct in them inconsistent with the Divine will,
I am jealous and fearful lest I should lose the
little desire I have after spiritual good.
Oh thou unslumbering Shepherd of Israel, preserve me!
May I become one of thy flock, whom thou leadest about in the green pastures of life!
May I go down to the washing pool oft, to be cleansed of the filth of the earth!
May I never fall into the snares of the devouring wolf!
but by constantly endeavouring to follow thee,
and be near thee,
be admitted through the only true door into the sheepfold of everlasting rest and peace.
Amen.

[.small-break]
'''

+++[+++About the time the last memorandum was written,
the yellow fever appeared in Philadelphia,
and although not attended with such mortality as in former years,
it was sufficiently alarming to cause many of the
citizens to seek a temporary refuge in the country.
Benjamin Johnson having closed his printing-office,
gave his apprentices the privilege of visiting among their relations out of town.
He sent Thomas Kite into Bucks County on business, who, after accomplishing it,
being at liberty to go where he would,
spent some time with his grandfather Benjamin Walton,
who was then living in East Fallowfield, Chester County, Pennsylvania.

Whilst he was at Reading, he addressed the following letter to his uncle John Letchworth,
then in the neighbourhood of Muncy, as companion to Annie Mifflin and Mary Gilbert,
who were engaged in a religious visit to Friends in those parts.]

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to John Letchworth

[.signed-section-context-open]
Reading, Ninth month 23rd, 1803.

[.salutation]
Beloved Uncle,

I am here on business for my master,
and supposing a letter may reach thee previous to thy return,
I can inform thee that thy family were well the day before yesterday.
Thy two apprentices, through fear of the fever, had left the city,
and John Folwell has offered aunt part of his country house,
if she would esteem it proper to remove from the city.
The yellow fever continues, but not in such an alarming manner as in some former years.
Four or five new cases occur daily, and sometimes more.
Father`'s school has been broken up, and my master`'s family have removed into the country.
Before my departure from Philadelphia our meetings were very small;
many Friends having removed into the country, especially such as lived near the water.

If this letter should reach thee seasonably,
wilt thou please to remember my love to thy dear fellow travellers,
Anne Mifflin and Mary Gilbert.

Wishing thee Light and Life in thy toilsome journey,
and the reward of that peace which the world can neither give nor take away,
I subscribe myself thy affectionate nephew,

--

[.signed-section-signature]
Thomas Kite.

[.offset]
+++[+++During this visit in Chester County he had an opportunity, for a short time,
of accompanying his old friend Peter Andrews, who was visiting the meetings there.
Under date of Ninth month 30th, his mother thus wrote to him.]

[.embedded-content-document.letter]
--

[.salutation]
Dear Thomas,

We had a small meeting this day, but to me it was a good one.
We had the company of Thomas Scattergood and William Savery,
which added strength to some,--at least to my mind.
Dear Sarah Harrison asked for and received a
certificate to attend Baltimore Yearly Meeting.
The loss of her company at this time seems trying, the galleries are so stripped.
I may say the whole house, for there is but here and there a solitary person sitting.

--

[.offset]
+++[+++Benjamin Kite added this postscript:]

[.embedded-content-document.letter]
--

As thy mother refers to me for an account of thy uncle`'s letters,
I shall briefly inform thee, that he seemed nearly worn out riding on horseback.
He mended as he went on, and seems to be preserved in faith and patience,
and in measure experiences, as he expresses it, the mountains to skip like rams,
and the little hills like lambs.
About the 22nd he left Muncy with his companions on their way to Cerestown, etc.
Anne supports her travel like a good soldier, as we expected;
poor Mary cannot endure so much; therefore they ride but about three miles an hour.
In one of the letters thy uncle addresses himself to each of his children particularly,
giving them very seasonable and pertinent advice, which I hope may not be lost.

Upon the whole I think the sickness rather increases, yet but slowly.
Mary Budd has been twice reported to be dead, but was alive at noon.
Whether she continues alive is doubtful.
If she has gone, I trust it is in innocency.

--

[.offset]
+++[+++The first entry made by Thomas Kite in his diary, after his return from the country,
is under date of Twelfth month 23rd. Reminded two Friends of the necessity of silence.
Teacher teach thyself.]

30th. Of late I am much given to lightness.
Beware of vain jesting.

1804+++.+++ First month 1st. At three meetings.
The first two painful, but Life and Light shone in the last.
The youth were invited and encouraged to take
the yoke of Christ upon them and learn of Him,
the meek and lowly Jesus.

8th. Evening meeting.
The gospel trumpet powerfully blown by a dignified instrument.
Attend the call! 10th. Beware of equivocation: oh, the noble simplicity of the truth.

19th. At meeting.
A female revived the promise "`Thine eye shall see Jerusalem, a quiet habitation.`"
How desirable is this solemn covering of quietude and
peaceful assurance which we cannot command of ourselves!
How refreshing to the weary, exercised,
drooping mind! 20th. How corrupt is my heart! "`Who
shall deliver me from the body of this death?`"
My soul,
apply to Him who was never foiled in battle! 24th. When
the sense of Divine Life is low in my mind,
oh may I endeavour to keep low with it, like Mordecai,
who had been exalted and rode upon the king`'s horse; yea,
his very enemy proclaimed "`This is the man whom the
king delighted to honour,`" yet after all this,
he was willing to descend and wait as before, at the king`'s gate.

27th. At meeting.
Sarah Talbot, a mother in our Israel,
opened a variety of states with clearness and precision;
administering reproof and invitations to the disobedient,
as well as encouragement to the honest-hearted.

Monthly Meeting.
A searching season on the Queries.
Much close advice communicated and the youth invited
and encouraged to come forward in faithfulness.

Fourth month.
Yearly Meeting.
Second-day:
the reading of the Queries occasioned some lively remarks from exercised minds,
tending to stir up to greater diligence and faithfulness in what many deem little things,
but which were shown materially to affect the cause and testimony of Truth;
particularly tale-bearing, and reading pernicious publications.

Third-day.
This morning some precious remarks were addressed to the youth.
Nathan Hunt, in a short, powerful testimony,
opened the passage of scripture respecting the league of Solomon and Hiram,
and the cutting of timber in the mountains for the building of the temple at Jerusalem.

The reading of two memorials appeared to increase the solemnity of the meeting.
One of them was concerning a youth of eighteen.
May the example of those young persons who have given
their names to serve the God of Israel stir us up,
who are too negligent, to greater diligence in making our calling and election sure.

Fifth-day.
Meeting for worship.
James Simpson addressed the youth.
His heart seemed drawn forth in affectionate desire and his soul appeared
earnestly to implore that they might indeed become the children of God.
He entreated those who had been brought out of Egypt, and had traversed the wilderness,
not to encamp on this side Jordan, but to pass over, sword in hand,
to subdue their enemies and possess the good land which flows with milk and honey,
and yields abundantly corn, wine and oil.

Sixth-day.
The business of the Yearly Meeting this day concluded,
having been favoured during its several sittings, and more especially in the last,
to experience the gracious condescension of the Great Head of the Church,
enabling the members present to transact the weighty
affairs of Society in harmony and love of each other.

[.offset]
+++[+++Having written to his esteemed friend Mary Harper complaining
of the malady of sin which still clave to him,
he received a reply, from which the following is extracted:]

[.embedded-content-document.letter]
--

Through favour I have nearly recovered.
Although pretty well, as to bodily health,
yet not wholly free from the malady the! mentions.
It is for want of a right application to the Great Physician we remain sickly.
I have often thought of thee since I last saw thee;
and notwithstanding there are many snares to entangle the feet of the youth,
I trust thou wilt be preserved whilst thou keeps up the watch.
Remember, the Christian life is a continual warfare.

[.signed-section-signature]
Mary Harper.

--

[.offset]
+++[+++Diary continued.]

1805+++.+++ First month 5th. I have lately been betrayed into
something very much resembling slander.
May the disagreeable feelings which this has occasioned, be a caution to me,
never to speak ill of the absent.

7th. Favoured in our afternoon meeting with the
acceptable company of several ministering Friends,
strangers to me.

Dear Benjamin White, who was also there, stood up with these words:
"`There has something been gathering round my mind, which causes me to say,
Blessed is God; blessed in himself, and in his Son, Christ Jesus our Lord;
blessed without us; complete without us.`"
Proceeding in Gospel authority in a short testimony,
he extended an invitation to the youth,
beseeching them to close in with those heart-tendering visitations with which,
in the present day, they are remarkably favoured.
Not only immediately in the secret of their own minds,
but by the ministry of those messengers whom the Lord hath qualified and is
qualifying and sending forth with the offers of salvation through Jesus Christ.

1805+++.+++ Second month 24th. At three meetings.
In the evening Ann Alexander had the Gospel to proclaim with power and authority.
A secret sense of my own unwillingness to submit to the
restraining influence of the cross of Christ,
painfully affected my mind this day.

25th. I am abundantly convinced by repeated experience,
that there is something alive in my mind, which would, if given way to,
lead me into self-exaltation.
Whilst this principle is nourished,
I believe I shall never be able so to descend into nothingness and abasement
of soul as acceptably to worship the Lord in the beauty of holiness.
Oh that the axe of the Lord`'s power may be laid to the root of this corrupt tree,
that I may vigilantly watch against self in all its various transformations,
and humbly wait to receive strength from the eternal Fountain
of strength to overcome all the enemies of my soul`'s peace;
those of my own household, the evil propensities of my own mind,
the old inhabitants of the land.
Though they may disguise themselves and feign to be something else,
may I be preserved from entering into a league or confederacy with them.
Oh that my soul may persevere under the Captain of Salvation
to wage war in righteousness against these spiritual enemies,
until they are subdued,
and my heart can feelingly adopt the language "`In that
day shall this song be sung in the land of Judah;
we have a strong city, salvation hath God appointed for walls and bulwarks.`"

Third month 9th. The morning meeting unusually favoured,
and several testimonies borne in the authority of Truth.
After meeting I was deficient in neglecting a gentle, secret intimation,
which is now a cause of grief to my mind.
May I become more increasingly willing to submit
everything to the requirings of the Holy One,
and be contented, if it be his will, to be considered a fool.
This life is, and must be, a state of probation; trials must be encountered,
the cross must be borne,
or we shall never be permitted to participate in
those eternal glories with which the Lord,
the righteous Judge,
will crown those who have passed through many tribulations and
have washed their garments in the blood of the Lamb?

18th. The day before yesterday I was again
guilty of neglecting to obey a gentle intimation,
which has introduced my mind into a state of darkness; so that,
though the morning meeting, yesterday,
was eminently favoured with the descendings of heavenly dew, I was poor and dry.
The rebellious dwell in a dry land!
Oh that my heart might be aroused to greater watchfulness;
that I might gird up the loins of my mind, watch and be sober,
that I may be favoured with the gift of deep repentance
for all my rebellions and backslidings,
and that I may indeed be made clean!
And oh, that in deep humility and prostration of soul,
I may at all times ascribe the praise of his own
works to the Almighty Helper of his people,
nor presume to attribute any excellence to myself, who am, indeed,
unworthy of all the mercy and all the truth which He has shown to my soul.
Forsake me not, thou gracious One!
Follow me, O Lord, with the visitations of thy love!
And though I let go my hold on thee, yet be pleased to pity me, a poor worm of the dust,
and exercise thy righteous power for my deliverance from the thraldom of sin.
Oh preserve me, and if consistent with thy blessed will,
create me anew in thy Son Jesus Christ, that my heart may be made pure;
a habitation for thy eternal Spirit to dwell in!

19th. At a favoured meeting at the North House.
Dear George Dillwyn appeared in a short encouraging testimony
addressed to those who wished to be classed on the Lord`'s side.
May those who have enlisted under the banners of the Great King,
and received his bounty-money, never desert the cause, nor presume to advance to battle,
without first receiving the word of command.

At dinner at my father`'s had the acceptable company of
three dear female labourers in the gospel vineyard.
Their conversation, and the love I was favoured to feel, afforded satisfaction to my mind.
May I be preserved in humility, and become increasingly united to the members,
and the Holy Head, of the church,
by the cementing influence of that love which is stronger than death.

21st. At our week-day meeting George Dillwyn appeared instructively in testimony:
the difference between an assenter to the doctrines of Christianity,
and a believer in Christ being set forth,
together with the difference between the false rest and
that rest which is prepared for the children of God.

22nd. At uncle John`'s (Letchworth`'s) in the evening, where was also dear Mary Gilbert.
As we sat together in the family, silence unexpectedly took place,
and after some time spent therein, they had each somewhat to communicate.
May those religious opportunities, with which our Society are so remarkably favoured,
be cause of thankfulness to the Author of all good,
and the means of our furtherance in the way of life and salvation.

24th. At morning meeting, several Friends favoured in testimony,
and in the afternoon Arthur Howell in a short arousing testimony,
prophetically declared that a time is approaching in which our foundations will be tried;
exhorting us to build upon that stone which alone stands sure, and which,
whoever builds upon, shall never be confounded.

Fourth month 21st. Last week I attended the several sittings of our Yearly Meeting,
which was large, and at times overshadowed by the wing of Ancient Goodness.
In the close of the last sitting the presence of the Blessed Master being evidently felt,
I trust thanksgivings and praises were ascribed to his name, in the secret of many minds.

Fifth month 4th. Being renewedly sensible that weakness is mine,
and that many impurities still remain in my heart;
and that without the aid of Omnipotence I cannot maintain the spiritual warfare,
I am at this time desirous that I may, on all occasions,
so descend into the valley of humiliation as to receive strength from the Lord,
and witness the arms of my hands to be made
strong by the hands of the mighty God of Jacob.
May I indeed be concerned to bow beneath the rod,
and turn with all my heart unto Him who hath appointed it.
Oh that I may experience forgiveness for my repeated sins of omission and commission;
that my soul may put on Christ Jesus, that I may be found in Him,
and experience his blessed Spirit to cleanse me
from every defilement of flesh and spirit.
The All-seeing One knows what lodges within me,--the evil
propensities of my fallen nature,--all is open before Him.
He knows the temptations that surround--the cunning devices of the grand adversary.
Oh that He may renew to my soul the preserving efficacy of his divine light and love.
Oh that He would be pleased to keep me, an unworthy and rebellious servant,
from the evil that is in the world:
that under his direction and influence I may be enabled to
steer my weak bark through the tempestuous ocean of life,
and having the blessed Pilot on board,
witness a safe arrival at the haven of eternal felicity;
that city which indeed hath foundations, whose builder and maker is God!

7th. Our Quarterly Meeting yesterday was eminently
favoured with the Great Master`'s presence.
In his power and authority dear Ann Alexander was opened in the meeting for worship.
The pure stream of the gospel flowed livingly through her, I believe,
to the refreshment of many minds.
In the meeting for business,
a Friend was several times drawn forth in affectionate entreaties to the young men,
encouraging them to persevere in the way of well-doing.
Oh that the counsel of those deeply baptized messengers
of Christ may make lasting impressions on our minds.
May we ever retain in grateful remembrance the many
benefits conferred upon us by our Almighty Benefactor,
who from time to time is favouring us with the descendings of heavenly dew,
that nourishes and refreshes the plant of renown; the seed of the kingdom,
which He himself hath implanted in our minds!
May the praise and glory of his own work be forever ascribed unto Him.

8th. This evening I violated the golden rule of "`doing unto
others as I would they should do unto me,`" by relating a
circumstance injurious to the character of another,
which it would have been better to have buried in oblivion.
Oh that I may never again be guilty of this vice!

[.small-break]
'''

+++[+++In the latter end of the Third month, 1805,
John Letchworth removed from the city of Philadelphia,
and settled on a farm in East Fallowfield, Chester County, Pennsylvania.
Thomas Kite could not help feeling the loss he sustained by being so
far separated from his sympathizing friend and relative.
As the best substitute for personal intercourse he frequently wrote to his uncle,
and many pleasant tokens of friendly remembrance passed between them.

On the 30th of Fifth month, 1805, he wrote to his uncle:]

[.embedded-content-document.letter]
--

[.salutation]
Dear Uncle:

At our Preparative Meeting today, six or seven new cases were introduced,
and all but one sent forward.
James Pemberton mentioned on the occasion the words of our Saviour,
"`The harvest truly is great,
but the labourers are few,`" adding "`but this is likely to produce a dismal crop!`"
So by this thou canst judge a little how it fares with the rightly concerned among us,
of which number, on the male side of the house, thou knowest we have too few.
It is cause of wonder to me that persons who appear of exemplary lives, and are diligent,
or frequent, attenders of meetings for worship,
should almost wholly neglect those for discipline.
It certainly indicates that something is wanting on their part.
I believe that all those whose minds have been mercifully quickened, have work to do,
according to their different capacities and measures.

--

+++[+++Immediately after Quarterly Meeting in the Eighth month,
Thomas Kite having a vacation allowed him by his master,
accompanied his father on a visit to their relatives in Chester County.
During their absence from home they attended the Quarterly Meeting held at London-grove,
and that at Concord.
Soon after their return the yellow fever again made its appearance in Philadelphia,
but it was of a less malignant type than that of some former years,
and its victims were comparatively few; still some of the cases were quickly fatal,
and much alarm, both in the city and county, prevailed for a time.]

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his uncle John Letchworth.

[.signed-section-context-open]
Philadelphia, Tenth month 21st, 1805.

[.salutation]
Dear Uncle:

Thy letter of yesterday, which I received today, was very acceptable.
The city now wears a more cheerful aspect; our friends have, many of them, returned,
and others are still returning.
Although a few cases of malignant fever occur almost daily,
yet the general health of the city is, I believe, pretty much as usual at this season.
On Seventh-clay the tents (erected for the sick) were removed,
and the encampment broken up.
The hospital on the Schuylkill continues open.
The Board of Health has concluded to grant bills of health as usual from this day forward.

Our meetings have been very small for some time past,
and they were rendered smaller by the circumstance of
five persons having the fever in the widow Kitt`'s house,
at the corner of Strawberry street and Market street.
The widow and her two daughters are both dead.
The son-in-law has recovered, and the girl is recovering.

I suppose thou hast heard the departure of Mary Harper as the companion of Anne Mifflin?
I suppose they are now at Baltimore.
We have heard of a number of Friends going thither,
so that probably their Yearly Meeting has been large.
John Hoskins and daughter, Nicholas Wain, Richard Mott, Elizabeth Coggeshall, etc.

Ruth Richardson has been confined, I think, with gout or cramp in her stomach,
and David Bacon with dropsy.
They are both much better, which seems a pleasing circumstance;
as we can ill afford to part with two of our good folks in such low times as these.
Low times they have been, at least with respect to myself, for some time past.
The future, were it allowable to indulge such thoughts,
might seem a gloomy prospect on several accounts:
the temptations youth are liable to,--some, who ought, from their years and appearance,
to be patterns of circumspect walking, occasionally staying away from meetings,
either induced thereto by business or political discussions, electioneering,
the weight of business at Monthly Meeting, the few upright,
sound pillars to bear that weight,
the apparently increasing lightness instead of solidity of my own mind,
and my unwillingness, yea,
obstinate refusal to submit to that cross which
crucifies us to the world and the world to us;
all these, and many more, are copious subjects for mournful contemplation.
Indeed,
I think country Friends ought to sympathize with the poor citizens in their many trials,
especially thou, who hast so lately made thy escape from amongst us; but trials,
I suppose, thou meets with, even in Fallowfield.

--

[.offset]
+++[+++His brother Joseph, a little boy of ten years of age,
being on a visit to his relatives in Fallowfield, Thomas addressed this letter to him.]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Philadelphia, Tenth month 21st, 1805.

[.salutation]
Dear Brother:

I thought I might write thee a few lines
to convince thee I have not forgotten thee.
I remember thee, and desire that while absent from under thy parents`' notice,
thou may behave with a watchful care and circumspection,`' endeavouring to be modest,
quiet and obliging, industrious in doing what thy friends may have for thee to do,
and attentive to meetings whenever way is made for thee to go.
Don`'t thee remember the words of one of the divine songs:

[verse]
____
What blest example do I find
Writ in the Word of Truth,
Of children that began to mind
Religion in their youth.
____

Young as thou art, dear brother, thou art not too young to be sensible of thy duty,
and that when thou doest well thou feelest more
composed and peaceful than when thou hast behaved amiss.
Love and cherish those calm feelings, and in order to procure them, be good.
Should thou wisely choose the better part in childhood,
and persevere as thou advances in life, the consequence to thyself will be happy indeed,
and pleasing and comfortable to our dear parents,
who have no greater joy than to see their children good and virtuous.
Think on these things when thou goes to bed.

[.signed-section-closing]
From thy loving brother,

[.signed-section-signature]
Thomas Kite

--

[.offset]
+++[+++Diary continued:]

Third month, 1806.
Although my mind during several of the preceding
months has been much in a state of dryness,
and to myself I seem to make but little progress on my heavenly journey,
yet have I cause to acknowledge with grateful emotions the kindness of the Father
of Mercies in touching a deeply baptized minister with a sense of my condition,
and leading him to administer thereto, not only in his public communications,
but in private conferences with me alone.
In these last he has pointed out the peculiar trials which await me,
and informed me that his prayers had been put up for my preservation.
Ah, may I, by patiently abiding under every dispensation meted out in unerring wisdom,
be preserved in an humble dependence on that Almighty Arm of power which
alone can lift the mind above the propensities of our fallen nature,
and enable us to persevere in the Christian life.

[.offset]
+++[+++Having written to this Friend, he received the following answer:]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Wilmington, Third month 25th, 1806.

Now my dear friend, Thomas Kite, I can inform thee +++[+++that]
before I received thy very precious letter,--for so it is to
me--I had been feeling and sympathizing for and with thee.
I well know thy poor mind is frequently tossed as with a tempest, and not comforted.
It will be so, I believe, for a season.
I see clearly, to my comfort,
thy tabernacle will be surrounded by the
guardian angel of thy Heavenly Father`'s presence.
Be comforted, and put on strength in his blessed name.
He will fight all thy battles for thee if thou art but really resigned to his divine will.

--

+++[+++Diary:] Fourth month 1st. Great is the necessity of silence and self-recollection.
Oh, may I become increasingly conversant therewith,
and humbly endeavour in retiredness of mind to distinguish the voice
of the true Shepherd from every presentation and imagination which
proceeds from the mysterious workings of the power of darkness.
How powerfully does the principle of self-love still operate in my mind.
How often do I let it out after selfish gratifications.
How little ability do I possess of truly loving, worshiping or praising that awful Power,
whose outstretched arm hath mercifully drawn me out of many pollutions,
and is willing still further to redeem and purify my soul,
were I enough resigned in all things to his holy will.
Oh, may I indeed press after this state of patient
acquiescence with the decrees of Eternal Wisdom.
Shall not the Judge of all the earth do right?

Yearly Meeting.
During the course of this week the weighty concerns of Society were deliberated upon,
and resulted in much harmony,
and the covering of solemnity was renewedly felt to be spread over the minds of Friends,
under which several exercised brethren delivered various concerns relating
to the subjects deeply interesting to the well-being and health of the body.
A travail and concern for the right education of the
youth peculiarly engaged the attention of the meeting;
and the frequent collecting families for silent retirement of mind,
and reading the Scriptures,
were pointed out as means of preservation and improvement to the youth.

Fourth month 28th. Second-day morning.
The Yearly Meeting closed.
It has been an interesting and favoured season.
The revised Discipline, which for two years has been under care of a committee,
being now finished by them, was agreed to, and directed to be printed.

Fifth month 12th. Yesterday morning at our Market Street Meeting,
Nathan Yarnall bore a short testimony.
He appeared much affected,
and I trust sympathy and unity were felt for and with him therein.
May he be preserved.

13th. Oh, that I were enabled wholly and unreservedly to give up all!
Oh, this unsubjected will!
How it hinders my access to the Fountain of Good.

[.small-break]
'''

+++[+++On the 16th day of the Seventh month, this year, he became of age.
In writing in aftertime of his early life, lie says:
"`During my minority I twice had the privilege of accompanying, for a short time,
Friends who were travelling in the work of the ministry,
which afforded me some seasons of profit.
From the time of the memorable visitation until the close of my apprenticeship,
I endeavoured conscientiously to discharge my duty to my employer.`"]
