== Chapter IV.

[.chapter-synopsis]
* 1811-1814.
* Letters Eli Yarnall`'s death
* Marriage to Edith Sharpless
* Thomas Scattergood`'s death.

+++[+++Although Thomas Kite was favoured to feel a good measure of
resignation at the time when his beloved wife was taken from him,
yet he soon after experienced great depression of mind.
His faith and confidence in the Lord`'s merciful regard to him, seemed to fail,
and for a considerable time he did not appear in the ministry.
About the time that the clouds were, in mercy, somewhat dispelled from about his faith,
he made the following entry in his Diary:]

[.small-break]
'''

Fourth month 21st, 1811.
Since the afflictive dispensation last recorded,
my poor mind has been tossed with a variety of temptations and trials;
feeling little of what I have heretofore regarded as Divine good.
Yet at times, through all,
my desires have been that the Lord will cause
all these things to work together for my good.
Oh! that my soul may be increasingly established in his everlasting patience,
meekly receiving the cup given me to drink, considering the Captain of salvation,
and what He endured, lest I be weary and faint in my mind.
Oh! enable me, thou gracious Benefactor,
to resign myself to thy disposal with an undivided heart, dedicating all my faculties,
attainments and possessions, unto thee,
from whom they all proceeded--thou who remainest to be God over all,
blessed forever and forever,--worthy of all praise,
adoration and worship from the soul which thou hast made.

[.small-break]
'''

+++[+++After this Yearly Meeting Charles Osborne visited the
subordinate meetings of this Yearly Meeting,
and in the Fifth month Thomas Kite accompanied him through the
meetings constituting Abington Quarterly Meeting.
This short excursion appears to have been of singular
service to the drooping mind of the young widower,
and a renewal of faith was graciously vouchsafed him from above,
and a fresh ability received to run with patience the
race which had been evidently set before him.
Whilst on this visit, he thus wrote to his parents:]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Horsham, Fifth month 21st, 1811.

[.salutation]
Dear Parents:

On Second-day we were at Abington Meeting,
where Charles had the Gospel to proclaim largely and livingly to a numerous,
solid audience.
George Williams went with us in the afternoon as a pilot to Byberry, to Hannah Yarnalls.
The meeting there yesterday was the largest ever known in the new house,
as I was informed.
Charles was furnished in an extraordinary manner with matter and utterance,
addressing the members of religious society, whether our own or others, separately;
and those who made no profession of religion also,
together with a variety of states and conditions.
A solid weight covered the meeting, and in my judgment,
it was a truly favoured opportunity.
Stephen Comfort and Hannah Yarnall came with us here, to the widow Spencer`'s,
where we now are waiting to attend Horsham Meeting today.
I see nothing about home yet, but expect, when Benjamin Johnson comes, to return.
I feel much bound to dear Charles, and can a little, I trust, sympathize with him.

--

[.offset]
+++[+++In relation to the state of his mind after the death of his wife,
and the animating effects produced on him by the visit with Charles
Osborn, he wrote thus in after life:]

[.small-break]
'''

After I had appeared a few times in the meeting I belonged to,
a dispensation of great affliction was permitted to overtake me.
The death of my beloved companion was one cause of my great sorrow, but not the only one;
great tossings were experienced, being left with two small children,
the youngest but a few weeks old.
Under these trials my mouth was shut in our meetings for worship for many months,
and I seemed very near losing my hold on heavenly good; but a friend in the ministry,
from a distance, taking me for a short time as his companion, hope revived,
and at length strength was received once more to advocate that cause which was, and is,
precious to me; and having obtained mercy,
I continue to this day in the exercise of the gift, which, I believe,
has been dispensed to me.

[.small-break]
'''

+++[+++Humbly attentive to his religious duties,
and industriously active in his outward business, Thomas Kite,
although still at times cast down, and often baptized into spiritual deaths,
found the summer wear quickly and tranquilly away.
In the autumn he thus wrote to his aunt, Elizabeth Letchworth:]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Philadelphia, Ninth month 11th, 1811.

[.salutation]
Dear Aunt:

Having finished my daily task, it occurred to me to write to thee.
True, I hardly know what to write about,
for very seldom do I write anything beyond an
entry in the day-book or a letter on business.
Yet, I trust,
I am not so entirely engrossed with the cares of this
life as to make me unthoughtful of my friends.
They are often recollected by me with sentiments of affection,
and I feel a lively interest in their prosperity.
Sometimes, in particular, I picture to myself your evening family circle:
Uncle John reposing his weary limbs in his comfortable arm-chair,
and disposing himself either to cheerful conversation, or silent meditation; whilst thou,
equally comfortable in the opposite corner, sits mending stockings, reeling yarn,
or paring apples for tomorrow`'s pies.
The other branches of the family, either busily engaged in acts of good housewifery,
or resting from the toilsome occupations of the day.
Cousin Mary^
footnote:[Thomas Kite`'s daughter not quite three years old, boarded at J. L.`'s,
and was under the particular charge of his daughter Mary.]
and her little charge form part of the picture;
Susan catching instruction from her cousin`'s lips,
or addressing her in the inquisitive language of childish simplicity.
But I had perhaps better stop my painting, and tell thee some matters of fact;
let thee know what has been said and done in this great city, the centre of news, trade,
and bankruptcy--the grand emporium of almost all things good, bad and indifferent.
In the first place, then, trade is dull, and dull it is likely to be.
Many people apprehend a war with England; in which case our foreign commerce,
already languishing, will receive a fatal blow.
The British have sent out a considerable naval force,
which is said to have arrived on this side of the Atlantic.
What object in particular they have in view is yet the subject of conjecture only.
A number of failures have taken place within a week, amongst whom may be mentioned.

The Jewish priest, Cohen, died a few days ago, and William Poyntell this morning.
Authentic intelligence of the death of John Simpson has reached us,
but I have not yet heard particulars.
Samuel Smith (currier) was married last Fifth-day, at Darby, to Hetty Stokes,
a daughter of Nathaniel Newlin.
Joshua and Mary Hoopes have removed to town, and live in Carter`'s Alley.
Edward Parker and Mercy Widdifield passed at last Monthly Meeting, Northern District.
Charles Allen and Rebecca Jackson,
and William Evans and Deborah Musgrave are expected to pass soon.

William Bowen`'s wife is deceased, and he is about breaking up housekeeping,
and intends going into the country to board.
We have been looking at a comet, visible early in the evening to the north-west,
near the horizon, of considerable magnitude,
and are on the lookout for an eclipse of the sun?
described in the almanac to take place on the 17th inst.
Joseph Walton has not yet returned, owing to the sickness of his companion,
which detained them at Cincinnati.

In looking a little towards the possibility of times approaching of outward difficulty,
it appears desirable that we who profess to have a
testimony to bear to the Messiah`'s peaceful kingdom,
should be preserved from mingling our spirits with the spirits of the people,
or catching that uncertain,
fluctuating state of mind which results from having the eye outward to the arm of flesh.
May we be redeemed from every disposition that prevents our becoming upright,
dedicated followers of the Prince of Peace; for if this is our happy situation,
whatever trials from without may arise,
having our confidence unshaken in the Supreme Disposer of events,
we shall be safe as in the hollow of his holy hand.

Our place of defence shall be the munition of Rocks, and not only so,
but by thus abiding under the seasoning virtue of Truth,
we may be instrumental in holding up the blessed ensign of peace in the view of others,
and thus become as the salt of the earth, or as a city set on a hill,
which cannot be hid.

[.signed-section-signature]
Thomas Kite.

--

[.offset]
+++[+++In his Diary, Tenth month 14th, is the following entry:]

Suffered anger to prevail, and,
under its influence, spake unadvisedly.
Oh! for more of the disposition of the Lamb!'``' In the Fourth month, 1812,
Thomas Kite being in Trenton, his father wrote to him:
"`Susanna Home`'s meeting was large;
and considering many of the company were like bullocks unaccustomed to the yoke,
was a satisfactory season.
The notice of it had spread over all the city.
Every seat, entry, and step were filled,
and hundreds went away because they could not get in the house.
The people were not all of the description intended,
but as much so as could be expected.

[.embedded-content-document.letter]
--

[.letter-heading]
Benjamin Kite to Thomas Kite.

[.signed-section-context-open]
New York, Fifth month 28th, 1812.

[.salutation]
Dear Son:

The Yearly Meeting here is smaller, they say, than usual.
There are many zealous ones among them.
Upon the whole, it has been so far satisfactory;
though we had last afternoon one of the most unsavory political speeches,
from a wild member, that I ever heard.
This was the harder to be borne,
as Friends here are remarkably clear of political engagements.
The meeting very properly took no notice of the harangue.

--

[.offset]
+++[+++In his Diary of Eighth month 26th, 1812, Thomas Kite writes:]

Yesterday morning died Eli Yarnall, a prince and a great man in our Israel;
eminently distinguished by gifts and qualifications,
yet not more so than by his humility.
He was remarkable for seldom appearing as a minister, yet when he did,
his communications were thought to be weighty and powerful in an uncommon degree.
May the mantle of Elijah--the prophetic spirit--rest upon Elisha,
for the harvest truly is plenteous,
but the rightly anointed labourers are comparatively few.

[.small-break]
'''

+++[+++Micajah Collins, who visited the Meetings of Chester and Delaware Counties,
in the early part of this year,
thus speaks of Eli Yarnall in a letter addressed to Edith Sharpless.
The letter possesses so much,
interest as to warrant the insertion of considerable extracts from it.]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Fallowfield, Second month 16th, 1812.

After leaving the city we proceeded to Haverford;
thence to several small meetings not far distant from the Lancaster Turnpike;
thence to Middletown; took a night`'s lodging,
and attended meeting with the celebrated and justly esteemed Eli Yarnall.
I was much interested in his company,
and wanted to hear the sound of his voice in meeting, but did not.
Was in hopes he would tack on his net, but it was a vain hope.
He was, however, very free and interesting in his converse,
and I found good reason to love him.

I did not meet thy father +++[+++Joshua Sharpless]
until we arrived at Concord, at the Quarterly Meeting, since which,
have had his company at divers meetings.
He was well, and I expect we shall meet with him at the meeting at this place today,
and that he will continue with me perhaps several days.
I should be glad of his company, as long as I stay in this part of your Yearly Meeting.

There is no small company of the fraternity when we all come together.
Beside the New England friends +++[+++himself and John Bailey], there are Willet Hicks,
of New York, Isaiah Balderston, of Baltimore, and the simple, humblehearted Abel Thomas.
The dear old man is so humble and backward among such a crowd,
he can scarcely put his net in at all.
However, he preaches, if he says nothing.
He has been with me at every meeting since Cain Quarter.

As I pass from meeting to meeting I meet with many who
are the salt of the earth,--many whom I love and esteem.
There appears a prospect among the young people, male and female,
giving ground to hope a succession of standard-bearers are rising,
and will arise from among them,
to supply the places of those who have gone and are going from the stage of action.

19th. London-grove.
Have this day attended the Quarterly Meeting at this place.
It was very large on both sides of the house.
There were many young people present, as also divers worthy examples among the ancients,
who are near to my tenderest feelings,
and in whose welfare I feel an affectionate interest.
The meeting stands adjourned until tomorrow at eleven o`'clock.

[.signed-section-signature]
Micajah Collins.

--

[.offset]
+++[+++Thomas Kite`'s Diary, Ninth month 1st, 1812.]

Another worthy departed in the meridian of life, Joshua Maule, who died on First-day,
being from home on a religious visit.
His disorder was a fever, and he suffered much pain,
but could testify notwithstanding during his illness,
that it had been to him a time of rejoicing.
He was much dedicated to his Master`'s service, and is, no doubt,
admitted to the rest prepared for the faithful.

[.small-break]
'''

+++[+++1813. Thomas Kite was now preparing to enter a second time into the marriage state.
His choice was Edith Sharpless, a daughter of Joshua Sharpless, a worthy man,
and a faithful elder of Birmingham Monthly Meeting, Chester County, Pennsylvania.
Edith had been employed in teaching school in the city,
and had made her home during the latter part of the time of
her residence in Philadelphia with that father in our Israel,
Thomas Scattergood.
Thomas Kite in proposing the marriage connection to her,
did it under the belief that it was in obedience
to the secret pointings of his Heavenly Guide,
as well as from the promptings of affection; and she, in accepting him,
did it in the assurance vouchsafed her, that he was one of the Lord`'s chosen; poor,
indeed, in this world, but rich in faith, and heir of the kingdom.^
footnote:[Edith Kite pleasantly remarked, that she had come to the conclusion in early life,
that three things she never would do--marry a man that was a widower,--one that was
younger than herself,--or a preacher,--yet all these met in her husband.]

Edith having given up her school,
and returned to her father`'s house to prepare herself
for the important change she was about to make,
Thomas Kite frequently addressed her by letter.
Their letters are good specimens of their kind; pleasant, affectionate,
and giving evidence on what his mind was mainly bent.
We give a few extracts.]

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to Edith Sharpless

[.signed-section-context-open]
Fourth month 4th.

My best wishes attend thee.
May thy residence at Birmingham be pleasant and profitable; and may we each,
not only now, but when joined in a more enduring relationship,
unitedly seek for that blessing which makes truly rich, and adds no sorrow with it;
as Cowper expresses it:

[verse]
____
Thou bounteous Giver of all good,
Thou art of all thy gifts thyself the crown!
Give what thou canst, without thee we are poor,
And with thee, rich, take what thou wilt away.
____

May we seek first his kingdom, and the righteousness thereof, confiding in his promise,
"`that all things necessary shall be added.`"
By the truly humbled mind, small possessions in temporals, are seen to be sufficient.
It dare not seek for great things, but having food and raiment, desires to be content.
I believe this state, though hard to come at, is through Divine aid attainable,
and desire I may endeavour for it.
Under a fresh feeling of affectionate regard, I salute thee, and bid thee farewell.

[.signed-section-context-open]
Fourth month 19th.

The Yearly Meeting is very large; quite as much so, I think,
as ever I remember it.
The strangers, however, who attend are fewer in number than common.
Sarah M. Watson^
footnote:[Daughter of Dr. Watson, of Buckingham, Bucks County, a valuable young minister.]
is with us, better in health than when thou saw her.
I met Ann Scattergood in the street after meeting;
she inquired affectionately after thy welfare.
I have seen thy parents, sister Lydia, and Cheyney, and am in hopes of meeting Phebe.
I have met with many friends to whom I am attached; Stephen Pike in particular,
and some beloved relatives, whose company has been agreeable;
but necessary attention to business has prevented my
enjoying their society to the extent I wish.

It is truly pleasant to see such a number of goodly-looking Friends,
particularly young women, walking our streets;
and if their conduct should indicate their dedication to the principle of Truth,
their being here may be an advantage to themselves,
and afford no cause of injurious remarks on the part of our sober fellow citizens.
Many of these are keen-sighted, and able to decide upon our conduct,
whether it comports with our dignified profession.
Oh! if this was more generally the case, how should we shine as lights in the world,
even as a city set on a hill which cannot be hid.
We should be as way-marks to those who are inquiring
the way to Zion with their faces thitherward.
I remain under the renewed impression of love and esteem, thy friend.

[.signed-section-context-open]
Fourth month 24th.

Our Yearly Meeting closed last evening,
and may be acknowledged to have been a favoured one,
wherein the minds of Friends generally were preserved in quietness and harmony;
and in conclusion a comfortable degree of solemnity was granted,
under which thanksgiving was vocally rendered as well as inwardly felt,
to the Author of all our blessings.

[.signed-section-context-open]
Fifth month 8th.

We have another striking and
affecting instance of the uncertainty of life.
Our friend Caleb Shreeve is deceased.
I suppose it was about the time you left the city that he had
a parting opportunity of religious retirement with his family,
intending to join Susanna Horne at Cropwell.
At the close of this opportunity he was taken with a pain in his head,
which it is thought was apoplectic, and which increased till he became insensible,
in which state he lay until about 2 o`'clock, and then expired.

[.signed-section-context-open]
Fifth month 27th.

May thy mind be preserved in quietude, until the important day;
and oh! that He who condescended to attend the marriage of Cana,
may favour us with his holy presence on that solemn occasion,
enabling us in his name to set up our banners,--yea, to choose Him for our portion,
and the lot of oar inheritance; trusting in Him for our supply,
both of the dew of heaven--the refreshment that keeps the soul alive--
and also for such temporal accommodation as He sees necessary.
In this, as in every other respect, may we seek for a qualification to say:
Thy will be done.

[.signed-section-context-open]
Sixth month 1st.

I received today thy letter, dated the 30th ult.
I am well pleased that you have agreed not to alter the time agreed on,
and feel very little uneasiness respecting the other
couple +++[+++to be married at the same meeting].
The principal wish in
relation to that part of the subject which I feel is,
that thou may be favoured to banish all unpleasant anticipations from thy mind,
and to renew thy confidence in Him who hath ever
proved a present Helper in the needful time.
Emmor Kimber started this day on his proposed visit.^
footnote:[To the meetings in New York Yearly Meeting.
Samuel Bettle was his companion.]
I called at Samuel Bettle`'s and found Jane in tears,
having just parted with her beloved companion.
The prospect of several months`' separation was evidently trying;
but she seemed aiming at resignation, believing him in his place.
Abraham Lower is going on a religious visit to the lower parts of New Jersey,
having Israel Maule for a companion.

[.signed-section-context-open]
Sixth month 5th.

I have for several days been very closely engaged.
Thou mayest recollect that Friends were generally invited throughout
our Yearly Meeting to attend a conference at Newtown last Sixth-day
on the subject of a superior school for boys only,
in which the higher branches of learning might be taught,
and youth of a riper age than can be admitted at Westtown might be accommodated.
I attended that conference,
and Friends saw fit to appoint me one of a committee of thirteen,
to take the subject into more particular consideration.
That committee met on Fifth-day afternoon.
Our meeting on that day, which was an adjourned Monthly Meeting,
held till near two o`'clock.
The committee met at three, and sat till seven.
Then again next morning at eight, and rose between ten and eleven.
In the afternoon the Asylum business came on at three, and we sat till near night.
So thou seest I have not been entirely unemployed.

--

+++[+++Thomas and Sarah Scattergood were invited to attend the
marriage of their friends at Birmingham,
but way did not seem to open for it.
Instead thereof Thomas, the day before the wedding,
addressed the following letter to the parties:]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Philadelphia, Sixth month 9th, 1813.

I do not see an opening for me to leave home under present circumstances.
Nevertheless, I feel a warm desire accompanying my mind,
that you may be favoured to get comfortably through your seeming trial tomorrow;
but more so after the accomplishment thereof, that you may yet, more fully than ever,
set your hearts to serve the Lord in the way required of you.
So will preservation be witnessed under all trials attending.
You have had a share of conflict, both of you, in travelling on so far;
be encouraged to persevere in desire to fill up your measure
of known duty even in the little opened before you,
and more from time to time will be manifest.
In so doing, your Father which is in heaven, will bless you.
And it is my prayer for you in penning these hasty lines, that you may be blest.

[.signed-section-signature]
Thomas Scattergood.

--

+++[+++The marriage was accomplished on the 10th in a satisfactory manner,
in Birmingham Meeting-house;
and the newly married pair were soon comfortably settled in Philadelphia.

The committee on the high school above mentioned, held many meetings:
but way did not open to take any steps towards establishing such a seminary.
Thomas Kite, shortly before his marriage,
having addressed a letter on the subject of the proposed institution to his friend,
Stephen Pike, then keeping school at Burlington,
early in the Sixth month received a letter in reply,
from which the following is extracted.]

[.embedded-content-document.letter]
--

[.letter-heading]
Stephen Pike to Thomas Kite

[.salutation]
Dear Thomas,

If it shall be determined that there be a school of that kind,
I think great caution is requisite in choosing a preceptor in classical literature.
He should be one that is fully convinced of the
subordinate utility of knowledge of that kind,
and one who is both capable and willing to influence
his scholars in forming a correct notion of its value;
keeping always in view himself, and endeavouring to hold up to their view,
that one thing only is needful.

I think that the procuring a teacher in this department every way qualified,
will be a principal difficulty.
I confess I have some doubts respecting the advantage that it
is hoped will be derived from the contemplated establishment.
Some favour it on the ground, that a knowledge of the languages,--and, perhaps,
classical learning in general,--is a desirable object; others,
that since there is an inclination in the minds of youth for such acquirements,
and this inclination is encouraged by their parents,
it will be prudent to furnish them with the least
exceptionable means of obtaining what they desire.
Science and literature are both, no doubt, worthy of attention;
but ought we not to be guarded against buying them at too dear a rate?
against sacrificing too much for them?
If we attain them at the expense of humility and simplicity,
will we not pay too much for them?
I know it does not necessarily follow that those who
possess the former are deficient in the latter;
but not many rich, noble, profound, or scientific, etc, is Cowper`'s idea; and certainly,
it is a just one.
The sum of what I have said, or intended to say, is:
If the higher walks of literature can be attained
without endangering the truly Christian virtues,
let us do it; if not, let us remain where we are.
I believe that minds rightly disposed may pursue
science and literature to a very considerable extent;
but those who are much given to self-complacency,
and are not capable of appreciating the inestimable value of humility and simplicity,
had better have their attention turned to something else.

--

+++[+++Ninth month 11th, Stephen Pike again wrote to Thomas Kite.]

[.embedded-content-document.letter]
--

How hard it is for a rich man to enter the kingdom!
I think exemplifies in its inhabitants the justness of that remark.
They, appear to me too rich in every sense of the term to entertain much of genuine Quakerism.
I fear there are many among them,
who think an agreeable and creditable establishment on earth, the prime good,
and who do not choose to be troubled with cares about futurity.
They have a pretty smart meeting-house, and it is sometimes pretty well filled;
but the gay appearance of the assembly, and the levity of the juniors after meeting,
give an unfavourable impression respecting their standing in a religious sense.

--

+++[+++Thomas Kite having informed Stephen Pike of the
conclusion of the labours of the High School Committee,
without having effected anything, he received the following:]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Burlington, Ninth month 20th, 1813.

Thou mentions the conclusion of the committee relative to the proposed Boarding School,
at which I am not surprised;
and I believe it to have been the best they could have formed at this time.
The little private seminaries that are forming in different parts, will, perhaps,
answer the purpose had in view, and better than a large unwieldy one.

We had an agreeable visit from our much beloved and loving friend Jacob Lindley.
I think if Jacob is exemplary in no other way,
he is considerably so in the love of the brethren--
which his conduct and conversation manifest.
I believe his visit was not only agreeable to his Burlington friends, but also to himself.
He seemed particularly gratified with being at John Cox`'s, and in that neighbourhood.
He said the farms appeared finely cultivated, and things around looked pleasant,
but these were nothing compared with the feelings that attended his mind.
John Hoskins and he embraced at parting, with a remarkable degree of warmth,
and the sympathy of fraternal love.
The former Friend seems increasing in that kind
of sympathy as he advances in the vale of years.
What a happy omen! when the natural capacity and
affections are impaired by the paralyzing hand of age,
for the distinguishing badge of discipleship to be more and more apparent.

--

+++[+++Edith Kite, in the Ninth month, taking her son William with her,
paid a visit amongst her relatives in Chester County.
Her husband thus wrote to her under date of Ninth month 26th, 1813.]

[.embedded-content-document.letter]
--

We had a grand illumination of the city on Sixth-day night,
in consequence of the naval victory gained on Lake Erie.
Some Friends were much alarmed at the prospect,
not knowing what the mob might do to those who
could not join in this mode of expressing joy.
I am sorry to say, the fears of a number led them into a compliance,
amongst whom were some from whom more consistent
conduct might reasonably have been expected.
The mob broke the windows of a number of Friends;
yet the injury done by them is not very expensive.
The illumination was very general.
It was a wonderful show, and the streets were crowded with people walking.
Companies were dragging burning boats about the streets; some making bonfires,
others firing squibs, whilst guns were heard in almost every direction.
Neither our dwelling nor store was molested.
I fear this is but the beginning of this kind of work;
and I feel very desirous if it should prove the case,
Friends may be preserved in a faithful testimony
for the peaceable doctrines of the Gospel.
'`This morning at meeting we had the company of Jane Snowden and John Cox,
each of whom ministered with acceptance.

The latter, as he frequently does,
handed forth the language of encouragement to the tired traveller,
who under great weakness and discouragement is
nevertheless looking with desire towards Zion.
Such he desired might hold on their way,
remembering that though the path is a tribulated one it leads to endless blessedness.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Stephen Pike to Thomas Kite

[.signed-section-context-open]
The 4th of Tenth month,

We had yesterday the favour of Benjamin White`'s company at our meeting.
He continued with us until today, very much to my satisfaction.
Beside a weighty communication from Benjamin, we had one from Mercy Brown,
another from Mary Bonsall, another from John Cox, and a prayer from Susan Smith.
A lively time and worthy of remembrance.
Elizabeth Coleman and Margaret Allinson obtained certificates
or minutes to visit some meetings in your State,
particularly within the compass of Cain and Concord Quarterly Meetings.
Rowland Jones was furnished with a minute to accompany them.

--

+++[+++1814. First month 2nd. Stephen Pike again wrote to Thomas Kite:]

[.embedded-content-document.letter]
--

Burlington has been much favoured of late by the visits of Friends.
Henry Hull spent several days among us very acceptably.
His visit was principally of a social nature;
but he has a minute from the Monthly Meeting whence he came,
and has been pretty largely in communication, both in meetings and private sittings.
He made his home at Nathaniel Coleman`'s, where I several times met with him,
as well as at other places.
His conversation is agreeable and his addresses
of a religious nature pleasing and instructive.
I suppose he is now with you in Philadelphia.

We have also had the company of the lively little Christopher Healy; little in person,
but some of us think him a large minister.
The inhabitants of Burlington were invited to
attend the meeting at which he was when here,
and there was a considerable gathering.
He was animated in testimony and prayer, and I believe gave general satisfaction.
He afterwards had a meeting at Mount Holly which, I am told,
was a very extraordinary time.
He addressed the different classes and descriptions of those who were present,
in a manner that occasioned the tears of many to be strewn on the floor.
The members of that meeting, which is rather a poor one,
think it was a day long to be remembered.
William Ridgway, who with some other Friends of this place were there,
thinks he was very eminent.
Simon Gillam was his companion;
and he gave us a specimen of his gift in two sittings at which I was present.
I liked what he said and the manner of it, much.
I hope he will continue to gain accession of wisdom and knowledge,
and be allowed to communicate to others, whether it be in a little or large way.
Robert S. Pitfield accompanied Christopher from this place,
and I suppose stayed with him till they reached your city, or its neighbourhood.
We have had a great deal of instruction and exhortation
latterly by strangers and by our own ministers.
Even the lips of the humble, but interesting Mary Roscoe,
though closed in silence for a long time,
have been opened to utter sweet and animating strains for the
encouragement of travellers in the holy spiritual journey;
and to invite those who are proceeding in the broad way of vanity and folly,
to enter at the straight gate into the circumscribed path of wisdom.
I hope we may improve our advantages.

I believe thou inquired of me when I was last in the city, respecting Mary Roscoe,
under the title of '`The Little Prophetess.`'
She lately dined at our house,
and in conversation gave us some particulars respecting herself.
Her father, who is her only surviving parent, is a rigid Methodist;
and her brothers and one sister also incline to the same persuasion,
or do not make any profession of religion.
The family are poor.
Mary was placed out when very young in the family of a friend in New York,
an acquaintance of her mother`'s. She at that time possessed a
sovereign contempt for Friends and their ways,
and thought it would be a distressing circumstance if
any connection of her`'s should become a Quaker.
Her views, however, changed; and she at length submitted through great reduction of self,
to make application to become a member of the Society,
as it appeared to be her indispensable duty.
For a still greater trial of her faithfulness,
she apprehended herself obliged to appear in open testimony to the principles of Truth.
In her first essays she did the utmost violence to her feelings,
and fainted several times in attempting to speak in public.
Her relations on hearing of the steps she had taken,
became almost entirely estranged from her, and treated her with cold neglect.
Her father was particularly embittered against her;
and I think for a long time refused all communication with her;
so that she has not seen him more than once in the course of many years.

About three years since she was on a religious
visit in the neighbourhood where he resided,
and considered it her duty, though a great trial, to go to see him.
He received her rather rudely, showing little or no marks of affection for her;
but he endeavoured with all his might to convert her to Methodism.
She listened to all he said with patience and in silence,
not feeling easy to make any reply to his arguments.
After saying a great deal, and finding it was to no effect,
he threatened to bring the officers of their society to convince her of her error,
and did make application to one;
but the man had a little before been at a meeting where Mary was,
and he wisely counselled that she should be let alone.
This cooled the father`'s zeal, and he became more moderate;
and when she took her leave of him he was affected;
and signified that he believed she was in her right place.
He has since written to her once, Mary says, quite charitably.
She does not wonder that her relations treat her with so much neglect,
for she well remembers when she was in the same spirit.
She has continued in the situation of a hired maid from the time of her becoming of age,
esteeming it her proper sphere,
and so far from being inflated at the attentions she
received since she became an approved minister,
she is modest and shy, perhaps to a fault.
She resided for some time in family, and it troubled him and his wife not a little,
that they could not by any means induce her to sit with them at the table.

I suppose they considered her a sister in the highest affinity--being
spiritually a child of the same Divine Parent,
a partaker of his favour and heiress of a mansion in his kingdom,
and they were unwilling she should be too much of a menial;
but she insisted that the kitchen was her proper place.
She has acted upon the same principle since, so uniformly, so perversely,
might I not say,
that Rebecca Grellett and Susan Smith`'s family have
desisted from expostulating with her on the subject.

Our last Quarterly Meeting was favoured with the
company of the animated Christopher Healy.
He had considerable to communicate, and his labours were attended by evident effects,
particularly in the women`'s meeting.
His representations and appeals were accompanied by a tendering sympathy,
which reduced nearly the whole company to tears.
Several young women sobbed aloud.
I suppose he is now with you.
I do not recollect anything material besides occurred at the Quarterly Meeting.
Yes!
Abby Barker was admitted a member of the Select Meeting.

Mary Roscoe is making a visit to the families of those
who are in the habit of attending our meeting,
members and others.
We shall be sorry to part with her, but I suppose our sorrow will be unavailing,
for Henry Hinsdale, it appears, has been persuading her she had better go to New York,
assume his name, and become a partner of his pains and pleasures;
circumstances indicate that she is of the same mind.

--

+++[+++In the early part of 1814,
Thomas Kite was summoned before a Court Martial of military officers to
answer for not having turned out with the militia in the preceding summer.
Accompanied by his father he went voluntarily before them;
gave them his reasons for believing their proceedings were illegal,
and obtained permission to place his protest against their authority upon their minutes.

On the 23rd of Third month Rebecca, the first child of Thomas and Edith Kite, was born.]

[.embedded-content-document.letter]
--

[.letter-heading]
Stephen Pike to Thomas Kite

[.signed-section-context-open]
Fourth month 1st.

I congratulate thee on the increase of thy comforts, alias cares.
'`Life`'s cares are comforts,`' and surely an
addition to the number of infantile dependents,
is a care of considerable magnitude.

Thou hast, no doubt, heard of the loss Society has met with,
in the removal by death of the ancient, honourable, and much beloved John Hoskins.^
footnote:[He deceased Third month 27th, 1814, in his 87th year.]
Friends of this place have mourned sincerely on the occasion; for there are, perhaps,
few so generally respected and esteemed by every class and age as he was.
A considerable portion of his time, of latter years,
was spent in making little social visits among his
friends--perhaps most of the members in the place--who,
whether at the wash-tub, spinning-wheel, other occupations, or in hours of leisure,
were at all times pleased to see him.
He mostly called on them when it suited him, without making any apology when he entered,
or when he withdrew,
and seemed to prefer that they should not press him to
stay when he showed a disposition to retire.
By these familiar visits, and his instructive conversation,
the venerable man was exceedingly endeared to his neighbours,
who derived both pleasure and advantage from them.
In him was seen the benign influence of Christian
principles when allowed to have their proper regard.
In early life it appears, his manners were rather austere, and his appearance repulsive;
but as he advanced in the knowledge and practice
of his duty in relation to his Divine Master,
and his fellow man, his deportment was exceedingly changed.
He was, indeed, a pattern of gentleness and affection for his friends.
When he entered a room he was cordially received,
and the arm-chair was placed with apparent satisfaction for his reception.
Even the young,
though a respectful deference for him might make a slight change in their conversation,
felt no unpleasant restraint from his presence.
He was a most exemplary observer of religious duties.
Scarcely any circumstance could prevent his attending religious meetings.
No weather was so stormy or inclement, as to induce him to stay at home,
when his health would allow him to go;
and the indisposition must have been considerable that could operate as a discouragement.
He was so punctual to the hour of gathering, that he used to be called pleasantly,
"`the regulator,`" and it was common to say: Come, it is time to go,
there is friend Hoskins.
His judicious activity and zeal in the different meetings for business is well known.
I think he said he had attended sixty Yearly Meetings.
When he died he was about eighty-six years old.
What a long course of well doing! and how peaceful was the close!, I attended him,
in company with his son John, during the last night except one of his life.
My mind was clothed with a calm solemnity as I watched near him,
and contemplated the approach of his closing scene.

He was extremely weak, and was much troubled with phlegm and difficulty of breathing;
but no murmur escaped his lips, nor any expression of fretful ness.
He appeared to be perfectly rational, except while dozing;
and his mind was evidently occupied with desires
for the prosperity of Truth and righteousness;
what he said was in short, detached sentences; but though uttered in a feeble voice,
it was clear and pertinent.
I was told he had a solemn opportunity with J. afterwards,
which was exceedingly affecting.

The departure of this dignified servant was not distinguished by the
triumphant air which some have been enabled to assume upon their deathbed.
Indeed, his humility taught him to think so little of himself,
that he said he had nothing to depend on but mercy.
When I entered his room, and he was told I had come to see him, he replied meekly:
"`He has come to see a poor thing.`"
He was continually in motion from the effect of his disorder,
and kept drawing Thomas Scattergood towards him in a very affecting manner.
Thomas kneeled down at his bedside and prayed with great fervency and
while in this act the dying man seemed to be sensible of the exercise,
for he lay entirely still;
but as soon as the prayer was ended he resumed his former motions.
This was about two hours before he left this
scene of trial and entered the mansions of rest.
His funeral was attended by a great number of Friends and others.
Arthur Howell spoke twice at the grave.
George Dillwyn and Susan Smith also spoke; and Thomas Scattergood appeared in prayer.
It was a solemn time.

--

+++[+++The time was now fast approaching when that eminent minister of Christ,
Thomas Scattergood, was to be released from his labours of love in the Church militant,
and translated to the Church triumphant; exchanging the conflicts, the baptisms,
the unspeakable sorrows which often depressed his spirit,
for the joys which human ear hath not heard the full of,
and the human mind fails to conceive of, which are reserved for the people of God.
He was at several sittings of the Yearly Meeting;
but being taken sick on the 21st of Fourth month, the disease,
though not apparently violent, soon prostrated his strength.
He retained his interest, however,
in the transactions of the Yearly Meeting,--inquired frequently concerning it,
and did not appear to apprehend that the disorder which handled him so gently,
was a messenger with a speedy summons for him to the invisible world.

On the 23rd, a friend, saying he felt a peaceful solemnity, Thomas added, "`So do I;
my mind is centered in quiet, peaceful resignation.`"
On the 24th, the day he died, he said,
"`This is the last piece of the garment that is to be worked up;
and if I can be favoured to join the righteous of every generation, it will be enough.
Well, I don`'t know that I have much to say for myself; I leave it to the Lord,
the Shepherd that sleepeth not by day nor slumbereth by night;
who watcheth over his children and over his nock.`"
"`I hope that a righteous generation, will be raised up and preserved as a seed.`"
He lay awhile in silence, then added,
"`Oh! if we can but be favoured to take some of that love with us--the end crowns all.
I have nothing to boast of;
I have been baptised into many low places and raised up again.`"

His last expression was: "`I will lead them!`"
This was uttered with emphasis, as if his soul could feel and rejoice in the assurance,
that Christ Jesus was about to lead his tabulated
spirit to the living fountains of waters,
where God should wipe away all tears.

Thomas Kite was deeply moved at the loss sustained by the Church militant,
in the removal of this faithful servant, this honourable elder, this discerning minister,
from the nock and family on earth;
and he thus poured forth his feelings to his father-in-law,
who had not been to Yearly Meeting:]

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to Joshua Sharpless

[.signed-section-context-open]
Philadelphia, Fourth month 25th, 1814.

[.salutation]
Dear Father:

Our city, his family, and the Church,
have truly sustained a loss in the removal of our beloved Thomas Scattergood,
who departed this life at twenty minutes past seven last evening.
He had been a little poorly with a cold for several days,
but on Fourth-day night became seriously indisposed.
On Fifth-day, at noon, Dr. Parrish was called; and his illness continuing, Drs.
Atlee and Griffiths were successively called in.
Yesterday morning he appeared so low, that Dr. Parrish proposed remaining with him,
and did so during meeting time; and in the afternoon Dr. Atlee took his place.
After afternoon meeting, both Griffiths and Parrish remained until the close.
They were sitting in the room when, perceiving a slight suspension of breathing,
they requested his children to be called.
They were in the house, and came immediately into the room,
where they had been seated but about two minutes,
when he gently drew up his feet into the bed,
and without the least apparent pain or straggle, breathed his last.
During his illness he appears to have had no prospect that it would so terminate.
He expressed to Dr. Atlee, in substance,
that he had several times been let down with great weakness, and been raised again.
That if this was his last sickness, he had not seen it;
but that it was among his Lord`'s secrets.
Expressing entire resignation, notwithstanding, to the Divine Will,
and appeared to be in a sweet, affectionate and composed frame of mind.

It may be said of the deceased,
that he had grown up to the stature of a Father in the Truth;
and in this city his services as such were eminent, indeed;
often handing out the cup of encouragement to the feeble travellers towards Zion,
and having had large experience of the Lord`'s wonders in the deeps,
he was remarkably qualified to speak to the states of those
who were sinking under discouragements of various kinds.
The Christian propriety which adorned his life and conversation,
gave great influence to his fervent labours in the Gospel; and in his own meeting,
particularly, he will be much missed, being taken away in the midst of his usefulness,
while he was still strong for the Lord`'s work, his spiritual eye not being dire,
nor his force as a living minister abated.
But though one generation of faithful labourers passeth away,
and another generation cometh,
the Word of the Lord,--that which quickened and qualified them
for the service of their day,--endureth forever.
As those who are now coming on the stage of
active life submit to its purifying operations,
they also will be enabled to stand as faithful witnesses for the same dignified cause.
Thus the spirit which animated Elijah, will rest upon Elisha,
and there will be a succession in the prophetic office;
testimony-bearers will still be raised up to blow the trumpet in Zion,
and to stand as watchmen on the walls of Jerusalem.

Fourth month 25th. The funeral was obliged to be yesterday afternoon,
as the body was not in a state to keep.
The funeral was very large, and the testimony which Henry Hull bore at the grave,
I suppose could not be heard by one third of the people collected.
The widow appeared more composed than could have been expected.

Mary Harper, who was left sick at father Kite`'s, continues there.
She has been very poorly, indeed, but is somewhat better.

--

+++[+++The information relative to Mary Harper`'s health was premature.
She continued to sink rapidly, and on the 29th,
three days after the above paragraph was written, was quietly released from suffering.
The loss of this valuable elder, who had been in some measure a spiritual mother to him,
was sensibly felt by Thomas Kite; but in her case,
as well as in that of Thomas Scattergood,
the undoubted persuasion that each had respectively
filled up their measure of duty on earth,
and were gathered home in mercy, took away much of the sting from the bereavement.]
