== Chapter VII.

[.chapter-synopsis]
* 1819-1824.
* Separation in the Society of Friends
* Letters to members of his family.

+++[+++It will now be necessary to allude to the defection from the original
doctrines and principles of the religious Society of Friends,
which finally resulted in the separation of 1827.
Thomas Kite thus wrote on the subject:]

[.small-break]
'''

About the year 1819, the trial of Friends in this country commenced,
from the dissemination of the unsound sentiments of Elias Hicks and his adherents.
In the sufferings and afflictions of my brethren from this cause I had a large share.
Believing it required of me by my Divine Master openly to oppose the spirit of unbelief,
and earnestly contend for the faith once delivered to the saints,
my conduct herein drew upon me much censure and reproach.
For a time it seemed as if I must have sunk under these trials;
but the tender sympathy of my dear companion, and other precious Christian friends,
proved a stay to my mind, and I was enabled to persevere until the separation,
which took place in 1827, opened a way in some degree for my relief.

[.small-break]
'''

+++[+++Although the defection commenced or became apparent, as the above quotation specifies,
about the year 1819,
but little disturbance was created in Philadelphia
Yearly Meeting until towards the close of 1822.
Thomas Kite frequently said,
that the first intimation he received of the
unsoundness of Elias Hicks was from the late John Cox,
of Burlington,
who told him sometime before the breaking out of the
controversy that "`Elias Hicks held Unitarian principles.`"
Being warmly zealous for the doctrinal purity of the Society he loved, he demanded,
why then he was not disowned?
John replied,
"`That the attempt to disown him would cause a separation in the Society of Friends.`"

In the year 1822,
it began to be well known that a doctrinal difference existed in the Society of Friends;
and it was as well understood that the heads of that profession in
Philadelphia were opposed to the Unitarian views of Elias Hicks.

We shall now return to Thomas Kite--giving no further
particulars of the disturbances amongst Friends,
except as they may incidentally arise, connected with his biography.]

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Susanna

[.signed-section-context-open]
Second month 15th, 1823.

It is very cold.
The Delaware closed yesterday; today the boys are skating,
and by tomorrow we expect it will bear horses, etc.

--

[.small-break]
'''

+++[+++Some sound and valuable Friends were uneasy at the open opposition
manifested by the faithful in Philadelphia to the doctrines of Elias Hicks,
and Thomas Kite received several letters from those he loved,
containing sentiments like the following, which is extracted from one of them:--"`I wish,
if it is proper to wish, that I could reach every heart with the sound of alarm,
and effectually proclaim the exhortation '`Be still.`'
I believe if strong measures are resorted to, by the active members of either division,
the wheat will be torn up with the tares,
and confusion,--perhaps utter confusion,--will
be introduced into the affairs of Society.`"

In reply to the writer of this, Thomas Kite said,
he thought the account received by his friend of
the state of fermentation in Philadelphia,
and the disposition to disown one another,
was exaggerated.
He declared his belief,
that the testimonies of the religious Society of
Friends would never be permitted to fall,
and concluded with urging the vital importance of knowing, each one for himself,
a preparation through faithfulness here, for the after scene.]

[.small-break]
'''

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Susanna.

[.signed-section-context-open]
Philadelphia, Third month 14th, 1823.

My omission of writing to thee has not proceeded from
any diminution of tender interest in thy welfare.
On the contrary, the older thou growest, the deeper is the solicitude I feel,
as regards thy whole conduct and behaviour.
I wish even thy amusements may not be too childish.
Remember, this is the season of improvement,
and that part of youth which is merely spent in sport, is lost or worse than lost.

Dear daughter, be serious.
Again I repeat it, be not too full of childish sports.
Remember thy Creator in the days of thy youth.
Take up the cross to the wild propensities of nature, and great will be thy own peace,
and great the comfort of thy parents,
who can have no greater joy than to behold their children walking in the truth.

--

+++[+++On the 30th of Fifth month, after returning from a journey of business to New York,
Thomas Kite wrote to his daughter Susanna at Westtown:]

[.embedded-content-document.letter]
--

It gives us satisfaction to administer to thy comfort;
let us in return have the satisfaction of beholding with thy increasing years,
an increase in dignity and propriety of behaviour.
The true foundation of good conduct is the fear and reverence of our Creator.
Remember Him, then in thy youth,--ask of Him to purify thy heart,
that thou mayest be enabled to love and serve Him,
and feel the rich enjoyment of a peaceful mind--a sense of Divine favour and acceptance.
Could all the gratifications the most unbounded imagination could conceive of, or desire,
be bestowed in full perfection, the possessor would be poor,
compared with one in the blessed inheritance of a conscience void of offence,
the peace which the world neither gives nor takes away.
Dear child, dare not, in the smallest instance, do anything thou knowest to be wrong.
Giving way to temptation in a little thing, opens the way for greater departures;
and some instances have been known wherein children once amiable and lovely,
have brought down by their conduct, the grey hairs of parents with sorrow to the grave.
I write not thus to cause thee unnecessary uneasiness,
but to relieve a mind full of parental anxiety and tenderness,
which greatly desires thy present and eternal welfare.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To the Same

[.signed-section-context-open]
Eighth month 18th.

Thy letter of last Third-day was agreeable to us.
Every circumstance and incident which occurs to thee, interests me,
because I feel so deeply for thy welfare, and so ardently desire thy happiness.

I know that evil-doing and misery are connected, as also well-doing and comfort.
When we have done wrong, whether in greater or lesser matters,
if we are sensible of our error, and seek to our Heavenly Father for forgiveness,
He will pardon our transgressions.
I want thee, dear, often to read in the Bible.
There thou wilt find that all have sinned, that all need repentance,
that our blessed Saviour came into the world to save sinners, to call them to repentance,
to suffer for them, to die for them!
What gratitude ought to fill our hearts towards our Divine Redeemer;
how ought we to open our minds to receive Him spiritually! for He
does appear in those who are made willing to forsake every evil way.
He appears as a cleanser and purifier of the children of men,
gradually washing away all impurity of thought, all envy, malice, unkindness,
enabling us to live in love one with another,
and to love our gracious God with all our heart, and soul, and strength.
My breathing to my Heavenly Benefactor for my dear child is,
that she may experience this,
and may become one of the adopted children of the heavenly family,
even while she lives on earth.
How would it console me, and enlarge my happiness!
I speak not these things as finding fault with thee.
So, my dear, thou hast for the most part, been to me a dutiful, and I believe,
always an affectionate child;
but from the sense I have that it is necessary all
should experience what the Scriptures term regeneration,
without which we cannot enter the everlasting
kingdom of our Lord and Saviour Jesus Christ.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To the Same

[.signed-section-context-open]
Eleventh month 4th.

Thy grandmother and aunt Mary continue their attention to the poor and distressed.
In addition to considerable attention to the orphan asylum in Southwark,
the former is banded with a little company who
are seeking the welfare of female prisoners,
not only by visiting and conversing with them on week days,
and supplying the most destitute with clothing,
but also collecting them every First-day and reading to them from the Scriptures,
and other religious writings.
On such occasions Friends sometimes speak to them in the love of the Gospel,
desiring that they may be converted from the evil of their ways.
I have been present a number of times on these occasions,
and have had to admire the goodness of the Lord,
who is waiting to be gracious even to such wretched outcasts.

But oh! my child,
what misery do those escape who are so wise as
to choose Him for their portion in early life,
and dedicate their lives to his service.
May this be thy happy experience,
and whether thy future life be marked by prosperous or adverse circumstances,
it will be comparatively of little importance.
Time is short, the human soul is immortal,
and so to live as to secure a blessed immortality, is the one thing needful.
Try then every day to increase in humility, love and the fear of the Lord,
which keeps the heart clean,
and to be found every day in the exercise of such tempers and
dispositions as thou wouldst wish to be found in at the hour of death.
This habitual preparation for the solemn hour of departure,
though it would check all giddiness and levity,
would not interfere with the cheerfulness natural to youth.
Surely they have the best right to be cheerful whose minds are kept in innocency,
and who have the Lord for their friend.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To the Same

[.signed-section-context-open]
Twelfth month 12th.

Thy grandmother continues improving, and thy aunt Mary is about again.
We had last evening information from thy uncle in
Susquehanna County by one of their neighbours.

He brought a letter from thy uncle John written very cheerfully.
He keeps school this winter and is paid so many bushels of corn a quarter.
To fill up time profitably he makes shoes of an evening, his wife sitting by at her work,
and thy uncle Nathan reading aloud.
It would gratify me to pop in on them some evening, and see how they look;
but the distance renders an excursion there a serious affair.
Hast thou heard that it is expected Cousin Edith Sharpless^
footnote:[A daughter of Nathan Sharpless.
George Martin deceased Seventh month 26th, 1847, having been an elder several years.]
is ere long to be married?
The Friend to whom she is to be united is spoken very favourably of.
His name is George Martin.

I have been this afternoon to attend the funeral of Jane Silliman, sister of Harriet,
who lives with Jane Canby.
She heard about three weeks ago of the death of her father,
which took place at a distance.
She appeared much affected, soon took to her bed, gradually weakened,
and died yesterday morning,
lamenting that she had not in early life chosen a religious course.
At such a solemn hour, of what unspeakable importance must it be to feel the assurance,
that having embraced the Saviour`'s love as our inheritance,
and followed Him in the way of self-denial,
his supporting power is felt to be underneath in the last struggle of expiring nature.
Embrace religion, my dear child.
Though it makes us serious it does not make us gloomy.
On the contrary, it leads to cheerfulness, gilding the sorrows of the present scene,
and opening bright prospects of a future world of blessedness.

How incomparably more desirable is such a life, than one passed in the bondage of sin?
For however splendid the transgressor`'s course may be,
sin and misery are indissolubly connected even in this world,
and the prospect of what awaits the impenitent when
death has dissolved the connection with this world,
is awful to think of.
Mayest thou and I, and my whole family, so lean upon the Saviour of men,
and receive Him as our Redeemer and Sanctifier,
that we may be accounted worthy to obtain that blessed
inheritance which is prepared for the Lord`'s children,
being carried by angels into Abraham`'s bosom, enabled to rejoice,

[verse]
____
No wanderer lost,
A family in heaven!
____

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to Joshua Sharpless

[.signed-section-context-open]
Philadelphia, Third month 6th, 1824.

[.salutation]
Dear Father:

William Poster has lately been in the
city holding public meetings with Friends and others.
He has since gone to Bucks Quarterly Meeting, and is now, I expect,
attending meetings within its limits.
His present prospect, I believe, is not to be at our Yearly Meeting, but to go eastward.

Our friend Hannah Elliott continues in a low declining state,
and probably we shall have her with us but a short time.
As we have good hope concerning her,
there is no cause of mourning except for some she leaves,
who are closely united to her in the bonds of religious friendship, and for the Society,
in which her example of simplicity and dedication will be missed.
On considering how we are stripped of devoted servants and handmaidens,
the wish seems involuntarily to arise,
that more of our youth would submit to the preparing Power, that,
by separating them from a worldly spirit, and uniting them to Christ,
our Holy Head would qualify them to take the places of those
who have entered and are about to enter their everlasting rest.

Dear father, may the gracious Shepherd himself be near thee in all thy trials,
sustain thy drooping mind;
renew thy ability to wait with patience all the appointed time until thy change come,
that at the last thou mayest feel the grateful arisings of
praise unto Him who has been with thee all thy life long,
and who having loved his own, loveth them unto the end.

And for dear mother, I feel most affectionate desires, that her Master,
whom she has desired to serve in integrity of heart,
may spread over her the shadow of his wings, support her under trials,
and centre her in a qualification to say "`Thy will be done,`" Then
will she see that every dispensation from the Lord`'s hand is in mercy,
and designed to do us good, to prepare, it may be,
through many tribulations from within and from without,
for an entrance into that blessed state,
"`where the wicked cease from troubling and the weary are at rest.`"

The time that brother waits is short, or in the love I feel, I could embrace you all;
dear sister Phebe in particular, who is often affectionately remembered, and, who,
being one of those on whom the burden and heat of the day is devolving,
I doubt not often feels clothed with a sense of insufficiency.

Well, this emptying prepares for being filled.
May she remember the promise, "`As thy day is, so shall thy strength be.`"
Again, "`Thy eye shall see Jerusalem, a quiet habitation,
a tabernacle that shall not be taken down;
not one of the stakes thereof shall ever be removed, nor one of her cords broken.`"

--

[.embedded-content-document.letter]
--

[.letter-heading]
To His Daughter Susanna.

[.signed-section-context-open]
Fourth month 22nd.

We have had thy uncle Cheyney,
aunt Martha and Ann Rogan as lodgers this Yearly Meeting,
though a number of our friends have called to see us.
Amongst the strangers attending are Anna Braithwaite and Isaac Stevenson from England.
The latter, we understand, proposes taking tea with us tomorrow evening.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To the Same.

[.signed-section-context-open]
Fourth Month 30th.

Shouldst thou return in my absence I have one request to make, which is,
that thou wilt not visit much until I see thee;
perhaps not beyond thy grandfather`'s and uncle Joseph +++[+++Walton`'s],
unless some peculiar circumstances seem to require it.
I wish some conversation with thee on the subject of visiting generally,
as well as other subjects relative to thy comfort and future prospects.

--

+++[+++Susanna returned from Westtown, Fifth month 12th, 1824,
and for sometime devoted herself to domestic duties.]

[.embedded-content-document.letter]
--

[.letter-heading]
Stephen Pike to Thomas Kite

[.signed-section-context-open]
Burlington, Fourth month 30th, 1824.

[.salutation]
Esteemed Friend:

I received thy acceptable communication of the 27th.
It may be said to have come in anticipation of my wish,
for, having missed of the advantage I have annually enjoyed,
of attending our Yearly Meeting, and feeling, in my measure, as a member,
with the body of our heretofore much favoured church,
I had thought of requesting that thou wouldst endeavour to convey to
me some views of the circumstances of its deliberations;
and this thou hast done.
I was not without some apprehensions that the dignity and solemnity
of the meeting might be materially affected by some of the restless
spirits who appear to have conspired from one motive or other,
to destroy in part at least, if not entirely,
the hedge which I have never doubted was planted around our vineyard, through favour,
by no human hand.
In looking towards the meeting, at various times, I felt a degree of confidence that,
notwithstanding the unfruitfulness of many portions of the enclosure,
and the wild nature of the fruit of some others, the time had not arrived,
nor was even near, when the sentence,
"`I will take away the hedge thereof,`" should be put in execution.

The firmness and steady perseverance of the "`aged servants,`" as well as
the secret fervent desires that the good cause should be maintained,
which are cherished by great numbers in less conspicuous situations,
have obtained for us a suspension of that fearful sentence.
Much I wish that the gratitude to which thou hast alluded,
may be experienced to work its proper effect on our individual conversation and actings,
and thereby secure to ourselves a continuance of preservation
from the quarter whence alone it can be derived.

I had heard before incidentally of the firm and effectual stand which
our highly valued friend John Cox was enabled to make,
with others, against the encroachments of a disorganizing spirit;
and have felt towards them an additional kindness on that account,
though sensible that the praise is due elsewhere.

--

[.offset]
+++[+++The following letter was written to a young female who had lost a brother.]

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to M. B. U

[.signed-section-context-open]
Philadelphia, Seventh month 12th, 1824.

[.salutation]
Dear Mary:

I returned home from New York on Fifth-day,
having the interesting company of William Jackson and his wife.
It has long been to me a source of peculiar satisfaction to
associate with such veterans in the Great Master`'s cause,
whose sweetness of spirit in old age indicates them "`like as a shock of corn
cometh in in his season`' to be nearly ripe for gathering unto the Heavenly Garner.
Such an intercourse prompts the rising wish,
that we of the younger ranks may be induced to follow them as they have followed Christ.
+++[+++If such be our experience]
then,
whatever clouds may occasionally rest upon our views
whilst treading the chequered paths of life,
they will all, through Divine mercy, be dispelled,
and "`in the evening time there shall be light;`" and peace, hope and confidence in God,
will go with us to the last confines of mortality.

Thou hast frequently been in my affectionate remembrance since
the pleasant visit I paid thee in thy rural retirement.
+++[+++That retirement]
I would fain cherish the secret hope, may, under the Divine blessing,
prove to thee a season of peculiar profit.
I have desired that as thou communest with thy own heart,
former days may be instructively called to remembrance,
the petitions and vows offered in the hour of affliction,
and the support then graciously vouchsafed.
Though there may not have been an entire devotion in following on to know the Lord,
yet I trust, desires after spiritual good are not extinguished,
and I believe the Lord ever merciful, waits to be gracious;
but then it must be on his own terms.
If we would be reconciled to God through the mediation of his dear Son,
our Lord and Saviour, we must take up the cross.

Thus it was the exercised mind of that brother, to whom thou wast so tenderly attached,
found rest.
How clearly was the doctrine of the cross opened to him in
that flood of light which was shed upon his departing spirit.
Remember, dear Mary, with reference to this lamented brother,
the sentiment of a pious writer:

[verse]
____
"`He mourns the dead who lives as they desire.`"
____

May it be the future steady engagement of thy soul to
follow in that path which leads to blessedness,
bearing the cross and despising the shame.
Then, when thy day of probation shall be over,
thou mayest rejoin him in that state of being where "`adieus and
farewells are a sound unknown,`" and surviving friends may say,
"`Lovely in life, and in death not divided.`"

--

+++[+++The following letter is supposed to have been written about this time.
A rough copy, or the original, was found among Thomas Kite`'s papers, endorsed by him,
"`Sketch of letter on H. G. F.`'s decease.`"]

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to Phebe

[.salutation]
Dear Friend:

It so fell out that I did not hear of your late
affecting bereavement until some time after its occurrence.

When communicated, it naturally introduced my mind into feeling with you,
especially as I had so recently been on several occasions with the dear deceased,
for whom I entertained a true respect, and with whom I was united in Gospel fellowship.
The retrospect of the time spent in her society when lately in New York,
is tenderly interesting, because I then beheld her fast ripening for eternity.
I +++[+++cannot]
now entertain the shadow of a doubt, that as a shock of corn cometh in in his season,
so she is gathered by the Great Husbandman into his heavenly garner.
I trust the same conviction has had a tendency to alleviate your sufferings,
to centre your minds in an endeavour after entire resignation,
and even to console under the loss of her sweet society, in the prospect that to her,
to "`die was gain.`"
Having loved and served her Saviour--followed him in the regeneration--
washed her robes and made them white in the blood of the Lamb,
she is now associated with those purified spirits who enjoy a happy immortality.
What then remains, but that you her children, may let her, though dead, speak,
"`Follow me as I have followed Christ.`"
In renouncing the fascination of a world which lieth in wickedness,
and following the footsteps of the flock of the companions of Christ,
you will enjoy a serenity of mind, of which no words can convey an adequate idea.
The Holy One of Israel will be your "`Sun and your shield,`"
affording light and protection to guide and to guard you,
not only through the slippery paths of youth, but throughout your earthly pilgrimage,
until you also arrive at a peaceful settlement in that city, whose walls are salvation,
and her gates praise.

Though these lines are more particularly addressed to thee, dear Phebe,
I have not been able, as thou wilt perceive, to separate between Maria and thyself.
The same love and hearty well-wishing attends you both, and also thy married sisters,
less known to me.
To thy dear father, please mention my love and sympathy.
He knows, under so deep a bereavement,
the cisterns of human consolation can hold no water,
and that the fountain of everlasting mercy, can alone afford an availing supply.
The God of all consolation can alone heal the broken in heart,
and bind up all their wounds.
May it be his experience to realize the fulfilment of the promise,
"`Call upon me in the day of trouble, I will deliver thee, and thou shalt glorify me.`"

--
