== Chapter XII.

1838

Letters--Death of John Justice--Death of Benjamin Kite--Marriage of William
Kite and Mary F. Clement--Visit to Concord Quarterly Meeting--Memoranda.

Thomas Kite to his daughter Susanna.

Philadelphia, Second month 11th, 1838.

Dear Daughter:--The poet Cowper, somewhere in the "`Task`" has this reflection:
"`How various his employments,
whom the world deems idle`" and lest that portion of the world
which occupies a certain farm in East Bradford,
should deem me idle, and one of them,
because I have delayed my acknowledgement of the
receipt of a very kind and acceptable letter,
I will endeavour to give a small account of my employments for
a portion of the preceding two or three weeks.

It had been concluded that the scholars in our Select School,
after a careful review of their studies,
should undergo an examination in the presence of the committee.
That for the boys commenced on Fifth-day, the 25th of last month.
Our morning meeting prevented my being there, but in the afternoon,
and on Sixth-day morning, I was present.
Sixth-day afternoon I had to attend a meeting of the Overseers of the Public Schools;
but on Seventh-day I was at the conclusion of the examination of the boys.
I was, as usual, at three meetings on First-day;
and commenced with attendance on the girls`' examination on Second-day.
It continued until Sixth-day evening, excepting that the girls, as usual,
attended our Week-day Meeting.
I was there morning and afternoon, until the conclusion,
when a satisfactory religious opportunity was had with the girls.
In both schools the proficiency of the scholars gave just pleasure to the committee.
On Seventh-day was our Select Quarterly Meeting;
and in the afternoon I had to prepare the business of the approaching meeting,
by digesting the Answers to the queries, reports on spirituous liquors, etc.
On First-day, three meetings again.
On Second-day we had a long and exercising meeting,
in which we had the company of Joseph John Gurney.
On Fourth-day I was at the Western Meeting in the morning,
and at a meeting of the committee on teachers for Westtown School, in the afternoon.

On Fifth-day I was at Abington Quarterly Meeting, held at Germantown,
where I saw Samuel Rhoads, Sarah Emlen and Hannah Rhoads, of your Quarterly Meeting,
and Elizabeth Pitfield, of our own, besides a number of other Friends.
It was a good meeting.
It is perhaps needless to pursue the sketch further,
but thou canst readily fill up these outlines--with
copying the minutes of the Quarterly Meeting,
occupying about eight pages--purchasing goods for Westtown--
occasionally marketing--buying groceries--some reading--some resting,
etc, and having done so, I think thou wilt frame an excuse for any apparent neglect.

Joseph John is engaged in visiting the families of the Northern District Monthly Meeting.
He has paid us a short visit, and seems affable and conversable.
His voice resembles that of Hannah C. Backhouse, who is, I believe, his first cousin.
I should take him to be six feet high, and well proportioned.
He looks like John Bullock; his age is about forty-eight,
and he is very gray for his time of life.

Thomas Kite, in the early part of the Third Month, this year,
paid a religious visit to the meetings composing Salem Quarterly Meeting.

In the Fifth Month he was again appointed by the Quarterly Meeting of Philadelphia,
one of a committee to visit Muncy Monthly Meeting.
Pretty soon after the Quarterly Meeting, the committee, filling two carriages,
started to fulfill their appointment; they consisted of George Williams, Thomas Kite,
William Evans, Joseph Snowden, Sarah Hillman, H. Regina Shober,
Elizabeth C. Mason and Jane Clark.

Thomas Kite to his Wife.

Muncy, Fifth month 20th, 1838.

My Dear Wife:--I am comfortably seated in Mercy Ellis`' back parlor, pen in hand,
prepared to communicate a brief account of our proceedings.
We started,
as thou mayest remember on Seventh-day week +++[+++12th]. That night we reached Pottstown.
On First-day morning William Evans and company went to Exeter Meeting,
exchanging Sarah Hillman, of our band, for R. Shober, of theirs.
The rest of us attended Pottstown Meeting, which was small,
but measurably owned by the Good Master.
We dined at Sarah Potts`', and went on to John Lee`'s in the afternoon,
rejoining our company.
One of the horses attached to William Evans`'
carriage having misbehaved on various occasions,
and caused some alarm, was here exchanged for a safer one.
On Second-day we travelled on to Orwigsburg, and lodged.
On Third-day we reached Catawissa.
I believe it was this day, walking up a mountain, I heard the warning of a rattlesnake,
and looking round, beheld him coiled near me.
I quickly stepped out of his way.
On Fourth-day we reached David Masters`', at Fishing Creek.
On Fifth-day called at Andrew Eves`',
and proceeded to their Preparative Meeting at Greenwood, held in the new house,
with which we were much pleased.
Here we separated for dinner, our party going to Thomas Mendenhall`'s,
the other to Josiah Haycock`'s. We went again to A. Eves`', and lodged.
On Sixth-day started for Muncy, arriving at Jacob Haines`' to dinner,
and proceeding in the afternoon to Mercy Ellis`' hospitable mansion.
It was settled for William Evans, Joseph Snowden,
Elizabeth C. Mason and Regina Shober to go to the Elklands;
and they started on Seventh-day morning, accompanied by our guide and friend,
Henry Ecroyd.
We who remained, occupied the day in visiting some families,
and in taking opportunities with some who still hand ardent spirits to their workmen.
To day we have been at meeting here, which held until about half-past one,
and was satisfactory.
We have continued also similar engagements to those of yesterday;
some of the opportunities both days being to our comfort.
We propose going to Pine Grove to morrow, and have a meeting with those under our name,
who reside there, and return in the evening; when, we hope,
our Friends will have accomplished their visit to the Elklands, and meet us.
On Third-day we propose going to Fishing Creek,
in order to attend the Monthly Meeting to be held on Fourth-day at Greenwood;
after which, our prospect is to attend Exeter Monthly Meeting on the following week.

Amongst the families visited is that in which Elizabeth Kately resides,
who seems green and lively at the advanced age of ninety-five,
going up and down stairs without assistance.
With love to my dear parents, to thyself and children, I am thy truly attached husband.

Rebecca Kite, Jr., having gone to Westtown as teacher, her father thus writes to her:

Philadelphia, Sixth month 22nd, 1838.

Dear Daughter:--Thy letter, which came by the stage on Fifth-day, was very acceptable.
It would seem by the information contained in it,
very doubtful whether our friend Sarah Ann Dillon,
will be raised from her bed of sickness.
I wished to be informed by every stage of the progress of her illness,
feeling a deep interest in her welfare,
and strong desires that when her warfare is accomplished,
she may be found amongst those who not only have come out of great tribulation,
but have also washed their robes and made them white in the blood of the Lamb.

Information has been received that our dear friend, Jacob Green,
was prevented from attending Dublin Yearly Meeting by a severe illness.
Of course his concern to visit this country lies over until next year.
We hear he is recovering from his sickness.
It would have been very pleasant to some of us again to have seen him in this land;
but let us not forget that the Lord can work without instruments when He sees meet,
and can raise up helpers to the Truth from very unexpected quarters.
May we all look to Him, and cease from a dependence on man, and keep to inward exercise,
and it may yet please the Great Head of the Church to
revive his work in the midst of the years,
and to turn our captivity as the streams of the south.

We hear that our valued Friend, John Barclay, is deceased,
which is no doubt felt as a great loss by faithful Friends in England.
I do not seem to have much to communicate, it being a season of depression,
from various causes, with me; but whether mourning over my weaknesses,
or lifting up my head in hope, I can truly say, in all states,
my desire for my children is, that their inheritance may be in the everlasting Truth,
and, that having served the Lord in their generation,
their portion may be forever with the ransomed and redeemed.
So wisheth, so prayeth, for thee, my dear Rebecca, thy affectionate father.

To the Same.

Sixth month 19th.

"`I trust that thou wilt not only be usefully employed in the school,
but that the consciousness of being for the present in thy proper place,
will produce heartfelt contentment.
Thy advancement in the way everlasting is the dearest wish I have for thee;
and I feel a secret hope that even this all-important object may be
promoted in some degree by this little surrender of thy own will,
through the tender mercy of Him who can cause all
things to work together for good to them that love Him.`

Thomas Kite to E. S. F.

Philadelphia, Sixth month 23rd; 1838.

Dear Friend:--My Rebecca has gone to Westtown to fill
for a short time the place of Sarah Ann Dillon,
as writing teacher.
Sarah Ann is very ill, and her recovery doubtful.
Many are the admonitions we get,
not to postpone the great work of preparation for the life to come, to a sick bed.
I mean not to insinuate this has been her case.
I believe she was when in health, a religiously inclined young woman;
but I wish to encourage thee to act up to thy own convictions,
steadily bearing the cross,
and waiting every day for power from on high "`to
crucify the flesh with its affections and lusts.`"
We must be born again of incorruptible Seed and Word, which liveth and abideth.
Short of this there is no true settlement of mind, no true peace, no true joy,
no entrance into the everlasting kingdom of our Lord and Saviour Jesus Christ.
+++[+++After alluding to the postponement of Jacob Green`'s visit as already mentioned,
he continues]. As regards himself at present, the will is taken for the deed.
Many would have rejoiced at seeing him,
who have had evidence that he is an anointed and baptizing minister of Christ.
But if our minds are happily turned to,
and centered on the great Minister of the Sanctuary,
we shall not so much regret the loss of instrumental help.
The Lord is able, from very unexpected quarters, to raise up helpers to the Truth;
of the stones of the street to make children of Abraham,
and to cause the dust of Zion to praise Him, yea,
out of the mouths of babes and sucklings to perfect praise.

Also, we hear that John Barclay is deceased.
An excellent writer, a minister of the Gospel, descended from Robert Barclay,
the Apologist.
It seems natural to feel the loss of such, in a low time;
yet we know the Lord remaineth the foundation of the righteous generations.
With sincere desires for thy preservation from evil,
and for thy growth in sincere heartfelt, vital religion, I remain thy friend.

Thomas Kite to his daughter Rebecca.

Seventh month 20th, 1838.

Last First-day morning I found my mind drawn to attend, the North Meeting.
Very unexpectedly I found our friend John Justice there.
I had heard a few days before that he was sick and like to die;
and indeed he seemed as to his outward man, in a very poor way.
But he was evidently raised up in the exercise of the Gospel Ministry,
to the comfort of some who are bound in heart to
the ancient testimony of the everlasting Truth.
I think he will not continue in this mutable state long.^
footnote:[See "`The Last Days of John Justice`" in "`The Friend,`" 1838.]

Thomas Kite to his daughter Rebecca.

Seventh month 31st, 1838.

The funeral of our relative, Mary Phipps, took place yesterday.
There was less difficulty with the body than was anticipated.
Notwithstanding its great size and weight, it was removed down stairs,
without much trouble, by six men.

On Seventh-day night thy grandfather rose from his bed to look at his watch,
and being taken with a vertigo, fell against the corner of a bureau,
and hurt his knee--the neighbourhood of his hip--and one of his hands.
He lies in bed, and is unable to help himself;
neither can he be moved by others without much suffering.
We hope the principal injury is a strain, that will be relieved.
I am not sure whether I mentioned meeting our friend John Justice at the North Meeting.
I did so last First-day, two weeks.
His testimony was remarkable, but he seemed very feeble.
We hear he got home; was at his own meeting on the following First-day,
and last Sixth or Seventh-day departed this life, rather suddenly at last,
though he had been for some time unwell.

From Thomas Kite`'s Diary: "`On the 16th of the Ninth month, 1838, my father died,
having attained the age of eighty-four years and eight months.
He resided in my family for several years previous to his death.
He was confined to the house for a few weeks,
in consequence of a fall received in his chamber; prostration of strength ensued,
and he departed this life with little apparent bodily suffering.
His love to the Truth continued unabated to the last, and his end was peace.`"

Amongst Thomas Kite`'s papers the following was found.

Last illness of Benjamin Kite.

Our father deceased Ninth month 16th, 1838, in the eighty-fifth year of his age.
The failure of memory, incident to an advanced period of life,
had been for sometime perceptible in him; and his bodily power weakened;
yet he was generally able to attend religious meetings.
In those for discipline he continued to take a deep interest,
and especially so in our late Yearly Meeting;
in those for worship he retained a lively frame of spirit.
At no period within our remembrance had it been otherwise; but we thought it remarkable,
that when age had in some measure subdued his natural powers,
not the least drowsiness on these occasions was apparent in him.
He was an example of a fervent, living worshipper to the last.
As a further evidence that his religious sensibility was unimpaired,
we often took notice,
that in reading aloud any composition in which the character and
offices of our Holy Redeemer were set forth in appropriate terms,
he frequently became so much affected as scarcely to be able to proceed.
He appeared to think his days`' work accomplished,
and to be quietly waiting for his dismission.

On the morning of Seventh month 28th, he fell in his chamber,
and straining the muscles of one side, he was afterwards entirely confined to his bed.
Loss of appetite ensued, and weakness gradually increased.

Eighth month 11th, he remarked, '`It has seemed to me for several days,
as if the Almighty would take me in this way;
and I can say Thy will be done on earth as it is in heaven!
That is my regular feeling.`'
To two of his nieces he observed, '`I am gradually going down to the grave.`'
Adverting to his close in a conversation with a grand-son, he said,
'`There is nothing in my way.`'

On the 14th he repeated this portion of one of the Psalms, '`Let God arise,
let his enemies be scattered, and let them that hate Him flee before Him.`'

Though depression of feeling had been previously but little perceived,
yet on the 19th he said he felt tried,
and seemed to be passing through much conflict of mind.
This day he was visited by a ministering Friend,
who addressed him in the language of encouragement, reviving this portion of scripture,
'`Though I walk through the valley of the shadow of death, I will fear no evil,
for thou art with me; thy rod and thy staff they comfort me.`'
This interview appeared to be consoling to him.
On the 24th, another Friend in the ministry, calling on him,
remarked that few had passed a more regular and innocent life than he,
but that this would not do to depend on.
When the Friend withdrew, he said: '`Oh, no! it is all of mercy;
I have nothing else to depend upon.`'

He frequently repeated this, as well as other comfortable passages of scripture,
'`The Lord hear thee in the day of trouble; the name of the God of Jacob defend thee;
send thee help from his sanctuary and strengthen thee out of Zion;
the Lord fulfill all thy petitions.`'
On one occasion,
as some of the younger members of the family were about
leaving the house to attend a meeting for worship,
he said, '`May the God of purity be with you that go, and give you good thoughts.`'
On Ninth month 11th, he said to one of his sons,
'`Though I enter the valley of the shadow of death with awe, yet it is not with fear.`'
Thus, preserved in humble, patient waiting, he gradually declined, until the 16th,
when he gently passed away, without apparent suffering, we trust,
to the everlasting inheritance.`"^
footnote:[See obituary in "`The Friend`' of this date.]

William Kite, with the approbation of his parents,
was married on the 8th of Eleventh month, 1838, to Mary F. Clement.

In the Eleventh month, Thomas Kite attended the meetings of Concord Quarterly Meeting.
In a letter to his wife, dated East Bradford, Eleventh month 17th,
after giving information of meetings at Darby, Goshen, Willistown and Birmingham,
he thus concludes:
"`I have found occasion in these several meetings to
endeavour to advocate the cause of Truth,
and in some more private opportunities to labour as ability has been afforded.
Yet, on the whole I have been in a rather low condition; but am content,
if I may but be preserved in my proper allotment, doing no harm,
and receiving the answer of peace.
I feel the need of watching unto prayer,
and desire that with me patience may have its perfect work.`"

Thomas Kite to his daughter Susanna.

Philadelphia, Twelfth month 28th, 1838.

Dear Daughter:--I thought I must write a few hasty lines,
to express our sympathy with you in your anxious cares about your suffering babe.
We know something of parental feelings in such a case.
May you be preserved in a state of resignation to Divine disposal,
and having done all you can to alleviate its sufferings,
commit the event to Him who doeth all things well.
Thy uncle James seems much better, which is quite a relief to our minds.
We have had Thomas and Elizabeth Robson to tea.
He is a very pleasant old Friend.
They were yesterday at our Monthly Meeting;
and were to set off this morning for the sea shore,
in pursuance of a prospect of visiting the meetings in New Jersey.

Thomas Kite to Martha Jefferis

Philadelphia, Twelfth month 28th, 1838.

Please give my love to cousin Ann.
I cannot put into words, nor need I, all the affectionate longings I feel for her.
She is one of the Lord`'s visited ones,
and through his aid has achieved some victories over the enemies of her peace;
but more conflicts are to be known,
more hardness as a good soldier of Jesus Christ is to be endured,
before the day will be fully enjoyed, which the evangelical prophet speaks of,
and which I fully believe our heavenly Parent designs she should experience;
"`in that day shall this song be sung in the land of Judah, we have a strong city,
salvation hath God appointed for walls and bulwarks.`"
I desire her encouragement.
I wish her to look forward,
not at the example of her fellow travellers towards the Holy City,
but at the pure and perfect example of Him who wore the seamless garment, and was holy,
harmless, undefiled, and separate from sinners;
that so through his power strengthening her, she may stand in her allotment,
clothed with the whole armor of light.

About the close of 1838, Thomas Kite,
having made a brief recital of the various religious engagements he had fulfilled,
with minutes of his meeting, adds:

"`In addition to these, I have several times been under appointment from the Quarterly,
and once from the Yearly Meeting, to visit Monthly and Particular Meetings;
besides which, I have often attended neighbouring Quarterly, Monthly and other Meetings,
as way has opened for it.
In these services I have had varied experiences;
sometimes wading under deep discouragements;
at other seasons humbly rejoicing in the renewed extendings of holy help;
for the most part earnestly desiring to be preserved in humility,
love and the fear of the Lord.
This is the feeling which at present covers my spirit;
and the prayer arises in the retrospect,
that I may be enabled to fill up my allotted portion of baptism and suffering,
for the sake of my dear Redeemer, as at length to finish my course with joy,
and the ministry I have received of the Lord Jesus,
to testify the Gospel of the grace of God.
In the year 1835 I was appointed clerk of the Quarterly Meeting of Philadelphia,
in which service I yet continue.
I have endeavoured, with Divine assistance, to fulfill the duties of this station,
under a sense of their weight and importance.`"
