== Chapter XV.

[.chapter-synopsis]
* 1841.
* Letters
* Yearly Meeting
* Edith Jefferis recommended as a minister
* Several letters
* Samuel Bettle and Nathan Kite visit Ohio and Indiana
* William Evans visits North Carolina
* Rachel C. Bartram`'s death.

+++[+++Thomas Kite, Jr., having purchased a foundry and machine shop in Cincinnati, Ohio,
his father thus wrote to him on the occasion:]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Philadelphia, First month 12th, 1841.

I have no doubt of thy industry, frugality and attention to business,
and yet a few hints may not improperly be offered for thy consideration.

In carrying on the important business thou hast undertaken,
keep such an oversight as to be acquainted with all its parts,
and particularly with the account books.
However trustworthy anyone may be whom thou employs,
a personal knowledge appears to me indispensable.

Keep a distinct cash book; and let it be balanced at least twice in every week;
my practice when in business was to do it daily.
Always examine whether the cash on hand corresponds with the balance.

Let no piece of work leave the premises without
the requisite entry having been first made.
A personal inspection will detect errors in quantity or price.

Avoid leaving balances due and uncollected.
Sometimes a considerable sum is absorbed in this way.
My master was accustomed to say that more money was
lost from not asking for it when it might be had,
than from any other cause.
Some people feel a delicacy about asking for money due them,
that seems rather out of place.
It ought always to be understood that men are at
liberty to claim what they are justly entitled to.
In making collections, be sure to call at the time mentioned by the debtor.

A bill book should be kept, and it might be well to have a memorandum book,
containing for daily inspection, an account of payments to be made,
as well as important business to be attended to.

Make it a practice to be punctual in thy own payments,
or if unforeseen contingencies render it impracticable, pay a part on account,
and ask as a favour an extension on the balance.

I scarcely need express my confidence, that whatever may be thy press of business,
thou wilt endeavour so to arrange it,
as not to interfere with the attendance of religious meetings;
but I would just hint my earnest wish that on these occasions thou
mayest be favoured to leave the world and all its concerns at home,
and through the fresh extendings of Divine love and mercy,
be made and preserved a living worshipper.

I have no doubt thou wilt continue plain and exemplary
in thy personal appearance and language;
and I earnestly desire that thy whole conduct
and deportment may be in correspondence with it.
Examples of uprightness in bearing these and the other
precious testimonies committed to our forefathers,
are much needed in the present day.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To the Same.

[.signed-section-context-open]
Second month 8th.

John L. Smith heard today of the decease of his sister Deborah,
which has been looked for, for some time.
There is reason to believe she made a good end,
having appeared increasingly serious for some time.
We have had a ministering Friend with us for some days, named Mead Atwater,
from the neighbourhood of Lockport, New York, with Benjamin Bowerman for companion,
an Elder from near Rochester.

They seem both worthy and humble-minded men.
Dost thou remember William Wetherill, the lame lad at Westtown?
He appears to be in the last stage of consumption, and will probably die to-night.
His conduct in some respects has been unguarded,
but there is good ground to hope he has been favoured
to experience repentance and a change of heart,
through redeeming love and mercy, and now seems quietly to wait for the great change.

--

+++[+++One of the inmates of Thomas Kite`'s family thus writes to his daughter Rebecca,
under date of Second month 22nd, 1841.]

[.embedded-content-document.letter]
--

John L. Smith seems to be clad with his usual cheerfulness, nearly.
Last evening, after reading, and a short silence, thy father spoke to us,
C+++.+++ W. being one of the company, of his young friend Deborah Smith, who,
he felt a comfortable evidence, had been prepared for,
and joined to that happy number who in heaven are enjoying their Saviour`'s countenance.
He said that for some time before her close,
she had secretly been maintaining the warfare against
the corrupt part which could not inhabit glory.
He pressed the necessity of our making ready for the change, as she had done,
and particularly craved for her brother, that he might be more in earnest,
as we know not when the messenger would arrive at our door.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to son Thomas.

[.signed-section-context-open]
Third month 12th.

Having written so often of late, I seem to have little more to add,
excepting the expression of the warm desire I feel for thy preservation.
Many are the dangers, in the most sheltered situations,
which attend our passage through the present world.
May thy attention be kept close to the heavenly Pilot,
that so thou may avoid the rocks and quicksands on which so many strike and perish,
and at last attain the port of everlasting peace.

--

+++[+++During the Yearly Meeting this year,
Thomas Kite manifested much concern in the various subjects coming before it,
speaking briefly at various times with much life and power.
On Sixth-day morning he adverted to the great number of valuable Friends who
had recently been removed from the church militant to the church triumphant;
and stated his belief there were several such with us,
who would never again assemble with their friends in this capacity.
He then expressed his concern that those upon whom the burden was now beginning to rest,
and on whom it would shortly more fully devolve,
might be rightly prepared to fill their allotted stations in the church.]^
footnote:[Of those present at this Yearly Meeting on the men`'s side,
who deceased before the next annual gathering,
the following Ministers and Elders were a part--Davis Richards, Samuel Atkinson,
Thomas Stewardson and Jesse Spencer.]

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to Elizabeth S. Fell

[.signed-section-context-open]
Fourth month 12th, 1841.

I received thy kind letter,
but various circumstances have hitherto prevented my making the acknowledgment;
and now I am principally induced to write to let thee know
that we have room for thee at our approaching Yearly Meeting.

It is natural for us to look forward to this
interesting occasion with some degree of solicitude,
and with secret desires that the right thing may prevail, and the mourners be comforted;
and if all who attend come with serious minds, and are favoured to keep their places,
we may hope that the wing of Ancient Goodness will again be spread over us.

I was quite interested in thy account of Martha Smith`'s expressions,
and should have been glad to have heard some further particulars.
It is, indeed, a great mercy that her eyes were so far opened as thy letter represents;
it would have been still more agreeable to have heard of penitential acknowledgments.
Several of the separatists have been favoured to see their error,
and have of latter time returned to us, offering satisfactory papers of condemnation.
There have been two such cases in the Western District, one in the Southern,
one at Uwchlan, and another in Burlington Quarterly Meeting.
There is also a female in this city who has forsaken their assemblies, attends ours,
and manifests a serious mind, who has not yet made an acknowledgment.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to Martha Jefferis

[.signed-section-context-open]
Fifth month 28th.

[.salutation]
Dear Sister:

This has been a week of considerable
interest as regards our Monthly Meetings.
On Third-day,
Joseph Snowden was nominated to the Monthly Meeting of which he is a member, an elder,
and the meeting united with it.
Elizabeth Pitfield and Sarah Hillman were each set at
liberty to attend Rhode Island Yearly Meeting,
and Joseph Snowden to accompany them.
On Fourth-day, Hannah Allen was appointed assistant clerk of her Monthly Meeting.
The same day, at an adjournment of the Western District Monthly Meeting,
the case of Rebecca Collins was considered,
and she recommended to the Select Quarterly Meeting as a minister;
and yesterday I was furnished by our Monthly Meeting with a minute to pay a
little debt of gospel love within the limits of Baltimore Quarterly Meeting.

It has been a comfort to me that cousin Edith +++[+++Jefferis]`'s
case was resulted in so satisfactory a manner.^
footnote:[Recommended as a minister.]
I hope, dear child,
she will be preserved in an inward attention to the puttings forth of the Good Shepherd,
and that she may be enabled to bear with patience those
baptisms which the fruit-bearing branches must partake of.
I hear she is now with thee; if it be so, salute her in my name,
as also dear Rebecca Biddle.
I hope the health of the latter is so far restored as
to permit her to fulfill her duties without oppression.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Rebecca.

[.signed-section-context-open]
Baltimore, Sixth month 16th, 1841.

As I suppose thy mother to be absent from home,^
footnote:[Gone to Muncy, on appointment of the Quarterly Meeting.]
I have concluded to write a few lines to thee, informing how we have fared.
We had a pleasant passage to this place on Seventh-day +++[+++12th],
and were kindly received at Hugh Balderston`'s. On First-day we attended meeting,
morning and afternoon, and took tea at William Proctor`'s. On Second-day,
we went to Gunpowder, distant about eighteen miles, having a hired horse and dearborn;
the horse was lame, and travelled slowly, otherwise our journey was agreeable.
The country diversified with hill and dale.
We put up at Thomas Scott`'s,
and had an appointed meeting yesterday with Friends and others,
to pretty good satisfaction.
In the afternoon returned to this city by another and more beautiful route,
calling on our aged friend, Ann Poulteney, who resides a few miles out of town,
and taking tea with her and four of her daughters.
In the evening I met with a friend from Hopewell,
with whom I have made arrangements respecting the more distant parts of my prospect.
This afternoon the Select Quarterly Meeting occurs; tomorrow that for business;
and on Sixth-day we expect to take the railroad car for Winchester, Virginia.

I seem to have very little to say, but thought my family would like to hear from me.
I do not wish to return before my service is fully accomplished, but when it is,
I believe I shall endeavour to be with you speedily.
With love to the whole family, I am thy affectionate father.

--

+++[+++In this visit he was accompanied by James R. Greeves.
A brief description of the close of this visit will be
found in the following letter to his daughter Susanna:]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Philadelphia, Seventh month 16th, 1841

[.salutation]
Dear daughter:

Did it occur to thy recollection that this is thy father`'s birthday?
I am now 56 years old,
and have abundant cause to acknowledge that goodness
and mercy have followed me all my life long.
May my closing years, whether few or many,
be more devoted to the service of my Divine Master than those which have passed;
and may my children be fully given up to serve Him in their day.
They will find Him, as the faithful have ever found Him, to be the best of Masters.
Thou, my dear child, art now coming a little forward in his service.
May He guide thee by his counsel, preserve thee in humility,
strengthen thee to fulfill his divine will, sanctify thee by his truth,
and prepare thee for his heavenly kingdom.

I would have given thee some particulars respecting my late visit,
but supposed cousin James would do it more fully by word of mouth,
than I could by my pen.
We travelled nearly five hundred miles, and I was at meeting but seven times, viz.,
twice at Baltimore, on a First-day; at Gunpowder, on Third-day;
at Select Quarterly Meeting, on Fourth-day, and the meeting for business, on Fifth-day;
at Hopewell, in Virginia, on the First-day following, and at Goose Creek the next day.
After which we returned home by way of Baltimore, and the railroad,
it being the first time I ever passed between that city and our own by land.
On the whole, I had a comfortable hope that I was in my proper place;
and though much weakness is apparent amongst our Friends,
yet evidence was renewedly furnished that the Lord hath not forgotten to be gracious,
but is extending his secret calls and visitations to
the different branches of our still favoured,
although in the parts I have visited, greatly reduced and scattered Society.

I was not very well whilst absent, nor for some weeks after my return.
Jesse Spencer has several times invited us to pay his family a visit, so, in hopes it
would prove beneficial to my health, thy mother, sister Rebecca and I,
concluded to go to Gwynedd on Fourth-day week.
On Fifth-day we attended their week-day meeting;
and in the evening Jesse took us to his brother George`'s, at Moreland.
We found the latter expecting to go next morning to Frankford,
to attend the funeral of Jonathan P. Knight, and Jesse and I concluded also to go.
It was largely attended; and Sarah Hillman was strengthened at the grave,
pertinently to address those who were present.
We returned to Moreland, took tea at Charles Spencer`'s, a cousin of Jesse,
where we met thy mother and sister,
and called at Samuel Spencer`'s (a brother of Charles) on our way to George`'s,
from whence we returned the same evening to Jesse`'s.
Seventh-day morning I walked to see Phebe Roberts,
Hannah Williams`' married daughter, who has, of late,
appeared at times in the line of the ministry.

In the afternoon we went to her mother`'s, at Plymouth, where we took tea,
and returned home by the Norristown railroad, arriving in the city before dark.
I think I was benefitted in my health by this little excursion.

--

+++[+++During his visit in Virginia, Thomas Kite called at the dwelling of a minister,
an honest, simple-hearted Friend, who lived in great simplicity.
Soon after his return he received the following letter from his late host, viz.]

[.embedded-content-document.letter]
--

[.salutation]
Dear friend:

Thy little visit to our habitation was so pleasant,
and has left so sweet a feeling upon our minds,
that I feel as though I cannot be satisfied without expressing it.

I am thankful thou wast not discouraged from it, as it made our hearts glad,
under a belief that the Great and Good Master inclined thee to it.
I hope thou wast favoured to reach home with the reward of peace,
for having paid the little debt which, no doubt, was due from thee to Baltimore,
and some other meetings.
The church here is not in a very flourishing state,
the world having engrossed the minds of too many of our members,
who seem to forget that they owe themselves, and all they are favoured with,
to the goodness and mercy of their Heavenly Father.
Oh! when will this strange and unnatural course
of life be exchanged for one of gratitude,
of love.
For myself, I trust I can say,
I had rather see the kingdom of the Holy Jesus
gaining ground in the hearts of the people,
and so spreading over the nations of the earth,
than to enjoy all the honours and pleasures of a transitory world.
Truly the peace He bestows upon those who humbly endeavour to follow Him,
and keep his commandments, is superior to everything else.

Well, dear Thomas, remember me and mine before the Father of Mercies, and pray for us,
that we may be made more and more partakers of the love
of God and the communion of the Holy Ghost,
and continue therein to the end.

[.signed-section-closing]
Affectionately thy friend,

[.signed-section-signature]
S+++.+++ F. B.

--

+++[+++In regard to this journey, Thomas Kite made the following short memorandum in his Diary:]

[.small-break]
'''

Having obtained the requisite permission of the Monthly Meeting, in the Sixth month,
1841, I visited nearly all the meetings composing Baltimore Quarterly Meeting,
having cousin James K. Greeves for companion.
Although many painful feelings attended,
and the state of our religious Society was low in most places,
yet I was favoured to get through mostly to my relief.
A fear, however, attended, that in the latter part of the engagement,
the desire of getting home was too much given way to.
May it operate as a caution on future occasions.

[.small-break]
'''

+++[+++Thomas Kite, Jr.,
having paid a visit to his relatives in Philadelphia and its neighbourhood,
returned home to Cincinnati, taking Niagara in his way.
Soon after his departure, his father addressed to him this letter.]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Philadelphia, Seventh month 19th, 1841.

[.salutation]
Dear Son:

I cannot avoid feeling some degree of anxiety respecting thy homeward journey,
and am looking forward with solicitude for a letter
announcing thy arrival in thy adopted city.
I trust a merciful Providence has watched over thee for good,
and that thy Heavenly Father has purposes of kindness in store for thee,
if thou art willing to bow to the visitations of his Holy Spirit.
The disappointments He permits to befall us, all pleasing and all adverse allotments,
health or sickness, poverty or riches, may be made subservient to our best interests,
if our hearts are set on Him.
All things shall work together for good to them that love God.
I felt an unusual solicitude whilst thou wast lately with us,
that thou may not rest satisfied short of the experience of that change of
heart which is described in the Scriptures as a new birth,--regeneration.
In order to this,
thou must deny thyself of everything the Divine Light discovers to be wrong.
Thou must take up thy cross daily,
and endeavour to follow the Lord Jesus in the way of his leadings.

I have great confidence in thy outward conformity to
the rules and testimonies of our Society.
I am thankful I can feel as I do in this respect, confidence in thy morals;
confidence in thy rectitude as a man of business.
But if thy Heavenly Father should show thee that
greater circumspection is needful in some particulars,
give heed to his Divine intimations.
With respect to the society of young persons,
I am not informed on what footing social intercourse is carried on in Cincinnati;
but in some places a manner prevails that is too free, bordering on levity.
There may be an opposite extreme, of too great reserve, but it is a safer one.
Young women should be treated with great respect.
I think there has been a great improvement in this respect with the younger
members of our Society within my memory,--I mean in country places.
I hope it will extend to every part of it, for sure I am,
our principles lead to the adoption of whatsoever things are pure, excellent, lovely,
and of good report.
I have poured out my feelings without premeditation; the drift of it all is,
I wish to see thee a consistent Christian, a living, baptized member of the Church;
one that in public assemblies, and in private retirement,
has access to the Living Fountain of pure spiritual refreshment.
Be not discouraged from persevering, if the attainment should seem difficult;
through many tribulations the righteous enter the kingdom;
the prize at the end of the race is worth all the sacrifices we can make to obtain it.
This is the prize--this is the promise:
eternal life,--happiness without alloy and without end!
But let us always connect with the consideration of these important subjects,
that solemn admonition, "`Without holiness no man shall see the Lord.`"

--

[.embedded-content-document.letter]
--

[.letter-heading]
Same to Same.

[.signed-section-context-open]
Eighth month 16th.

Thy travels to the Falls, and description of it, we have become acquainted with.
Do not forget to tell us how thou fared in getting home.
Our Rebecca Walton is in expectation of setting out tomorrow morning for Mount Pleasant.
She has for company our old friend, Jane B. Temple, etc., etc.
Thou hast, no doubt, heard of the burning of the steamboat Erie,
on the lake of the same name, with the appalling loss of life.
It has raised thankful emotions that a kind Providence watched over our beloved son,
and led him in safety to his distant home.
May it be increasingly thy concern to live to the glory of his great name;
and this can only be done as thou art willing to bring thy outward conduct
and inward thoughts and desires to the test of that Divine Light,
wherewith thou and all men are enlightened,
by its assistance to discover what the Lord`'s controversy is against,
and by his Divine aid, to put it away.

--

+++[+++Extracts from letters of Thomas Kite to his brother Nathan,
whilst the latter was with Samuel Bettle attending Ohio and Indiana Yearly Meeting.]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Ninth month 5th.

Thomas B. Gould accomplished his marriage on Third-day.
The meeting was remarkably solemn.
The newly-married pair, with Thomas`' sister and Martha`'s mother,
departed for their residence on Sixth-day.
We were last evening invited to the funeral of our cousin, Isaac Jones,
which takes place today at Germantown.
Edith and I are about starting to attend it.

Ninth month 12th. Samuel Bettle, Jr., has gone with Regina Shober to Exeter,
which meeting, I believe, she omitted on her way to Bellefonte.
William Evans has found a pair of horses, and proposes to set off next Sixth-day,
after the Meeting for Sufferings.
He expects to take Goose Creek and Hopewell Meetings on his way south,^
footnote:[To visit the meetings of North Carolina Yearly Meeting.]
of which I am glad.
Thou art aware, perhaps,
that John Wilbur has had a severe attack of pleurisy since his limb was fractured.
Dost thou remember to have heard of his daughter Foster, a minister?
It seems she has a son of uncommon promise, who has lately appeared in testimony,
in his thirteenth year.
He commenced with, '`This is a faithful saying, and worthy of all acceptation,
that Jesus Christ came into the world to save sinners, of whom I am chief.`'

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to Martha Jefferis.

[.signed-section-context-open]
Ninth month 28th, 1841.

I do not expect to attend the examination +++[+++at Westtown],
but have thought of being at the school in time to meet
the Committee on Instruction on Fifth-day evening.
Smith Upton and Sarah B. Thompson are proposing to
take each other in marriage on Fifth-day next.
My wife and I are appointed to attend on that occasion.
William Evans and Jeremiah Hacker were heard from yesterday;
they had reached Goose Creek, in Virginia, and were in comfortable health.

Ebenezer Roberts was in the city last week, attending our Monthly Meetings.
He was more extensively engaged in ministerial
labours than I have heretofore known him to be;
his visit was acceptable, he being an honest-hearted Friend.
I note thy remarks respecting the uncertainty of thy prospects
after thy engagements at the school shall terminate.
There is no use in straining our eyes by endeavouring to see in the dark.
Be encouraged to keep fast hold of the anchor of faith; wait on the Lord,
and He will in his own good time open a way.
To be where He would have us to be,
and to be doing or suffering what He would have us to do or suffer, ought to content us;
because as his will is our sanctification, that state of purification He designs for us,
can only be attained in the resignation of our will to his.
Dear sister, I do not write these things as new,
but simply because they arose as I was writing.
I trust He who has been with thee from early life,
and strengthened thee to bear the burden and heat of the day,
will continue so to be to thee a Father and a Friend,
until thou hast finished thy allotted portion of labour,
and art prepared to take thy flight to the land of rest.

--

+++[+++On the evening of Tenth month 3rd,
a religious opportunity took place in Thomas Kite`'s family,
which one of those present thus describes:]

[.embedded-content-document.letter]
--

Our dear father appeared in supplication, first, for the female head of the family,^
footnote:[Edith Kite was about starting on the Quarterly Meeting`'s Committee to Muncy,
etc.]
who was soon for a season to be separated for the service of
Truth from those who are near and dear to her;
he interceded that she might be strengthened and supported;
that though she might go forth weeping, she might return with rejoicing.
Then for S. L., that she might perform the duties of her responsible station.
Then for all the rest, that those who had entered the narrow way might continue on;
and that judgments mixed with mercy, might follow those who had not.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his brother Nathan

[.signed-section-context-open]
Tenth month 14th.

Thy letter written at the close of Indiana Yearly Meeting has been duly received.
I cannot remember whether I mentioned the death of our friend Jesse Spencer,
of dysentery;
it occurred the very day he was to have started for
Tunessasah with Robert Scotton and Joseph Elkinton.

The two latter have since started.
Uncle John Letchworth has been again indisposed, but is better.
My wife, and all the Quarterly Meeting`'s Committee except Phila
Pemberton and me, have gone to Muncy.
Smith Upton and Sarah B. Thompson were duly married,
and we were favoured with a solid good meeting.
Elizabeth Evans ministered to us.^
footnote:[One of Thomas Kite`'s nieces writing of this meeting to her uncle Nathan, says:
"`We had a very good meeting indeed the day they were married;
very much to my satisfaction.
Elizabeth Evans gave us one of her very best sermons, commencing with,
'`He that loseth his life for my sake shall find it.`'
It was a very tender and affectionate appeal to the young people present,
especially to the visited of the Lord,
to be willing to lay down their life in worldly things
for the sake of their dear Lord and Saviour.
Uncle Thomas appeared in supplication,
in the course of which he was led to petition for those who had just covenanted together,
that they might be enabled to keep their covenants, etc.
It was a solemn time;
and the parties spake as if '`they deeply felt the solemnity of it.`"]
The company was orderly.
Caleb Pierce, Sally N. Dickerson, Edith and I were overseers.

Yardley Warner and Hannah Allen were married yesterday.
They spoke more audibly than the former couple.
Indeed I know not that I ever heard the ceremony more feelingly pronounced.
Elizabeth Evans ministered also on this occasion.
She is to set out on her visit to the meetings of
Abington and Bucks Quarters on Second-day next.
In this portion of her service,
she is to be accompanied by Margaret Shoemaker and Samuel B. Morris.
Rebecca Hubbs passed through the city yesterday to visit the same meetings.
We hear comfortable tidings of William Evans and Jeremiah Hacker.
At the last account they had nearly reached Tennessee.

We hear from Aaron`'s today, that Ennion Cook has deceased;
but have received no particulars.
I went to Westtown last week to attend the Boarding School Committee;
it was a comfortable meeting, but rather smaller than usual.
The examination at the close of the session was favourably reported of.
Martha Jefferis has been with us two nights.
James and Sarah Emlen have called,
and divers of the teachers +++[+++being vacation]. This day at our meeting Mary Hinsdale,^
footnote:[See an account of her, page 73, as Mary Roscoe.]
from New York, spoke to us, and Rebecca Collins was engaged in prayer.
It is pleasant to think that the time will soon be here when we may expect you.
It is not likely we shall write again, so with desires for thy safe return,
improved in bodily and spiritual strength, I conclude,
remaining thy affectionate brother.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his Wife.

[.signed-section-context-open]
Tenth month 15th, 1841.

William Kennard took tea with us on First-day, after attending our meeting,
in which he was silent.
He seems to be a solid, valuable Friend.
I hear Thomas and Elizabeth Robson are in town on their way to Baltimore Yearly Meeting.
I have not seen them.
Hannah Warrington, Jr., has a minute to attend North Carolina Yearly Meeting.
Nathan gives an account of Indiana Yearly Meeting.
Some excitement prevailed on the abolition question,
arising from a minute introduced by the Meeting for Sufferings
against opening Friends`' meetinghouses for lectures;
noticing also Joseph Sturges`' letter, and Arnold Buffington`'s paper, and one other.
The meeting adopted the minute of advice,
and ordered it to be inserted in the printed minutes.
Samuel and Nathan are expected home about the time of our Quarterly Meeting.
I am endeavouring to bear thy absence as well as I can.
The belief that thou art in the way of thy duty in going,
and the hope that I have not improperly remained at home,
serves to alleviate the trial of thy absence.
I desire that we may each be preserved in watchfulness, and, if favoured to meet again,
that we may increasingly become each other`'s joy in the Lord.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to Edith Jefferis.

[.signed-section-context-open]
Philadelphia, Tenth month 25th, 1841.

[.salutation]
Dear Cousin:

Notwithstanding way has not opened lately to address thee by letter,
thou hast lived in my remembrance;
and I am not aware that the affectionate interest I
have long felt in thee and thy concerns,
has suffered the least abatement.
I believe thou art in the school of Christ, in which many lessons are to be learned,
and some of them humiliating and mortifying to the flesh;
but if we are attentive scholars, we shall be instructed even by our misses;
the corrections of our kind Master will be administered in love,
and all our varied exercises will be blessed and sanctified to us,
and we shall more and more perceive that to act in the meekness,
simplicity and obedience of little children,
is the way to obtain Divine favour and approbation.
We shall also learn, that it is not needful to be much cast down,
when we fail to obtain the approval of our
fellow mortals yet we cannot at times but feel,
particularly if anything that seems hard to bear, comes to us from those we love.
It is evident that the Psalmist had a sore struggle on this account.
"`It was not an enemy,`" he says, "`that reproached me; then I could have borne it;
neither was it he that hated me that did magnify himself against me;
then I would have hid myself from him; but it was thou, a man mine equal,
my guide and mine acquaintance: we took sweet counsel together,
and walked to the house of God in company.`"
Many since the days of the Psalmist have had their trials from those they loved,
and have been wounded in the house of their friends.
But it is through all,
the privilege of the Lord`'s children to know they have an unfailing Helper,
who bindeth up their wounds, and causeth all things to work together for their good.
Well, whatever may befall thee, trust in Him, and wait upon Him,
and He will send thee help from his sanctuary and strengthen thee out of Zion.

I don`'t wish improperly to draw thee out, but may simply say,
that when thou feels like writing,
thy communications will be acceptable to thy affectionate uncle.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Susanna.

[.signed-section-context-open]
Philadelphia, Tenth month 25th, 1841

We had John Cox, aged nearly eighty-eight, at our meeting yesterday,
who spoke on this text, "`Say not thou, the former days were better than these,
for thou dost not inquire wisely concerning this.`"
He seemed lively and instructive.
The latest intelligence from William Evans and companion,
was contained in a letter from the latter, dated at Knoxville, Tennessee.
They have a labourious and trying service; have met with very bad roads,
and had to leave their horses to rest, whilst a friend furnished them with others.
Third-day morning.
Samuel Bettie and thy uncle Nathan returned last evening in good health.
We welcomed the latter cordially.
All the city Friends of the Quarterly Meeting`'s committee returned last evening,
excepting thy mother.
She has gone to Cerestown, accompanied by Enos Lee, Ellen McCarty and Henry Ecroyd.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to Martha Jefferis

[.signed-section-context-open]
Eleventh month 8th, 1841.

Our aged friend, John Cox, has been paying a visit to his daughter Susan,
and has attended our meeting divers times, and ministered to us acceptably.
Considering he is now in his eighty-eighth year, he is remarkably bright and intelligent.
Hannah Warrington, Jr., has gone to North Carolina Yearly Meeting,
accompanied by Lydia Stokes and Benjamin Albertson.
The meeting of business was to commence today.
Very favourable accounts continue to be received from William Evans and Jeremiah Hacker.
It is not likely they will return home before the First month.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Rebecca.

[.signed-section-context-open]
Eleventh month 10th, 1841.

I write in haste, but before I conclude, I may express the earnest solicitude I feel,
that wherever thou art, and in whatever useful way occupied,
the Divine blessing may rest upon thee.
I have not the shadow of a doubt thou art
designed to be made a vessel in the Lord`'s house.
Submit, then,
with cheerful resignation to those dispensations
which are designed to break down thy own will,
and prepare thee for the Lord`'s use.
Then wilt thou be able to say with the devoted servant of the Most High,
"`I am crucified with Christ; nevertheless, I live; yet, not I, but Christ liveth in me,
and the life which I now live in the flesh, is by faith in the Son of God, who loved me,
and gave Himself for me.`"

--

[.embedded-content-document.letter]
--

[.letter-heading]
Same to Same.

[.signed-section-context-open]
Eleventh month 12th.

I expect to be at the school tomorrow week,
and should be glad to see thee settled and feeling in thy proper place by that time.
Such a feeling reconciles us to trials and privations.
It is a precious promise, and one that we may lay hold of,
if conscious that amidst all our weaknesses, we are desiring above everything else,
to please our Heavenly Father,
"`All things shall work together for good to them that love God.`"
I feel towards thee not only the flowings of paternal affection, but something else,
I humbly trust, of gospel love, and not merely desire thy advancement in the best things,
but have been enabled to believe that by various dispensations of his love and mercy,
thy Divine Master is preparing thee to surrender thy own will to his blessed will,
and to give thyself up to be, or to do,
whatever He may assign thee in his church and family.
Then be thou faithful unto death, and He will give thee a crown of life.

At our meeting yesterday, B. Wyatt Wistar and his friend accomplished their marriage.
Many spectators were present,
but it was not so much unsettled as such occasions often are.
Our dear friend, Sarah Hillman, was present, and ministered suitably,
to which H. L. Smith made some addition.
The young folks spoke distinctly, and kept to the orthodox form, "`loving and faithful.`"

--

+++[+++When Hannah Warrington, Jr., left Philadelphia for North Carolina,
Thomas Kite addressed a brotherly salutation to William Evans, and one to his companion.
The one to the latter was as follows:]

[.embedded-content-document.letter]
--

[.salutation]
Dear friend:

I felt much unity with thee in thy giving up to the service
of accompanying our beloved friend in his arduous engagement for Christ`'s
sake and the Gospel`'s. I intended to have called at thy house to manifest it,
but was hindered.
It has rested on my mind as a debt due thee, to make this known to thee,
and therefore I take up my pen to convey to thee some of my feelings,
as thou hast many times since leaving home been brought to my remembrance.
I have no doubt it was a close trial of thy faith to leave thy wife, children,
and business, for so long a time;
and I have no doubt thou dost experience other trials of thy faith,
in part on thy own account, in part in sympathy with dear William,
and in a still greater degree in beholding the
inroads the enemy has made upon our Society.
With regard to thy trial in leaving home, remember, for thy encouragement,
the promise of the dear Master: Matt., 19 chap.
29 verse, '`And every one that hath forsaken houses, or brethren, or sisters, or father,
or mother, or wife, or children, or lands, for my name`'s sake,
shall receive an hundred fold, and shall inherit everlasting life.`'
As respects the trial thou mayest meet with, in relation to thy own state, it is said,
'`All things shall work together for good to them that fear God.`'
For thy companion thou hast done much more than give a cup of water, having,
I have no doubt, beside cheerfully waiting on him,
yielded him the sympathy of thy spirit, and endeavouring,
according to the ability received, to go down with him, even unto the bottom of Jordan,
whilst he was preparing to bring up stones of memorial; and, therefore,
thou mayest surely take hold of the comfort of our Lord`'s address to his disciples,
when sending them forth to preach the Gospel of the Kingdom,
'`Whosoever shall give you a cup of water to drink in my name,
because you belong to Christ, verily I say unto you, he shall not lose his reward.`'
With regard to the church,
though it is painful to mark the desolations the spirit of the world has made,
yet we must believe the Lord is watching over it for good; '`I, the Lord,
do keep it,`' etc., and He may, by blessing the faithful labour of devoted servants,
and by the immediate operation of his own blessed Spirit,
turn our captivity as the streams in the south.

--

[.embedded-content-document.letter]
--

[.letter-heading]
William Evans to Thomas Kite.

[.signed-section-context-open]
Eleventh month 12th, Boarding School, N. C.

[.salutation]
Dear Friend:

It is very cordial to receive the
evidences of the remembrance of our home friends,
and their affectionate desires for our preservation every way,--among
which was thy acceptable token of brotherly regard,
by Benjamin Albertson.
We thought and spoke of our own Quarterly Meeting,
at the time we supposed it was sitting;
and I felt the trust and persuasion that the Good Shepherd was with you;
and I know there are not a few in our beloved city who desire
the honour of his name and the exaltation of his cause,
more than any earthly thing.
These are bone of my bone; and my secret breathing to the Lord, while far separated, is,
that we may be more and more firmly planted in his house,
and be made instrumental in gathering the dear children to Christ,
and presenting them with increasing beauty and perfection in Him.
It is his will, I believe,
that we should labour fervently to persuade our fellow
members to lay aside every hindering thing,
and to come up nobly to the help of the Lord against the mighty,
and He will bless the sincere prayers and labours of his upright and dedicated children.
My love was never stronger towards my dear, faithful friends in Philadelphia;
and it is a comfort to believe,
there is a little band who are united in the Truth and in the fellowship of suffering,
and who long to see the ancient standard lifted up by a rising generation,
that the Great Name may be magnified, and others may flock to it,
and own the Truth as it is in Jesus.
We have had various fare in different places.

Thou knowest it is a pleasant thing to hand forth the consolations of
the Gospel when the spring is opened for those who are prepared;
but to be dipped into the state of lifeless outside professors,
without being able for a long period to come at anything of the quickening power,
is hard for us poor creatures to endure.
And when this does appear,
the kind of service is often very different from what we would make choice of.
But we have good cause to speak well of our Lord and Master,
who has many times given evidence that his sustaining hand was underneath,
strengthening us to labour in his love to draw the hearts of the people unto Him.
And when He withdraws, for the trial of our faith, we cannot but mourn for his return,
and sometimes fear lest we should now be left, and our emptiness be discovered by others.

We are now staying at the boarding school.
A pretty large company.
Old Nathan Hunt is here; he looks quite patriarchal,
and maintains a strong interest in the concerns of the Society.
He is determined if in his power,
no innovation shall appear upon the simplicity of the
dress and manner of wearing the hair among his people.
He called out yesterday in the Yearly Meeting, "`What a pity;
that a child of a Friend should be going up the
gallery steps with a frock-tailed coat on!`"
He often refers to the Prophet Isaiah`'s denunciation of many articles of dress,
and says he believes many of the present day are as opposite to the Divine Will as these.
I hope a little discrimination will be granted and continued
amongst us whatever may be said of our standard.
There are, I believe, notwithstanding their easy way, some well concerned men;
and I think their appearance has generally improved since my first visit.
Could the boarding school be rightly sustained by the
members sending their children in larger numbers,
it would have a direct beneficial influence on Society in these parts.
Indeed,
it has already done good by imparting instruction to
many who would perhaps have obtained none,
and it keeps the committee and other members frequently employed in its concerns,
and thus their attention is necessarily drawn to the subject of education.
It would be a great loss were it permitted to go down,
and more especially as the spirit of migration has nearly subsided,
and the Yearly Meeting is believed to have been on the increase several years.
Notwithstanding sickness has prevailed in several parts around this neighbourhood,
and it was expected to be a discouragement to Friends coming to it,
yet the present Yearly Meeting is considered the largest for many years.
The conduct of the young men has been marked with sobriety,
generally keeping their places during a session of four to four and-a-half hours,
and on benches without backs.
I know there are many discouraging things here;
but are we to let our hands hang down and conclude nothing is to be done?
or is it not rather better to arouse one another up to
his portion of the labour to bring about a reformation?
Much may be done by the willing-hearted,
when they set about in good earnest to examine in the light of Truth their own state,
and then through Divine help to build the wall against their own houses,
and encourage others to do the same.
I believe Friends have been stimulated to renewed efforts to pay off the school debt,
and it is now reduced so that there appears very little
doubt it will be effected in the course of the year.
This Yearly Meeting has decided to close the door against children not members;
in favour of doing which they had the united voice of all the visitors,
who sat with the committee appointed to deliberate on the matter.
I cannot but hope the cause of education is gaining sure ground in this country,
and that the present meeting will give force to it.
Jeremiah and I enjoy good health; and tomorrow (Seventh-day),
expect to pursue our journey to the meetings, commencing with Deep Run.

Dougan and Asenath Clark have received and treated us with marked kindness;
assisted us in laying out the route.
They are Quakers of the original stamp, and are not carried off with mere words.
Love to thyself,
wife and to Mary and Nathan. Jeremiah desires me to acknowledge the receipt of thy letter,
and wishes his love communicated.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Rebecca.

[.signed-section-context-open]
Eleventh month 23rd, 1841.

[.salutation]
My Beloved Child:

I feel very tenderly for thee, having left thee not quite well;
and although I have not looked for its being anything more than a slight indisposition,
yet it will be pleasant to receive the assurance from thy hand that so it turned out.

The Apostle Paul lays great stress upon faith, as thou mayest remember.
It is a Divine gift; yet keeping close to the little grain of it received,
endeavouring to walk by it and humbly asking for its increase,
we may become strong in it, even as Abraham and other holy ancients did,
together with many in times nearer our own.
I think it is another apostle who exhorts believers to
add to their faith many excellent Christian qualities,
amongst which is patience: and if amidst the vicissitudes of this mortal state,
we are favoured to keep hold of faith, and to add thereto patience,
other needful graces will not be wanting;
and we shall not only be strengthened in our
endeavours to do all things to the glory of God,
but shall learn with the apostle I have first alluded to, in all states to be content.
It is a difficult lesson to learn, but to the sincere disciple not impossible.
Let us never forget who it is that rules in heaven and amongst men--that
superintends and orders all events--without whom not a sparrow falls to the ground;
and remembers the hairs of our head.
Let us endeavour to commit the keeping of our souls to Him in well doing,
as unto a faithful Creator.
Then all the events of this fluctuating state will be blessed and sanctified to us,
and be made helpful in the great work of preparing us for the coming change,
when this corruptible shall put on incorruption,
and this mortal shall put on immortality;
when shall be brought to pass the saying that is written,
"`Death is swallowed up in victory.`"
The greatest foreign news is an account of the burning of the Tower of London,
involving great pecuniary loss,
as well as the destruction of many objects of historical interest.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Same to Same.

[.signed-section-context-open]
Eleventh month 26th.

Mary M. Sheppard and her brother Mark are in the city;
he proposes returning to Greenwich tomorrow, and leaving her here for a few days.
She looks more unwell than I expected to see her;
but I hear she is somewhat improved this evening.
Thou art aware that I feel much interested in her,
believing her to be one of the visited children of the family,
for whose preservation and advancement I have long travailed in spirit.
It is a comfort to believe there are many such in our day;
but we know the enemy is very busy,
endeavouring to draw them aside from the right way of the Lord,
or at least hinder their advancement therein.

May the Good Shepherd care for these; by the crook of his love recall them,
if their hearts should wander for a moment from Him,
exercise his righteous discipline upon them,
and prepare them for his own work and service,
and after they have fulfilled their course in dedication to his will,
admit them into everlasting habitations.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Same to Same.

[.signed-section-context-open]
Twelfth month 8th, 1841.

I arrived in safety at home about one o`'clock,
and found thy aunt Mary very much improved in health;
John L. Smith feeling better than he has for two months;
thy uncle Nathan out as usual attending to his business.
So thou seest, things on the whole look favourable as it regards my own family;
but I found a most affecting incident had occurred in my absence.
Our friend Rachel C. Bartram was walking with her sister Ann Richards,
and near the corner of Fifth and Race Streets they were both
run over by a horse that had previously thrown his rider.
I do not learn amidst various statements exactly how it occurred;
but the former was much injured, her skull being broken,
and in about twenty minutes she expired.
It does not appear she was conscious of anything after receiving the hurt.
Her sister Ann was considerably bruised, her head cut, and her arm broken in two places;
yet she is likely to recover.
It is another affecting instance of the uncertainty of life,
and conveys an admonition to survivors to be in
a state of readiness to meet the solemn close.
I regret that the time fixed for the interment is Sixth-day afternoon,
at the very hour when the Boarding School Committee are to assemble.
As she was a member of it,
a number of the Friends belonging to it would
have felt interested in attending her funeral.

On looking back over my last visit it seems pleasant,
and a hope is felt that the committee were in the line of duty in being at the school.
My interest in the institution continues unabated,
and my sense of the weight of responsibility resting on the teachers as great as ever.
I do earnestly desire that thou mayest be strengthened to
discharge thy portion of the labours and care with uprightness,
and with a single eye to the Divine glory;
seeking to the Lord every day for strength to
avoid right hand errors and left hand errors;
and to be preserved from even the appearance of evil.
Then wilt thou at seasons have to partake of that joy
with which the stranger does not intermeddle.

--
