== Chapter XVI.

[.chapter-synopsis]
* 1842.
* Family letters
* Death of Robert Letchworth
* Notes of a Family Sitting At Thomas Kite`'s
* Letters.

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Rebecca.

[.signed-section-context-open]
First month 7th, 1842.

Our cousin Robert Letchworth has been very ill;
and although he is thought to be better he can scarcely be considered out of danger.
Thy aunt Mary is assisting in nursing him.
Our Board of Overseers +++[+++School Corporation]
met this afternoon to distribute amongst poor housekeepers the
income of a legacy of J. Jones and some other bequests.
We had about two hundred and eighty dollars, and divided it amongst 115 persons,
in proportion as we thought their necessities required.
There will be some glad hearts from this little bounty.
We had at our meeting on Fifth-day, Charles Collins, of New York, noted as a Hicksite.

He told me he had been at the North and Western Meetings also.
There was likewise a female preacher of the same Society present,
who is understood to be very uneasy with the situation amongst them;
she was silent and sat far back in the meeting.
Tell thy aunt Martha that the Daniel S. Dean,
whose decease is mentioned in the present number of "`The Friend,`" is the same person,
noted formerly as a minister, who lost his right in Society.
After remaining in that situation for many years,
he sought and obtained restoration in advanced life;
and I believe was thought to be sincere in his love to Friends.
He was uncle to our friend Lydia Dean.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Susanna.

[.signed-section-context-open]
First month 7th, 1842.

Elizabeth Robson is visiting families in the Western District Monthly Meeting.
Her husband accompanies her.
William Evans and Jeremiah Hacker have returned from their long journey,
and appear to be glad to be again with their families.
It seems, from their account, that in places where they have been,
and especially so in Tennessee, Friends live in great rusticity,
their children are acquiring very limited schooling,
and their wives have to work very much; Jeremiah thought, in some instances,
harder than slaves.
It is to be wished some change could be produced.
William thinks, if the boarding school could be efficiently sustained,
and money raised to school some of the poorer children, great good might be effected.
We shall be pleased to see cousin Edith in the city on her way to Greenwich.

It is well we can love the young folks so heartily;
it lightens our labour on their behalf,
and parents may lawfully look forward to the time when, if life be spared,
their offspring will be better able to appreciate the
care and pains bestowed upon their infant years.
A mother`'s duties are arduous; if faithfully performed,
it is not alone a peaceful consciousness of Divine acceptance is her enriching portion:
"`She looketh well to the ways of her household, and eateth not the bread of idleness;
her children arise up and call her blessed.`"
Mayest thou be favoured to imbue the minds of the
tender lambs with a love for all that is excellent,
just and true; and in days to come, see of the travail of thy soul on their account,
and be satisfied.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Rebecca.

[.signed-section-context-open]
First month 17th, 1842.

Cousin Edith +++[+++Jefferis]
remained with us until Sixth-clay afternoon, when I accompanied her to Woodbury.
We lodged at George Mickle`'s,
and had Rebecca Pike and her daughter with us in the evening.
In the morning, after seeing Edith safe in the Greenwich stage,
I went to Joseph Whitall`'s. He has been quite poorly, but seems a little better;
yet on the whole is like a breaking-down man.
The Church has been so stripped of late,
that it is not pleasant to think of the removal of such a pillar.^
footnote:["`Joseph is very much tried that some
people who appear as heads in our Society,
should openly declare the opinion,
that our Society has very much fulfilled the design for which it was raised up;
and that it is not much matter how soon it goes down.
Such sentiments were delivered at a late Quarterly Meeting.`"
Extract of a letter dated First month 17th, 1842.]
I returned home on Seventh-day afternoon.
We hear that Abigail Richards has been removed from amongst us.
She was on a visit to a married daughter, when she was taken ill,
and remained there until her decease.
I suppose she was buried yesterday at Darby.
Our friend Ann, the wife of Joseph R. Jenks, died today; her disease, dropsy.
So the generations of mankind pass successively away.
Thrice happy are they, who are rightly prepared for their exit.
May it be increasingly thy concern, my dear child, to be thus prepared,
by constantly abiding under the influence of that Grace which brings salvation;
seeking daily for ability to do thy day`'s work in the daytime;
so that when the midnight cry announces the coming of the Bridegroom,
thou mayest not be alarmed, nor unprepared to meet his approach with joy.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Susanna.

[.signed-section-context-open]
First month 25th, 1842.

I have been frequently at the late residence of
our late kinsman R. Letchworth since his decease.
The members of his family seem tried,
yet conscious it will not answer so to give way to grief,
as to incapacitate them for exertions which are needful to obtain a livelihood.
Uncle John Letchworth seems tranquilly awaiting
his dismission from this scene of trouble;
yet there is nothing in his present state to forbid the hope
on the part of his friends that he may see another summer,
and again sit with them in a religious assembly.

+++[+++After mentioning the death of, the letter continues:]
But though the Church is stripped in many places of
those who have stood as standard bearers in their day,
I have faith to believe others will be raised up to fill their places,
as faithfulness is kept to by the visited children;
and that the doctrines and testimonies which were dear to our forefathers,
will not be without defenders in our day.
I do feel anxious at times that my own children may be of this number,
and be prepared to partake of the goodness that the Lord will dispense to his heritage.
For "`the Lord will comfort Zion, He will comfort all her waste places.
He will make her wilderness like Eden, her desert like the garden of the Lord;
joy and gladness shall be found therein, thanksgiving and the voice of melody.`"

--

+++[+++During the visit which Edith Jefferis paid in the city,
to which reference has been made in the preceding letters,
several religious opportunities occurred at places
where she and her uncle Thomas were together.
One that took place at Thomas Kite`'s residence,
at which the members of his family were generally present, Charles Sheppard`'s family,
and Anna Garrett, is thus described in a letter:]

[.embedded-content-document.letter]
--

I came in about nine o`'clock, and found them sitting in silence.
After a time Edith commenced speaking.
Her mind had been exercised on account of some one or more present.
She addressed them as being in a tried, disconsolate state;
as having in times past acknowledged Christ before men, but now flinching from the cross.
In this connection she commented on the weakness even
of those who loved the Lord Jesus in measure.
She exhorted these individuals to faithfulness; declaring that if they were obedient,
some of those of whom they were now afraid,
would have cause to glorify God on their account; but warned them,
that for further continued disobedience,
they would experience still greater distress and
suffering of spirit than they had ever endured.
She afterwards spoke a few words, expressive of her belief,
that the Church although in a wilderness state, was kept there in safety,
and would be brought forth again in ancient brightness, through individual faithfulness.
Thy father +++[+++Thomas Kite]
then addressed us; exhorting to faithfulness, without looking out at others and saying,
'`What shall this man do?`"

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his son Thomas.

[.signed-section-context-open]
First month 29th, 1842.

Very trying scenes to our men of business, and the community generally, seem approaching.
There are those amongst us, who wish our banks broken up,
and if they succeed in their wish, we cannot foresee the whole consequence, though,
it is evident,
many whose means of living arise from bank dividends will be greatly straitened,
and some perhaps may be reduced to poverty.
It may be, such a state of things may have been permitted to come upon this land,
as a chastisement for our sins.
It will be well for us individually to inquire in our own breasts, how far we are clear.
To the Christian there is a consolation in remembering that the Lord reigneth;
that He can rule and overrule, so as to promote his own glory,
and the good of his dependent children.
"`Surely the wrath of man shall praise thee,`" says the Psalmist,
"`and the remainder of wrath thou shalt restrain.`"

I wish not to tire thee with advice; there is that Divine Guide in thy own heart,
placed there by thy Heavenly Parent, which, if attended to, will preserve thee from evil,
and lead thee in the way everlasting.
Permit me to recommend to thee a close attention to its pointings and its restraints,
particularly as it regards the company thou keeps, and the books thou reads.
If ever thou shouldst incline to marry,
consult this precious Guide before thy affections become engaged.
Remember, a companion for life may influence thy character and prospects,
not for this life merely, but also for eternity.
I received a message from Margaret White the other day, saying in substance,
that she understood thou wast diligent in attending meetings.
I suppose she thought it would be pleasant to me to hear it.
I had no doubt it was the case before I received her message,
but I accepted it as a token of her good-will and
sympathy with a parent separated from his child.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Rebecca.

[.signed-section-context-open]
First month 31st, 1842.

We understand that Elizabeth Pitfield, and her coadjutor, Sarah Hillman,
are proceeding in the weighty service of visiting the
families of their own Monthly Meeting.
Joseph Snowdon is their male attendant.
Perhaps thy letters of last week informed thee,
that Elizabeth Robson had a prospect of a similar service
within the limits of the Southern District Monthly Meeting,
but way did not open in the meeting to encourage her to proceed.
'`The subject of a new nomination of elders,
was weightily before our late Monthly Meeting,
and a joint committee of men and women separated to attend to the concern.
I feel very solicitous that a single eye may be
kept by all the members of that committee,
and by the members at large, to the pointings of the Great Head of the Church,
that so evidence may be furnished who is gifted by Him for this responsible service.
We have just heard of the decease of our friend, George Jones, the husband of Ann,
which is said to have occurred after an illness of only three days.

+++[+++After referring to an existing excitement about the banks, he continues]:
But there certainly is a place of quietude under every storm,
to be attained by the devoted Christian,
whose confidence is firm in the everlasting truth, "`The Lord reigneth.`"
'`May my dear children, with myself,
be increasingly engaged to love and serve Him in our generation,
and count nothing too dear to be parted with to evidence our
gratitude to Him who loved us before we loved Him.
And if the impression is made upon the mind at times,
that a full and entire surrender of our own will yet remains to be effected in us,
may we seek unto Him who hath all power, for ability to be faithful unto death,
the death of the first nature,
knowing the old man with his deeds to be crucified and slain;
that thus we may be prepared to partake of that spiritual
resurrection which those witness who have been planted with their
dear Redeemer in the likeness of his sufferings and death.

--

+++[+++When Thomas Kite resigned the printing business at the close of 1833,
into the hands of his brother Joseph, and his son William, he had property,
the income of which was sufficient comfortably to support his family.
He held some real estate, but the bulk of his property was in bank,
railroad and canal stock.
He soon found difficulties connected with his real estate, which induced him to sell it,
and invest the proceeds, except a portion left on mortgage, in "`stock.`"
As the difficulties in the mercantile community consequent on
the "`war against the banks,`" began more and more to be felt,
Thomas Kite perceived the value of his stocks gradually diminishing, until,
about the time the above letters were written, his,
property had been reduced to about one-third of its value when he retired from business.
Those of his friends who had known his frugal and economical habits,
now looked for some visible token of depression or sorrow at his great losses,
but they looked in vain.
He felt, as the letters we have just quoted testify,
that "`the Lord reigneth,`" and that his Omnipotent Arm could and
would direct all things for the good of his dependent children,
and in this belief he was enabled in sincerity to say, "`Thy will be done.`"
He occasionally spoke of going into business again,
but the way did not open in his own mind for it;
and as he found by having a few young friends boarding in his family,
he could live without reducing the principal of his stock,
he waited in trustful hope for better days.
Time passed on; stocks rose in value; banks declared dividends,
and so did some of the railroads; and at the time of his decease,
his income was nearly as great as it had ever been,
notwithstanding he had lost several thousand dollars by the failure
of debtors and the breaking up of the United States Bank.]
