== Chapter XIX.

1843.

Diary--Letters--John Letchworth`'s death--Edith Jefferis`' Decease--Letters--Diary:

First month 1st, 1843.
"`First-day.
Felt a draft to attend the Western Meeting;
and therein was concerned to open the doctrines of the Gospel from the testimony of Paul,
'`After that, in the wisdom of God, the world by wisdom knew not God;
it pleased God by the foolishness of preaching, to save them that believe.`'
A good degree of solemnity seemed to attend.
The afternoon meeting was silent.
In the evening meeting I was again engaged, commencing with nearly these expressions:
'`It appears that whenever reformation has commenced, however glorious,
in a short time an eclipse has followed;
whenever a considerable body of believers has
been gathered to the truth as it is in Jesus,
in a brief period there has been on the part of some,
a falling away from their steadfastness.
This arises from the stratagems of the old enemy,
working on the corruptions of the human heart,
and seeking to prevent the spreading of the cause of Truth and righteousness.
Yet the Lord, whose power commences the work of reformation,
does not desert his own cause,
but in mercy raises up and qualifies instruments
to labour for a revival of pure religion;
and the work of these has ever been to lead the people back to first principles,
and first practices.`'
These expressions were followed by references to the state of the primitive Church,
its first glory, its decline,
and the labours of the apostles to bring the professors
of the name of Christ to the experience of his power.
Also to the state of our Society in the beginning;
the excellency that appeared amongst those bright sons of the morning;
the declension of zeal which followed; the prevalence of worldly-mindedness;
the faithful men and women since raised up; the nature of their testimony, etc.
Following this, was an address to the younger members,
and an exhortation to dwell under the power which would
prepare them for the service of their day;
with an encouraging prospect of the future state of the Church,
after a time of sifting and trial,
through faithfulness to the visitations of the Day-spring from on high.
Calling after meeting at a Friend`'s house, those present were drawn into silence,
and therein a door of communication was opened in a line of close, plain dealing,
seasoned with Gospel love.

2nd. Second-day.
At the Girls`' Select School on James`' Street by appointment.
Elizabeth Evans had some seasonable remarks to offer to the children,
and I had a share in the labour.
As the Select Schools were established from a
religious concern for the welfare of the youth,
it is much to be desired that this ground may be steadily kept to,
not only by the teachers, but by the committee to whose care they are entrusted.
Then we may reasonably hope that the Divine blessing will rest upon them.

8th. First-day.
During several of the past days I have been depressed;
very little sense of Divine life attending.
Today I have been somewhat revived with sensations of good.
In the morning meeting a testimony was delivered.
The declaration of Paul was uttered, with remarks, as way opened;
'`Being justified by faith, we have peace with God, through our Lord Jesus Christ.`'
In the afternoon my dear friend, Elizabeth C. Mason,
who has long been shut up as to public labour in this place,
was opened in a lively and appropriate testimony, to my comfort.
In the evening, after several testimonies were borne +++[+++by S. Bettle,
H+++.+++ Rhoads and E. Pitfield,]
I was prostrated in vocal thanksgiving and supplication.
A remarkable solemnity covered the meeting to its close.
Afterwards in a religious opportunity in a Friend`'s house some labour was extended.

11th. Fourth-day.
At Orange Street Meeting, opened on the passage,
'`Verily thou art a God that hidest thyself, O God of Israel, the Saviour.`'
Those were addressed who had experienced the hidings of the Lord`'s face,
in consequence of their unfaithfulness; and those also who were walking in darkness,
and yet truly desiring to know and do the Lord`'s will; with counsel for each class.
Elizabeth Evans had afterwards acceptable service.

12th. Fifth-day.
At Radnor Monthly Meeting.
Many young Friends were present from Haverford Boarding School,
towards whom my mind was opened in love.
The nature of the Gospel dispensation was set forth,
and a testimony borne to the Law which is written not with ink,
but the spirit of the living God; not in tables of stone,
but in fleshly tables of the heart.
Something also was addressed to the aged.
In the meeting for discipline the youth were again spoken to.`"

Thomas Kite to his daughter Rebecca.

First month 6th, 1843.

I take a whole sheet of paper to acknowledge the
receipt of thy closely written and well filled epistle,
but not with any settled conclusion to write on each page.
'`Thy aunt Mary has been at Ruth Jess`'s nearly all the time for more than a week.
A young friend from North Carolina boarding there, and attending medical lectures,
was taken ill, and his life was considered in danger.
No marvel was it that thy kind-hearted aunt was found at his bedside;
nor that Ruth was desirous of retaining her, as she still does,
although the youth is getting better.
But he still requires good nursing, as he is weak.
I have occasionally met with a new history of
the Great Reformation of the Sixteenth Century,
by J. H. Merle D`'Aubigne, but felt no desire to read it,
having heretofore perused divers accounts of those eventful times;
but recently looking into it, I became interested,
and am inclined to think I shall travel through it.
It is written in a lively and striking manner,
and thy mother has listened with much satisfaction to
portions of Martin Luther`'s personal history.
The great Reformer, as he is styled by many,
had his mind very gradually opened to the errors of the Romish creed; and after all,
was far short of the brightness of the Gospel day,
which broke forth amongst our early Friends.
George Fox was undoubtedly the greatest of the modern Reformers;
depending not on human learning, as the others too often did,
but on the openings of the Holy Spirit,
and exemplifying in his life a beautiful consistency with his doctrines.
But I must not enlarge on this subject at present.

With regard to thy future movements,
whether to remain another session at Westtown or leave at the close of this,
I wish thee to feel after the subject deliberately.
I have rather looked forward to the latter alternative;
but am willing to sacrifice personal feelings, if the other course should appear best.
It is a precious state to have our wills brought into subjection to the Divine will,
and to have that will clearly made known to us.
I feel a hope this may be thy experience.

Thomas Kite having received a letter from his friend, Joseph Edgerton,
then travelling on a religious visit through New York Yearly Meeting,
was feelingly drawn into sympathy with him,
in the trials of spirit to which he was subjected;
and soon felt an engagement of mind to salute him with a brotherly epistle.

Philadelphia, First month 11th. 1843.

Dear Friend,
Joseph Edgerton:--I duly received thy letter dated the 28th and 30th of last month.
It was interesting to be informed of thy movements since thou left us;
and feelings of sympathy were awakened by its perusal.
Truly it is a day in which the faithful burden-bearers have to go, many times,
mourning on their way.
And yet they do not serve a hard Master.
He, for whose blessed cause they are made willing to surfer, can and will,
as they keep near to Him, make good in their experience the ancient declaration,
"`He that goeth forth weeping, bearing precious seed,
shall doubtless come again rejoicing, bringing his sheaves with him.`"
As it is possible thou mayest not have heard from thy family for some time,
it seems as if it might be right to inform thee, that thy daughter,
whose health was poor when thou left home,
has since been removed from the conflicts of time.
The circumstances that attended her departure, I am not acquainted with,
but understand that William Evans has been several times at thy house,
and has been in company with thy wife since this afflictive dispensation,
and found her calm and tranquil.
These are events which call for the exercise of resignation,
particularly occurring when we are at a distance.
May the Lord enable thee to centre in that frame of spirit which strengthened Job to say,
under his bereavement, "`The Lord gave, the Lord hath taken away,
blessed be the name of the Lord.`"
The last letter I have heard of, received from William Evans by his family,
was written at Salem; he had nearly attended all the meetings in Ohio.
Beaver and one or two others in Pennsylvania would remain,
and one in Virginia belonging to Redstone Quarter.
After attending these and visiting Mildred Katcliffe,
he proposed coming pretty directly home, where he is expected about the 18th inst.
He will then be in time to attend our Meeting for Sufferings,
which stands adjourned to the 20th. From various sources I have learned,
that his visit has been seasonable to Friends of your Yearly Meeting;
and though he has had his conflicts of spirit,
yet I believe he has had the evidence of being in his proper allotment.
We shall on various accounts, be glad of his return.

We have been holding an evening meeting on First-days,
at the Arch Street house this winter,
for the members of the Society in this city generally.
Through the renewed extensions of Divine regard,
they have been generally solid good meetings;
and I trust will have a cementing influence.
Nothing has lately occurred to produce any collision amongst us,
yet I fear there are too many who hold this modified Quakerism,
which has been the source of so much painful exercise.
No less than seven changes have been made in our
Meeting for Sufferings within the past year;
five from death and two from resignation.
Nearly or quite all the new members are thought to be attached to our ancient principles,
which is a great favour;
it being of great importance that this representative
body should be preserved sound and firm.
+++[+++Sister Mary]
as well as my wife join me in love to thyself and companion.
I am thy friend in the Truth.

P+++.+++ S. I gave thy message to Elizabeth Evans, who says, "`Give my love to him;
and tell him a line from him would be acceptable to us.`"

Diary continued.
"`15th. First-day.
Our meetings were silent, morning and afternoon.
I went to the late residence of our friend Hannah Hollingshead,
on the occasion of her funeral,
and had some service in calling the attention of the company there
assembled to the necessity of being prepared for the close of life,
and for an admittance into that city '`which hath no need of the sun,
neither of the moon to shine in it; for the glory of God doth lighten it,
and the Lamb is the light thereof.`'
In the evening meeting +++[+++I was]
opened on the fundamental doctrine of the divinity of the Lord Jesus Christ;
also in acknowledgment of his manhood,
and bearing testimony to Him as the Light of the world, and the life of men.
A young man, who has joined the Separatists,
afterwards appeared both in declaration and on his knees,
in a very unsatisfactory manner; yet the meeting was preserved in quietude,
not one person in that assembly rising at his last appearance.

16th. Second-day.
Had a sitting with a young friend, at present a member of my family;
in whom I endeavoured to stir up the pure mind by way of
remembrance of the Lord`'s merciful dealings with her,
and encouraged her to unreserved dedication of heart.

20th. Sixth-day.
A favoured time at the Meeting for Sufferings.
Friends were enabled to enter into a feeling
conference on the present state of our Society;
which resulted in the separation of a committee to prepare an address to the members.`"

Thomas Kite to his daughter Rebecca.

First month 21st.

Our friend William Evans is indeed again with us;
and I was particularly glad of his company yesterday at the Meeting for Sufferings.
I there saw a number of our valuable country Friends, whom it is pleasant to see.
Our dear friend, Joseph Whitall, was again amongst us; fervent in spirit,
though weak in body.
He has been forty-five years a member of that meeting.
Our uncle, John Letchworth, seems rather revived.
Our aged friend, Mary Wistar, is also much indisposed,
and is thought to be in a critical state,
so that her husband did not come to the Meeting for Sufferings yesterday.

My dear child, the present is a critical time in our religious Society,
and indeed in what is called Christendom at large.
Conflicting elements are at work.
It is too copious a theme to enter much upon, on such a piece of paper as this.
I mention it, however,
to introduce my conviction that there is great necessity for each one of us,
whether young or old, to repair to the foundation, which stands sure;
and to be built upon it,
and then all the shakings and overturnings that are in
the world cannot move us from our steadfastness.
"`Watch and pray,`" said bur Divine Master, "`that ye enter not into temptation.`"
And when we consider the prize of our high calling,
how willing ought we to be to bear the cross,
to crucify the flesh with its affections and lusts, and to do or suffer the will of God,
which is experienced by the faithful to be their sanctification.
Mayest thou, then, be of the wise number to whom the promise belongs,
"`Blessed are all they who do his commandments,
that they may have a right to the tree of life,
and may enter in through the gates into the city.`'
Remember me affectionately to A. Williams and Martha Barton,
and tell them I desire their encouragement in the
tribulated path which leads to everlasting life.

Diary: First month 22nd. First-day.
In the morning meeting engaged on the query of the disciples,
'`Lord wilt thou at this time restore again the kingdom to Israel?
The afternoon was wholly silent.
A covering of solemnity was experienced in that held in the evening.`"

Extract from a letter from one of the family to Thomas Kite, Jr.

"`I thought him +++[+++Thomas Kite]
this morning eminently favoured.
He began with the sixth verse of the first chapter of Acts, '`Lord,
wilt thou at this time restore the kingdom to Israel?`'
and repeating the seventh and eighth verses; '`And He said unto them,
It is not for you to know the times or the seasons
which the Father has put in his own power.
But ye shall receive power, after that the Holy Ghost is come upon you:
and ye shall be made witnesses unto me, both in Jerusalem, and in all Judea,
and in Samaria, and unto the uttermost part of the earth.`'
He then commented on these passages, showing that though his disciples had been with Him,
and were witnessses of his miracles, healing the sick, curing the lame,
restoring sight to the blind, unstopping the deaf ear, and even raising the dead,
yet their views were still outward;
they had not fully discerned the spirituality of his mission.
They were anticipating the restoration of their nation from under the Roman
bondage to its peaceful and happy state in the reigns of David and Solomon.
It was not for them to know the times and the seasons
which the Father had put in his own power;
yet He gave them instructions how to do,
'`Tarry ye in the city of Jerusalem until ye be endued with power from on high.`'
I wish I could give the whole of it, with the feeling,
impressive and forcible manner in which it was spoken.`"

Mary Kite to Susanna Sharpless.

Oh, it is cheering to my spirit to sit beside dear uncle`'s +++[+++John Letchworth`'s]
bed, and look at his placid, shall I say heavenly countenance,
beaming with kindness on all who approach him.
As I sat by his side he remarked, "`All the days of my appointed time will I wait,
till my change come.`"
I said to him, "`I suppose thou would be glad to be released?`"
"`Oh yes,`" he said, "`but I desire to have no will in it.`"
He is very feeble; and often so prostrated, that he appears nearly gone.
Many friends call to see him: indeed few are more universally beloved than uncle John.

Diary continued.
"`First month 24th. Third-day.
Took tea, with my wife, with our aged friend, Elizabeth Cleaver.
In a religious opportunity, Sarah Hillman, who was also there with her mother,
addressed our dear friend impressively.
I also had a short communication.

25th. Fourth-day.
At the Western Meeting I was concerned to revive the address of our Lord, '`Fear not,
little flock, for it is your heavenly Father`'s good pleasure to give you the kingdom.`'
I was considerably enlarged, both to the little flock of the Redeemer`'s followers,
and also to others, who have not as yet taken up his cross,
which would bring them to be of that number.
I had also to bear testimony to the nature of his kingdom.
Afterwards my mouth was opened in the solemn service of vocal supplication.
At the close of the meeting I called to see my young friend, Lloyd Bailey,
who is in declining health; and had an opportunity with him, his mother being present,
in which they were respectively spoken to.

26th. Fifth-day.
At our Monthly Meeting.
A covering of good in silence, and under the lively ministry of dear Elizabeth Pitfield.
The meeting for business more heavy.
I obtained the concurrence of my friends with my paying a religious
visit to the meetings within the limits of Abington Quarterly Meeting.
Was informed after meeting that our friend, Charles Allen,
was found dead in his bed this morning.
He had for some time been in declining health.
In the afternoon I called at his late residence, and being invited to see the widow,
had an opportunity with her, nearly all the children being present.
My mouth was opened in testimony from this passage of Scripture,
'`Precious in the sight of the Lord is the death of his saints.`'
Afterwards I was engaged in supplication for the widow and the fatherless.

27th. Sixth-day.
Calling in the evening on business at a friend`'s house,
I was unexpectedly brought under exercise, and had to address him, his wife,
and her sister in a line of close counsel,
in which the testimony of our Lord to the sister of Lazarus was brought into view;
'`Mary hath chosen that good part which shall not be taken from her.`'
28th. Seventh-day.
Deeply bowed under the prospect of engaging in my religious visit,
and the consciousness of my own unworthiness and utter helplessness.
Strong desires arose to the Father of Mercies for the remission of sin,
and for a more thorough washing in the laver of regeneration.

29th. First-day.
Commenced the visit after a restless night, by attending Germantown Meeting;
and was helped to speak to the people.
The Prophet`'s testimony to the Lord`'s dealings with his servant Jacob was quoted:
'`He found him in Bethel, and there He spake with us: even the Lord God of Hosts;
the Lord is his memorial.`'^
footnote:[Hosea 12:4.]
All the Lord`'s visited children have a Bethel,
a season in which He reveals his love to them; and as they take hold of it,
they are enabled to enter into covenant with Him.
Various incidents in the Patriarch`'s life were brought into view,
with applications to the states of those assembled.
Afterwards I was prostrated in vocal supplication.
Returned to the city with peaceful feelings.
In our evening meeting our friend, William Evans,
recently returned from a religious visit to the meetings of Ohio Yearly Meeting,
was excellently engaged in unfolding the practical, self-denying doctrines of the Gospel,
to a large and attentive auditory.
May his labours be fastened as a nail in a sure place.

31st. Third-day.
At Frankford Monthly Meeting held at Germantown,
my mouth was opened in testimony to the nature of the
kingdom and government of the dear Son of God;
and various classes were addressed.
The meeting for worship was favoured;
and the business afterwards was transacted in a solid, becoming manner.
Alice Knight was set at liberty to visit the families of Sadsbury Monthly Meeting,
and part of those of Bradford.
I was comforted in finding this exercised Friend under this concern,
and trust she will be strengthened to fulfil it to her own peace,
and the honour of the Great Head of the Church, who not only puts his own forth,
but goes before them.

Thomas Kite to his son Thomas.

First month 29th, 1843.

+++[+++After narrating several deaths, he adds:]
Thus are our elder and younger Friends called away;
and these and many other instances of mortality,
ought to awaken us to increased diligence in making our calling and election sure.
So many valuable Friends have been of latter time removed from
the important posts they occupied in the Church,
that desires can hardly fail to be excited,
that our dear young Friends may effectually take up the cross,
and become crucified to the world and its bewitching vanities;
prepared by the Great Head of the Church to fill the vacant places,
and to show forth out of a good conversation their works with meekness of wisdom.
Nothing in relation to thee could gratify me more,
than to know that thou hadst become a firm, decided, consistent,
cross-bearing follower of the Lord Jesus Christ.

Diary: "`Second month 2nd. Fifth-day.
At Gwynedd Monthly Meeting held at Plymouth.
Enlarged in testimony to the relief of my own mind.
The meeting for business a low time.
A religious opportunity was had at Hannah Williams`', where I dined,
in which my mouth was opened in supplication to
the God and Father of all our sure mercies.

Second month 3rd. Sixth-day.
In the evening, with my wife, visited Rebecca Allen and family.
Before we left them, after a time of silence, I had a brief testimony to deliver.

5th. First-day.
At Frankford Meeting.
A covering of good attended.
I stood up with the subject of the appearance of Jesus to his disciples,
walking on the water, whilst they were tossed with the waves,
the wind being contrary unto them.
I was considerably enlarged on that and other topics, speaking also to various states.
Returned home in time to attend evening meeting,
in which Truth did not seem to arise into dominion,
although a valuable Friend had a short communication.
Afterwards called with my wife at Benjamin Albertson`'s, and divers Friends being present,
we were drawn into silence, and Phebe Roberts was engaged in a short testimony,
after which I also appeared.

6th. Second-day.
At our own Quarterly Meeting.
Several Friends +++[+++E. Comfort and E. Pitfield]
laboured pertinently in the first meeting.
That for business was not entirely satisfactory: there was much to engage its attention,
preparatory to the approaching Yearly Meeting; and perhaps it was too much hurried.

7th. Third-day.
At Abington Monthly Meeting.
A season of favour, in which I was enabled to speak to various states,
bringing into view the language of the prophet,
'`Then they that feared the Lord spake often one to another;
and a book of remembrance was written before Him for them that feared the Lord,
and thought upon his name.
And they shall be mine, saith the Lord of Hosts, in that day when I make up my jewels;
and I will spare them, as a man spareth his own son that serveth him.`'
Afterwards attended the Select Preparative Meeting,
and felt sympathy for the few who were present.

8th. Fourth-day.
At our Quarterly Meeting of Ministers and Elders.
I thought it a solid time.
I was enabled to bear testimony to the manner in which the
Lord`'s children are enabled to rejoice in his presence:
it is after enduring toils, and trials, and various conflicts,
and being strengthened to keep the faith through all,
according to the testimony of the prophet,
'`They joy before thee according to the joy in harvest,
and as men rejoice when they divide the spoil.`'
I was also led to speak of the duty of watchmen as set forth by the prophet Ezekiel.
In the evening, at Sarah Churchman`'s, a religious opportunity occurred,
in which she and her two daughters were separately addressed.
Margaret, the youngest, seems very near, in the Truth.
May she be found faithful.

9th. Fifth-day.
After lodging at Samuel B. Morris`'s, at the breakfast table I had to address his son,
who is but a lad, endeavouring to encourage him to live in the fear of the Lord.
Then went to Abington Quarterly Meeting.
The Great Head of the Church was near, to our comfort,
enabling several servants to advocate his cause,
and spreading over the assembly a covering of solemnity.
I stood up with the caution addressed to each of the seven Churches, in the Revelations:
'`He that hath an ear, let him hear what the spirit saith unto the Churches.`'
I was led to take a view of our Society in its early days,
the chaste love and zeal of its primitive members, the degeneracy Which has crept in,
the goodness of our Almighty Helper,
in raising up and qualifying instruments to recall us to first principles,
with some prospects concerning future times, and exhortations to individual faithfulness.
The business seemed to be conducted in a good degree of the savour of Truth.
On the whole, thankfulness is the covering of my spirit for this day`'s favour.

Second month 10th. Sixth-day.
At an appointed meeting at Abington.
A low time;
yet was enabled in some degree to relieve my mind by addressing various states.`"

Extract from a letter to his daughter Rebecca:

"`Second month 10th. Think seriously whether it may be
thy place to offer +++[+++as a teacher at Westtown],
but say very little about it.
The opinions of thy friends may confuse thy mind;
whilst feeling after Divine direction may rectify and settle it.
There is a right place for every one of the Lord`'s children,
and it is his prerogative to point it out.`"

Diary: "`12th. First-day.
At Plymouth.
I was concerned to open the nature of spiritual worship,
from the discourse of our Lord with the woman of Samaria at Jacob`'s well.
The meeting was rather heavy and labourious.
Dined at Jacob Robert`'s, and had a religious opportunity in his family.
Afterwards visited Josiah Albertson, confined with a paralytic attack,
and had a sitting in his chamber.
Then went to Gwynedd, and lodged at the house of Mary, the widow of my late friend,
Jesse Spencer.

13th. Second-day.
Had an appointed meeting at Gwynedd, to my comfort.
The Gospel was preached, and towards the close, Phebe Roberts,
daughter of my friend Hannah Williams, appeared in supplication.
Went to George Spencer`'s, at Moreland, to lodge.

14th. Third-day.
At an appointed meeting at Horsham,
I was opened on the testimony and invitation addressed by Moses to Hobab,
'`We are journeying unto the place of which the Lord said: I will give it you;
come then with us, and we will do thee good;
for the Lord hath spoken good concerning Israel.`'
I was strengthened to speak to various states,
and was afterwards engaged in prayer and thanksgiving.
Went to Thomas Wistar, Jr.`'s, to lodge.

15th. Fourth-day.
Went to Byberry week-day meeting.
A very small company attended; yet a covering of good was vouchsafed.
I was unexpectedly opened on John`'s baptism, and Christ`'s baptism,
in which I had a testimony to bear, with reference to various states.
After which I was engaged to bow my knees in vocal adoration and supplication.
This meeting, which completes my present religious concern, was relieving to my mind;
and after dining at David Comfort`'s, I returned to the city,
under a thankful feeling that Divine aid had been extended throughout this journey to me,
an unworthy creature.
May my future life be more entirely devoted to the service of the Lord my God,
in the Gospel of his dear Son.
My friend Jeremiah Hacker,
has been acceptably my companion in this religious engagement.`"

From the letters of Thomas Kite it appears that the weather
was cold during the time he was performing this visit,
and that heavy snow-drifts made the travelling difficult.

Diary: "`19th. First-day.
In the morning meeting a testimony was delivered on the words of our Lord to Peter,
'`Simon, Simon; behold, Satan hath desired to have you, that he may sift you as wheat;
but I have prayed for thee, that thy faith fail not; and when thou art converted,
strengthen the brethren.
Encouragement was offered to the tempted and tried.
The afternoon meeting was silent.
In the evening meeting, after Elizabeth Evans had appeared in testimony,
I was drawn forth in vocal thanksgiving and prayer.

22nd. Fourth-day.
I attended the funeral of J. M.

Whitall`'s son, aged two years.
At the house, Sarah Hillman addressed the parents of the child, and others present;
after which I had something to communicate.

23rd. Fifth-day.
Our Monthly Meeting.
William Evans was acceptably engaged in public labour,
showing that where there is faith and obedience, there will be growth.

25th. Seventh-day.
Called at J. M. WhitaH`'s. The company present were drawn into silence,
and I was engaged in ministering to various states.
His wife was particularly addressed.`"

Thomas Kite to his daughter Rebecca.

Philadelphia, Second month 25th.

A few copies of the memorandums of Jane Bettle
having been placed in my hands for distribution,
I have concluded to forward one to thee,
supposing thou wouldst value it as a memento of our deceased friend.
Thy aunt Mary went on Fifth-day morning in the stage +++[+++to Concord],
to assist in nursing cousin Edith Jefferis.
'`We hear unpleasant tidings from the West.
The ultra-abolition members of Indiana Yearly Meeting
have organized a separation from our Society.
Daniel Prickett and Charles Osborne are prominent men in this movement.

In regard to Edith Jefferis`' illness, alluded to in the foregoing letter,
Susanna Sharpless thus wrote, under date of Second month 20th:
"`Probably you have received intelligence of the alarming illness of our dear
cousin E. J. It is a very affecting example of the uncertainty of life and health.
She went down to Concord on Fifth-day afternoon to help aunt Phebe +++[+++Middleton]
prepare for Quarterly Meeting.
In the afternoon she raised some blood from the lungs in small quantities,
yet enough to induce them to send early in the morning for Dr. Marsh.
He directed her to keep still in bed, and hoped there would be no increase.
About four in the afternoon of that day (Sixth), a much larger hemorrhage occurred.
This excited a good deal of alarm in our dear cousin,
who now asked for her mother and Dr. Thomas; but the roads were not good,
and a difficulty of sending, prevented their getting there until ten next morning,
when a great discharge had just occurred.
Since then there has been an increase, attended with cough.
The doctors gave strict orders that none should see her;
they also enjoined great quietness and composure in those necessarily in her room.
Any exertion of her own, as turning, etc, produces some discharge.

Her strength is greatly prostrated,
and fever accompanies the disease,---both unfavourable symptoms.
Her dear mother was calm,
and met the trying dispensation in a manner that awoke my admiration;
but she is too feeble for nursing in such an illness as this.
'`It seems as if the blow is so great, that I cannot at all realize it.
Out of my father`'s household,
there is no friend so near and dear to me as this beloved cousin.
From our early years we have been as sisters,
and you know of latter time how closely we have been
united in the sweet bond of Christian fellowship.
To me she has often had a word of counsel and encouragement, that has helped me on my way.
During the late pleasant visit she paid me,
she said she had had some very peculiar feelings lately in looking to the future,
and was ready to think her days`' work was nearly done.
I hoped otherwise.
Yet, what dare we say?
Shall not the Judge of all the earth do right?
He may see meet to call away those whom we deem useful instruments in his hand,
and to whom we look for help in these clays of treading down and of perplexity.
Where shall we see her mantle fall in our poor stripped meeting?
We felt the influence of her spirit there.
Her dear, feeble mother,
who looked to her as the prop and stay of her declining clays!
how does she call forth the sympathy of her friends!`"

Diary: "`Second month 26th. First-day.
In the morning meeting S. Bettle appeared in testimony;
after which I was engaged in supplication.
In the afternoon our aforesaid friend again delivered a testimony,
after which I had to revive the exhortation of the apostle: '`I beseech you, therefore,
brethren, by the mercies of God, that ye present your bodies a living sacrifice, holy,
acceptable unto God, which is your reasonable service.
And be not conformed to this world; but be ye transformed by the renewing of your mind,
that ye may prove what is that good and acceptable and perfect will of God.`'
The evening meeting was long silent,
but towards the close some labour was extended by a Friend, with, I believe,
right authority.
I thought the meeting ended too soon.
Care is requisite in this respect,
as well as not to continue our meetings to an unseasonable length.`"

Thomas Kite to his son Thomas

Second month 27th..

Very often is my mind turned towards thee with
affectionate desires for thy preservation from evil.
I wish thee to be cautious as to forming intimate friendships.
Take no one into thy confidence who does not appear to fear the Lord,
and to be aiming at a consistent life.
These who take up the cross of Christ, which crucifies to the world and its spirit,
these are safe companions.

I feel no fear that thou wilt neglect the attendance of religious meetings,
either on First or other days;
but I wish thee not to rest satisfied with merely
presenting thy body at the time and place appointed.
May it be thy fervent concern to be a living worshipper;
and this can only be attained through the powerful operation of the quickening Spirit.
Those who live habitually in the fear of offending their Creator,
and take heed to their ways in their daily intercourse with men,
are those who are most likely to experience his
blessed presence and power to their comfort,
when assembled with their friends to wait upon and worship Him.

Diary: "`Second month 28th. Third-day.
At the North Meeting strength was again vouchsafed to
preach the Gospel of life and salvation,
and to encourage my brethren and sisters to faithfulness.

Third month 1st. Fourth-day.
At the Western Meeting, where a marriage was accomplished.
I was concerned to mention the marriage in Cana of Galilee,
and the miracle performed by the Lord Jesus, manifesting forth his glory,
and confirming the faith of his disciples.
William Evans followed in a lively and appropriate testimony;
and a friend afterwards appeared in supplication.
It seemed to be a good meeting.

2nd. Fifth-day.
At our own week-day meeting.
I was engaged on the subject of some who are '`ever learning,
but never able to come to the knowledge of the truth;`' showing
that whilst any strive to comprehend the doctrines of religion
without putting in practice what they already know,
they are not in the way to become established in the Truth as it is in Jesus.
I endeavoured to keep to the opening; yet it seemed rather a low time.
In the afternoon I attended the funeral of David B. Griscom,
assistant teacher at our Select School, who died after a short illness,
in the nineteenth year of his age.
I sat with the near connections at the house,
and William Evans was well engaged in testimony;
after which my knees were bent in supplication,
intercession being made for various states present.
A good degree of`' solemnity prevailed.`"

Thomas Kite to his sister Mary.

Third month 3rd.

Elizabeth Pitfield and Sarah Hillman were yesterday at Gwynedd Monthly Meeting,
and met with William Kirkwood and his companion.
They expect, on First-day, to be at Germantown Meeting, and then proceed homeward.
We hear sorrowful tidings from Cincinnati.
A fire has occurred there, and several lives lost,
amongst which were two of their friends, Caleb Taylor and Joseph Bonsall,
son of our late friend Isaac.
With love to cousin Edith, and all connections at Concord, I am, affectionately,
thy brother.

Diary: "`Third month 5th. First-day.
The morning meeting silent, excepting a few words from an aged Friend.
It seemed a solid opportunity.
That in the afternoon was silent, and a low time.
In the evening, Elizabeth Evans was largely engaged in a close testimony;
after which I was concerned to revive the expressions of the Apostle Peter,
'`Blessed be the God and Father of our Lord Jesus Christ, which,
according to his abundant mercy,
hath begotten us again unto a lively hope by the resurrection
of Jesus Christ from the dead,`' with more of the passage;
setting forth, amongst other matters which opened to my mind,
the connection of the heavenly doctrines of the Gospel; and the belief was expressed,
that the Lord was preparing, by the visitations of his Holy Spirit,
those who should bear testimony to these doctrines.

6th. Second-day.
Before leaving the breakfast table, I had something to communicate,
several of our connections from the country being present.
Then attended the Select School for Girls,
as one of the Committee on Religious Instruction,
on which occasion I was engaged in vocal supplication.
In the afternoon, in company with my wife, and several other Friends,
I attended the funeral of Samuel Rhoads, at Darby.
He was a humble, unassuming man, and, I believe, according to his measure,
a faithful minister of Christ.
At the late dwelling of the deceased,
Hannah Gibbons was concerned to plead with some
whose day`'s work had not kept pace with the day.
I followed, bearing testimony to the uprightness of my deceased friend and brother,
and addressed various states; after which,
Elizabeth Evans had a close and arousing declaration,
in which some present were admonished to prepare for the solemn close.

Third month 7th. Third-day.
From a secret impulse I went in the evening,
and had a religious opportunity with Charles Sheppard and wife,
which I thought was measurably owned by a covering of good.
I was led to speak to their states, respectively, particularly to that of the latter,
who is, I believe, passing through deep exercises and conflicts of spirit.
May the eternal God be her refuge, and underneath his everlasting arms.

8th. Fourth-day.
Having occasion to call on Rebecca Biddle, we were drawn into silence,
and a belief was expressed, that her present bodily affliction and confinement at home,
has not only been designed by her heavenly Father for her good,
but that He has already sanctified it to her.
She was encouraged to trust in Him,
and yield unreserved obedience to the requisitions of his Holy Spirit.

10th. Sixth-day.
Visited Elizabeth Baily, the widowed mother of Lloyd Baily,
who deceased the 12th of last month, in the twenty-sixth year of his age.
I had a comfortable, religious opportunity with her;
she was addressed in the love of the Gospel,
as also her eldest remaining son and only daughter.

Third month 12th. First-day.
Supplicated at the breakfast table for my family.
In the morning meeting,
the substance of the narrative contained in the sixth chapter of the 2nd Kings,
concerning the Prophet Elisha, when the King of Syria sent a great host to take him,
was impressed on my mind, and a testimony was borne.
The Lord remains now, as in that day, to be the sure refuge of his people,
and is as able to deliver them out of all their troubles.
The passage in which Paul addresses an epistle '`to the Church of the Thessalonians,
which is in God, the Father, and in the Lord Jesus Christ,`' was also adverted to,
and the safety and blessedness spoken of, of those who,
by submission to the power of God, are brought into this state,
and are thus '`built upon the foundation of the apostles and prophets,
Jesus Christ himself being the chief corner-stone.`'
After our evening Scripture reading,
I had something to communicate to my nieces and nephew,
and also to S. L. In the evening meeting,
after an excellent testimony borne by a Friend +++[+++W. E.],
and a prayer offered by another +++[+++E. P.], I was engaged in reviving,
with very little addition, the language of our Lord to his disciples,
near the time when He was to be taken from them, as regarded his bodily appearance,
'`Let not your heart be troubled; ye believe in God, believe also in me.
In my Father`'s house are many mansions; if it were not so I would have told you.
I go to prepare a place for you.
And if I go and prepare a place for you, I will come again and receive you unto myself;
that where I am, there ye may be also.`'

14th. Third-day.
At the North Meeting.
Opened on the subject of the transfiguration of Christ,
on which a testimony was delivered.
Two communications which followed did not appear to add to the solemnity of the meeting;
but dear E. Pitfield was afterwards enabled to preach the Gospel to the poor in spirit.
Accompanied by my wife, I attended the funeral of Joseph Price,
whose widow Margery is a member of our meeting.
At the house I appeared in prayer, and at the grave in testimony,
commencing with the words of Peter, '`Neither is there salvation in any other;
for there is none other name whereby we must be saved;`' alluding,
as he himself explains it,
to '`the name of Jesus Christ of Nazareth,`' '`which was crucified;
whom God raised from the dead.`'
I was enabled to discharge my conscience faithfully in bearing
witness to the only means of redemption and salvation.

Third month 15th. Fourth-day.
At Orange street meeting.
Prostrated in supplication to the Throne of Grace.
Intercession was made for the gift of repentance, for forgiveness of sins,
and for the renewal of faith; for ministers, that they might be kept from falling,
be strengthened to finish the work assigned them,
and be finally numbered amongst those who have turned many to righteousness,
and who shine as the stars, forever and ever.
Request was made that the Lord of the harvest would be
pleased to send forth labourers into his harvest.
Other petitions were presented,
and thanksgiving and praise was offered up to Him who sitteth upon the throne,
and unto the Lamb.

17th. Sixth-day.
At the Meeting for Sufferings.
A solid time, in good degree favoured;
a united exercise prevailing for the promotion of the cause of Truth.`"

Thomas Kite to his daughter Rebecca.

Third month 17th.

We had Christopher Healy to tea last evening,
and it proved so stormy that he concluded to stay all night, which pleased us very well.
He did not leave us until near ten o`'clock, when he went to the Meeting for Sufferings.
How many smiles his liveliness called up in S. L.`'s face I cannot tell;
certainly not a few, and she seemed quite to enjoy his company.
Ezra Comfort dined here after meeting, and sat with us until near four o`'clock.

Diary: "`19th. First-day.
A short testimony was delivered in the afternoon
meeting to the necessity of humility and meekness,
and setting forth the duty of submission to those dispensations by
which our heavenly Father would subdue in us all loftiness of mind,
and put on us the ornament of a meek and quiet spirit.
And those who are thus prepared, He will guide in judgment and teach his way.`"

Thomas Kite to his son Thomas.

Third month 19th.

The sorrowful tidings respecting J. Bonsall and C. Taylor,
we had received through the public papers,
yet thy communication made us acquainted with some additional particulars.
There are two considerations present themselves on this occasion, neither, I presume,
new to thee, but I mention them to corroborate sentiments which, I doubt not,
have been raised in thy mind.
One is,
the loud call such events make to survivors to be anxiously
engaged in preparing for another state of being,
for unless an interest in Christ be secured by
submitting to his power and bearing his cross,
life will have been lent us in vain, or only to add to our condemnation,
by bringing on ourselves the sentence of exclusion from heaven and happiness.
The other consideration is, that the removal of useful members from the Society,
necessarily brings an increased burden on the faithful members who remain, and ought,
therefore,
to excite the younger and less experienced ones to be
willing to submit to that Power which can alone enable
them rightly to assist in supporting the cause of Truth.
It is not merely being ready to act when called on by our friends;
but it is to submit to the restraining, regulating, regenerating power of Truth,
which brings our conduct and our thoughts into right order,
and begets a living exercise of soul for our own improvement and preservation,
in the first place, and then for the encouragement and help of others.
I hear occasionally of thy regularity in attending meetings,
which is grateful to my paternal feelings,
but I want to encourage thee to an increase of concern
to be found amongst the living worshippers;
those who worship God in spirit, rejoice in Christ Jesus,
and have no confidence in the flesh.

I suppose when I wrote by B. C,
I mentioned that cousin E. Jefferis had been affected with a hemorrhage from the lungs.
The bleeding has very much ceased, and she appears recovering slowly.
Thy aunt Mary continues with her.

Uncle John Letchworth continues feeble, and is confined to his room.
'`C. Healy lodged at our house on Fifth-day night,
and we were much interested with his account of some
things he saw in the West during his late journey,
and also some particulars of his early life.
He is much devoted to the service of his Divine Master.
We also had on Sixth-day the company of other valuable Friends.
The wish sometimes arises that our T. could enjoy with us these privileges, yet we know,
if faithful, the Lord can make up to him every privation.
Although the state of Sardis of old was very low as to the life of religion,
yet even there the Lord preserved a remnant to himself.
"`Thou hast,`" said the faithful and true witness, "`a few names even in Sardis,
which have not defiled their garments, and they shall walk with me in white,
for they are worthy.`"
How blessed a thing it is to be of this number.

Diary: Third month 23rd. Fifth-day.
In our weekday meeting I felt an engagement to address the children and youth,
many of whom were present, on the words of the wise king,
'`He that loveth pureness of heart, for the grace of his lips,
the king shall be his friend.`'
I endeavoured to discharge myself in faithfulness,
but the power of Truth did not appear to rise into much dominion.
If any of the precious lambs were benefitted, to the Lord alone be the praise;
to me belong blushing and confusion of face.
In the evening, after spending some time in social intercourse at a Friend`'s house,
a season of silence ensued, and a short testimony was delivered.
Lord, preserve me, lest having '`preached unto others, I myself should be a castaway.`'

Thomas Kite to his daughter Susanna.

Third month 24th.

After stating circumstances prohibiting him from paying a visit to her,
the letter continues:]
I console myself with the prospect of seeing thee at Yearly Meeting.
We understand Joseph Edgerton is likely to be with us at that time.
We have only heard of one other Friend in the ministry, that is, Zeno Carpenter,
of Utica, who expects to attend the approaching annual assembly;
yet probably we shall have others.
As the time approaches,
those who are concerned for the cause of Truth
can hardly fail to feel some exercise of mind,
in desire that the right thing may prevail, and Friends be edified and comforted.
I believe such an engagement is profitable for the older and younger branches,
especially in this day of trial,
in which we hear sad tidings from the east and from the west.
Our friend, John Wilbur, is disowned,
and C. Osborne has put himself at the head of a movement which has
ended in a separation from Indiana Yearly Meeting and the
establishment of "`Indiana Yearly Meeting of Anti-Slavery Friends.`"
It is probable there will be much trouble from this source,
as well as from the causes which are in operation in New England.
Meanwhile, however, "`the foundation of God standeth sure, having this seal,
the Lord knoweth them that are his,`" and his faithful
followers may still rely on his protecting power,
for "`his kingdom ruleth over all.`"
"`He can cause the wrath of man to praise Him,
and the remainder of wrath he can restrain.`"

Diary: "`Third month 26th. First-day.
In our afternoon meeting I was engaged in testimony,
from the words of the Lord Jesus to his disciples, '`I am the true vine,
and my Father is the husbandman.`'
The evening meeting was the last of this character for the present season.
A stranger present +++[+++William Kirkwood,]
had a brief communication, and another Friend +++[+++G. M. E.]
appeared in prayer: after which I stood up with the words of Christ to Nicodemus,
'`As Moses lifted up the serpent in the wilderness,
even so must the Son of man be lifted up;
that whosoever believeth in Him should not perish,
but have everlasting life directing sinners to the only means of salvation,
even Him who declared himself to be the resurrection and the life.
Elizabeth Pitfield preached Christ in a living testimony,
and Elizabeth Evans was afterwards engaged in supplication.
A solemn covering attended; and it was a good close to those meetings,
which for the past winter have been held for Friends in the city generally.
For the most part they have been held to the honour of our Holy Head;
and to our own edification and comfort.
After meeting I went with my wife to Caleb H. Canby`'s;
unexpectedly a silent pause took place;
and I was drawn to speak encouragingly to a young woman
Friend from the country who has lately been married:
afterwards I had also to offer counsel to the young people of the family.

28th. Third-day.
Feeling drawings to sit with a Friend of our meeting,
who has been a widow for many years, I gave up thereto,
and counsel and encouragement were imparted.

Thomas Kite to his daughter Rebecca.

Fourth month 1st, 1843.

I received thy letter dated 28th ult., and have reflected on its contents,
and also consulted with thy mother.
We consent to the course thou art best satisfied to take +++[+++offering
herself as a teacher at Westtown]. It will be some privation to us,
should the committee accept thy offer,
which I have communicated to the women Friends appointed on the subject;
but it will be a comfort to believe thee to be in thy right place;
endeavouring to be useful.
My desire is,
that every day thou mayest seek after Divine ability to
discharge the duties of the passing day,
and leave the future.
It seems of little use to strain our mental
vision by endeavouring to see what is before us,
and which in wisdom and kindness is often concealed from our view.
The prospect of having thee with us during vacation, is truly pleasant.
Our annual assembly is nigh at hand; the thought awakens many reflections;
the deep importance of the occasion; the desire that the right thing may prevail;
the weak be strengthened, and the mourners comforted;
the remembrance of dear friends with whom we have mingled on similar occasions,
whom we shall see no more, because they have put off the shackels of mortality,
and entered, as we trust, into their everlasting rest.
These and other considerations, such as the swiftness of time, etc,
are salutary thoughts, which I hope may make their due impression on my mind,
and on the minds of some who are dear to me, and particularly on thine,
my precious child, whose advancement in the way of self-denial and the daily cross,
which is the highway of holiness, I ardently desire.

Diary: "`Fourth month 2nd. First-day.
In the morning meeting the words of our Saviour were remembered and rehearsed,
'`Except ye repent ye shall all likewise perish.
The necessity of '`repentance towards God,
and faith in our Lord Jesus Christ,`' were enforced,
with a testimony to the mediatorial office of Jesus,
from the intercession of the dresser of the vineyard,
in the parable of the barren fig tree, '`Lord let it alone this year also,
till I shall dig about it, and dang it, and if it bear fruit, well; and if not,
then after that thou shalt cut it down.`'
Some present were exhorted to repent and turn to the Lord,
whilst a renewed evidence of Divine visitation is in mercy extended.
In the afternoon, the young people were addressed from the caution of the apostle,
'`Beware lest any man spoil you through philosophy and vain deceit;`'
warning being extended respecting the company they kept,
and the books they read.
In the evening, in an opportunity with my family,
I was concerned to approach the Throne of Grace
in vocal supplication on their behalf and my own.

9th. First-day.
I was sensible of a gentle pointing to attend the Western Meeting.
Giving up thereto, I was enabled after a time of silence,
to bear testimony to the Lord Jesus Christ as the
Author of eternal salvation to all who obey him;
bringing into view some of the expressions of George Fox.
At our own meeting in the afternoon, the condition of the impotent man being before me,
some words were spoken relative thereto; and a belief expressed,
that He whose word is with power, is willing to heal us of our spiritual infirmities.

13th. Fifth-day.
My aged relative, John Letchworth, departed this life about four o`'clock this morning,
aged nearly eighty-five years.
His first appearances in the ministry were about the time of my great awakening,
near forty-one years ago, and they were instrumental of good to me.
I believe he was faithful according to the gift dispensed to him,
and that he was Divinely supported under many trials;
so that he remained green and lively in old age, and his end was peace.

14th. Sixth-day.
I heard of the decease of our beloved niece, Edith Jefferis.
She was one who feared the Lord from her youth,
and through Divine mercy she was enabled to follow her
crucified Saviour in the narrow way which leads to life.
A gift of Gospel ministry was dispensed to her,
in which she was acceptably exercised during the last few years of her life.
In the Second month she had an attack of hemorrhage of the lungs,
and has been declining since.
She died a little after midnight this morning, aged thirty-two years.
I believe the testimony which John heard from heaven is applicable to her;
'`Blessed are the dead which die in the Lord from henceforth; yea, saith the Spirit,
that they may rest from their labours, and their works do follow them.`'
15th. Seventh-day.
Attended the first sitting of the Yearly Meeting of Ministers and Elders;
and went with my wife in the afternoon to Concord to
attend the funeral of our aforesaid niece.

16th. First-day.
The remains of dear Edith were interred before meeting.
We were favoured with seasons of solemnity at the house, by the grave,
and when assembled for worship.
I was concerned in testimony at the former place, also very briefly at the graveyard.
In the meeting, Sarah Emlen first broke the silence, commencing with this passage,
'`Precious in the sight of the Lord is the death of his saints.`'
Afterwards I spoke to several states,
believing a renewed call had been extended to some who were then present,
and who were exhorted to faithfulness.
After which I was led to speak of the deceased,
and to commemorate that Grace by which she was what she was.

22nd. Seventh-day.
The Yearly Meeting closed.
It has been an instructive season,
many concerns relative to the welfare of Society
having been disposed of with much unanimity.
The Meeting for Sufferings had prepared,
'`An Address to our members`' unfolding the spiritual nature of the Gospel dispensation,
and calling upon them faithfully to support the doctrines and
testimonies which were dear to our forefathers.
It was united with, and directed to be printed.
The same body had also prepared an account, derived from authentic sources,
of the rise and progress of the concern in our
Society on behalf of the descendants of Africa,
and the successive steps by which Friends were
led to clear their hands of the evils of slavery.
This document was likewise directed to be printed.
A concern on behalf of the children belonging to the Society,
led to an address to parents on their account,
to go down to the subordinate meetings and the appointment of
a committee to have charge of the subject of education.
On the occasion of the new separation within the bounds of Indiana Yearly Meeting,
suitable sentiments were addressed K to that meeting,
and to all the others on this continent and those of London and Dublin.
The meeting separated under a grateful sense of the
Lord`'s unmerited goodness to his Church and people.`'

Thomas Kite to Martha Jefferis

Fourth month 22nd.

Dear Sister:--The Yearly Meeting has closed; we have just dined;
our friends are scattering, and amidst the bustle of packing up and leave-taking,
I am endeavouring to compose my mind to address a few lines to thee.
It is needless to attempt to describe my sympathy with thee,
or the fervency of my desire that the "`Lord may hear thee in the day of trouble,
the name of the God of Jacob defend thee, send thee help from his sanctuary,
and strengthen thee out of Zion.`"
Thou knowest the brotherly affection I have entertained for thee daring many years,
which is in no degree lessened in this, the season of an additional affliction;
but I trust He who has been with thee in former trials,
will be very near to thee in this; and that thou wilt know his name to be a strong tower,
into which the righteous run and are safe.

We have had a good Yearly Meeting.
The evidence of the Lord`'s gracious presence was, at times, vouchsafed,
and a comfortable solemnity crowned the close of the last sitting.

Diary: "`Fourth month 23rd. First-day.
In the morning meeting I spoke on Paul`'s thorn in the flesh;
the messenger of Satan to buffet him, lest he should be exalted above measure.
The afternoon meeting was silent.
In the evening I had the satisfaction of having the company of all my children,
my youngest son being now here on a visit.
After our usual Scripture reading,
in a season of retirement my mouth was opened in thanksgiving for many mercies,
and in supplication for the children, and for my dear companion and myself,
as well as for the other inmates of my family who were present.
Afterwards I had some brief exhortations to offer to divers of the company.

30th. First-day.
In the afternoon meeting I was concerned to speak from the words of King David,
'`The Lord my God will enlighten my darkness; for by thee I have run through a troop;
and by my God have I leaped over a wall.`'

Fifth month 1st. Second-day.
At our Quarterly Meeting.
On first sitting down a degree of solemnity was attendant.
Impressions were received concerning several valuable members of this meeting,
of late removed from amongst us,
and an evidence seemed to attend that they had finished their courses with joy.
I stood up with the passage, '`Your fathers, where are they?
and the prophets, do they live forever?
I was enabled to relieve my mind towards several classes, particularly the youth.

3rd. Fourth-day.
At the Western Meeting.
After long sitting in silence, I arose with some impressions towards the people,
and was enabled to deliver what was before me, to a good degree of satisfaction.

5th. Sixth-day.
At Germantown.
I called to see the children of the late Jane B. Haines,
who deceased the 26th of last month, after a few hours`' illness.
I had a sitting with these young people, now deprived of their last parent,
and was engaged to counsel them, and other near connections who were present,
in the love of the Gospel; the opportunity being to my own peace.
Afterwards I went to see my friend Alfred Cope,
whose wife Hannah died on the 19th of last month, leaving him with three small children.
I felt tender sympathy with my bereaved friend,
and way opened for a religious opportunity with him and his late wife`'s mother.

7th. First-day.
At morning meeting I was engaged in communication on the parable of the householder
who went out at various periods of the day to hire labourers into his vineyard.

Joseph Edgerton to Thomas Kite

Near Barnesville, Belmont Co., Ohio, Fifth month 9th, 1843.

I may inform thee, that through the mercy of a gracious Providence,
I was favoured to arrive at my own home on Second-day evening, the first of the month.
I found my family well, excepting our eldest daughter Eunice, and little Isaac.
'`Our meeting was a joyful one;
and mutual thanksgiving to the Great Preserver of men for his providential care over us,
through many conflicts and dangers, both within and without.
May my soul forever commemorate his marvellous loving kindness,
and return to Him the most full and unreserved obedience the remainder of my days.
Truly it was all of mercy, that the poor, unworthy, unprofitable servant, was led on,
supported and qualified, step after step, for the allotted portion of service.
Most fully do I feel that this precious treasure is held in earthen vessels, and,
therefore, no marvel if these vessels should have to experience many baptismal washings,
that the treasure may appear in its virgin purity, to the honour of the great Giver,
and to the present and everlasting peace of its poor, unworthy occupant.

I often feel for myself, as well as for my dear friends,
whom our blessed and holy Head hath by his quickening power,
qualified to speak well of his excellent name,
being fully confirmed that it is only as we keep low and humble,
deep and fervent in spirit, as in the days of our espousals,
that we can be preserved alive in the ever blessed Truth,
and enabled to occupy in that single-hearted dedication which will meet with acceptance,
when the Chief Shepherd shall appear.
I, indeed, am one of the least of the family,
not worthy of the least of the Lord`'s mercies,
yet my spirit is united to the living in our Israel,
who are not only waiting for the consolation thereof, but who also are willing,
as Divine ability is vouchsafed, to contend for the faith once delivered to the saints,
and to come up faithfully in every part of the testimonies which our Holy
Head laid on our forefathers to bear as a seal of allegiance to Him.
I do believe there is cause for encouragement,
even in the midst of the general mass of weakness that is to be seen,
that for his own seeds`' sake He will arise, furnishing Zion with a new,
sharp threshing instrument, having teeth,
whereby to thresh the mountains and hills of opposition,
and so make a way for his own blessed cause, which is dignified with immortality,
and in the end will be crowned with eternal life.

Our dear friend, Benjamin Hoyle,
is set at liberty by his Monthly Meeting to attend the Yearly Meeting of New England,
which I feel with.
I hope if way should open for such an act of dedication,
he will be supported and strengthened by Him who
will be head over all things to his Church.
Much do I feel for the ark of the testimony,
and have thought that as the living members keep in fervent exercise of spirit,
prayer will be offered up, which will ascend as the smoke of sweet incense,
and will conduce to the enlargement of the oppressed seed,
in the day when He who hath all power in heaven and in earth,
shall arise for the avenging thereof.
My health is much improved, and I never was more pleasantly at home,
enjoying a peaceful poverty.

Diary: Fifth month 9th to 12th. From Third to Sixth-day I was engaged in going to,
attending, and returning from Salem Quarterly Meeting.
I had some service in the Meeting for Ministers and Elders,
and also in the meeting for worship, preceding that for discipline,
to a good degree of satisfaction.

I had likewise some more private labour.
I enjoyed feelings of precious fellowship with some dear friends,
to whom I have long been closely united, amongst whom was my valued,
aged brother Joseph Whitall,
who has long stood as an upright pillar in the house of the Lord.

14th to 17th. First-day afternoon I left home to attend Concord Quarterly Meeting.
The Meeting of Ministers and Elders on Second-day was a season of favour,
the tendering influence of heavenly good being felt.
I had some labour amongst my dear friends.
On Third-day the meeting did not seem so solemn
as on some former occasions at the same place.
Returning homeward, I lodged at the house of Jane Garrett, widow of Nathan,
and in the morning had a religious opportunity with the family,
and several friends who were visitors, much to my satisfaction,
access to the Fountain of Divine Grace being vouchsafed in supplication,
and several states spoken to.
Afterwards I visited two Friends, who are indisposed, at their respective habitations.
Dined at Edward Garrett`'s, and returned home on Fourth-day afternoon.

18th. Fifth-day.
I stood up in our week-day meeting with the exhortation of the apostle,
'`Examine yourselves whether ye be in the faith; prove your ownselves.
Know ye not your ownselves, how that Jesus Christ is in you, except ye be reprobates?`'
I was enlarged beyond expectation; and feel a degree of assurance,
that the opportunity was not without profit to some.

21st. First-day.
At our morning meeting we had the company of Elizabeth Evans,
who had acceptable service in testimony and supplication.`"

Thomas Kite to his daughter Rebecca.

Fifth month 23rd.

I returned home comfortably from Concord.
On my way I lodged at Jane Garrett`'s; visited several invalids;
and had in several places the company of Thomazine Valentine,
a young woman of Downingtown, plain in appearance, and serious in her deportment,
whom I have not before met with.
She is, I believe, a great-grand-daughter of that eminent minister, Robert Valentine.

I incline strongly to the opinion, dear daughter,
that thou art in thy proper sphere of action, at least for the present.
That thought reconciles me to the temporary separation.
What is before us must be left.
It is noways inconsistent with the idea that thou art in thy allotment of duty,
that thou hast many trials and exercises, but rather confirmatory thereof.
Give my love to A. Williams, and accept the same for thyself.
I hope you may be bound together in the increasing bonds of a truly religious friendship.

Thomas Kite to his son Thomas.

Philadelphia, Fifth month 23rd.

Although we have it not directly from thyself,
yet by another channel we have information of thy safe arrival at thy distant home.
It is pleasant to find, that through the superintending care of Him,
who cares for the sparrows, and numbers the hairs of our heads,
thou art again in the place which seems thy allotted sphere of action.
May it increasingly be thy concern to live answerable to his unmerited mercy,
so as to become by thy obedience to Divine requirings,
and the steadiness of thy deportment, as a way-mark to others, and,
as the Redeemer`'s faithful followers always are, as the salt of the earth.

To the Same.

Fifth month 25th.

Towards the latter part of the time thou wast with us,
thou seemed to have so many things to do, and to think of,
that I omitted a few hints I would gladly have given thee,
in all a father`'s tenderness and love.

Thou knowest my wish that thou shouldst keep to the
simplicity of dress in which thou wast brought up,
even as regards outer garments and those for occasional use.
The plain language I have no reason to believe thou ever departs from;
and it is a comfort for me to believe,
that the views of thy parents have much influence with thee.
I did give thee a hint respecting female society.
I much desire that all intercourse between young men and young women in our '`Society,
may be of a strictly refined character,
and that a holy awe of offending their Great Creator,
might go with them into all social meetings.
The last thing I propose to mention, is the most important of all;
mayest thou never rest satisfied until thou hast
the certain assurance from heart-felt experience,
that the great work of regeneration is in progress;
that the Lord is carrying on in thee the work of redemption from all evil.
However painful the cross, yet once thoroughly submitted to,
it opens the way to joys more pure than earth can give.
"`The Kingdom of God`"--the kingdom which our holy Redeemer
sets up in the hearts of his obedient followers,
"`is righteousness, peace and joy in the Holy Ghost.`"

I write rather hastily, expecting to set off in the morning for New York Yearly Meeting.
William Evans is going in company, as well as Samuel Cope, of Chester County.
The latter also intends attending Rhode Island Yearly Meeting.
