== CHAPTER XX.

1843.

Attends New York Yearly Meeting--Diary and Letters.

Thomas Kite was liberated by his Monthly Meeting, held Fifth month 25th, 1843,
to attend the Yearly Meeting of New York.

Diary: "`Fifth month 26th. Sixth-day.
Having had drawings to attend the Yearly Meeting of New York, I set out,
and had the company of my beloved friend, William Evans, who, as well as myself,
had obtained a minute for that purpose.

27th. Seventh-day.
In the Meeting for Ministers and Elders I had some service.
Our friend Samuel Cope, from our Yearly Meeting, was well engaged in testimony.

28th. First-day.
Attended the morning meeting in the upper room.
It appeared to me to be an open, favoured time.

After I had spoken on the parable of the husbandman who went
out at successive periods to hire labourers into his vineyard,
and had been enlarged to various states,
William Evans followed in a lively and powerful testimony.
The afternoon meeting in the basement proved a heavy time.`"

Thomas Kite to his Wife.

New York, Fifth month 28th.

We arrived at this place towards evening on Sixth-day,
and found our friends John Wood and William Birdsall waiting on the wharf.
Samuel Cope and Moses Baily went home with the latter,
and William Evans and I are accommodated at the house of the former.
Benjamin Bowerman is our fellow-lodger, and Prince Gardner, of Nantucket,
besides a number of other Friends.
On Seventh-day the Select Meeting had two sittings.
The morning one was a favoured time; the afternoon more trying.
We attended the Meeting for Sufferings in the evening.
This morning I called at J. A.`'s to deliver the children`'s letters;
afterwards we went to meeting, which proved a favoured one;
our friend William Evans was raised up in a powerful testimony to the everlasting Gospel.
The afternoon meeting was not so lively.
Friends hold two meetings at the same time in the same house.
One in the principal room and one in the basement.
The women hold their Yearly Meeting in the large apartment--the men below.
John Meader is here with a minute.
We dined on Seventh-day at William Birdsall`'s;
took tea at Thomas Buckley`'s to be with Smith and Sarah B. Upton.

Second-day morning.
Yesterday dined at William F. Mott`'s, and took tea with Elizabeth Coggeshall.
From present appearances the Yearly Meeting is not likely to be quite as large as usual.
I think no less than sixteen representatives to the Select Meeting were absent;
for very few of whom any reasons were offered.
I met with many Friends of my acquaintance, and inquiries for thee are often made.

Thomas Kite to his daughter Rebecca.

New York, Fifth month 29th.

William Evans and I are pleasantly accommodated at the house of John Wood;
not our old friend of that name, but our valuable friend in the ministry.
'`I do not think the young women in general, appear so plain as with us,
and yet I have met with some who seem promising.
A young woman puts up here,
who has come nearly five hundred miles to attend Yearly Meeting.
She has appeared in the ministry.
I think there are more of this description within the bounds of this meeting than with us.
May they all be preserved in the right line.

Please give my love to thy uncle Nathan Sharpless and aunt Lydia,
thy cousin Joseph Walton and Abby Williams.
Tell her not to be discouraged because of the
difficulties the Christian traveller has to meet with;
for the Captain of our salvation was never foiled in battle,
and remains to be near to his sincere followers; and in his own time,
as faith and faithfulness are kept to, He will give them the victory.

Farewell, dear child; be humble, circumspect, and keep inward to the Lord,
and He will preserve thee, and thou wilt experience a growth in grace,
and a qualification to discharge acceptably as in his sight,
all the important duties devolving on thee.
The trials of time will be sanctified to thee, and conduce,
through the mercy of the Lord, and the accompanying baptism of his Holy Spirit,
to thy preparation for the state of endless happiness in the kingdom of our Father.

Diary: "`Sixth month 3rd. Seventh-day.
Returned home.
The Yearly Meeting closed yesterday.
It was a season of suffering to the upright in heart.
Creaturely activity, and a want of proper weight, were obvious in many;
and a painful sense of unsoundness pervaded the minds of a remnant.
Yet there were some times of favour;
and the conclusions come to appeared to be safe and proper.
During the various sittings I endeavoured, as way opened, to discharge my duty honestly;
and William Evans and I were concerned to visit the womens`' meeting in company;
and were enabled to relieve our minds to a good degree of satisfaction.
On returning, I felt peace in the belief,
that I had been in the way of Divine appointment.
Our friend Samuel Cope, proved himself, on various occasions,
a workman that needeth not to be ashamed; and at the close of the last sitting,
he had a powerful testimony to bear,
which I hope will be fastened on some minds as a nail in a sure place.

4th. First-day.
I was engaged in vocal labour in our morning meeting on the passage,
'`These are they which came out of great tribulation,
and have washed their robes and made them white in the blood of the Lamb.`'

Thomas Kite to his daughter Rebecca.

Philadelphia, Sixth month 5th.

We met with many interesting Friends, +++[+++at New York,]
and amongst these a number of seriously disposed young persons,
some of whom have appeared in the ministry.
Their manner of conducting the concerns of the Society is different from ours.
There is with them more freedom of discussion and diffuse remark.
I like our own way the best.
It seems to me that skillful,
tender fathers and mothers in the Truth might find appropriate
business in caring for and watching over the youthful preachers,
and some other ardent juvenile personages, who seem to have plenty of zeal,
which is not always according to true knowledge.
A strong anti-slavery feeling prevails in many sections of New York Yearly Meeting.

Nathan Kite to Thomas Kite, received by the latter in New York.

Philadelphia, Fifth month 31st.

The committee from Virginia arrived on Seventh-day afternoon.
They were kindly entertained at the house of N. Crenshaw;
and perhaps have returned rather improved in health.
The committees of the different Yearly Meetings united in
proposing that Virginia Yearly Meeting should be laid down;
that its Quarterly Meetings should be suspended;
and that a Half Year`'s Meeting should be substituted therefor;
that this should be attached to Baltimore Yearly Meeting; that, nevertheless,
it should have a Meeting for Sufferings of its own,
authorized to act on behalf of the colored people,
and in all intercourse with the Legislature of Virginia.
These propositions were fully united with by the Yearly Meeting;
and it has adjourned to the usual time next year,
to receive from Baltimore Yearly Meeting information,
whether it is willing to accept them.

David Cope thinks their First-day morning meeting,
owing to the unsettlement that prevailed, was very unsatisfactory,
notwithstanding an abundant supply of ministry.
David was much interested in the proceedings of the Meeting for Sufferings,
and its care over the rights of the colored people.
Some remarkable instances of this care he related.
Micajah Bates was clerk of the Men`'s Yearly Meeting,
and the wife of Micaj ah Crew of the women`'s.

N+++.+++ Crenshaw was acknowledged a minister by the
Quarterly Meeting preceding the Yearly Meeting.
From the reports it appeared that the number of members
belonging to the Yearly Meeting w as about three hundred,
of which there were only eighty adult persons.
Sarah Hillman mentions one plain little girl of
about sixteen who was appointed on the Epistles,
and on the committee of conference.
'`At parting after the close of the meeting much affectionate
feeling was manifested towards the committee;
and many children clung round them in tears.
By information from Indiana it appears that Charles Osborne is
travelling about visiting the meetings that have separated,
endeavouring to strengthen the hands of the members,
and prevent them from returning to the Society.

In one of Rebecca`'s letters she expresses a desire to this effect,
that "`you ministers from this Yearly Meeting, may speak the truth without fear;
and may be enabled to exhibit the meekness and gentleness of Christ,
whilst honestly labouring to perform the allotted portion of labour.`"
This is a wish in which your friends at home can all join.
Be ye clothed with the armor of Light, the blessed Spirit of the Saviour,
and then never flinch from your posts, but in truehearted faithfulness,
stand valiantly by that banner which he hath given,
"`that it might be displayed because of the Truth.`"

It is probable by the time this letter reaches thee,
that thyself and William Evans will have principally fulfilled the service assigned you;
but Samuel Cope, with New England before him,
will have great need of a large supply of faith and patience.

Thomas Kite to R. W. at Blockley, +++[+++afterwards R. W. Kite].

Sixth month 6th.

I feel a word of encouragement arise for thee.
Paul says, "`We know that all things work together for good to them that love God.`"
Believing thee to have become, through Divine grace, a partaker of this love,
I feel the comfortable hope, as thou keeps near thy Divine Lord and Master,
He will keep thee; and cause every trial, every disappointment, yea,
and every temptation also, to work together for thy good.
"`Tribulation,`" says the same apostle in another place, "`worketh patience,
and patience experience, and experience hope; and hope maketh not ashamed,
because the love of God is shed abroad in our hearts,
by the Holy Ghost which is given unto us.`"

Diary: "`Sixth month 8th. Fifth-day.
I attended Radnor Monthly Meeting, and stood up in the first meeting in much weakness.
I was unexpectedly enlarged, particularly towards the scholars of Haverford School,
who were, I believe, mostly in attendance.

10th. Seventh-day.
I paid a religious visit to my comfort to an interesting young Friend.
May she be strengthened fully to take up the cross, and follow her Divine Master.

11th. First-day.
In the morning I found an enlargement to stand up with the expressions of the apostle,
'`The Grace of our Lord Jesus Christ, the love of God,
and the communion of the Holy Ghost be with you all.
Amen.`'
In the course of the communication I was drawn forth particularly to the aged,
and had to repeat David`'s prayer, '`Now also, when I am old and grey headed, O God,
forsake me not, until I have showed thy strength to this generation,
and thy power to every one that is to come.`'

13th. Third-day.
I went to Wilmington, and returned in the evening.
Way opened for some religious service.
Visiting a Friend who had been confined about a year with the palsy,
I had to address her in the language of encouragement, as likewise her husband,
mentioning to him the language of the apostle, '`We were as sheep going astray,
but are now returned unto the Shepherd and Bishop of
our souls,`' which I believed was his situation.
Afterwards I had an opportunity with my esteemed friend Elizabeth Stroud,
I believe to our mutual comfort.

14th. Fourth-day.
I attended the Orange street meeting, and had something to communicate;
after which Elizabeth Evans was drawn out in supplication.

15th. Fifth-day.
Towards the close of our week-day meeting I was strengthened
to approach the Throne of Grace in vocal prayer.
Petitions were offered for various states; for our religious Society,
for the professors of the Christian name at large, and also for the heathen.`"

Thomas Kite to his daughter Rebecca.

Sixth month 16th.

+++[+++After mentioning a visit of his wife to New Jersey,
and her attending Haddonfield Quarter, he continues]:
They had a good time at the Quarterly Meeting.
Christopher Healy, Elizabeth Pitfield, and Sarah Emlen, I believe,
ministered respectively.
Sarah Hillman was also there.
The first-named Friend has been holding a number
of meetings amongst those not of our Society,
on the other side of the Delaware.
He particularly wishes the most degraded classes invited; not, however,
excluded those of greater respectability.
This is the day of our Meeting for Sufferings,
and many valuable Friends have been in the city.

Diary: "`Sixth month 18th. First-day.
A day of exercise and labour.
In the morning meeting I was enlarged in testimony to
the Lord`'s goodness and power in all ages,
commencing with two Scripture passages, concerning an antediluvian saint,
'`Enoch walked with God, and he was not, for God took him.`'
'`By faith Enoch was translated, that he should not see death; and was not found,
because God had translated him; for before his translation he had this testimony:
that he pleased God.`'
I was enabled to relieve my mind to a good degree of satisfaction.
In the afternoon meeting I had a short communication to make,
on the words of the prophet, '`Verily, thou art a God that hidest thyself, God of Israel,
the Saviour!`' I had to offer encouragement to the sincere-hearted,
who are at present shut out from a sensible enjoyment of Divine good.
Among the promises quoted for this purpose was that of the Psalmist:
'`The needy shall not alway be forgotten;
the expectation of the poor shall not perish forever.`'
After the meeting I attended the funeral of James Cresson;
and at the grave had a testimony to bear to the necessity of being prepared for death;
which was followed by a separatist,
endeavouring to invalidate some points of doctrine which I had advanced,
and to insinuate the views of that people against the divinity of the Lord Jesus.
It was truly painful to hear.

19th. Second-day.
Called on R. Biddle.
I was dipped into sympathy with her,
and had to counsel her to keep faithful to Divine manifestations.
Afterwards I visited my long-acquainted friend, E. C. Mason,
and was led renewedly to feel for her, and to offer her the word of encouragement.

May she be kept in the line of simple, unreserved obedience to her Lord`'s commands.

21st. At the Monthly Meeting for the Western District.
I stood up with the words of the unfaithful steward, on which I had, as way opened,
considerable to say: '`I cannot dig; to beg I am ashamed.`'
I endeavoured to encourage those present to engage in spiritual labour,
and also in petitioning for mercy and grace to help in time of need.
I was wholly silent in the meeting for discipline.

24th. Seventh-day.
Poverty has of late been my portion,
accompanied with the sense of the need of further
purification than I have yet experienced.
May I be kept inward to the Lord, minding carefully to observe Divine direction.
In every season of trial and temptation,
may I witness the holy preserving fear of the Lord, keeping under my body,
and bringing it into subjection, lest that by any means, when I have preached to others,
I myself should be a castaway.
In the afternoon I attended the funeral of Elizabeth Williams, a young Friend,
aged about twenty-one years.
I had some service, both in her late residence and in the burying-ground.
I have very often been engaged in admonishing others to
endeavour to be prepared for the solemn change,
and may I never relax in the concern that this may be my own happy experience.

25th. First-day.
We had at our meeting, both in the morning and afternoon,
the company of our friend Benjamin Hoyle, of Ohio, who ministered acceptably.
In the evening, after our usual family reading, I had a communication to make,
addressed to a tried state.`"

Thomas Kite to his daughter Rebecca.

Sixth month 27th.

I have several times turned my attention towards continuing my advices,
according to thy request, but for the present, way does not seem to open to do so;
this is the less material, as thou hast, through Divine favour,
an infallible Director in thy own breast.
If thou avoids all that it shows thee is wrong, and does all it points out as right,
thou wilt indeed do well.
But if through human infirmity thou falls short, be willing to come under judgment;
be willing to feel thy Divine Master come in with his whip of small cords,
to correct in mercy,
and to turn all out of the temple of thy heart that his controversy is with.
Zion is redeemed through judgment, and all her converts by righteousness.

I find it of little use to form plans;
but I wish to see thee whenever I can feel at liberty to come to the school.

Diary: "`Sixth month 29th. Fifth-day.
At our Monthly Meeting I felt poor and depressed.
In the afternoon I attended the funeral of Elizabeth Mason,
eldest daughter of the late Samuel Mason, at Germantown.
Our friend Alice Knight, had a lively testimony at the house,
in which she expressed the belief that the departed was at rest.
I found it my place to follow her, in an exhortation to some who were present.

Seventh month 2nd. First-day.
I attended Germantown Meeting in the morning,
and was enabled to preach the Gospel to the relief of my own mind;
after which my beloved friend, Elizabeth C. Mason,
was favoured in bearing testimony to the one everlasting Foundation.
It was to me a comfortable meeting,
and I desire to be duly thankful for the unmerited mercy.
I returned to the city to our afternoon meeting.

9th. First-day.
In the afternoon meeting, the language of the apostle was remembered,
'`If there be first a willing mind, it is accepted according to that a man hath,
and not according to that he hath not;`' on which
I was drawn forth in a brief communication.

10th. Second-day.
I received a visit from Needham T. Perkins, a serious young Friend from North Carolina.
I had a religious opportunity with him,
and the counsel imparted appeared to make a suitable impression on his mind.

11th. Third-day.
Attended the North Meeting.
I sat in great weakness and poverty,
but was somewhat relieved under the lively ministry of my friend William Evans.

12th. Fourth-day.
At the Western Meeting I was favoured in testimony on the case of Esau,
who for one morsel of meat, sold his birth-right.
Counsel and caution were imparted.

14th. Sixth-day.
I went to Haddonfield to attend the funeral of my friend Elizabeth Edwards,
who in a private station, was an exemplary member of our Society.
At the grave I was enabled to preach the Gospel
from the words of our Lord to his disciples,
'`Let not your hearts be troubled; ye believe in God,
believe also in me,`' with more of the passage.
A good degree of solemnity seemed to attend.

16th. First-day.
I felt a concern to attend the morning meeting at Newton,
and the afternoon meeting at Haddonfield.
At the first I had an open time in testimony.
The subject principally treated of was,
'`that we must through much tribulation enter into the kingdom of God.`'
The afternoon meeting was less lively;
yet way opened to speak of the last passover which our Lord partook of with his
disciples before He suffered,--the nature of typical ordinances,--their abolition,
and the glorious realities which they prefigured.
Testimony was borne to the true supper of the Lord,
and his own emphatic declaration was stated, '`Except ye eat the flesh of the Son of man,
and drink his blood, ye have no life in you.`'

18th. Third-day.
I attended the North Meeting,
and was opened in testimony on the excellency of living faith,
'`the substance of things hoped for, the evidence of things not seen.`'

19th. Fourth-day.
I visited William Smith, son of the late Thomas, who seems to be near his close,
and to be in a calm, resigned state of mind.
Afterwards I had an opportunity with one who has lately
been received into membership with Friends.

20th. Fifth-day.
Our week-day meeting was small,
by reason of the absence of many of our members from the city.
Elizabeth C. Mason was well engaged in testimony from the words of our Lord,
'`This is life eternal, that they might know thee, the only true God,
and Jesus Christ whom thou hast sent.`'
Near the close I had a short communication, commencing with the passage,
'`Ye are not your own, for ye are bought with a price; therefore glorify God in your body,
and in your spirit, which are God`'s.`'

Thomas Kite to his daughter Rebecca.

Philadelphia, Seventh month 21st.

We do not hear when the English Friends are coming.
I was told yesterday that two of them,
John Pease and Isabel Carson were at York
Quarterly Meeting the latter part of last month,
and took leave of the Friends present; so it seems likely they may be here before long.
'`I do earnestly desire thy encouragement steadily to
persevere in the straight and narrow way.
Very hard it is to submit to the baptisms which reduce
our own wills into subjection to the Divine Will;
but the blessed result is well worth all the suffering it costs us.
"`Be thou faithful unto death;`" this is the command, and the promise,
"`and I will give thee a crown of life.`"

Again remember me affectionately to A. Williams;
tell her it is nothing new for the disciples of Christ to have many
afflictions in their passage to the land where sorrow is unknown.
Tell her, although she already knows it,
yet to stir up the pure mind by way of remembrance,
that the doctrine preached by Paul and Barnabas, as at Lystra, Iconium, and Antioch,
is the doctrine which is according to the truth of the Gospel; it is recorded of them,
that in those places they confirmed the souls of the disciples,
"`exhorting them to continue in the faith,
and that we must through much tribulation enter into the kingdom of God.`"

Diary: "`Seventh month 25th. Third-day.
At the Northern District Monthly Meeting.
In the meeting for worship I had to offer solemn
warning and encouragement to different states,
from the declaration of Christ, '`That servant which knew his Lord`'s will,
and prepared not himself, neither did according to his will,
shall be beaten with many stripes.
But he that knew not, and did commit things worthy of stripes,
shall be beaten with few stripes: for unto whomsoever much is given,
of him shall be much required; and to whom men have committed much,
of him they will ask the more.`'
In the meeting for business,
my dear friend Sarah Hillman obtained a certificate to attend Ohio Yearly Meeting,
some meetings belonging to it,
and a few within the compass of Baltimore Yearly Meeting.`"

Thomas Kite to his son Thomas.

Seventh month 27th.

I often feel desirous, and perhaps I often express it,
that Friends of Cincinnati may increase in the life of true religion,
so as to set a consistent example to those not of us;
and also that they may be prepared to hold all their meetings--those
for worship and those for discipline--with weight and dignity;
that nothing may be done in a barren form, or in creaturely activity;
but that coming under and abiding under the cross of Christ,
and waiting for the qualification which He gives,
all may be done to the glory of the Great Head of the Church,
the edification of the members, and the promotion of the cause of Truth in the earth.

Diary: "`Seventh month 30th. First-day.
At Westtown Boarding School.
In the morning meeting I was exercised on behalf of the children, the teachers,
and other caretakers; and addressed the various classes at some length.
In the afternoon meeting I was drawn out in vocal supplication.
Way opened for an opportunity with the three female assistants, who appeared tender.
May they be faithful to the Heavenly Guide.

Thomas Kite to his Wife.

Upper Darby, Seventh month 31st.

I had quite a comfortable ride to the Paoli tavern, on Seventh-day morning.
A bright little school-girl sat near me, with whom I had some interesting conversation.
She was but nine years old, yet seemed sensible, well informed, and religiously disposed.
'`I had felt my mind turned towards the Monthly Meeting of Darby, which occurs tomorrow.
On mentioning it to brother N. Sharpless, he seemed quite willing to accompany me;
so about four o`'clock, or a little before, we set off.
The rain had laid the dust, and the road by Bishop`'s mill was not much muddy,
so we had a nice ride to Jane Garrett`'s, where we now are.

May the Shepherd of Israel be near thee,
strengthening thee in the resolution to live more entirely to himself,
during the future days allotted thee, be they many or few,
so that when the end of thy race here shall arrive,
it may be the commencement of that state of never-ending felicity,
reserved for the faithful followers of the Lamb in his everlasting kingdom.

Diary: "`Eighth month 1st. Third-day.
At the +++[+++Darby]
Monthly Meeting.
I was opened in the first meeting on the nature of the Church of Christ,
bringing into view his declaration to Peter on his acknowledgment, £ Thou art the Christ,
the Son of the living God;`' '`Blessed art thou Simon Bar-jona;
for flesh and blood hath not revealed it unto thee, but my Father which is in Heaven.
And I say unto thee, Thou art Peter; and upon this rock I will build my church;
and the gates of hell shall not prevail against it.`'
Returned to Westtown in the afternoon.

2nd. Fourth-day.
Under an impression of duty I had an opportunity with the female teachers;
then went to Birmingham Monthly Meeting.
In the first meeting I had a short communication.
Went after the meeting to my son-in-law`'s,
where I had the agreeable company of my two daughters and other relatives and friends.`"

Of this meeting, one who was present wrote: "`His Gospel labour was acceptable this day,
to many of us.
He had a word of encouragement to hand forth to those who were
willing to become disciples of their dear Lord and Master.
I think it was a comfortable meeting.`"

Diary: "`Eighth month 3rd. Fifth-day.
I went to Concord.
In the afternoon visited Rebecca, widow of Samuel Trimble,
and had a religious opportunity in the family,
encouraging the bereaved mother and her children to trust in Him of whom it is declared,
'`A Father of the fatherless, and a Judge of the widows, is God in his holy habitation.`'

4th. Sixth-day.
At Concord Monthly Meeting, and was again engaged in testimony.
Returned to the city in the evening.

7th. Second-day.
At Quarterly Meeting.
Sarah Hillman`'s prospect received the necessary sanction,
and she was set at liberty to pursue it.
May Israel`'s Shepherd go with her and preserve her!

10th. Fifth-day.
At our week-day meeting,
I had to revive a part of one of the blessings pronounced by Moses,
when he blessed the children of Israel before his death: '`And of Levi he said,
Let thy Thummim and thy Urim be with thy Holy One, whom thou didst prove at Massah,
and with whom thou didst strive at the waters of Meribah.`'
I offered encouragement to some who had been called to the work of the Lord,
who had proved him as at Massah, and had striven with him as at the waters of Meribah.`"

Thomas Kite to his daughter Rebecca.

Eighth month 11th.

It is probable that B. H. Warder and his sister-in-law, Margaret Sheppard,
will accompany Sarah Hillman to Ohio.
It is understood that the expected English Friends have
taken passage in the steamer Hibernia for Boston,
which will be looked for from the 16th to the 20th of this month.
With fresh desires for thy preservation in the narrow path,
the end whereof is everlasting life, I bid thee affectionately farewell.

Diary: "`Eighth month 13th. First-day.
I was engaged publicly to speak of the sufferings and death of the Lord Jesus Christ;
and being dipped into sympathy with those who are
endeavouring to follow Him in the regeneration,
I had to offer such encouragement.
Afterwards I ventured to bow the knee in vocal supplication and thanksgiving.
Our afternoon meeting was silent.

Thomas Kite to his son Thomas.

Eighth month 19th.

I do not wish to weary thee on the subject which is nearest my heart in relation to thee;
but I can hardly let any letter escape me without adverting to it.
I am not without my wishes for such a share of temporal prosperity
for thee as thy Heavenly Father may see meet to grant;
but far more ardent are my desires for thy spiritual and everlasting wellbeing.

Oh! that thou may be increasingly devoted to thy Creator and Redeemer;
that thou mayest be a consistent Friend; a crucified and quickened Christian;
dead to the world, but made and kept alive unto God through Christ Jesus;
prepared to be a spiritual worshipper of Him who is a spirit,
and to be a preacher of righteousness in life and conversation.
Such are greatly needed in our Society, in almost every part of it; and I apprehend,
especially so in the place where thy lot is cast.
Perhaps, through the faithfulness of individuals to the visitations of Divine grace,
which appear to all,
the Lord in mercy may grant you a revival of zeal and earnestness for his cause,
and unite the hearts of some amongst us to labour for a thorough reformation,
and to endeavour in the ability received to promote family discipline,
and the discipline of the Church.

Diary: "`Eighth month 20th. First-day.
After several days of tossing and conflict,
wherein I felt oppressed under the prevalence of the earthly nature,
in our morning meeting I felt somewhat relieved; and an opening for service presenting,
I was strengthened once more to proclaim the way of life and salvation.

23rd. Fourth-day.
I felt drawn to attend the Monthly Meeting for the Southern District;
and was engaged to appear in testimony, commencing with the words of the prophet Isaiah:
'`In that day shall this song be sung in the land of Judah; we have a strong city,
salvation will God appoint for walls and bulwarks.`'
My friend William Evans obtained a minute to attend Indiana Yearly Meeting.

24th. Fifth-day.
Our Monthly Meeting.
My mind has been exercised of late with a concern to attend
the approaching Yearly Meeting to be held in Indiana.
After feeling in a good degree resigned thereto, it seemed to be very much withdrawn;
within a few days, however, it has revived; and under some feeling, as I believe,
of that Power which subjects the creaturely will, I opened it to my friends,
and obtained their concurrence.
I now feel a state of peaceful poverty.`"

Thomas Kite to his daughter Susanna.

Philadelphia, Eighth month 25th.

The English women Friends arrived in this city yesterday.
Isabel Casson is a comely, fleshly person, apparently about sixty-five years old.
Rachel Priestman is small, of slender proportions, and is no doubt much younger.
Thy mother and I saw them.
They seemed affable;
and hardly able to realize that in a few days they had made so great a change.
They met Jacob Green in Liverpool on his way to Scotland.

Diary: "`Eighth month 27th.. First-day.
At our morning meeting I was concerned to revive the Psalmist`'s declaration:
'`The fear of the Lord is the beginning of wisdom;
a good understanding have all they that do his commandments;`' on
which I was considerably enlarged in addressing various states.
In the afternoon meeting an opening presented from the book of Psalms;
from which I had to offer the consolations of the Gospel to some tribulated minds,
it being the following: '`How amiable are thy tabernacles, O Lord of Hosts!
My soul longeth, yea, even fainteth, for the courts of the Lord;
my heart and my flesh crieth out for the living God.
Yea, the sparrow hath found a house, and the swallow a nest for herself,
where she may lay her young, even thine altars, O Lord of Hosts, my king and my God.
Blessed are they that dwell in thy house: they will be still praising thee.`'

Ninth month 3rd. First-day.
At morning meeting, the command given to Moses when he was about to make the tabernacle,
was revived:
'`See that thou make all things according to the pattern showed to thee in the mount.`'

Thomas Kite to his daughter Rebecca.

Philadelphia, Ninth month 4th.

My prospect is to attend the Meeting for Sufferings next Sixth-day week,
and set off for Indiana the same afternoon, by way of Baltimore, Wheeling and Cincinnati.
If the river Ohio is too low for steamboats,
I may be under the necessity of taking the stage at Wheeling,
and proceed directly to Richmond.
My intention is to try and find time to come out and bid thee farewell before I go;
perhaps on Seventh-day next.
If I fail, it will not be for want of inclination.
How long the journey will occupy me, I do not know;
but suppose it may take about four weeks.

Diary: "`Ninth month 5th. Third-day.
At the North Meeting I bent my knees in vocal supplication to the Most High.
At this meeting my young friends Clarkson Sheppard and
Anne Garrett took each other in marriage.

6th. Fourth-day.
At the Western Meeting.
I was engaged in testimony on the subject of worship.
The circumstance of the two men who went up into the temple to pray, the one a Pharisee,
and the other a publican, was introduced.
Various states were addressed.

7th. Fifth-day.
At our week-day meeting a short communication was made,
respecting the woman who had an alabaster box of very precious ointment,
and poured it on the Saviour`'s head as He sat at meat.

10th. First-day.
In the afternoon meeting a testimony was delivered on the declaration of the apostle:
'`Without controversy great is the mystery of godliness: God was manifest in the flesh,
justified in the Spirit, seen of angels, preached unto the Gentiles,
believed on in the world, received up into glory.`'

Isabel Casson and Rachel Priestman had appointed a meeting,
to be held in the Mulberry Street house,
on Ninth month 10th. Thomas Kite in a letter to his daughter Rebecca, dated the 11th,
thus speaks of it: "`The meeting for the market people, butchers, hucksters, etc,
was held on First-day evening.
It was not very large.
The people behaved well.
Rachel Priestman had all the public service.
She spoke twice by way of testimony, and appeared in supplication.
She and Isabel have gone to Jersey to attend Haddonfield Quarterly Meeting,
and some meetings within its limits.`"

Diary: "`Ninth month 12th. Third-day.
At the North Meeting,
I was opened on the subject of the prophet Jeremiah`'s visit to the potter`'s house,
when he saw, '`and behold, he wrought a work on the wheels:
and the vessel that he made of clay was marred in the hands of the potter;
so he made it again another vessel, as seemed good to the potter to make it.`'
I had to express a belief,
that a renewed visitation has been extended to some who
had been as vessels marred upon the wheels,
and also to caution others upon whom the Lord`'s hand is
turned to form them into vessels for his use.
I likewise had comfort to offer to those who love the Lord, but are walking in darkness.
Afterwards William Evans ministered to the afflicted
children of our Heavenly Father`'s family.`"
