== Chapter II.

[.chapter-synopsis]
* 1806-1808.
* Thomas kite joins in partnership with his father
* Meets with Elizabeth Barnard, and is married to her.

+++[+++Benjamin Johnson was so well satisfied with the conduct of his late apprentice,
and so assured of his correct moral principles and good business habits,
that he offered him a share in his business.
This offer Thomas Kite accepted,
and remained in partnership during the latter part of the year 1806.
In the Eighth month of that year,
having business to attend to in the State of Delaware and the eastern shore of Maryland,
he concluded to accompany his father to Chester County,
and there seek a means of conveyance to enable him to accomplish his proposed journey.
While absent he wrote to his mother and sister Abi.+++]+++

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Elkton, Md., Eighth month 7th, 1806.

[.salutation]
Dear Mother and Sister:

We left Philadelphia on
Third-day morning last (Eighth month 5th).
We reached grandfather`'s about 10 o`'clock at night;
left aunt Sarah there and proceeded on to uncle Nathan +++[+++Walton`'s+++]+++,
where we arrived about 11,
and got to bed about 12. Next morning I went over to Abraham Romans,
who kindly offered me a horse to pursue my contemplated journey.
+++[+++That day+++]+++
father and I went to London-grove Monthly Meeting, he in uncle Nathan`'s light wagon,
I with Abraham Romans.

Uncle John +++[+++Letchworth+++]+++
opened a concern which had impressed his mind,
under which he believes it to be his duty to
attend the ensuing Yearly Meeting at Baltimore,
some meetings belonging to the Quarterly Meeting of Baltimore,
the Monthly Meeting of York, and some meetings on the way.
A number of Friends expressed their unity with his prospect,
and a committee was appointed to prepare a certificate.

Fifth-day.
This morning, after breakfast, I started from uncle Nathan`'s. The country,
on leaving his house, very soon has a more level appearance,
not many high hills to be seen except the Octoraro,
which at a few miles distance from the road appeared to extend
in a range not much differing from a north and south direction.
Dined at Nottingham, in a public house, and proceeding, crossed the Maryland line.

The land from West Fallowfield to within a few miles of Elkton appeared poor,
and poorly cultivated.
Since dinner there has been several appearances of gusts, and I was caught in the rain.
About 6 o`'clock I reached this town, which is situated on Elk River,
a stream navigable within a mile, and emptying into the Bay of Chesapeake.
It is the capital of Cecil County, contains a jail and courthouse;
and a number of respectable buildings.
It was very sickly last fall, but some marshes in the neighbourhood having been drained,
it is not so much so this year.
While I write the rain falls considerably, and it thunders.
Some of the claps have been very loud; but a blessing attends,
rain being very desirable from the dryness of the ground.

[.signed-section-context-open]
Chester Town, Kent County, Maryland, Eighth month 9th, Seventh-day.

On Fifth-day evening, in one of the streets of Elkton, I saw a black lad,
born without arms, Next morning,
seeing him again as he was sitting on a bench at the door of a house,
I entered into conversation with him, He can read and write,
and his master maintains him.
I threw a trifle of money on the ground for him; he picked it up with his toes,
threw it up, caught it on the back of his foot, laid it on the bench,
took it up with his teeth,
and twisting his body into such a position as opened his pocket,
let the money fall into it.
At my request, he with a stick wrote, my name on the ground.
All this he performed with apparent ease and great dexterity.

Yesterday, Sixth-day, I left Elkton, and crossing Elk Creek, one of two streams,
the confluence of which forms the Elk River, I passed the Maryland line into Delaware.

This morning I crossed one of the branches or feeders of the proposed
canal for uniting the waters of the Delaware and Chesapeake,
and arrived at Glasgow, or Akinstown, a sickly village.
From there to Middletown; from there to Warwick, +++[+++in Maryland+++]+++,
a miserable looking village, and proceeded to the "`Head of Sassafras.`"
This last-named village derived its name from several streams
uniting near it and forming the head of Sassafras River,
which is navigable within a few miles of the place.
I lodged there at a Friend`'s house, and proceeded this morning to Georgetown Cross Roads,
a small village; from there to Chester-town, the capital of Kent County, where I now am.
This place is situated on Chester River, which is a navigable stream, wider,
I believe than the Schuylkill at Philadelphia.
The town contains a courthouse, jail, market-house, several places of worship,
and near it is a large house built for a college, but not so occupied at present.

[.signed-section-context-open]
St. George`'s Hundred, New Castle County, Delaware.

Eighth month 11th, Second-day.
After writing the preceding, just as I was going to bed,
I was taken with a chill and fever, and passed a very trying night.
The thought of being sick so far from home was afflicting.
In the morning I called on a physician, who prescribed medicine,
advised me to lay by till the fever left me, and then return immediately to Pennsylvania,
as the sickly season had commenced.
I rode accordingly slowly out of Chester-town into the country about five miles,
put up at a farm-house, and took the medicine.

During its operation I felt very unwell,
but in the afternoon the fever abated considerably,
and I rode on to the head of Sassafras River, and lodged at the house of a kind Friend,
where I was favoured with a good night`'s rest.
I have ridden about 13 miles this morning, feel much better than yesterday,
and expect a few day`'s residence in Chester
County will render me strong and hearty as usual.

--

[.small-break]
'''

+++[+++Thomas Kite returned home by way of Wilmington,
and attended Concord Quarterly Meeting before reaching Philadelphia.

Although in partnership with Benjamin Johnson,
Thomas Kite was not satisfied that it was his proper place.
His father was growing old, had become temporarily very hard of hearing,
and his school duties, for the right performance of which this had partly unfitted him,
had become irksome to him.
Benjamin thought the time for his release from teaching was drawing near,
and both he and his son believed it would be right for them to
enter into the book selling and publishing business together.
After much deliberation thereon,
they signed articles of co-partnership on the 2nd of the Twelfth month of this year,
although they did not engage in business for several weeks thereafter.

Benjamin Kite having informed his brother John Letchworth of
his prospect of entering into business with his son,
John felt concerned to address a letter of caution to his nephew,
who he well knew would be the active business member of the firm.+++]+++

[.embedded-content-document.letter]
--

[.signed-section-context-open]
East Fallowfield, Eleventh month 30th, 1806.

[.salutation]
Dear Nephew:

Your father hints that he has a prospect of entering into business with you.
This is a subject not new, I believe, to him; therefore I hope, indeed I expect,
it has been well weighed.
The calling he is at present in is not likely to yield
much to lay by for those days of feebleness,
when the lighting on of a grasshopper may seem a burden.

I was going to hint that you have served a regular apprenticeship,
and have some experience in the store, have a pretty large acquaintance,
and perhaps by this time large ideas of doing business; for youth is violent.
Mournful instances of this has your city produced.
Your father styles himself, and, perhaps, justly, timid.
Now I wish, if there be any portion of rashness in your composition,
that his timidity may act as a just counterpoise,
that so you may get along with reputation and peace.
My desire is that if he should, in the course of your business,
not be willing to go all lengths you would wish, you should not impute all to timidity,
or his not understanding the business.
Remember he has wisdom, age and experience on his side,
which ought to operate strongly to temper your zeal for doing much.
Ah!
Thomas, do not be a dasher, but let the grave counsel of your father have its due place,
and then, as Franklin describes the New England teams,
two pulling down the hill and two up, lets the wagon down in safety.
That you may thus conduct, is the desire of your affectionate uncle,

[.signed-section-signature]
John Letchworth.

--

[.offset]
+++[+++To this letter Thomas Kite thus replied:+++]+++

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Philadelphia, Twelfth month 11th, 1806.

[.salutation]
Dear Uncle:

Your letter, and the concern it expresses for my welfare,
were both agreeable,
and I hope you will never omit communicating what you
may apprehend will prove beneficial to me.
Youth, as you observe, is rash,
and is moreover oftentimes exposed to temptations which render the advice
and counsel of those who have trodden the slippery paths before us,
useful to those who are just upon the threshhold of manhood.

Independently of forming an establishment which may afford myself a livelihood,
can my attention be turned to a more proper object than to
relieve my beloved father from that labourious and irksome
employment so peculiarly unsuitable in the evening of life,
and from which his mind feels very much relieved?
As he is scarcely a day quite well, teaching hangs as a burden upon him.
To all this it may be added that his family is increasingly expensive,
and necessarily so, while his business is scarcely adequate to bear it.
These are in part my motives for entering upon that business to which you allude,
in the prosecution of which I desire we may do nothing
which will bring reproach upon our profession.
I hope, in conformity to your advice,
to pay proper attention to the cautions of my father,
and not to undertake anything of magnitude that has not his concurrence.

--

[.small-break]
'''

+++[+++In the spring of 1807 Benjamin Kite gave up his
school and devoted himself to his new occupation.
The firm had not much capital; the father put in a small sum,
the saving of thirty years of quiet, industrious attention to teaching,
and the son brought business habits, activity and enterprise.
With much constitutional timidity,
Thomas Kite had in the commencement of his business too earnest a desire to extend it.
Some severe lessons which he soon received, were of essential service to him.
The most important one was this: A person, married to a rich woman,
whose property was however, secured from his creditors, persuaded Thomas,
as a mutual accommodation to them in their business,
to exchange promissory notes to a considerable amount.
This placed in the hands of each a capital,
which was used to extend their publishing operations and increase their stock.
Objects, which promised to inexperience advantages which were never realized.
The man soon failed, and leaving the new firm to pay his and their own notes,
amounting to more than all their capital,
he quietly retired behind his wife`'s secured patrimony and lived in affluence,
while those he had wronged had to strain every nerve to
collect sufficient to meet the notes as they became due,
and maintain their credit.

In the latter end of the Seventh month, 1807, Thomas Kite visited New York,
with many of the cities and towns of New England,
and established business connections with the principal publishing houses there.
On his return to Philadelphia his father paid a visit to their
relations and friends in Western Pennsylvania and Ohio.

Thomas was fond of being in the company of those
whom he esteemed of religious experience,
from whom he could hope to derive instruction in righteousness.
One of his visiting places during the latter part of
his apprenticeship and for some years after,
was at the house of Emmor Kimber, who was then esteemed, and doubtless was,
a valuable minister of the gospel of Christ Jesus.
In Emmor`'s family he became acquainted with Elizabeth Barnard, a pious young woman,
who had been educated an Episcopalian, had joined the Baptists,
but being favoured to see beyond the administration of outward rites,
and convinced of the doctrines of the Society of Friends,
had been admitted into membership among them.

To her his mind was drawn in affectionate feeling,
and believing it was according to the will of his Heavenly Father, he,
with the consent and approbation of his earthly parents,
made proposals of marriage to her, which were accepted.

She was a native of Wilmington, in the State of Delaware,
and appears to have derived spiritual benefit from the ministry of Joshua Maule,
from whom, after her removal to Philadelphia in the spring of 1806,
she received several letters.
One of them we insert.+++]+++

[.embedded-content-document.letter]
--

[.letter-heading]
From Joshua Maule to Elizabeth Barnard

[.signed-section-context-open]
Wilmington, 3rd of Seventh month, 1806.

[.salutation]
Dear Friend:

I received a few lines from you informing of your situation,
which was very comfortable to me.
When I read them my mind was humbled and broken into
tenderness by the fresh manifestations of Divine Good,
which we have very unworthily, and yet largely partaken of.
May our minds be deeply humbled under a sense of it,
that we may be qualified to render grateful acknowledgments to Him,
who has been thus mindful of us, and helped us when we had no power to help ourselves.
How, dear Elizabeth,
can we better express our gratitude than by
yielding unreserved obedience to the Divine will,
however it may be in the cross, remembering it is not every one that says Lord!
Lord!--that shall enter into the kingdom of heaven,
but he that does the will of the Father in heaven.
I have often thought of you, since you left us, with secret satisfaction,
and am solicitous that not only you, but I,
may be qualified to adopt the language in humble resignation of mind--"`Lord,
I will follow you whithersoever you go.`"
Then I believe we shall not only experience the way made plain before us,
but we shall be strengthened to walk therein.
Though at first it may seem to be a strait and narrow way,
yet it will be experienced to be a way of pleasantness and a path of peace,
by all those who become acquainted with it.

James Brobson buried his daughter Sally last week; a very affecting case.
A flower nipped in its bloom, respecting whom it may be said, "`how has beauty fallen!`"
It seems to be an additional testimony that "`all flesh is as grass,
and the goodliness of man as the flower of the field.`"
Though the grass withers and the flower fades as soon as it is in bloom,
yet the Word of the Lord endures forever.
I do not mean the Scriptures, they are not the Word.
I mean that quickening Word of Life,
that more sure Word of Prophecy unto which we shall do well if we take heed,
as unto a light shining in a dark place.
It is able to build us up and give us an inheritance among all them that are sanctified.
That we may have this truth realized in our own experience, is the desire of your friend,

[.signed-section-signature]
Joshua Maule.

--

[.small-break]
'''

+++[+++The marriage of Thomas Kite and Elizabeth Barnard was
accomplished on the 30th day of the Third month,
1808, at the meeting-house of Friends in Pine Street.
David Sands, who was then in Philadelphia on a religious visit, was at the meeting,
and dined with the wedding company.

Thomas Kite, in a short account he left of his life,
thus speaks of this marriage connection.+++]+++

[.small-break]
'''

On the 30th day of the Third month, 1808, I was married to Elizabeth Barnard,
a pious young woman, who, after having been brought up in the Episcopal way of worship,
had, when quite young, been induced to attend the meetings of the Baptists,
and to submit to the outward rite from which they have their name.
For a time she walked in communion with them,
but not experiencing that inward satisfaction she longed for,
she was at length convinced of the principles of Truth as held by us,
began to attend our meetings,
and after a time of serious attention to the gradual unfoldings of Heavenly light,
was joined in membership with us,
about the period when my acquaintance with her commenced.
I believe she continued faithful to her Divine Guide,
and we were measurably favoured together with the incomes of heavenly love.
