== Chapter III.

[.chapter-synopsis]
* 1808-1811.
* Call to the ministry
* Death of Elizabeth Kite
* His testimony concerning her.

+++[+++Thomas Kite was now married, and in his new connection,
with unusual cares he experienced an accession of unusual comforts.
He was affectionate in his feelings,
and was well qualified by his natural disposition to promote domestic happiness,
and to enjoy it.
His conversational powers were good,
and he had a fund of interesting incidents in his memory,
ready to come forth in their proper place to enliven his discourse.
Above everything he appeared desirous that the members of his
household should be seeking the Lord for themselves,
and endeavouring to grow up in good likeness before Him.
His letters manifest this concern,
and also pleasingly set forth the strength of his affectionate feelings.

Soon after the Yearly Meeting in 1808,
Elizabeth Kite visited her relatives and friends in her native place.
While she was absent her husband addressed the following note to her.]

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to His Wife

[.signed-section-context-open]
Philadelphia, Fifth month 6th, 1808.

[.salutation]
My Dear:

Home has lost part of its charms since you left me, yet considering our loss,
we are tolerably comfortable.
Robert L. Pittfield and Elizabeth Folwell accomplished
their marriage yesterday at our meeting,
and were addressed in the language of encouragement by Samuel Smith and David Sands,
the latter of whom took leave of Friends.
Farewell, my love, tomorrow I hope to see you.

--

+++[+++A few cases of highly malignant bilious fever occurred
in Philadelphia in the latter end of the summer of 1809,
and occasioned some alarm to the inhabitants.
At this time, about the middle of the Eighth month,
Elizabeth Kite and her little charge retreated for a few weeks
from the city to the house of Stephen Morris at Evesham,
New Jersey.
While she was there her husband frequently wrote to her.
In one of his letters, dated Eighth month 26th, he says: "`As I mentioned yesterday,
the city continues healthy,
indeed I question much whether a case has been known
within a week that looked like yellow fever.
Home seems to me very lonely,
deprived as I am of the society of her whom I love beyond all others;
but believing the country to be useful to our dear child,
I am willing to submit to the deprivation for her sake.
Beside, I trust, your health will be improved, which is another motive for resignation.`"

Looking back to this period of his life and business, Thomas Kite afterwards wrote thus:]

[.small-break]
'''

In the prosecution of my outward concerns I had many trials and temptations,
yet I was favoured to keep the love of Truth so far predominant,
as never to neglect my religious meetings, and though at times much discouraged,
and after my marriage full of fears lest I should not
be able to support my family reputably,
yet through the Lord`'s unmerited goodness I was not only permitted to
discharge my engagements with a good degree of punctuality,
but never knew the lack of the necessaries and common comforts of life;
so that I have abundant cause to acknowledge to the truth of Christ`'s promise,
Seek first the kingdom of God, and all these things we have need of,
while in this state of being, shall be added.

[.small-break]
'''

+++[+++Thomas Kite was passing through many inward conflicts
to fit him for the work of the ministry,
to which he was sensible he was called,
yet he made no note of his exercises from Fifth month 13th, 1806,
until the beginning of the Fourth month, 1810,
shortly after his first public appearance as a minister.]

[.small-break]
'''

+++[+++Diary:] Fourth month.
I have for several years believed, if I kept my place,
it would be required of me to bear testimony to the Good Hand
that has delivered me out of Egyptian darkness.
This concern has latterly increased upon me,
so that I have sometimes thought a few words required of me in religious opportunities,
to which I have several times given up in private,
but not in public until the 20th of the Third month,
when at Frankford I expressed a small matter that had rested on my mind, in great fear.
Oh may I be preserved near the Divine Guide.

[.small-break]
'''

+++[+++His friends had, some of them, been dipped into sympathy with him,
in the prospect of his being called to this awful work,
and the day of his appearance at Frankford,
his relative and friend Mary Harper had exhorted him to
faithfulness to the requirings of duty in this line.
He spoke on the text in the Apocrypha, Ecclesiasticus ii.
10: "`Look at the generations of old and see;
did ever any trust in the Lord and was confounded?
or did any abide in his fear, and was forsaken?
or whom did He ever despise, that called upon Him?`"]

[.small-break]
'''

+++[+++Diary:] Fourth month 4th. Attended Byberry Meeting;
believed myself commissioned to sound an alarm to some, who, I apprehended,
had not many years to live,
and who were not yet prepared to receive the inscription of "`Holiness unto the Lord.`"

21st. Our Yearly Meeting concluded yesterday.
During the course of this meeting Friends have been
preserved in a good degree of quietude and harmony,
and although the power of Truth in the meetings of Discipline
appeared not to be so eminently manifested as at some other times,
it was, upon the whole, a comfortable season.

Fifth month 13th. Oh that I may be preserved in humble, patient waiting in the deeps,
nor presume to offer strange fire on the Lord`'s altar.
Oh may I never step forth, unless the Shepherd of Israel puts forth and goes before me.
Under an impressive sense of my insufficiency for the awful work,
may I be increasingly incited to abide in the Vine,
to receive the circulation of sap from the Root,
which will indeed keep the plant alive in my soul,
and enable it to bear fruit to the honour and praise of the everlasting Husbandman,
who indeed is worthy of the praise of his own work, now and forever, amen.

Sixth month 11th. Attended Haddonfield Monthly Meeting.
Found peace in endeavouring to discharge my mind of a concern for parents,
near the close of a meeting for business.

[.small-break]
'''

+++[+++Having taken his wife to Wilmington,
he left her there to spend a short time with her friends and relatives,
and returning to Philadelphia, met with the adventure described in the following letter.]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Philadelphia, Sixth month 21st, 1810.

[.salutation]
My Dear:

I sit down in the cool of the morning
to give you an account of our progress yesterday.
The morning was fine and a breeze rendered the ride agreeable,
so that we came along pleasantly enough until we arrived at Chester creek, where,
the tide being low, the bank presented an abrupt descent.
As we were going down to the flat the driver says one of the horses was frightened,
stepped on one side, and the horses and stage were turned over,
the horses into the creek, the stage at the edge of the water.
We were somewhat alarmed at our awkward situation.
I crawled out into the mud, and Rebecca Maule followed,
but being assisted did not get so muddy as I. We
went up to the tavern and changed our clothing,
the tavern-keeper`'s wife lending me some of her husband`'s clothes.
I felt most concerned respecting Rebecca, but she appears to have sustained no injury,
and stood the whole ride very well.
After we were thoroughly dried, it appearing that the roof only of the stage was damaged,
we proceeded on our journey and reached home about two o`'clock.

[.letter-heading]
To His Wife.

[.signed-section-context-open]
Sixth month 22nd.

Yesterday, Fifth-day, was Preparative Meeting.
James Sellers`' request to become a member of Society was introduced,
and a committee appointed.
We had the company of Mary Morton, who was exercised in supplication.
Farewell, my dear, may you be preserved in the way of duty,
the path of Divine appointment, whether rejoicing be your portion or affliction your lot,
and if you are favoured to feel ability to do so, pray for your poor husband,
that he may be kept from the snare of the devourer.

Sixth month 26th. We have another instance of the uncertainty of life,
in the removal of Thomas Annesly.
He appeared in usual health on Seventh-day evening and died in the night.
His remains were interred on First-day evening attended
by a large concourse of Friends and others.
I have felt poor and low since you left me,
but I desire to be contented with my allotment.
In a little time all our trials will be over.
May we then be enabled so to improve the time and opportunities
afforded us as to lay up for ourselves a good foundation,
that when our earthly tabernacles fail we may be received into everlasting habitations.

--

+++[+++Diary:]
Seventh month 31st. During the present month I have suffered loss from
reading books not written by persons under the influence of Truth.
Too much talking has been indulged in, and something of slander.
I have felt convictions for the last.
Something of a waspish temper,
an additional evidence that my will is not thoroughly subjected to the principle of life.
Lord! pardon my sins.
In writing a letter this day, I mentioned a text of Scripture,
and made observations of a religious nature.
I am fearful they were not seasoned with salt, as I felt afterwards burdened.
Went to North Meeting.
Some observations were expressed on the necessity of faith in God,
and in the propriety of all his dispensations.
I feel very feeble; may I be preserved watchful, patient and humble.

Eighth month 1st. Some small symptoms of anger in my mind, not much apparent to others.

2nd. Spent this day without much cause of self-reproach.

5th. In the morning meeting the people were invited to Jesus Christ, the same yesterday,
today and forever.
Afternoon meeting proved a low season.
I was deficient in patient waiting.

8th. Having in a jocular way repeated a passage of Scripture, felt sorry for it.

12th. Morning meeting: an exercise attended on account of some of the younger class;
after disburdening my mind I felt poor and weak.
Afternoon meeting: dull, and a wandering mind much prevalent in me,
against which I did not war so earnestly as I ought to have done.

13th. Paid a visit of a sociable nature; but not being rightly timed,
I had little satisfaction.
In the evening a pleasanter one.

14th. Was thoughtful about attending a country meeting,
but after a solid conference with a Friend on the subject, was easy to omit it.

19th. At morning meeting; an opening, but without sufficient life to be uttered.
That which dies of itself you shall not eat.

26th. Last evening, wishing to give some advice to a particular person,
I enlarged somewhat in the way of preaching but without the requisite qualification:
it has since been burdensome to my mind.

30th. Returned last night from a visit to my child at Wilmington.
During my absence from home I engaged in political conversation with a friend,
to the wounding of my mind.

Ninth month 2nd. Yesterday, by gratifying my inclination,
introduced my mind into weakness.
Felt naked and wounded in morning meeting, yet some desires for a thorough purgation.
In an opportunity of retirement with my family after dinner,
some serious thoughts were present, which I dropped among them.

9th. Returned yesterday from a journey to New York, during which,
for lack of more indwelling, my mind has been too much outward and dissipated.
While I was at New York our Friend Benjamin White arrived,
returning home from a religious visit to Friends in Great Britain.
In the same vessel with him came Susanna Horne, on a like errand to this country.
May she be instrumental to arouse the careless, comfort the feeble-minded,
and enabled to proclaim liberty to the captive.

At morning meeting: some considerations with thoughts of expression,
but wishing to have the prospect weighed in the balance, was easy in silence.
Afternoon: fear I was not earnest enough in spirit after retirement of mind.

10th. Spoke hastily on finding something in the line of
business had not been accomplished according to my wish.
Called to see a sick young man.
Dropped a word of encouragement, but have feared it had not sufficient savour.
Tried of late with poverty.
May every dispensation prove a means of my refinement.

16th. On looking back over the few past days I find
cause to deplore a lack of greater watchfulness.
In the morning meeting an impression concerning individuals,
but as I was making ready another stepped in before me.
The matter continued after he sat down, but the meeting soon closing,
I did not unburden myself.

27th. Fear I have been rather too much engrossed for several days past, with the world.
A few evenings since at a meeting of a society of a benevolent nature,
too active in discussing and promoting measures relative thereto.
Yesterday at Pine Street and today at our Monthly Meeting somewhat favoured in silence.
In the evening,
dear Susanna Home had a precious opportunity with us of the young classes of Society,
and those of similar ages, not in membership, who attend our meetings.
Invitation and caution were handed forth, and a covering of solemnity prevailed.
May the Lord alone be praised!

30th. At morning meeting: an impression of duty to stand up,
but many appearances being made, I was silent.
Hope the opportunity was not entirely unprofitable.

Tenth month 5th. Yesterday our adjourned Monthly Meeting.
First meeting my mind engaged in religious considerations,
but fear they were not in the pure openings of Truth,
but rather the fruit of my own cogitations.
In the meeting for discipline I might have been easy with being less active in words.
Oh for a more deep indwelling under that exercise of mind which is
begotten by the Truth in all our meetings of worship and discipline.

14th. May I be preserved patient and humble,
nor presume to burden the living by words without life.
I fear that self has had too great influence,
although I was not sufficiently sensible of it.
Oh that I may be enabled to abide low, and experience all my sins,
whether of omission or commission, whether proceeding from the activity of self,
or the transformations of the power of darkness, washed away in the blood of the Lamb.
The desire of my heart is, that every dispensation may, by the Lord`'s sanctifying power,
be made to work together for my real good, and furtherance in the way of peace.
May I be enabled to cast down imaginations and every high thing,
and simply wait upon the Lord Most Holy in the
nothingness of self in prostration of mind.
Oh Holy Being, forsake me not.

21st. On a review of the past week I am persuaded my mind has been too much outward;
intent on worldly things,
and little or no qualification experienced to aspire after heavenly treasures.

[.small-break]
'''

+++[+++Towards the close of the Ninth month, Elizabeth Kite fell down a flight of stairs,
and although not at the time conscious of receiving much injury, it proved,
in the opinion of her medical attendant, the cause of her death.
Her second child, William, was born on the 25th of the Tenth month,
soon after which event her health rapidly sunk.
Her husband thus describes her close in his Diary.]

[.small-break]
'''

Eleventh month 16th. My dear wife is very ill.
The physicians give no hope of her recovery.
She has been a precious companion to me, and has been a spiritual worshiper.
I trust, through the mercy of her Almighty Saviour, if removed at this season,
it will be to a mansion of rest.
Oh that I may be permitted so to experience the cleansing operations
of Divine love as to witness a qualification to join her,
when the appointed time comes, in celebrating the depth of his love,
who remains to be the Father of the fatherless, the Judge of the widow,
the refuge of the afflicted, and the salvation of his people.

19th. My dear companion was this morning removed to her everlasting resting place.
Oh may I be favoured to get deep enough to discover whether it is not
for my correction that this afflictive dispensation has befallen me.
May I kiss the rod and turn to Him who has appointed it, saying "`The Lord gave,
and the Lord has taken away, blessed be the name of the Lord!`"

20th. The body of my dear wife was this day interred.
The evening after her departure, in testimony,
Isaac Paxson expressed his belief of her qualification
for entering into the heavenly kingdom,
as also in the same opportunity, Emmor Kimber.
At the grave,
Thomas Scattergood had to testify his belief that she had stood in her allotment,
and was safely landed,
"`Where the wicked cease from troubling and the weary soul forever is at rest.`"
In the evening, in a season "`of silent retirement in my family,
with some sympathizing Friends, my mind was mercifully made quiet and resigned.
Emmor Kimber addressed the throne of grace in supplication for the company present,
and thanksgivings for mercies past;
and in particular that my mind had been favoured with resignation,
as well as the minds of other near connections of the beloved deceased.
His prayer was that our language might continue to be "`It is the Lord,
let Him do what seems Him good.`"

[.offset]
+++[+++The following short testimony concerning his deceased
wife was found among Thomas Kite`'s papers.]

[.embedded-content-document.testimony]
--

[.letter-heading]
Some Particulars Respecting My Dear Wife.

Elizabeth
Barnard was born the 12th of Second month,
1786, at Wilmington.
She was, when young,
tinctured with that vanity to which childhood and youth are incident,
yet through the merciful kindness of the Lord she was early
visited with a sense of his controversy against sin,
and earnest desires were begotten in her for deliverance from its bondage.
In this state of mind she attended the religious meetings of the Baptists,
and having submitted to the initiatory rite practised by them,
became a member of their communion.
She continued in this way a few years,
and was considered a young woman of exemplary conduct:
but her mind soon became uneasy with some outward observances practised by that people,
feeling them to be lifeless and formal,
and being earnestly desirous of an establishment in a state of greater purity,
she was mercifully favoured with a more full discovery of the means of salvation,
the grace of our Blessed Redeemer, and humbly submitting to its inward operations,
she experienced a gradual growth in Christian stability.

She removed to this city in the early part of 1806,
and became one of the family of Emmor Kirnber; soon after which,
from a prospect of religious duty,
and a thorough convincement of the inward principle professed by Friends,
and the testimonies flowing from it, she requested the care,
and became a member of the Southern District Monthly Meeting.

In the spring of 1808 she was united to me in marriage.
She was a truly valuable wife, fulfilling her domestic duties with assiduous attention,
and tenderly sympathizing with me under trials and discouragements.
Not long after our marriage she passed through a close
exercise of mind for several months under a suspension of that
sensible enjoyment of Divine good she had before experienced.
This led her into close searching of heart,
with earnest desires that in a married state she might be favoured to
serve her great Master as acceptably as she had done while single.
Although she was particularly cautious of expressing
much concerning her religious experience,
I have reason to believe that He who knew the sincerity of her heart,
was again pleased to restore to her the joys of his
salvation which produced a peaceful serenity of mind,
which she was mostly favoured with afterwards, during the short residue of her life.

During the year immediately preceding her decease,
she several times expressed a belief that her continuance in this life would not be long.
About five weeks before her last confinement, she had a fall, which,
although no very serious apparent effects immediately followed,
was supposed to have occasioned an inward injury.
Soon after the birth of her second child she became very ill.
She called me to her bedside and affectionately addressed me,
appearing desirous that she might be favoured
with an evidence how her illness would terminate.
I think it was the next day that she again spoke to me,
informing me that she now believed that her departure was near,
and endeavoured in the most tender manner to prepare my mind to be resigned to the event.
After this she was for several days mostly delirious,
but there is cause to think that for a few days before
her close she had the possession of her understanding,
although unable to speak intelligibly.
She was preserved throughout her illness in a remarkable degree of patience,
and though her suffering must have been great, she uttered no complaint.
Having lain in stillness for several days, on the 19th of Eleventh month, 1810,
without moving hand or foot she gently breathed her last, and her spirit departed,
I dare not doubt, to its prepared mansion of rest.

My dear wife was a woman of rather a hidden character, more in substance than in show;
exceedingly devoted in heart to what she believed to be her religious duty,
and cautious in examining the evidence thereof.
My wish for myself and my dear children is,
that we may be willing to submit to the operation of
that Holy Power which was her preservation,
and be enabled to walk, as she did, in humble circumspection before the Lord,
that so we may experience Him to be our guide and refuge through the probations of time,
our hope in the hour of death, and our crown and diadem in everlasting inheritance.

[.signed-section-signature]
Thomas Kite.

--

+++[+++Various letters of condolence and sympathy were received from the
friends of the family on the occasion of the decease of Elizabeth.
John Letchworth says in one from him:]

[.embedded-content-document.letter]
--

I think I feel for Thomas;
he is young to be left in a state of widowhood,
and it is pleasing to find that he felt a degree of resignation to the stroke.
As we believe these things do not happen by chance,
it may put him upon examining in the secret of his own heart.
For what good end is it, that just as I have begun to be comfortably fixed,
with the prospect of a rising offspring,
who probably might be the support of my declining years,
that I am thus stripped of her in whom I could confide, who was my comfort in trouble,
and the partaker of my joy, my adviser in difficulty, my anchor when running too fast?
I believe Young`'s idea was correct when he wrote--

[verse]
____
When heaven would kindly set us free,
And earth`'s enchantments end,
It takes the most effectual means,
And robs us of a friend.
____

--

John Heald, a beloved minister, residing at Fairfield, Columbiana County, Ohio,
thus wrote on the subject to Benjamin Kite.

[.embedded-content-document.letter]
--

What you mentioned with regard to your son Thomas being left in a solitary way,
I notice with attention, and, I trust, with a measure of affectionate sympathy;
but I do not know that I can send anything that can help to bear up a drooping mind,
or dry the tears of grief.
He is, no doubt, deeply tried.
He does not know for what purpose; that lies hid.
I shall only observe that I have heard, he has, for some time, made a public appearance.
I may here observe that among the many who set out well in this way,
few hold out to the end.
Some soon turn aside; some flourish for awhile and then forsake the cause;
some at different points fall from a favoured state,
where unnumbered blessings were in possession, or near at hand, into an impoverished,
lamentable condition: the most abject and pitiable.
I have often viewed these things and applied them to myself.
How dangerous my lot, how unsafe I am.
It appears to me that more of these, according to their number, than of any other class,
the adversary has drawn down and degraded.
I could, but shall add no more respecting this,
and only say that in early life some small sufferings compared to those of Thomas,
which I endured, I have found brought to my mind, at different times, to the present day,
to my own profit and that of others.
We know not, when we pass through adverse trials,
the use they may be to ourselves or others.

--
