== Chapter V.

[.chapter-synopsis]
* 1814-1815.
* Close of the war with England
* Death of Anne Mifflin and Sarah Matthews
* Letters from Stephen Pike.

+++[+++Business calling Thomas Kite to the east in the early part of the summer of 1814,
from New York, he addressed a letter to his wife, under date of Sixth month 4th,
from which the following is extracted: "`We had a very agreeable company in the stage;
one Presbyterian and one Episcopalian clergyman,
together with other intelligent and well-behaved persons.
We reached our lodging place, Somerville, about nine in the evening,
and started at half-past four in the morning.`"

Soon after his return from the eastward, Thomas Kite wrote to his wife,
then at Birmingham,
under date of Sixth month 20th. He describes the
great commotion among the citizens that day,
consequent on the launch of a new frigate.
People gathered in from all the neighbouring places;
sheds were erected and crowded with spectators, as were also housetops chimney-tops,
and all sorts of river craft.
After stating that it was estimated that 50,000 persons were gathered, he adds:]

[.embedded-content-document.letter]
--

I am sorry to hear some Friends were led away
by curiosity to join this great multitude,
evidently for lack of attention to that which preserves, not only from evil,
but from the appearance of evil.
Doubtless it is an evil thing for those who profess to have a testimony against war,
to give their company on such occasions.
I have not yet heard whether many casualties occurred.
One man is stated to have been killed; and if no more, it will be cause of wonder.

--

+++[+++1815. The war, with its depressing effects on trade, and its illuminations for victory,
passed away; and all classes of the community seemed to rejoice at the return of peace.
Stephen Pike, writing to Thomas Kite,
gives a lively picture of the sensation produced in the quiet city of Burlington,
by the announcement of the treaty of peace.]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Burlington, Second month 15th, 1815.

Among the circumstances which have latterly excited a powerful
interest among the peaceful inhabitants of Burlington,
is the long hoped-for dawning of peace over the dark and fearful prospect of
privation and calamities which seemed daily thickening around us.
There are few places, perhaps, of the same magnitude,
in which there are so many genuine lovers of peace as in this.
What, then, must have been the sensation produced by a sudden,
and to many an unlooked-for annunciation of the near approach of such a delightful guest.
Everyone seemed inspired with fresh and unusual animation.
A buzz of pleasure circulated from neighbour to neighbour, and from street to street.
The bells of the town were employed in uttering a more clamorous expression of joy;
a large proportion of houses--except Friends`'--were illuminated,
as emblematical of the state of the owners`' minds.
I had not received any information respecting the event,
which I thought could be depended on,
until it was announced by an animated peal of the bells,
a little before the close of my school.
It is customary with me previous to dismissing my scholars, to have a pause of silence.

At that time the contrast between the profound stillness
within and the noisy expression of joy without,
was so strong that it made my scholars want to laugh.
I was obliged to double the appearance of gravity on my own countenance,
to produce a becoming degree of it in theirs.
My feelings on the occasion were in some degree solemn;
and I endeavoured to experience a sense of gratitude for the extraordinary favour
which appeared likely to result from this dispensation of a gracious Providence.
Some of our friends, on being informed of the peace, were singularly affected.

Our neighbour Maria (George Dillwyn`'s sister, and mother to Gulielma M. Smith),
on receiving the intelligence, burst into tears,
and expressed an apprehension that we were not worthy of so great a blessing.
Nathaniel Coleman, Robert L. Pitfield says, was completely intoxicated.
He ran to convey the news to his wife,
and seized her by the arm with such a powerful grasp, as to make her call out.
I wish future events may justify the rejoicing which
has been indulged in to such a degree by many;
but I am apprehensive (as well as my pious neighbour), we shall prove ourselves,
in a collective capacity, unworthy of such a favour, and shall again, at a time to come,
forfeit that we have received, and by increasing our debt, incur still greater penalties.
But we have one consolation under every circumstance, prosperous or adverse,
we have it in our power to become associated with the righteous, that band of alchymists,
possessed of a stone which transmutes all into good.

--

+++[+++Thomas Kite having written a letter to his uncle, John Letchworth,
in which he spoke of quickness of temper as being one of his besetting sins,
he received the following reply:]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
East Fallowfield, Third month 12th, 1815.

[.salutation]
Dear Nephew:

Iron sharpens iron.
So a man sharpens the countenance of his friend.
This seems, in some measure, the case with a letter.
I received yours of the 5th of this month, and was gratified thereby.
Your observations, I believe,
are correct with respect to trials of various kinds awaiting us,
and that others beside yourself have their besetting sin, there need be no doubt of.
Quickness of temper you apprehend to be yours.
May I not say, "`hail fellow, well met!`" for it is mine, also.
What is the result?
When we are off our watch, and this predominates, are we not met with?--and
do we not receive chastisement?
Now, what conclusion shall we draw from this?
One seems evident, that we are poor weak creatures,
and stand in need of the care of the great Caretaker.
This ought to have a humbling tendency.
Though this may cast us down, yet we ought not to despair, for I think it is written,
"`Whom the Lord loves He chastens, and scourges every son whom He receives.`"
I may, perhaps, take the liberty to hint at +++[+++a thing]
wherein I have been tried sometimes, and that is,
a prospect of duty which appears far beyond my depth or strength to accomplish;
it appears the work of a man, no, a strong man, and not a child like me.
So that I am almost led to doubting;
there appear so many obstacles from within and from without to oppose it.
Yet I feel disposed to try the fleece wet and dry,
that I may be furnished with a clear evidence; and sometimes persuade myself,
were this obtained, I would not prove rebellious.
But I am weak.
In seasons like the one described,
it is not always easy to wash the face and anoint the hair;
yet I have endeavoured to be in the disposition of not appearing unto men to fast.

--

[.offset]
+++[+++Thomas Kite replied Third month 30th, 1815.]

[.embedded-content-document.letter]
--

[.salutation]
Dear Uncle:

Your last revived feelings of sympathy towards you,
which have often secretly prevailed in my mind
under a consideration of your various exercises;
and the desire that arose was,
that you might press forward in the path of simple dedication.
Though in seasons of weakness you may be ready,
under a view of apprehended requiring to say, "`who is sufficient for these things?`"
yet how encouraging the language of our Divine Master,
"`My strength is sufficient for you, for my strength is made perfect in weakness.`"
What a favour it is that we do know that of ourselves we can do nothing,
and that we are sensible our trust is not in ourselves,
but in the sufficiency of that Power who not only puts his own forth,
but goes before them; whose promise is,
"`As your days so shall your strength be;`" and who has never failed
to reveal Himself as a present Helper in the needful time.

Our meeting has been stripped of two ministers.
Anne Mifflin departed on Third-day week, in the afternoon,
and Sarah Matthews the next morning.
They had each been unwell for some time;
had each partaken considerably of trials of various kinds, and we trust,
are each gathered to that blessed inheritance where the weary are at rest.

This day was our Monthly Meeting, in which sat the first time for many years,
Joseph Dillworth, having been reinstated to membership at the preceding meeting.
Today an acknowledgement was received from John James, I hope, made in sincerity.
The meeting also accepted it, and he is again a member.
Samuel Bettle obtained a minute to visit the meetings about Muncy, Roaring Creek, etc,
but does not expect to set out till after Yearly Meeting.
I suppose you knew his gift had been acknowledged by the Monthly Meeting,
and he recommended to the last Quarterly Meeting.
Caleb Pierce expects to accompany him.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Stephen Pike to Thomas Kite.

[.signed-section-context-open]
Burlington, Third month 19th, 1815.

Our Morning Meeting this day was an unusually solemn one.
We had sat in silence during perhaps half an hour,
when our much esteemed Mary Roscoe rose and began an
interesting and very instructive address.
She generally comprises what she has to say among us in a single paragraph or two;
but at this time she made several pauses.
She commenced with expressing an apprehension she had,
that some present were oppressed in the bonds of affliction,
and were under the influence of discouragements,
and she administered consolation to their drooping minds.
She observed bonds were far from being a sure
indication of Divine displeasure and desertion;
and instanced Peter bound in chains in prison,
who was liberated by an angel sent from heaven.
She exhorted them to rely on the strength of the Almighty arm,
the never-failing support of which is promised to the faithful.

She added other instructive and encouraging remarks,
and then in a solemn and impressive manner addressed the youth of her own sex.
She said she had experienced much satisfaction in the belief that though the
faces of many of them did not appear to be turned toward Zion,
their hearts were filled with good-will to the cause.
That though, when interrogated under certain circumstances, like Peter,
they might deny their connection with their Divine Master, they were deeply interested,
in what, through weakness, they affected to slight;
and she exhorted them with fervency and affection to come forward in
their life and conduct as the avowed disciples of Jesus,
and the advocates of truth and righteousness.
I cannot say with certainty whether others were circumstanced like me,
but if I might judge by the reigning silence and solemnity,
and by the number of handkerchiefs employed to
veil the face on the women`'s side of the house,
there were many, as well as myself, enamoured of the beauty of holiness,
and excited strongly to desire the possession of what appeared so noble,
and at the same time so lovely.
Mary was followed by Abigail Barker, George Dillwyn, Richard Smith,
and by Susan Smith in prayer.
Richard`'s matter on this, as well as several late occasions, was more in quantity,
and I think also in weight, than formerly.
He appears to be increasing in strength and integrity of mind.
He exhibited lately an uncommon instance of simple
dedication in the performance of apprehended duty.
He made confession in the Preparative Meeting,
of having improperly beaten a boy that was under his care.
He said he knew the mention of it would appear singular,
but his peace was concerned in doing it.
Who will undertake to assert that no use will arise from it?
Rowland Jones, our other minister in embryo, seldom appears now in public.

Robert and Elizabeth Pitfleld!
The latter I consider shaping to be a minister of the first order,
endued with power to baptize.
I was lately witness to a special instance of the exercise of her gift,
in a private sitting, in which she, George Dillwyn and Margaret Allinson spoke.

--

+++[+++Lydia Jefferis, a young child of Cheyney and Martha Jefferis,
having deceased about the 1st of Ninth month, this year, Thomas Kite wrote to his wife,
who was with them, the following:]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Philadelphia, Ninth month 5th, 1815.

Your letter came to hand on Second-day,
and the intelligence of little Lydia`'s release from her sufferings was not unexpected.
Though both reason and religion in such a case suggest topics of consolation,
yet still to parents such a bereavement must be affecting.
Our dear sister no doubt feels it so; yet I trust she, as well as brother Cheyney,
have been favoured with resignation.

Henry Hull was, and perhaps still is in the city, journeying southward.
I spent last evening at Samuel Bettle`'s. Jane was quite lively and pleasant,
and Samuel quite as much so as common.
Elizabeth Pierce is better than she was at Concord.
She seems in a pleasant, innocent state of mind, and if taken hence,
I doubt not it will be to rest.
This is the crown of all!--and oh! The solicitude I sometimes feel
that you and I may so bend to the forming hand of the great Potter,
as to become instruments for his use;
that we may fill up our measure of usefulness on this stage of action,
that at the solemn close we may be entitled to "`Well done.`"
Let us then cheerfully give up to those baptisms of spirit which reduce the
creaturely will,--which bow and prostrate us before the Father of Mercies,--
and which make us renewedly willing to be what He would have us to be;
and as this is our engagement, He will be near to help in every trial;
He will lift up the drooping head, confirm the feeble knees,
teach our hands to war and our fingers to fight;
give us the victory over our own corruptions, preserve us from falling,
and finally (oh!--precious hope!) present us faultless
before the presence of His Glory with exceeding joy.
What is the world and all its amusements, profits and honours,
compared with a crown immortal that fades not away,
which is reserved in Heaven for all who are kept
by the power of God through faith unto salvation.
I am sensible I can write nothing new,
but feel desirous our minds may be increasingly drawn from earth to heaven,
that as we advance toward the termination of our earthly course,
we may be increasing in a qualification to join the
innumerable company who stand before the throne,
whose garments have been washed and made clean through the blood of the Lamb,
who have followed their Lord in the regeneration,
continuing with Him in his temptations--drinking of the
cup He drank of--baptized with his baptism,
and therefore permitted to reign with him.
It is very unexpected to touch upon these solemn subjects in this way,
but as they presented, I drop them in love and tenderness, being truly your affectionate,

[.signed-section-signature]
Thomas Kite

--

[.embedded-content-document.letter]
--

[.letter-heading]
Stephen Pike to Thomas Kite.

[.signed-section-context-open]
Burlington, Tenth month 25th, 1815.

I had considerable conversation with Joseph +++[+++Scattergood, son of Thomas],
though on indifferent subjects.
I think him possessed of strong natural powers,
and probably if his talents had been cultivated,
he would have been one of our most shining characters.
As it is, he is calculated to be highly useful in society.
He may never be commissioned in the Divine embassy as his father, that eminent minister,
but his service in the councils of his fellow members in the church militant,
may still be exceedingly valuable.

It is really melancholy to observe the diffusion
and multiplication of error in our Society.
To see value set on some things of not intrinsic worth,
and the value of other greatly misapprehended and immoderately esteemed;
while the virtues of meekness, temperance, charity,
exhibited in a life of condescension and forbearance, of contented frugality,
and the essence of benevolence and humble piety,
appear to be considered as subjects in which the eloquence of
our galearies may indeed be employed with great propriety,
but not as indispensable acquirements.
Ah! How I wish that heads of families should see things in the light of truth,
and weigh them in the balance of the sanctuary;
that nothing should appear beautiful to them but what accords with simplicity and purity;
and that nothing should seem possessed of weight
which has not some degree of eternal importance.

Our meeting, you knew, liberated several couples to travel to the north and to the south,
with a view to preach the knowledge of truth, and persuade men to abandon error.
Since then,
John Cox has obtained concurrance in a prospect of attending
the meetings composing Westbury Quarterly Meeting,
New York; and our Burlington Nathaniel, in whom, perhaps,
there is nearly as little guile as in the Hebrew whose name he possesses,
has gone to bear him company.
I think very well of it for several reasons.
He, (that is Nathaniel Coleman) is by no means an unsuitable companion,
and he has had rather a melancholy kind of life latterly.
Since the war, and the levying of the tax on plate, he has declined business,
except a little in the mending department,
which has left him more leisure than one not given to lounging,
and not particularly fond of reading, can satisfactorily dispose of.
Add to this the absence of a wife +++[+++Elizabeth Coleman being on a religious visit],
whose absence he could but ill tolerate for a day,
when he had more concerns to occupy his attention,
and you can easily imagine him not very comfortable.
His daughters have not been remiss in endeavouring to console him,
but they could succeed but in a small degree,
and had the mortification to be told by him that the attentions of a hundred
children could not suffice to fill the blank occasioned by the absence of a wife.
Elizabeth and Margaret are expected home in the course of a few days,
and Abigail Barker and company about the same time.

--
