== Chapter VI.

1816-1822.

Thomas Kite recommended as a minister--Rebecca Jones`' death--
Death of George Dillwyn--Death of Isaac Sharpless.

In the year 1816,
the Monthly Meeting of Philadelphia recommended Thomas Kite to the Quarterly
Meeting of Ministers and Elders as one to whom they believed a gift in the
ministry of the Gospel had been committed by the Head of the Church.
His uncle, John Letchworth,
who sympathized with his nephew in the trials and temptations
incident to the station into which he was called,
addressed the following instructive letter to him:

East Fallowfield, First month 4th, 1817.

Dear Thomas:--I often hear talk of great ministers, and, unless I deceive myself,
hear it without envy.
Shall we consider what it is that constitutes a great minister?
By what rule shall we judge?
Common fame is the rule in courts to judge of a person`'s character.
Well, be it so.
Hear what is said: "`Such a one spoke largely; I think not less than an hour and a half,
or two hours; he is a great minister!`" "`Well, for my part, (says a second),
I must confess, my head was not sufficient to contain all; I was glad when he sat down.
I even thought the few words dropped by the other Friend,
carried as much weight with it as all the other`'s put together.`"
"`I don`'t like your '`poppers,`' "`says a third.
Again: "`Such a one is a great minister, and she has a most beautiful delivery;
her voice is quite musical.`"
"`Well, now, I thought when I heard her,
what a pity it was there had not been some good elder with her in her early setting out,
to have prevented her singing instead of preaching.`"
"`Well, I admire at this!
How do you like the delivery of such a one?`"
"`Why, I think he delivers himself in a clear, distinct, intelligible, manly manner.`"
"`Now, I think, he seems to read his sermon over like a school-boy saying his lesson.`"
I have given a short specimen of the observations which
are made on ministers of our Society,
and by members, too.

There is a path, a path of safety, and this is the path of clear, plain duty.
As this is kept in, and we journey forward,
although we may be stripped and wounded by thieves and robbers,--although
the Priest and the Levite may look on and pass us by on the other side,
and make no observations at all, yet when the good Samaritan comes along,
he will pour in wine and oil, bind up our wounds, and set us upon his beast.
Thus it will be done unto the man or woman whom the King delights to honour;
who seek the honour that comes from Him, and not from man,
whose breath is in his nostrils.
Therefore, "`Do you seek great things for yourself?
seek them not,`" but be of good cheer.
So says your loving uncle,

John Letchworth.

Thomas Kite was very much concerned for the right education of his children,
and he devoted much of his leisure hours to them,
endeavouring to promote their instruction in useful and interesting things.
In the Eleventh month, 1817, he makes the following note concerning the two eldest,
and their reading: "`Susan in her ninth year.
William just turned of seven.

Previous reading, parts of the Bible, Barbauld`'s Lessons,
interesting anecdotes of children, original poems,
the first part of Harry and Lucy and Frank and Rosamond.
Began a regular course of reading and conversations with them, Tenth month, 1817,
for from twenty minutes to an hour in the evening.
Melish`'s School Atlas furnishes geographical
exercises for a portion of almost every evening.
Evenings at Home furnishes interesting matter for many evenings;
much of it found to be beyond their comprehension, and, therefore, left for the present.

Eleventh month.
Dr. Aiken`'s Arts of Life does not seem sufficiently to interest them.
Frank and Rosamond, and Harry and Lucy, the second parts.
Highly interesting; furnishes much matter for remark.

15th. Went to see the camels.
Their natural history.
Key to knowledge; useful information, but not conveyed in a lively and interesting manner.
New Robinson Crusoe excites much interest.
Some parts needful to be suppressed in reading to children,
being calculated to encourage a martial spirit.

Twelfth month.
Evening Entertainments.
Some parts to be suppressed,
but containing much that interests and informs
respecting the manners and customs of nations.`"

Sarah Sharpless, the wife of Isaac, Edith Kite`'s brother, was now in declining health.
As she was patiently and hopefully drawing near her close, her mother-in-law,
Ann Sharpless, who resided under the same roof with her, became much depressed in spirit.
Joshua Sharpless having written to his son Thomas,
giving an account of his wife and daughter, received the following letter:

Philadelphia, Twelfth month 19th, 1817.

Dear Father:--I had thought of writing to you before I received your letter,
when I found we were not to see you at this time.
The situation of sister Sarah, though on her husband`'s, children`'s,
and the Church`'s account, it may be regretted, yet on her own account it cannot be,
because there is ground to believe that her warfare is accomplished,
her iniquity is pardoned; and waiting in readiness, her loins girded, and lamp burning,
for the call of the Heavenly Bridegroom.

It is affecting to hear that dear mother is plunged into so low a spot;
but I cannot but hope she will be favoured with strength to lay hold on his promises,
"`who cannot lie,`" and be enabled to cast her care
upon Him who cares for her as well as the sparrows,
and in whose sight, being of the number of his dear children,
she is of more value than many sparrows.
May her confidence be renewed in Him who is both a sun and a shield,
light and protection, that so from a fresh feeling of his everlasting, loving kindness,
she may be qualified to say, "`The Lord is the strength of my life;
of whom shall I be afraid?`"

It is a humbling consideration,
that even those who have had large experience of the
Lord`'s goodness and preserving power in youth,
middle age, and more advanced life, have often, nevertheless,
toward the close of their pilgrimage, been deeply tried,
both from within and from without.
If some experience of this kind, my dear father, should be allotted you,
it is a favour that you are enabled to believe "`that these light
afflictions are working out through Divine favour a far more
exceeding and eternal weight of glory;`" and though your humbled mind,
in looking back over a long life of dedication, may be obliged to confess,
"`I am an unprofitable servant;
I have done but that which it was my duty to do,`" yet how precious
to be enabled to offer the incense of a contrite heart,
renewedly believing, that He who has delivered out of past conflicts and dangers,
will be near to preserve in the few remaining trials,
and by the operation of his own eternal baptism,
refine and prepare for an admission into his undefiled rest.

Rebecca Bacon was suddenly called out of time about a week ago;
having retired apparently in usual health,
and being found dead in her bed in the morning; probably occasioned by apoplexy.

1818+++.+++ At the time of the Yearly Meeting in 1818,
Joshua Sharpless judged himself too infirm to venture to Philadelphia to attend it,
yet he was not so indisposed as to make it needful for his wife to remain with him.
Rightly appreciating the trial it must be to one who had long been
zealously and actively concerned for the prosperity of Truth,
to be unable to attend the annual assembly and mingle in
social and religious fellowship with those who were bound to
the support of the same precious cause and testimonies,
and also feeling with him in his lonely situation,
Thomas Kite believed it right to address him a few lines of sympathy and encouragement.

Philadelphia, Fourth month 18th, 1818.

Dear Father:--Both Edith and myself feel sensibly disappointed at not seeing you,
with mother and Isaac +++[+++when they came]; but cannot blame you,
considering your state of weakness, for deciding upon remaining at home.
Though it is likely you will feel somewhat lonely,
yet we hope your mind will be supported in peaceful contentment, remembering,
that when able,
you did not permit trifles to prevent you from assembling with your friends,
and going down into exercise and baptism with
those who bear "`the burden and heat of the day.`

Mother +++[+++Sharpless]
appears to feel very comfortable;
says she feels this morning less of a pain in her shoulders.
Aunt Esther Garrett is with us, and lodges with mother.
Cheyney and Martha are also with us; no others have yet come to lodge.

Rebecca Jones rests from her labours and painful conflicts.
Her sufferings during a few late months have been great.
She died on Fourth-day afternoon, and is to be buried this morning before meeting.

William Williams and John Heald are here, and lodge at Father Kite`'s. Esther Griffin,
and her daughter; Mary Naftel, and other friends, are in town, among whom, I believe,
Daniel Howland, of Rhode Island, is one.

Early in the Fifth month of this year, Thomas Kite started on a visit,
principally of business, through the Eastern States.
Desirous of administering pleasure to his infirm father-in-law,
by showing him he was not forgotten in his weakness, soon after his return,
Thomas wrote him a letter, giving some account of his journey.

Philadelphia, Sixth month 5th, 1818.

Dear Father:--Having returned from my little journey,
I am willing to devote a sheet of paper to giving you some account of it.
I left home the day of our Quarterly Meeting +++[+++held Fifth month 4th]
in the afternoon, by the Bristol steamboat.
Took stage +++[+++at Bristol], and reached Kingston, in New Jersey, that night,--bad roads,
and a drunken driver, occasioning me considerable uneasiness.

The next morning +++[+++Third-day]
I reached New York.
Fourth-day was Monthly Meeting there, which I attended;
and having dispatched my business, on Fifth-day evening I took the steamboat for Albany.
I regretted passing the Highlands in the night,
but rose about midnight to get such a view of them as I could,
which was but the majestic outline.
The next morning I saw the Catskill Mountains, still white with snow.
In the evening reached Albany;^
footnote:[Taking 24 hours from New York to Albany.]
and having on Seventh-day morning attended to business there,
went in the afternoon to Troy.
First-day attended morning and afternoon meeting +++[+++in
that place]. Between meetings I climbed a hill,
from which I had a distant prospect of Cohoes Fails,
where the whole Mohawk River is precipitated seventy-five feet, I was told.
I met at Troy agreeable Friends,
and I think it one of the handsomest little towns I have ever seen.
In the evening I returned to Albany, from which, on Second-day morning,
I took my departure towards Boston.
That day passed by Lebanon Springs--the Shaker settlement adjunct,--
and went over the mountain on which said settlement is situated.
There again I saw snow.
We afterwards ascended the Green Mountain,
which is here said to be twenty-five miles over.
On the elevated land spring had not made its appearance;
the ground was not clear of snow, and not a leaflet to be seen.
The farmers are discouraged from attempting to raise Indian corn,
and are substituting potatoes, which yield an abundant increase.
I think they are better than ours,
and they say answer very well for fattening both pork and beef.
Lodged at Northampton, a beautiful town, on the Connecticut River.
The next day rode through a cultivated country one hundred miles, to Boston.
I think in no part of Massachusetts, not even in the mountainous country,
is so much land left iu timber as about the Brandywine,
Pa. Most of the way are thick stone fences, and many handsome towns.
Boston is very much improved in buildings since I was there eleven years ago,
but is still the crookedest town I ever saw.
I went to see Friends`' meeting-house, now shut up;
it is next door to the Merchants`' Exchange.
On Fourth-day evening I went to Lynn, and lodged at Micajah Collins.

Next day +++[+++Fifth-day]
attended their Monthly Meeting, which was large; I thought the business well managed.
That evening I went to Salem; lodged at Betsey Purington`'s. Returned next day to Boston;
finished my business there, and on Seventh-day went in a stage to Providence.
Here Obadiah Brown kindly insisted on my staying at his house.
On First-day I attended two meetings.
On Second-day, finding no stage for Hartford, I was obliged to remain.
I spent the morning with Obadiah at +++[+++the house of]
his father, Moses Brown, who interested me much with anecdotes of Job Scott,
who lived with him when he first appeared in the ministry.
He showed me a number of Job`'s letters to him, and interesting books and papers.
After dinner we all went to see the Yearly Meeting school house, now nearly finished.
It is on a very fine and commanding situation.
I afterwards went to William Almy`'s, with whose daughter Anna I was pleased.

Her simplicity and dedication, in the midst of affluence, being very exemplary.
She had just returned from visiting families in a neighbouring meeting.
Third-day morning I started for Hartford,
and was much pleased with the Institution for the Deaf and Dumb +++[+++at that
place]. The pupils appear to be making considerable progress in knowledge.
The superior class, who have been there about a year,
can understand the significant motions of the hands of their
preceptors so as to write down grammatically complex sentences.
They also learn arithmetic.
From Hartford, on Fourth-day, I went to New Haven,
and embarked again the same evening on a steamboat for New York.
Our passage through Hurlgate was difficult.
We reached New York on Fifth-day morning, and on Sixth-day left for Philadelphia.
As I was going down from my lodgings to the steamboat, I met my uncle, John Letchworth,
and my sister Mary, who had just arrived to attend the Yearly Meeting.
I reached home on Seventh-day morning.
Thus I have given you a brief account of every day`'s movements.
I may add, that B. White sailed last Seventh-day for Liverpool;
and that Stephen Grellett,
who was liberated for his northern journey by his own Yearly Meeting,
expects to sail for England on the 15th or 16th of this month,
accompanied by Mary Naftel.

While passing through Connecticut, Thomas Kite became interested in a fellow traveller,
a young female of pleasant manners and good intellect.
Beside the conversation growing out of the scenery around them,
and the various little circumstances occurring,
she made some inquiries into the doctrines of the Society of Friends;
which not only led him into an explanation and defence of them,
but induced him to present her with a copy of Barclay`'s Apology.
They parted mutually pleased with each other;
and an occasional interaction and friendly interest was
maintained between them until his death.
Her name was Lydia Huntley, since better known as Lydia H. Sigourney.

Thomas Kite was a pleasant travelling companion,
possessing excellent conversational powers, an enquiring mind, a clear head,
and a memory stored with anecdotes.
He had also a facility in drawing others out, and in overcoming the reserve of strangers;
and he rarely, if ever, passed along in a stage or steamboat,
that he did not elicit information from those about him,
and engage them in pleasant and profitable discourse.
He was not forward to obtrude his religious sentiments on such occasions,
but it not infrequently happened that those who became interested in his general remarks,
were desirous to converse on some of the
doctrines of the Society of Friends with one who,
from his dress and address, appeared a consistent member.
Thus he was often enabled to advocate the Truth--
to enlighten the understanding of seeking minds,
and to remove the prejudices of his hearers,
without violating any of the conventional proprieties of life.

His mind was tenderly alive to the spiritual trials and exercises of the young,
particularly such as he deemed under the preparing Hand for usefulness in the Church.
Having written to a female whom he considered of this class,
he received the following reply:

Upper Darby, Seventh month 5th, 1818.

It had been on my mind before I left home, to request you to write;
but I was best satisfied to omit it,
hoping you would be influenced by a motive more powerful than that of friendship.

The single eye shall be filled with light;
but I have greatly feared that my eye being evil,
my whole body has become full of darkness.
I know not my vocation;
neither have I much reason to hope that I shall
ever be qualified for usefulness in the Church.
Tis a mournful consideration, and it has often filled me with sadness.
Perhaps if I were willing to be nothing,--to be laid aside as
a broken vessel,--I might witness a preparation for service,
though in a small degree, in the Master`'s house.
Yet think not that I am too much depressed; on the contrary, apathy, insensibility,
more to be deplored than suffering, is my present state.
Continue, my dear friend, your intercession for me,
that "`Light may arise out of obscurity, and my darkness become as the noonday.`"

After a long period of probation,
the writer of the above letter came forth in the ministry.
Her communications were short,
and her voice in that line was only heard after long intervals of silence.
Her appearances were lively and very acceptable to her friends.

A time of pressure had now commenced in the commercial world,
and many failures among men of mercantile business and
speculators in real estate took place.
This state of things lasted for two or three years.
Thomas Kite having given Stephen Pike a description of
the difficulty in the community consequent thereon,
received the following reply.
It was written after the ice had obstructed steamboat navigation in the Delaware.

Burlington, Twelfth month 30th, 1818.

Philadelphia seems to be fifty miles further from us than when
the steamboat afforded an opportunity two or three times a day
to transport ourselves there in a couple of hours.
You mention the overturnings that are taking place in your city.
On reading your account, as at many other times, I have felt that

"``'Tis pleasant, through the loopholes of retreat,

To peep at such a world.`"

`'Tis true, I am obliged to ply a business replete with care and difficulty,
but then I am never visited by bank notices;
and though I have no prospect of being quickly rich,
I am not yet obliged to encroach upon my little fund of savings,
but have a trifle to spare.

Thomas Kite to Martha Jefferis.

Philadelphia, First month 29th, 1819.

My business is not very brisk, yet sufficiently so, with frugality,
for a decent maintenance.
I am content with my situation, and have no prospect of change,
and I believe Edith is pretty well satisfied.
To be sure her cares and concerns in her family sometimes are trying,
but afford her a noble opportunity of manifesting forbearance, patience,
and other Christian virtues;
in the peaceful daily exercise of which I hope she and I may be favoured to increase.
My business is not so pressing but I find time, when a duty in the case is apprehended,
to attend a neighbouring meeting;
and am at times favoured with a secret hope that I am not doing my own will therein,
but seeking rather to serve the Holy One in the
Gospel of his Son--an awfully important office!
What manner of persons ought such to be who assume it,
in all holy conversation and godliness?
How far, very far, indeed,
am I from having attained such an establishment
in righteousness as I believe is attainable,
and which we are called to.
May I not settle down into ease and security, but rather be incited to daily vigilance,
that forgetting the things which are behind,
I may press forward towards those things which are before,--
even complete redemption and acceptance in Christ.
And, dear sister, as the wish arises with freshness and fervency, may brother,
and you also, be found pressing forward.
It is the will of the great Head of the Church, in this day of deep degeneracy,
that his people should arise, shake themselves from the dust of the earth,
and go forward.
May you, placed as you are, in a station which makes your example conspicuous,
be favoured day by day with the renewings of Holy help,
enabling you to take your journey before the flock,
speaking by the language of example the invitation, "`Follow us,
as we endeavour to follow Christ.`"
Thus strengthened to overcome the evil in yourselves,
you will be qualified to rule your own house well,
and keeping your authority in the dignity of our Holy Head,
you will be qualified more eminently to take care of the house of God,
as instruments in his hand,
who alone can enable us to work for his honour and our own peace.
Excuse me, dear sister,
for thus speaking to a beloved brother and sister of more experience than myself,
and whose sympathetic desires for my preservation I have.

I had omitted to notice your query concerning dear S. Wilson`'s illness.
She seemed recovering; had been once out,
but was taken on Seventh-day with bilious colic, which, after a painful conflict,
terminated her earthly course on the following Third-day,
There is reason to believe an apprehension had attended her mind,
that her days`' work was drawing to a close.
Well, she was a precious plant in the Lord`'s heritage, and is, doubtless,
transplanted to his everlasting kingdom.
The Church has met with a loss which will be sincerely felt;
her particular intimates will miss her much, for she^
footnote:[A minister of the Southern District Monthly Meeting,
deceased Twelfth month 29th, 1818.]
was much beloved by them.
But it is all well, being his work who does all things well;
who is still able to raise the beggar from the dunghill,
and set him with the princes of his people; to call strangers in to feed his flock,
and to make the sons of the aliens plowmen and vinedressers;
while the children of his family who abide under his forming hand, will not be cast off,
but will be made priests and ministers unto Him.
Thus we have the consolation of believing, that the foundation remains.
Though one generation goes and another comes, the Word of the Lord abides forever.

Thomas Kite to Joshua Sharpless.

Philadelphia, Seventh month 13th, 1819.

Dear Father:--I wrote to you a few days ago on the state of our health,
and that of the city generally, but no opportunity presented of sending the letter, and,
therefore,
thinking you may have reports which have been
circulated on the subject of the yellow fever,
and feel some anxiety for us, I have concluded to write again.
There have been in the neighbourhood of Market street wharf,
a few cases of malignant fever, of which about five persons have died.
The Board of Health has caused the removal of those who have taken +++[+++the disease]
as fast as they came to its knowledge.
This they deemed a measure of prudent precaution;
as also the cleaning of certain dirty and offensive places in that vicinity.
I know of no new case yesterday or today.
The city in general is remarkably healthy.
My family, excepting little Thomas, enjoy their accustomed health.

The times, as to business, are remarkably dull,
and there have been some considerable failures.
Indeed, the wild speculating spirit which has prevailed,
and which led to the present embarrassments, has met with a serious check.
It is to be hoped that warning may be taken, and a different manner of business adopted,
which will lead to more favourable results.

Thomas Kite, Jr.,
the third and last child of Thomas and Edith Kite (born Second month 25th, 1818),
was now very unwell, and his mother, soon after the above letter was written,
went with him to her father`'s, in East Bradford,
to try whether country air would not recruit him.
While there, Edith Kite received the following letter from her husband:

"`Samuel Bettle and George Williams left home yesterday on their way towards Ohio.
Perhaps if you had written you could have informed whether uncle John
Letchworth was set at liberty by the Western Quarter.^
footnote:[J. L. was set at liberty, and paid a religious visit west of the mountains,
attending the Yearly Meeting in course.]

From Byberry we hear that our friends there are mourning the removal of Ezra Townsend^
footnote:[An elder; he deceased Eighth month 14th, 1819, aged 60.]
Perhaps a greater loss to that meeting and neighbourhood could not have taken place.
To have a man of his experience and exemplary deportment,
which gave him a great place in the minds of Friends,
removed in the full possession of his powers and usefulness,
seems to have occasioned a general mourning amongst his neighbours.
But, no doubt, it is in wisdom;
and He who has removed and is removing from the militant to the triumphant Church,
those who have long borne the burden and heat of the day, can, and, we humbly trust,
will continue to qualify those who are made willing in the day of his
power to succeed such in a faithful testimony to the Truth.
May you, and I, dearest,
be amongst the number of those who are witnessing the cleansing baptisms of the Spirit,
increasing in weight and religious experience, faithfully serving our generation,
and witnessing a gradual preparation for that awful day, when we may be enabled to do it,
in humble hope that our sins are forgiven us for his name`'s sake,
who has loved us and whom we have desired to serve.
Oh, my dear,
it is animating to be favoured with a hope of admission within the
pearl gates to the general assembly and Church of the first born;
and what a tendency such a hope has to raise desires that even here we may be
purified even as He is pure,--that heavenly dispositions may be implanted,
and all unholy affections done away.
But alas for myself! when I consider how far I am from such an attainment,
my own weakness and the strength of surrounding temptations,
my heart is ready to meditate terror.
Pray for me, that, having preached unto others,
I may not become a castaway from Divine favour and acceptance.
I hardly know how to cease,
such is the solicitude unexpectedly awakened for our increasing
dedication to the '`God and Father of our Lord Jesus Christ,
of whom the whole family in heaven and earth is named.`'
But I pause, with recommending us to Him, and to his keeping,
who only is able to keep us from falling,
and to present us faultless before the throne of his glory with exceeding joy.

The young child continuing ill,--so much so that the mother despaired
of his life,--their stay in the country was prolonged.
On receiving which information Thomas Kite wrote:

Ninth month 7th, 1819.

I feel such a void, in your absence, I hardly know how to spare you longer,
yet if your health, or that of our dear boy requires it, I must endeavour to submit.
I rank amongst the chief blessings of my life,
my happy connection in marriage with my dearest earthly friend;
and I feel that more than six years`' experience of its
comforts has increased my affectionate attachment.
Yet, while I desire to be grateful to that kind Providence
who has provided me with so beloved a companion,
I also desire to be preserved from such an undue or inordinate affection for the gift,
as might lead to a neglect of the Giver.
Often has the aspiration been excited, that our union,
through the sanctifying influence of our Heavenly Father, may be more and more purified;
and that while we are permitted to feel the comforts which flow from our mutual,
natural affection,
we may experience an enlargement in that blessed communion which is spiritual and divine:
and to this end much have I craved, that we may be frequent and fervent in waiting for,
and feeling after those baptisms which cleanse
the heart and preserve it sweet and tender.
Thus favoured,
may we not hope that death itself will not separate us long?--a
thought calculated to afford the survivor comfort in a trying hour.
Indeed, in every situation we can be placed in on this probationary scene,
how consoling the evidence that we have an interest in Him who has abolished death,
and brought life and immortality to light through the Gospel.
Oh! that this consolation may be ours!

Although under much anxiety about the health of his child,
Thomas Kite believed it right to mention to the Friends of his Monthly Meeting,
held Ninth month 23rd,
a prospect of religious service which had been long ripening on his mind.
This concern,
as expressed by the Minute granted him was "`to pay a religious visit
to the meetings composing the Monthly Meetings of Exeter,
Roaring Creek and Muncy: also,
the meetings belonging to Centre Monthly Meeting
within the compass of Warrington Quarter.`"
He had the unity of his friends, and the company of his brother-in-law, Joseph Walton.

1820+++.+++ At an adjournment of Philadelphia Monthly Meeting, held Second month 3rd, 1820,
Thomas Kite received a minute to attend a few meetings
within the limits of Abington Quarterly Meeting,
and some in that of Shrewsbury and Rahway.
On the eighth he left Philadelphia to accomplish his prospect,
having Charles Townsend as a companion.
Of this journey some particulars are given in his letters.

Thomas Kite to his Wife.

Mendham, Second month 12th, 1820.

I will begin at our departure, which was, as you recollect, no doubt,
on the afternoon of last Third-day +++[+++the 8th]. That
evening we reached Dr. Mitchell`'s at Horsham;
were kindly entertained; and on Fourth-day morning rode to Watson Fell`'s, at Solebury,
to dinner.
While we were there it began to snow; bat we pushed on through it,
and arrived at Henry Clifton`'s, at Kingwood, near night.
We were kindly received, and pleased with meeting our friend Abraham Lower,
who had an appointed meeting there that morning,
and had been detained by the badness of the roads,
the snow not permitting him and his companion proceeding in their chair.

Fifth-day morning, in company with him, I attended the Select Preparative Meeting,
which is held at nine o`'clock, as also the Monthly Meeting, which begins at eleven.
In the afternoon, leaving Abraham, and his companion Joseph Warner, at Henry Cliftons,
we proceeded towards Randolph, in the face of a severe fall of snow,
having Joseph Stevenson for a guide.
By tying our handkerchiefs over our hats and faces,
we secured ourselves somewhat against the driving snow,
and stopped for the night at John Dawes`', an aged Friend,
who lives remote from any other of the Society.
In the welfare of himself and family of daughters,
apparently amiable and intelligent young women, we were much interested.

In the night a large quantity of snow fell, in consequence of which,
instead of reaching Randolph on Sixth-day, as we expected,
we scarcely exceeded half that distance.

Such travelling I never saw; snow-drifts nearly or quite to the horses`' backs.
Frequently having to break the road for considerable distances;
at other times getting into fields to avoid heavy drifts--altogether obstructed our
progress so much that it was noon by the time we had travelled about six miles.
Towards evening we arrived near a tavern, but hearing they were without hay,
and probably without oats, we petitioned a Presbyterian farmer to take us in,
who willingly consented.
His wife, we found, was descended from Friends; himself very zealous +++[+++in his belief]
yet not bigoted.
His brother-in-law, a physician, was present,
and much interesting conversation relative to our principles, occupied the evening,
towards the close of which way opened for a religious opportunity.
Indeed, unlike any former journey,
my way has opened in several families already for services of this kind, to my own peace.

This morning +++[+++Seventh-day the 12th], we have also had our difficulties,
though on the whole travelling is rather improved.
We have come (having parted with our guide) about twelve miles to Aaron Boker`'s,
who formerly lived in Philadelphia, and whose wife is a member.
+++[+++At his house]
we have just dined.
We have about nine miles to go this afternoon, which,
with calling a few minutes on Samuel H. Cox, which we propose to do,
will probably occupy us till near night.
To morrow +++[+++First-day]
we propose being at Randolph Meeting--and nothing further is clear at present.

As you know how deeply I was depressed under the prospect of leaving home,
I think it right to say I have been remarkably supported in calmness and contentment;
so that nothing I have met with has been hard to bear, and scarcely unpleasant.

Thomas Kite to his Wife.

Randolph, Second month 14th, 1820.

I wrote from Aaron Boker`'s, bringing my account down to Seventh-day afternoon.
After leaving his house we rode to Samuel H. Cox`'s, who professed himself glad to see us.

After a short visit we pursued our way towards this place,
but found such heavy snow-drifts that it seemed impossible to get our horses through.
We had to dismount and encourage them to plunge
onward a few paces and then stop them to rest,
as my mare in particular seemed ready to give out.
At length we reached a beaten road which lasted nearly to this place,
+++[+++our way was then along]
a road which no one had passed.
We endeavoured to hire a man to go with us;
but he told us he was afraid it would kill his horse to go through the snow.
So we were obliged to venture without a guide and night coming on,
very great was our difficulty,--often we were on the point of giving out.
My colt having scarcely strength or patience to get through the drifts, was kicking,
and plunging and exhausting herself, while I wading and falling about,
was endeavouring to guide her by the bridle.
At length we gave out.
After getting the horses onto a bank in the wood, I left Charles with them,
and plunged into the snow, to endeavour to reach a house,
the light of which glimmered through the darkness.
We knew from information +++[+++this house]
must be that to which we were bound.
I left the road to try the fields,
but the darkness not permitting me to distinguish the drifts, I frequently fell,
and thought of Thompson`'s description of a man perishing in the snow.
Having regained the road, I reached Thomas Dell`'s house much exhausted,
in a profuse sweat, and glad to get there.
He (T. D.) kindly sent three stout sons to Charles`' assistance,
and they succeeded in getting our horses through.

Charles says he had a time of very comfortable meditation in the woods.
A good supper cheerfully prepared by kind and hospitable friends was very refreshing.
We yesterday, First-day, attended the meeting here, which was large for the place,
many of the neighbours attending.
It was, I trust, a solemn and profitable opportunity.
As there is said to be no suitable stopping place between this and Hardwicke,
distant 18 or 20 miles, and we have had so much bad road, we concluded +++[+++yesterday]
to rest until this morning and then set out with
a view of being at meeting there tomorrow.
We are now waiting for breakfast.
Last evening Abraham Lower and company again met us,
they having been at Harchvicke Meeting in the morning, and come on in a sleigh.
They are bound to Railway to the Quarterly Meeting.
'`My mind continues to be sustained in quietness and resignation,
which I esteem a favour indeed.
'`

A short account of the rest of this journey is contained in
the following extract from a letter to his father-in-law.

Second-day the 14th. We rode to Hardwicke, formerly Great Meadows,
where on Third-day we had a meeting; and that afternoon crossing the Delaware on the ice,
we passed through the Water Gap to Stroudsburg.
There we waited to attend their usual week-day meeting on Fifth-day,
and rode in the evening to Easton,
and were kindly entertained at the house of Mordecai Churchman.
Sixth-day we rode to Richland expecting to have a meeting there on Seventh-day;
but on arriving at 2 o`'clock found Friends going into the meeting-house to a
meeting of Amos Peisley`'s. Tired as we were we attended this,
and way opened to relieve my mind,
so that on Seventh-day we felt at liberty to return home.

A few days after Thomas Kite left Randolph,
the following letter was addressed to him by a friend, of that place.

Hyale Ann Sammes to Thomas Kite

Randolph, Second month 17th, 1820.

It has been on my mind this sometime to write you a letter,
feeling drawn towards you in that love which unites
together the children of our Heavenly Father,
and causes them to feel near one to another, when distant as to bodily presence.
These can sympathize with each other in their trials and exercises,
and can also rejoice with them in their consolations.
Dear brother, for I believe I may call you so,
I have often thought of you since I saw you at Shrewsbury.
I esteem it a favour that you should have taken notice of me, and felt for me,
a poor unworthy creature, one of the least among the thousands of Israel,
if numbered among them at all.
Yet I feel the evidence that I sincerely desire the welfare of my fellow mortals.
Unto God would I commit my cause,
who alone can qualify his humble depending children and
prepare them for his work and service.
I know without Christ I can do nothing.
May I always, look to Him with an eye of faith.
He is my only helper; and I desire no other.
May we be encouraged to go in the way of his holy leading, casting all our care upon Him,
for He cares for us.

Soon after reaching Philadelphia,
Thomas Kite received a letter from his friend John Phillips,
an elder of New Garden Monthly Meeting, Chester County, a portion of which is given.

Kennet, Second month 22nd, 1820.

The choice little, weakly, Mildred Eatcliffe was here,
and in this neighbourhood about two weeks past;
and I thought her much favoured in some close and feeling testimonies amongst us.
She is busily travelling this cold weather.
My wife +++[+++Lydia Phillips, a minister,]
got home about six weeks since.
She was away about six months, and much favoured with health nearly all the time.
They went through the State of Ohio, part of Indiana, Kentucky, Tennessee,
North and South Carolina, so through Virginia, home.
They attended the Yearly Meeting in Carolina, which they thought a favoured one, +++[+++having]
a large number of innocent, goodly Friends,
who treated them with much kindness and affection.

I have no doubt they kept open houses in the fullest extent of the word.
Rachel Barnard^
footnote:[A minister of New Garden Monthly Meeting travelling with Lydia Phillips.]
took a bad cold when about Cincinnati, with some fever; she got a little better, went on,
came to Carolina, and the meeting-house +++[+++being]
open and without fire, and the weather uncommonly cold for the season, she got it renewed.
She was frequently unwell on her way home, and +++[+++has not been]
very well since.

In a letter to Joshua Sharpless dated Fifth month 29th, 1820, Thomas Kite says:

"`William Foster, so long expected, has arrived from England.
He is but 33 years old.
His prospect is to visit Friends and others on this continent,
and some of the West India Islands.
After New York Yearly Meeting he expects to go to New England.`"

George Dillwyn, that venerable minister of the Gospel of Christ,
having by a fall during the preceding winter injured his hip,
had been since that period declining in health.
On the 23rd of the Sixth month, 1820, he was released by death,
having a few months before completed his 82nd year.
The following letter gives some account of his latter hours.

Stephen Pike to Thomas Kite

Burlington, Sixth month 23rd, 1820.

Dear Friend:--As sad intelligence is of rapid flight,
you will perhaps have learned before this reaches you,
that "`a prince and a great man has this day fallen in Israel.`"

Our doubly-honoured and beloved friend George Dillwyn,
being removed by the hand of death from this scene of
his long continued and very useful labours.
My first impressions on hearing of the circumstance were solemn,
but not accompanied with much of the sadness produced by deep regret;
for I am fully convinced that having fought the good fight and kept the faith,
his course is finished with the approbation,
and by the appointment of Him whose wisdom and goodness are both without bounds.
The suddenness of the change was rather surprising;
though it was not supposed he would continue long with us,
as he had in addition to his hurt, the cholera morbus.
He was free for a day or two past from the latter complaint, +++[+++and]
it was thought he might continue some weeks longer.
He conversed, as I understand, very freely and pleasantly with those around him,
and said, that, except his lameness, he felt as if he were well.
In this situation he went to sleep and never awaked,
but passed away quietly about five in the afternoon,
without any symptoms of approaching dissolution,
except a little unusual motion in the muscles of his face.
I find that the`' impressions of others on this occasion are
similar to my own--those of solemnity without sorrow.
After an unusually long pause at the tea table, John Cox, in a very solemn manner,
expressed a short exclamation to this effect:
"`We would not approach you with unhallowed lips, but we feel engaged to say,
'`Your name is as ointment poured forth, therefore do the virgins love you.`'

George`'s poor widow, now a little childish,
who has been very fondly and strongly attached to him
during upwards of 60 years that they have been united,
feels the separation very greatly.
She obtains the sympathy of her friends.

Thomas Kite to Joshua Sharpless

Philadelphia, Sixth month 26th, 1820.

Dear Father:--I thought it might perhaps interest you
to hear of the removal from the present scene,
of two precious Friends,
the one in the meridian the other in the declining years of life,
George Dillwyn and Mary Morris, wife of Israel.

The latter was under nomination from our Quarterly
Meeting to visit some of the meetings belonging to it;
and was to have started on Sixth-day.
The day previous she was taken with cholera morbus,
which carried her off in twenty-two hours.
She dying about 4 o`'clock on Sixth-day morning.
She was a sweet-spirited Friend, very useful in her family and meeting,
and had for some time past, appeared in the ministry.
I went out to Merion to the funeral on Seventh-day afternoon.
It was largely attended and a sweet solemnity was thought to prevail;
several testimonies being borne under a sense of
the blessedness of those who die in the Lord.

Dear George Dillwyn since his hurt, has been rather declining;
and was also taken with cholera morbus, but appeared to obtain relief,
so that on Sixth-day, conversing cheerfully with his friends, he said,
that except his lameness he felt quite well.
Thus circumstanced he went to sleep, but never awoke,
passing quietly away to the mansion prepared for him,
without any symptom of approaching dissolution excepting a
little unusual motion of the muscles of his face.
Though it feels solemn, yet there is no cause for sorrow; full of years,
as a shock of corn fully ripe, having kept the faith and finished his course,
he no doubt enjoys the crown laid up for the righteous.

During the summer of this year, 1820,
a few cases of highly malignant bilious fever occurred in the City of Philadelphia,
which, of course,
gave occasion for an alarm through the country that the
yellow fever had once more visited the place.
Thomas Kite went to Lancaster County during the Eighth month.

Stephen Pike to Thomas Kite

Burlington, Tenth month 1st, 1820.

Elizabeth Foulke,^
footnote:[Elizabeth Foulke was a minister belonging to Philadelphia Monthly Meeting.
She died Tenth month 19th, aged 63 years.]
who is next door to us, is thought to be sinking pretty fast.
It is the doctor`'s opinion that she is not likely to remain long.
She has suffered a great deal; and as there is no hope of her recovery,
I shall be glad to hear of her release.
It is a great favour that she has the full and proper exercise of her faculties,
though within a few days she declines conversation.
She appears frequently to be in private supplication,
which shows the foundation of her hope.

Thomas Kite to Joshua Sharpless

Philadelphia, Tenth month 13th, 1820.

Dear Father:--Hearing from brother Isaac of your increased suffering,
has awakened feelings of sympathy and commiseration.
Under the anguish which I can readily conceive you must endure,
I have felt a desire that the power and presence of Israel`'s Shepherd may be witnessed,
enabling you to support with a degree of patience those remaining probations,
which will probably before long wear out the poor afflicted tabernacle,
and release the immortal part to its everlasting home.
It has not been uncommon, I believe, in the wisdom of Him whose counsel is unsearchable,
for his dear children near the close of lives of dedication,
to be closely tried in many ways, even as to a hair`'s breadth.

And it is not marvellous that it should be so,
when the Great Pattern submitted to the same cup and baptism.
Great, no doubt, was his distress, both of bodily suffering in his humanity,
and a sense of the sins of a fallen race, when He cried out, "`My God, my God,
why have you forsaken me?`"
Yet soon the conflict ended, and He ascended to his God and our God:
and though his followers who have endeavoured to continue with Him may be at seasons,
when the bitterness of anguish is felt, almost ready to conclude they are forsaken,
yet the everlasting Arm is underneath,
and for the elects`' sake those days of suffering will be shortened, the conflict ended,
and they enabled to ascend to their prepared mansions,
triumphing in the power of an endless life, over death, hell and the grave.
A firm persuasion that this will be the blessed end and consummation of all your trials,
my dear father,
has afforded some comfort under the trial which
your increased afflictions have occasioned.
An end unspeakably glorious.
No more pain, neither sorrow nor crying, and God himself shall wipe all tears away.
I might enlarge further, but hope this will suffice you.
I have had feeling with you.
Edith sends her love,
and also unites with me in the expression of it to mother and sister;
who we hope will experience the fulfilment of the promise,
"`As is your day so shall your strength be.`"

In the Tenth month Thomas Kite attended the Southern Quarterly Meeting,
and beside the labour which fell to his share in the public meetings,
he appears to have had frequent religious opportunities in families, visiting,
as way opened, the afflicted.
He was absent from home on this little journey about eight days.

Thomas Kite to Joshua Sharpless

Philadelphia, Twelfth month 19th, 1820.

Dear Father:--Our cousin Ann Yarnall departed this life last Seventh-day night,
continuing to the last, when not under the influence of delirium,
supported in her mind by a comfortable hope that she was about
to be gathered to the habitation of the blessed.
Her remains were yesterday deposited in our burying place;
and in the evening a number of her connections being collected at her late abode,
a religious opportunity took place,
in which the covering of Divine Good was eminently witnessed.
I was present, having gone there from an apprehension of duty,
not knowing that so many were likely to be there.
Testimony was borne to the sufficiency of that Divine power that enabled her
to be faithful in the line of duty--to visit the sick and afflicted,
and minister to the necessities of the poor;
and the young people were invited to bow to the operation of it,
that they might become qualified thereby,
to fill up their allotted portions of duty in the church and in the world.
The blessing of having the Lord for their friend
in the trying hour of approaching dissolution,
was set before them.
Amongst others,
Elizabeth Pitfield was very sweetly engaged in a strain of persuasive Gospel ministry.
Poor cousin Nathan^
footnote:[Nathan Yarnall, then labouring under alienation of mind.]
has been informed of his wife`'s decease, and was brought in the morning to see the corpse.
He was sensibly affected;
and his behaviour was more quiet and composed than has of late been common.

I thought you would, perhaps,
be willing to hear that on First-day last I had a meeting in
the morning with the male convicts in our prison.
About three hundred and ninety were present.
Their deportment on the whole was becoming,
and there were many of them very attentive to what was offered for their consideration.
In the afternoon I had the company of the female convicts, in number not exceeding forty,
who were also commenclably quiet and orderly.
The flowing of gospel love was felt in both the opportunities,
and its message declared to them, I humbly hope, in a degree of his authority,
who was anointed "`to preach deliverance to the captives,
and the opening of the prison to them that are bound;
to preach the acceptable year of the Lord.`"
If any of their hearts were at all reached, to Him be the glory.

Thomas Kite to Edith Kite

Philadelphia, Eighth month 22nd, 1821.

Since you left several friends have deceased.
Josiah Hewes, on Fifth-day evening; John Alsop, on First-day morning.
Having called to inquire after the latter, I was present at his close,
which was remarkably quiet.
Though solemn, yet the scene was attended with calm and pleasing sensations to my mind.
John Wilson, a nephew of Joshua Harlan, was buried last evening,
and this morning Ludawick Laws is to be interred.
He went to the sea shore, I believe, in usual health, a few days ago for bathing,
was taken with bilious colic, which terminated his life.
Thus are we furnished with admonitions to endeavour to
be ready when the time of our dismission comes.

In the early part of the Eighth month, Thomas Kite,
having business requiring his attention in New York, took his wife with him there.
His daughter, Susanna, then at the house of her uncle, Cheyney Jefferis, on a visit,
wrote him a letter, directed to Boston.
He replied to her in a pleasant manner,
calculated to please a child of twelve years of age,
who was very fond of cats and kittens,
and had in the letter enquired after her feline favourites at home.

Philadelphia, Eighth month 21st, 1821.

Dear Daughter:--I received your very acceptable letter, not at Boston, but at home.
You were mistaken in supposing my intention to be to go so far as Boston.
You have, no doubt,
heard of your mother being at her father`'s. We returned from New York on Fourth-day last,
and found your uncle Nathan +++[+++Sharpless]
here, prepared to take her out.

You will probably get to see her.
She took Rebecca with her, and has left her at Concord, I expect.
Susan Renouf +++[+++a domestic in the family]
is at grandfather Kite`'s. Our house is very quiet and lonesome.
The cat and kitten are in very good health, as far as we may judge from appearances,
for though the old one seems rather sedate, the young one is frolicsome enough.
It is quite agreeable to hear that you are going to school.
Be diligent, and, dear child, don`'t be wild, but endeavour to be a good girl.
You are not too young to have serious thoughts of your duty to your great Creator;
and I hope when you sit in meeting, and at other times,
you feel desirous to live in his favour, and have Him for the Guide of your youth.
This is your affectionate father`'s wish for you.

I went out to Frankford last evening to see your aunt Abi +++[+++Walton],
and returned this morning.
The family there is in usual health.
Your grandmother is not quite well, though better than she was a few weeks ago.
Your grandfather has gone to Byberry.
I have little more to add at present, except to desire my love to your uncle, aunt,
and the children.
And please mention to little Joshua, that father sends his love to him.

Thomas Kite to Joshua Sharpless

Philadelphia, Tenth month 16th, 1821.

Dear Father:--It has been a time of uncommon sickness in many parts of the country,
and also in the city; mostly with those who have been spending some time out of town.
We know of no neighbourhood near the city where
it has been much more mortal than at the Asylum.
Several have died there.
Our cousin, Nathan Yarnall, amongst them, though not of the prevailing fever.
On Seventh-day afternoon he appeared to go into a kind of stupor,
after having eaten his dinner, which increased, and about half-past one at night,
he quietly departed.
Sister Abigail Sharpless accompanied Edith and me to the funeral on Second-day,
at Frankford.
It was very small,
but one of uncle Ellis`' family being there occasioned
by the prevalence of the fever in the family.
Uncle, aunt, Sarah, and Edward, had been sick with it.
Of these, uncle is supposed to be the most unwell.
Indeed, his situation is thought critical.
Sybil Dawes deceased a few days ago.
During the early part of her illness, which lasted, perhaps, ten days,
she appeared favoured with a renewed visitation of Divine goodness,
in which past failings were brought into view, and forgiveness experienced,
so that a reconciliation to the prospect of the closing scene was mercifully afforded.

Sarah Humphreys to Thomas Kite

First month 8th, 1822.

I feel much interested for the welfare of Zion and the enlargement of her borders,
and my heart mourns for the desolation of that part +++[+++Radnor Monthly Meeting]
of the vineyard,
and believe the work is marred on the wheel by
an unwillingness in some to serve the Lord,
who seem as if they would not so much as touch a burden with one of their fingers;
and by the expressive language of conduct are saying,
we will not have this man to rule over us.
Oh, what lovely plants in the Lord`'s garden might some of these be,
if they were but willing in simplicity to yield themselves into his hands,
to be anything or nothing, as He might see fit!
How would He qualify such to go forth as valiants who are '`now lying as among the pots!
Truly our sufficiency is not of ourselves, but of God, and our help comes from Him,
and not from man, whose breath is in his nostrils--and whereof is he to be accounted of?
I feel as one of the weaklings of the flock, and one of the least in the family,
needing the prayers and the help of the rightly
exercised that I fall not to the right or left.
Weak as I am, the desire of my heart at this time is,
that all who see and feel the necessity for faithfully labouring as God may give ability,
may seek to be preserved in that state of true humility,
as to be willing to do the meanest office in the King`'s
house,--to bear the cross and despise the shame,
that so the blessed cause of Truth and righteousness may be exalted in the earth,
and they at last, when their day`'s work is done,
may be set down at the right hand of God, far above all principalities and powers,
bearing the inscription of "`holiness unto the Lord!`"

Under a previous feeling of love, flowing, as I humbly trust, from the Father of Mercies,
I bid you, affectionately, farewell.

Thomas Kite to Joshua Sharpless

Philadelphia, First month 12th, 1822.

Dear Father:--The Yearly Meeting`'s Committee are at present visiting
the Monthly Meeting of Burlington and Haddonfield Quarterly Meetings.
We hear William Forster has gone into the Illinois country.
Geo. Withy was at Washington on First-day last, wishing to have a meeting in the Capitol;
but a Baptist preacher having had a previous grant, he was disappointed.
It was uncertain whether he would stay over another First-day.
Thos.
Evans, son of Jonathan, is his companion in this southern journey,
which will probably extend to Carolina.

I have heard of your more comfortable state of health,
and I have felt tender desires that whether it may please the Supreme Control]
er of events still further to restore ft) health,
or whether increasing pain and weakness may be attendant,
your mind may be preserved in the everlasting patience,
deeply anchored on Him who has been your morning light,
your strength in the meridian of your day, and, I trust, will be your evening song.
Paul, that experienced servant of Jesus, was deeply tried with a thorn in the flesh,
the messenger of Satan sent to buffet him.
We hardly know what particular trial he alludes to;
perhaps it was the irritability of a temper naturally quick and ardent.
Whatever it was, he sought its removal.
"`I besought the Lord thrice,`" said he,
"`that it might be taken from me,`" and the gracious answer was,
not that he should be exempt from the trial, but sustained under it:
for My grace is sufficient for you, for my strength is made perfect in weakness.`"
Very encouraging for those who may, like Paul, be tried,
singly to depend upon the sufficient grace of our Holy Redeemer, who,
having loved his own, loves them unto the end, and enables them, through his power,
to overcome all the propensities of corrupt nature, and finally to triumph over death,
hell, and the grave.

Thomas Kite`'s oldest daughter, Susanna,
was placed at Westtown Boarding School in the latter part of the Fourth month, 1822.
Her first letter on the 24th,
tells other childish griefs--her alarm the first morning after
her arrival at the sound of the great bell,
calling the scholars to arise; as she thought, in her half-awakened state,
that she was in the city and heard the fire-bell.
She appears to have been afflicted with home-sickness--had had a
hearty cry--and thought herself thereby disqualified to write.
Under date of Fifth month 4th, her father thus wrote to her.

"`Dear Susanna:--I was disappointed in not receiving a letter from you by the last stage.
If permitted, I should like to hear from you frequently.
You can be at no loss for subjects to write on which will interest your parents,
who feel anxiously solicitous for your good every way.
Your studies--your companions--the little incidents of
the school--your meetings for worship--all these,
and many other subjects, will prove to us interesting from your pen.
We feel for you,
not doubting that at first the trial to your feelings in being separated,
will be considerable.
It is so to ours.
But be encouraged;
attention to your business will assist in shaking off unprofitable regrets;
and you will soon feel comfortable amidst your new associates,
towards all of whom I wish you to behave with perfect kindness,
while you are not very intimate, except with a few.`"

Susanna, having informed her parents in one of her letters,
that it was against the "`order`" of the school for her to have been
thus employed at the time she wrote it--her father replied:

Philadelphia, Fifth month 9th, 1822.

Pleasant as it is to receive letters from you,
I have no wish you should infringe the rules of the school,
nor even go counter in the least degree to the wishes of the teachers.
When you have an opportunity to write,
begin a letter and add from time to time until the paper is full.
Write as neatly as you can.

It is my particular wish that your behaviour may be
toward your teachers both respectful and affectionate.
Never appear heedless or unmindful when addressed by them,
but endeavour by prudent conduct to gain their confidence.
It will add much to your comfort, and afford your mother and myself sincere satisfaction.
I will just add, while I am advising you,
a hope that you will be particularly careful of your deportment in meeting.
Let it be serious, and, dear child,
endeavour to have your thoughts collected as in the presence of the Holy One,
that thus a qualification may be furnished you to worship; to rejoice in his goodness,
to fear before him, to choose him for your portion,
to say unto him in the secret of your heart, "`My father,
you are the Guide of my youth.`"
Oh! that you may be thus favoured.
How earthly distinctions and earthly advantages fade
when compared with these spiritual blessings.
Learning is good; the outward comforts of life are good;
it is a favour to have kind parents and affectionate friends;
but what are these compared with being the sons and daughters of the Most High,
instructed in the school of Christ,
and united to the blessed society of the saints in light.
Keep this in your view above all other acquisitions or advantages.
The benefit will be experienced not only here but hereafter;
for godliness is profitable unto all things, having the promise of this life,
and that which is to come.

Now, for news.
George Withy had a meeting for the young people of the city on Third-clay afternoon.
A great collection--but he did not preach; a great disappointment to many.

After visiting his daughter at Westtown, Thomas Kite wrote to her, Fifth month 17th.

"`When I left you on Second-day evening, I went to your grandfather`'s to lodge.
In the morning I walked up to the top of Osbourne`'s Hill,
and heard the music of the little birds,
as well as feasted my eyes with the delightful prospect
of the cultivated hills of the Brandywine.
I have seen few more lovely landscapes in my travels.
We went to Concord to the Quarterly Meeting, and lodged at Samuel West`'s, near Chester;
attended Chester meeting on Fourth-day, where was a marriage;
dined with the wedding company, and reached home in the evening.
I have but little to say more than this; frequently ask yourself in your amusements,
'`Would my father approve of this?`'
My dear child, your preservation in innocency is a wish that is very near my heart.`"

Thomas Kite to his daughter Susanna.

Sixth month 17th, 1822.

I do not wish for you, my dear, anything far beyond the common standard,
yet I do wish for your diligent improvement of the faculties you are favoured with.
Not that you may shine and be applauded,
but that you may be qualified to discharge your
duty in any situation of your future life.
The habit of industry is of great consequence,
and when we consider how uncertain all temporal possessions are,
it seems peculiarly important that we acquire habits in youth
which may render it easy to labour for a subsistence,
in case it should become necessary.
Far more important is the habit as regards the concerns of the immortal part in us.
In this respect we should be diligent, fervent,
labouring to know ourselves to be redeemed from wrong things, from every habit,
passion and propensity which will render us unacceptable in the Divine sight.`"

Same to Same.

Sixth month 22nd, 1822.

I saw the Superintendent yesterday,
and received from him a pleasant account of your health and cheerfulness.

I do not want you to lose your affectionate regard for your friends at home;
but I do want you to feel entirely contented where you are,
so long as it appears best for you to remain there.
This disposition will be valuable in assisting
you to prosecute your studies to advantage;
for, remember, you are not sent to Westtown to be amused, but to study,
and this implies diligence, attention, assiduity.
Nothing valuable is to be obtained without labour.
I wish you particularly to endeavour to cultivate a habit of abstraction,
as essential to mental improvement.
I mean that you think only of the subject before you.
If you allow your mind to be drawn aside by every trifle that occurs,
or thought that presents,
it is hardly possible you can lay in a good stock of valuable knowledge.
Keep close to the study before you,
endeavouring thoroughly to understand it--passing over
nothing without clearly comprehending it,
conquering weariness, disgust and the love of indolence.
In this way, my dear daughter, you will answer my design in sending you to school,
and lay up such a foundation of useful learning as will
be pleasant to yourself and us in future days,
should your life be spared to us.

David Cope came with your uncle Cheyney to attend some meetings in the city.
He lodged at our house.
Our friend Sarah Hopper is deceased.
She had been a remarkably healthy woman, but since last fall her health has declined,
and of late rapidly so.
She was buried on the day appointed for the marriage of
her brother John Tatum to Anne Biddle.
Her own daughter`'s marriage is also postponed.
She will be much missed in her large family.
The children will feel the absence of such a counsellor and friend,
but if they apply to that Almighty Being, who has, no doubt removed her in wisdom,
we have room to believe, that being the father of the fatherless,
he will condescend to be the Guide of their youth.

Thomas Kite to his daughter Susanna.

Philadelphia, Sixth month 30th, 1822.

Circumstances prevented my writing to my dear daughter by the last stage.
'`I think I mentioned your mother`'s visit to Woodbury on Seventh-day week.
She did not return till Fourth-day morning,
when she and I attended the meeting at Twelfth street,
when John Tatum and Anne Biddie accomplished their marriage.
I cannot say I was pleased with your observations respecting your food at Westtown.
Were you in a humble, contented disposition,
you would feel that such fare was not only better than your deservings,
but cause of thankfulness to the bountiful Feeder of the human family.
This leads me to mention what, perhaps, you have not heard,
that in Ireland the poor are suffering for lack even of the coarsest food.
In many parts last year the crop of potatoes failed, and the horrors of famine,
and consequent disease, have been experienced.
When next you takest your plentiful meal, remember,
that to thousands it would seem a feast of delicacies.
There has been a great fire in Baltimore; about thirty houses destroyed,
and much distress experienced.
Thus is there continually occurring something to
call forth our tender commiseration for others;
and the sympathy we now give, we know not how soon we may need.
This life is made up of changes.
They, and they only, who, endeavouring to live in the fear of the Lord,
and in obedience to his will, are prepared for every change.
It is declared, "`all things, work together for good to them that love God.`"
I long more than my pen can express, that in your young and tender years,
you may be brought into the love of the Heavenly Father,
and into the experience of his favour.
Oh! how religion dignifies and adorns the beloved youth,
enabling them to fill up with propriety every station
in which the providence of the Almighty places them;
and when their pilgrimage is terminated,
how it opens to them an access to that blessed company that
surround the throne of the Eternal in never-ending bliss.
May a life of religion be your deliberate choice, that, having lived the life,
you may die the death of the righteous.

Same to Same.

Seventh month 5th, 1822.

Dear Susan:--You know not the parental anxiety I feel for your welfare every way.
It is impossible for you fully to appreciate it; but you are old enough to know,
that the course of life I wish for you, will conduce to your happiness,
to present peace--contentment in every situation--and
if persisted in to the close of life,
it will open the cheering hope of a blessed immortality.

13th. It often happens to people who seek pleasure by change of place,
that they come home disappointed.
Happiness depends less on outward situation and circumstances
than on the inward disposition of the mind.
With a humble sense of how little we deserve,
and a grateful sense of how much Providence has done for us,--
a lively wish to fulfil all our own particular duties,
and a continued endeavour to make all those around us comfortable,--
we can hardly fail to become in a considerable degree happy,
let oar outward situation be what it may.

19th. I spent nearly two days with +++[+++his wife and family in Jersey],
enjoying those beauties of nature, of which I perceive by your letters, you are sensible.
Let us raise our hearts to the contemplation and love of the bountiful Author of nature,
who has given us all things richly to enjoy.

26th. On looking at your letters I find another question unanswered.
You say, speaking of our coming to see you, "`if you all come at once,
how can I part with you all?`"
Now, perhaps, to save your feelings, we had better stay away altogether.
Do you think so?
Dear child, you must endeavour to control your feelings, and discipline your mind.
Close attention to your studies will be a good way to get the
better of your excessive longings and anxieties about us.
We prize your love very highly,
but would rather it were shown in doubling your diligence at school,
that you may be the sooner restored to us.

There have been many deaths; some of them so sudden as loudly to give the warning:
"`You also be ready!`' A serious consideration of the
end of life is proper even in the season of youth,
and it is not incompatible with cheerfulness, though it excludes levity.
May the blessing of Providence be your experience.

30th. There are some practices which unthinking young persons have fallen into,
which I wish you to avoid, such as speaking unhandsomely of their places of learning.
This marks a very unpleasant state of mind.
The Institution in which you are now placed had its origin in a concern for
the guarded religious education of the youth of our Society;
and a little reflection must teach you, that in order to attain that end,
a degree of method, order and restraint must be introduced,
which is somewhat irksome to young minds.
It is, +++[+++however,]
ungrateful in such who know they are deriving essential benefits from the school,
to speak ill or complain; and particularly would it be unbecoming in you,
who were sent there at your own request.
I speak this as a caution, not only now while at school, but when you leave it,
that you may be particularly guarded on this point.

Another disagreeable practice with some children is finding fault with their teachers,
or ridiculing them to their young companions.
I know not that you ever did so, but I warn you affectionately against such a procedure.
Many are the trials of teachers,
arising from the great variety of dispositions they have to deal with;
and much they have to give up to devote themselves to so arduous an engagement.
I hope you will be one that will endeavour rightly to feel for,
and sympathize with all the teachers,
to pay a respectful attention to all their admonitions, and by example, and persuasion,
when necessary, endeavour at all times to uphold their authority.
This you will find conduce much to your peace and comfort.

Lastly, some children are prone to find fault with their provision.
This, I feel a comfortable hope, you will not fall into.
What do we deserve,
compared with the bountiful supply for our needs which
a beneficent Providence continually affords us?
Rather let us endeavour to feel the sentiment of the Psalmist,
"`What shall I render to the Lord for all his benefits?`"
'`It is pleasant to us to hear from you.
Believe me, dear child,
you are not likely to find firmer friends anywhere than in your father`'s house.
Be not anxious to make a large acquaintance;
and if any you have made should seem to slight you, be not much concerned about it.
Keep near to your parents, brothers and sister, in true affection.
Separate from us as you are, I dare say, you think such an admonition superfluous,
and that you are in no danger of forgetting to love us.
See, then, that your conduct speaks the same language.
Let your love to your parents induce you to do nothing
in their absence you fear would be unpleasant to them,
and when restored to the domestic circle,
if Providence should permit us to be again united,
may your love to your brothers and sister lead to
increasing patience in bearing their little foibles,
increasing self-denial when your inclinations are in opposition,
and an increasing concern as our eldest hope,
to set the younger a good example in all things.
Thus will our desires--may I not say our prayers--concerning you be answered,
and you prove a solace to our declining years.
May it never be otherwise,
for nothing is so bitter to a parent`'s feelings as a disobedient or ungrateful child;
nothing so likely to bring down his grey hairs with sorrow to the grave.

Sixth month 16th. There is one hint,
both as regards your studies and the reading you
may undertake in the intervals of your studies.
Read nothing, study nothing, without understanding it.
If you have not clear and precise ideas, ask the teachers at a suitable time;
and if done in a proper manner,
I have no doubt they will be glad to give you all necessary information.
A certain English writer says, "`If it is worth while to do anything at all,
it is worth while to do it well.`"
Attend to this both in important and small matters; whether it be waiting on table,
hemming a handkerchief, writing a letter, or getting your lessons,--do your best.
Establish habits of order, neatness and industry, now in your youth.
If you do, these habits will prove of great consequence in advanced life.

Why do I give you so much advice?
Because I love you.
Because I earnestly desire you may grow up worthy to be loved.
My spirit at times is bowed in secret prayer to my God, that He may bless you,
that He may incline your heart to fear and love Him, and to keep his commandments always.
Then will your peace flow as a river;
no uneasiness will be indulged at any present situation,
but in all states you will be content, daily blessing the Lord for all his benefits,
and rejoicing fn the God of your salvation.

The following portion of a letter to Thomas Kite was written by a young female minister,
who had been on a religious visit to Philadelphia.
One phrase in it marks the district in which she was educated.

"`Eighth month 26th, 1822.
We were favoured to reach our homes in safety and peace, which, indeed,
is cause of thankfulness.
Since which my lot has been much circumscribed,
the door closed as to public communications,
and my dwelling-place within the compass of quiet and rest.
How evident in every line of life is the goodness, great loving kindness,
and tender mercy of Him, who is sometimes pleased to call into action,
and operate upon the instruments in his own way;
and when they have humbly attended to his directions, to release them,
with a portion of the oil of comfort,
causing the light of his countenance to attend them on their way,
and return with them to their accustomed departments.

Things are in a low and trying state among us, as a Society;
but neither to those within or without its pale who are rightly engaged,
had this ought to administer discouragement.
Those of this description +++[+++humble seekers], it is my belief, however situated,
have very much to dwell alone; their secret exercises known but to themselves.
But their sighs and silent intercessions are noticed by Him, who regards his heritage,
and watches over his little ones.`"

Thomas Kite to his daughter Susanna.

Ninth month 30th, 1822.

Your last letter, my dear Susan, was peculiarly acceptable,
because it marked a contented mind.
Cherish and cultivate this disposition, which will, I am assured,
conduce to your comfort, as well as the comfort of your parents and friends.

Tenth month 12th. From your uncle Isaac Sharpless, accounts are not more favourable.
He appears to be gradually declining;
and it is probable before many months have elapsed he will be numbered with the dead.
An affecting circumstance to us all, particularly to his dear wife and children;
the latter being now of an age sufficient in some degree to understand their loss.
You have heard, I expect, of the injury your aunt Mary Sharpless received in her eye.
It is doubtful whether she will have the use of it.
With her affliction, her husband`'s situation,
and of that of your grandfather and grandmother,
there has been a time of great trial amongst them;
and your aunt Phebe has been under the necessity of making great exertions.
'`I need hardly repeat my desires for your diligent improvement
of the opportunities afforded you for acquiring learning.
Be not afraid of labour; do not give way to indolent feelings,
but arouse yourself to exertion,
supported by the sweet consciousness of the approbation and esteem of your parents;
and above all,
looking for a blessing upon every good endeavour from your Heavenly Parent,
in whose favour the Scriptures say "`is life,
and at his right hand rivers of pleasure forevermore.`"

Isaac Sharpless deceased Eleventh month 13th, 1822, and after attending the funeral,
Thomas Kite and wife paid a visit to their daughter at Westtown.

Thomas Kite to his daughter Susanna

Twelfth month 7th, 1822.

My Dear Susanna:--I wish your literary improvement,
and in propriety and decorum of manners; but far above all, I wish your heart improved.
This can only be produced by your submission to the cross of your Saviour.
Now in the spring time of life, may you take up that cross,
that so should your days be lengthened to maturity, it may prove your crown of rejoicing.

About this period Thomas Kite received from his stagecoach acquaintance, Lydia Huntly,
a copy of her poem on the "`Aborigines of America,`" with the following letter:

November 18th, 1822.

Friend Thomas Kite:--You may possibly recollect having presented several years
since a copy of "`Barclay`'s Apology for the Quakers,`" to a young female,
of Connecticut.
The gift was not lightly valued, nor the giver forgotten;
and as a testimony of such remembrance, she begs leave to present you with a Poem,
in whose second Canto allusion is made to that peaceful sect, who,
whatever may be the pretensions of other denominations,
certainly adhere the most perfectly to the unresisting system of that Redeemer,
who at his death bequeathed to his disciples that spirit of peace,
which turned to joy the harps of angels,
when the star of his birth first gleamed over the mountains of Bethlehem.
