== Chapter VIII.

1825-1828.

Letter from a young friend--Thomas Kite`'s reply--Joshua Sharpless`' death--Memoranda.

Thomas Kite was often dipped into sympathy with the young,
and through the unfolding of the Holy Spirit,
was made acquainted with their departure in heart from the principle of Light and Life,
which would have preserved them from sin.
Having been brought, as he believed,
into a sense of the lapsed state of one of the children of a man he dearly loved,
he unfolded to the young man plainly and affectionately his concern on his account.
He soon afterwards received the following letter.

Second month 2nd, 1825.

So far am I from feeling offended at your communicating your
exercise on my account to me in the manner you have,
I can assure you it was acceptable;
and I have desired that I might experience a qualification duly to appreciate the favour.
But alas!
I must candidly acknowledge that it is with me as you have feared.
I am not what I once was.
The truth of this I sometimes keenly and sensibly feel,
when in seasons of serious reflection I am brought in a degree
to feel my alienation from the Commonwealth of Israel.
Yes!
I have wandered, widely wandered from that which tends to true peace of mind.
I have rebelled and rebelled,
till I have gone so far that I am led to think
at times that I shall never be able to return.
Yet there are seasons when the little good which is yet left in me predominates,
and I feel anxious to be found a dedicated follower of the Lamb,
and thereby become an honour to the Truth.
But a dread of the cross, added to a strong natural inclination,
has enabled the adversary of my soul to keep me in bondage,
and introduce me into a state,
which I may truly say I have at times felt to be worse than Egyptian darkness.
I could say much, but it is far from being a pleasant subject for me to dwell upon.
But I considered my acknowledgments were due to your kindness;
and sincerely hope that I may be qualified to receive anything
further which you may have to communicate in this way,
in a degree of that spirit which has introduced you into a tender
solicitude for the welfare of your sincere though unworthy friend.

Thomas Kite in reply

Second month 3rd, 1825.

I have been affected in reading your letter, which I received last evening,
and can truly say, that as you are in some degree enabled to see your situation,
my petitions on your behalf are,
that your convictions of the exceeding sinfulness of sin,
and of the awful danger of continuing in it, may be strengthened and confirmed.
There are two kinds of sorrow for sin.
There is a sorrow for that loss of comfort and respectability, the first of which always,
and the latter of which generally, follows a sinful course.
This kind of sorrow mends not the heart, being merely selfish.
There is another sorrow which springs from conviction, impressed by the Divine Spirit,
of having violated the law of a beneficent holy God.
This sorrow is genuine, leading to an abhorrence of our whole life of iniquity,
and to a willingness to suffer such a portion of anguish of spirit as
the Most Merciful shall see needful for our correction.
"`I will bear the indignation of the Lord,`" said one of old,
"`because I have sinned against Him.`"
As such a disposition is cherished, the truly awakened and contrited sinner,
though despairing, and justly so, of his own strength and his own resolutions,
dare not despair of the mercies and forgiveness of God;
being led to look in faith to that blessed Redeemer,
who is the Propitiation for our sins, the Mediator and Intercessor with the Father,
and a High Priest touched with a feeling of all our infirmities.
The Apostle Paul, in confidence of the mercy of God through Christ,
thus addresses some of old: "`My God shall supply all your need through Jesus Christ.`"
Now, what do we?
What do you, need?
Is it that your hard heart should be broken?
Behold the promise: "`I will take away their stony hearts,
and give them hearts of flesh;`" that is, hearts capable of feeling.
Is it that the heart, being broken, has need of healing?
"`He heal all the broken in heart, and binds up their wounds.`"
Is it to he cleansed from former pollutions?
"`The blood of Christ cleanses from all sin.`"
"`A fountain is set open for the house of Judah and the inhabitants of Jerusalem,
for sin and uncleanness.`"
Is it strength to resist evil in time to come?
"`I can do all things through Christ that strengthens me.`"
Is it light upon your path?
or is it protection you need?
"`The Lord God is a sun and a shield.`"

Let me invite you, then, to the footstool of the cross;
let me entreat you to take the Saviour`'s yoke upon you;
to flee from sin as from a serpent.
Never do anything you know to be wrong; endeavour to be inwardly watchful unto prayer,
and I cannot but believe, if you make use of the little strength you have,
you may at length experience a restoration to a state in which the consciousness of
the Heavenly Father`'s love and protection will be your greatest joy.

Every truly enlightened mind must abhor the idea of allowing themselves to transgress,
because God is merciful; of continuing in sin that grace may abound.
But when brought to a proper abhorrence of sin,--when we can say,
"`How can I do this great evil and sin against God?`"
or, "`If I have done iniquity,
I will do so no more,`" then there is comfort to be gathered from the assurance,
that the "`Lord is merciful, and ready to forgive.`"
In such a state, the experience of David is deeply instructive.
Behold how great his fall!
The man who had enjoyed intimate communion with God--the sweet Psalmist of Israel,
who had proclaimed to others the name of Him,
who is glorious in holiness,`' and fearful in praises--yet grossly fell.
Behold, also, the depth of his penitence, his anguish of spirit, his self-abhorrence,
his prayers for restoration:
"`Take not your holy spirit from me!`" "`Create in me a clean heart,
and renew a right spirit within me.`"
Behold the mercy of that God against whom he had so grievously sinned.
There is yet some encouragement to the poor penitent,
sincerely desirous of returning from the evil of his ways.

With regard to your outward situation +++[+++he having
spoken of retiring where he was not known],
I would rather encourage you to remain where you are, for the present.
Beware of rash steps.
Stay where you are known, and where you are beloved,
and where there are those who will feel for you, pity, comfort and advise you.
If you wish to see me, I will call on you.
If you have anything whatever to say, or any advice to ask, I am willing,
to the best of my ability, to hear and counsel you;
remaining your truly affectionate friend.

There is one thing I particularly wish to press upon you,
when you feel a state of wretchedness and poverty,
beware of turning again into folly for temporary relief.
This would be to add bitterness to the bitter, to bar up your own way,
to heap up wrath against the day of wrath.
Rather under such feelings endeavour meekly and
patiently to bear what you are conscious of deserving,
remembering, it is better that our sins go beforehand to judgment,
than that they should follow after.

The young man settled down into a useful citizen,
and became a religiously concerned member of the Society of Friends.
He continued to reside in Philadelphia, and within his domestic circle numbered a happy,
virtuous wife, and an interesting family of children.

Near the close of the Tenth month, this year,
Thomas Kite`'s three eldest children spent a short time
at Burlington with their father`'s friend,
Stephen Pike.
On their return, they were made the bearers of the following letter:

Burlington, Tenth month 30th, 1825.

Esteemed Friend:--The company of your children has been acceptable to us all;
to myself particularly so.
This earth has nothing so interesting as the loveliness of innocence
accompanied with sprightly intelligence and benevolent affections;
and I think these inestimable qualities are possessed
by my young visitors in no small degree.
Much I wish for them, that the contact with a corrupt world,
which they must necessarily experience, as they advance in life,
may not contaminate them,
and that they may advance in the improvement of the faculties with which they are gifted,
and also of those exterior graces which render their possessor agreeable to others, and,
consequently, better qualified for usefulness.
In haste, your sincere friend,

Stephen Pike.

During the years 1824, 1825 and 1826,
Thomas Kite continued labouring as ability was afforded against the
inroads of unsound doctrines into the religious Society of Friends.
From time to time, at the pointings of duty,
he attended neighbouring Quarterly and Monthly Meetings,
but paid no extensive religious visit during those years of commotion.
For his faithfulness to what he esteemed fundamental truths,
he was much disliked by the followers and admirers of Elias Hicks,
who manifested their displeasure with him in various ways.

Thomas Kite to his daughter Susanna.

Philadelphia, Eighth month 19th, 1826.

I find, my dear child, whenever I take up my pen to address you,
that desires for your welfare in the best sense predominate.
This is, no doubt, because I love you,
and love ever wishes the best things for the beloved object.
If it were possible for me, with a wish, to obtain for you riches and honour,
and all worldly advantages, I would not let the wish escape,
because far from proving to your advantage, they would be a snare.
But in desiring for you heavenly treasure, durable riches and righteousness,
I cannot limit my desires.

Cultivate then, every day, and every hour of the day, the favour of that Great Being,
who can dispose of these precious gifts;
and however slender your portion of what the world chiefly values,
you will become an heir of glory.
To see you really adorned with humility, meekness, and the fear of the Lord,
will afford me the most lively satisfaction;
while few or any circumstances could cause me such heart-rending
grief as to see my children turn aside into the paths of folly.

Be circumspect, then,
lest the dissipating effects of visiting about should
indispose your mind for serious reflection.
Let no morning or evening pass over without an
endeavour to draw near to your Creator in spirit,
to implore his protection, to bless Him for favours past, and supplicate for more.
The actions of time are weighed in the balance of eternity,
and such as we sow such shall we reap.
Oh! that, sowing to the Spirit, you may of the Spirit reap life everlasting.

Joshua Sharpless, father-in-law of Thomas Kite, deceased the 21st of the Ninth month,
1826.
The funeral took place on the following Seventh-day, the 23d, at 10 o`'clock.
Thomas Kite remained for a short time with the bereaved family at Bradford,
and his Christian labours in consolation and counsel on that occasion,
were long had in remembrance by some of the grand-children collected.

The Hicksites having agreed amongst themselves to establish Monthly
and Quarterly Meetings in unity with their separate Yearly Meeting,
it became the duty of the Quarterly Meetings of the Society to
appoint committees to strengthen their subordinate meetings,
especially such as contained within them many unsound members.
Philadelphia Quarterly Meeting, in the year 1827,
appointed a few men and women Friends to extend aid to Radnor Monthly Meeting.
The clerk of that meeting united with Friends,
but the larger portion of the members were separatists,
and they determined to throw off their allegiance to Philadelphia Quarterly Meeting,
and attach themselves to a body favouring their views.
Thomas Kite was one of the committee, and shared with other of its members,
the trouble incident to the duties of such an appointment.

This year Susanna Kite commenced keeping school in Philadelphia, and her brother William,
then but seventeen years of age, undertook a similar occupation at Medford, New Jersey,
for the winter of 1827-8. His father felt much concern and anxiety at
this early engagement of his son in so important a matter,
and his letters testify his care.

Thomas Kite to his son William.

Philadelphia, Eleventh month 21st, 1827.

Dear Son:--I feel anxious to hear how you feel in the
new and important station in which you are placed,
and for your good conduct, wherein I feel myself in some degree responsible,
not only because of my relationship,
but because of my recommendation of you to the Friends who have employed you.

I trust your endeavours will not be lacking to give satisfaction,
not only by diligent attention to your school,
but also by a prudent and exemplary course of conduct.
I think you had better not resort to corporal punishment.
Pass over slight offences, as if not observed; in more serious cases,
if admonition fails to reclaim, complain to the trustees.
But while mild and gentle towards all your scholars, be not too familiar with them,
and have no favourites.

With respect to your demeanor out of school, either in the family you board with,
or where you may visit, be modest and unassuming, patient and willing to be pleased.
I have confidence in your religious principles,
yet I wish you not too freely to assert them, nor be too liberal of your remarks,
particularly when with the young, on the present unhappy state of our religious Society.
May the blessing rest upon you which was "`on the head of Joseph,
and on the crown of the head of him who was separate from his brethren.`"
A dear aged friend of mine, Elizabeth Collins, lives near you.
I wish you, some First-day afternoon, to call on her, make yourself known to her,
and remember me affectionately to her.

To the Same

Twelfth month 22nd.

I have received some information of your getting along, which has been satisfactory,
I mention this not to elate you,
because I know that every degree of preservation from evil is a mercy
which calls for humble gratitude to the Lord our Helper,
but I mention it to excite you to continued watchfulness that
you may be strengthened in stability of conduct,
which will prove consoling to your best friends and be of lasting benefit to yourself.
You are aware that some interesting young persons,
whose early lives gave promise of much future
usefulness have been overcome by temptation,
in an unguarded hour,
and have brought a stain on their characters and grief upon their friends.
+++[+++In order]
that you may avoid the rocks on which these have been wrecked,
look to the Heavenly Pilot, dwell in the fear of the Lord all the day long,
earnestly seek to feel his presence contriting your heart in religious meetings,
and in more private seasons of retirement.
This course of life, far from rendering life gloomy, as some have falsely imagined,
will prove a fruitful source of comfort.
Outward blessings will be enjoyed with a double relish,
when received as gifts from Heaven;
and innocent cheerfulness is not incompatable with the most ardent devotion.

Moreover it is the uniform testimony of the Lord`'s servants,
that no earthly joy is to be compared with that which is
'`unspeakable and full of glory,`' even in the present life;
and then they have the blessed assurance that
death itself cannot destroy their pleasures.
They know that '`if the earthly house of this tabernacle were dissolved,
they have a building of God, a house not made with hands, eternal in the heavens.`'

Among Thomas Kite`'s papers was found the following:

"`God created man for enjoyment,
and therefore implanted in him an instinctive desire for happiness.
As first created,
his thirst for happiness was gratified by partaking of the fountain of supreme bliss,
by communion with his Creator.
By his disobedience and fall from the state in which he was created, both he,
and his posterity, partaking of his nature,
have sought to have their desires for happiness
gratified by partaking of fleshly delights.
These can never satisfy, because the mind is immortal,
and nothing short of an immortal good can fill the soul.
The work of regeneration commences by making man sensible of what he has lost,
and raising desires for its restoration.
Hence he craves purity, that he may again assimilate with God and enjoy Him.
By submitting to the power of the Spirit,
the instinctive impulse after happiness becomes purified.
That which in a fallen state is carnal desire becomes heavenly and spiritual;
it is hunger and thirst after righteousness.`"

Soon after the Yearly Meeting in the Fourth month, 1828, Rebecca,
daughter of Thomas Kite, went to Westtown Boarding School,
and in the Fifth month his father and mother broke up
housekeeping and became inmates of his family.
As his book store did not realize sufficient profit to support his family,
he now added a printing office and a bindery to his means of maintenance.
The printing office proved a profitable investment,
and he retained an interest in it for a number of years.
