== Chapter IX.

[.chapter-synopsis]
* 1828-1834.
* Elizabeth Robinson`'s last meeting
* Visit to Virginia yearly meeting
* Doctor Godman`'s death
* Yearly meeting`'s committee
* Letters.

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Rebecca.

[.signed-section-context-open]
Philadelphia, Sixth month 7th, 1828.

You make some allusion to the state of your mind; dear child,
I wish you to be serious and weighty in your
attention to the concerns of the immortal part.
It is no new thing for those who sincerely desire to serve and
love the Lord to be tried with wanderings of mind,
and the intrusion of unprofitable thoughts, even when sitting in religious meetings.
But look steadily to the Lord, and cry unto Him,
and in his own time He will send deliverance.
Remember, to bear the cross is the way to win the crown.
It is worth while to suffer many trials here, if they may but be sanctified to us,
and work out for us, when the trials of time are over,
an exceeding and eternal weight of glory.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To the Same

[.signed-section-context-open]
Sixth month 28th.

[.salutation]
My beloved child,

I have no doubt the gracious Hand of mercy has been extended unto you,
and this it is that troubles you for wrong conduct and for wrong thoughts.
Be not discouraged, the Lord is merciful!
Wait in the simplicity of a little child upon Him,
and ask of Him to change your heart and make it better.
His power alone can do it; and He is as willing now as ever He was to cleanse and purify.
Though you may experience your inward troubles, yet if you follow on to know the Lord,
He will in his own time, '`give you beauty for ashes, the oil of joy for mourning,
and the garment of praise for the spirit of heaviness.

--

+++[+++During the early part of summer, this year,
Susanna Kite`'s health became somewhat impaired,
and her father concluded that a short relaxation from school duties was necessary;
and feeling a freedom to visit his friend Henry Hull at Stanford, Dutchess County,
New York, he took his wife and daughter there.
They left Philadelphia the 2nd of Seventh month and were gone a little over a week.
The visit proved pleasant to all and exerted a beneficial influence on Susanna`'s health.]

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Rebecca.

[.salutation]
Dear Rebecca:

I thought it would interest you to be informed of the
proceedings of Elizabeth Robson for a few days before leaving us.
On Fifth-day evening week, she had a public meeting at the North house, favoured,
though not large.
The next morning she had an interview with the ministers and elders of the city,
in which much feeling was evinced.
In the afternoon +++[+++she had]
an opportunity with the younger classes, members and attenders of our meetings,
at the Arch Street house.
It was largely attended, particularly on the female side,
and she was extensively engaged in the love of the Gospel,
in persuading to a holy life and conduct.

On Seventh-day she saw at her lodgings many Friends,
who called to have a parting interview with her.
On First-day morning she was at our meeting, and this, her last opportunity,
was a memorable one, in which Divine goodness was pleased to appear,
tendering the hearts of very many,
and enabling his servant to appear both in testimony and supplication,
in the love and authority of the Gospel.
I think I never knew so many tears of tenderness shed in a meeting.
It seemed like a seal to her services in our land.

She went from the meeting-house to the steamboat,
and proceeded in the afternoon to New Castle, where the ship was waiting.
About thirty friends accompanied her to the vessel, which immediately got under weigh,
as the sailors phrase it.
She is now, most probably, several hundred miles on her way to join her family,
from whom she has so long been separated.

Hinchman Haines`' wife was buried yesterday.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To the Same.--From the residence of John L. Kite.

[.signed-section-context-open]
Silver Lake Township, Susquehanna Co., Tenth month 10th, 1828.

[.salutation]
Dear Rebecca:

I thought it would please you to receive a token of
remembrance from so distant a part of the country as this.
You were probably aware of my intention of visiting my
brother and accompanying your aunt and cousin home.^
footnote:[Phebe and Abigail Sharpless.
They had been on a visit to Western New York and
intended returning home through Susquehanna Co.]
I left Philadelphia last Seventh-day for New York; arrived safely in the evening;
attended at the new meeting-house twice on First-day; and with A. Braithwait, Henry Hull,
Samuel Adams, and other Friends.
On Second-day I went up the River Hudson to Newburg, and was quite unwell on the passage.
As the stage was to leave Newburg at 2 o`'clock in the morning, I went early to bed,
but between my indisposition and the constant noises in the house I did not sleep at all.
I ventured to start notwithstanding,
and continued that day and night for upwards of one hundred miles westward.
I left the stage on Fourth-day morning about 10 o`'clock.
I could not obtain a passage to Montrose without paying an unreasonable price,
so I footed it.
My baggage proved very heavy in a walk of nine miles.

At Montrose I found there would be no stage into brother`'s neighbourhood until morning,
and therefore, fatigued as I was, I set off, and arrived at J. Mann, Jr.`'s, about dark.
His son took me two miles in a dearborn to brother`'s,
where I met with a welcome reception.
Yesterday I attended Friendsville Preparative Meeting, dined at uncle Jehu +++[+++Lord`'s],
and visited Dr. Rose and Silver Lake in the afternoon in company with brother John.
The lake is beautiful.
We took tea at the doctor`'s and found his wife and daughters agreeable.

Today I propose going to Friendsville in company with sister
Mary L. to make some arrangement for sister Phebe and cousin
Abby`'s accommodation when they may arrive there,
as well as to see the place, and some Friends who reside in that neighbourhood.
Though very much tired I was better in health
when I arrived than I had been on my journey,
and feel very well excepting some soreness.
I propose waiting in this neighbourhood for sister and Abby;
and return as soon as they feel ready,
by any of the various routes which they may prefer.
I should not choose, if it were left to me, one that travels all night.

--

+++[+++Thomas Kite was desirous that his children should acquire a
good literary taste and facility in composition.
This led him to encourage a proposal made by one of his
brothers that his family and some of their relatives,
should combine and prepare a periodical,
which should be read every Seventh-day night during the winter season.
Although no one but the editor or reader, knew the writer of each particular,
yet it was the understanding that no one should be present at anytime,
who had not for that occasion furnished his mite.
Thomas Kite was a frequent contributor, and some of his essays will be added.]

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Rebecca.

[.signed-section-context-open]
Philadelphia, Second month 13th, 1829.

My time is so much occupied,
that I can scarcely find leisure even for writing to my beloved child.
I feel a hope you are improving, not merely in literary attainments,
but in a knowledge of yourself, in humility, in love, and in the fear of the Lord.
You well know how little parents can do for their children in a spiritual sense.
They may advise them to be faithful to the discoveries of Divine Grace;
they may pray for them; but after all, the main point rests with the children themselves.
If they obey the call of the Lord, He will be a father to them,
and they shall be made the adopted sons and daughters of the Lord Almighty.
I believe, my child, your desires are good.
I wish you may not be too much discouraged by the strength of natural corruption,
which may sometimes be powerfully felt, but wait on the Lord to receive power over them,
and be sure to yield obedience to the discoveries of his will,
even when most adverse to your natural inclination.
As you trust in the Lord, and not on yourself, He will make way for you,
and in his own time introduce into the glorious liberty of his children.

In the progress of the great work of the soul`'s salvation,
many are the changes we experience;
sometimes rejoicing in the light of God`'s countenance, sometimes mourning its withdrawal;
sometimes praying for its restoration.
At one time, perhaps, thinking our mountain stands strong,
at another almost overwhelmed with the consciousness of weakness.

But through all these changes, as the Lord is steadily looked to,
He will gradually carry on his own work,
at times give the evidence of his lovingkindness, which is better than life,
in seasons of adversity afford hope, which is as an anchor to the soul,
sure and steadfast, and which enters into that which is within the veil.
He will moderate our rejoicings in prosperity, keep us in the hour of temptation,
guide us by his counsel, and afterwards receive us into glory.
Feeling that all the work is the Lord`'s,
we shall be enabled to render Him the praise of it.
I find by your letter to Susanna,
that you have been favoured with the company and gospel labours of Ann Jones, and others.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To the Same.

[.signed-section-context-open]
Fourth month 18th, 1829.

We have been comforted with the arrival of many
precious friends to attend our annual solemnity.
The Meeting of Ministers and Elders met this morning, and was a large meeting.
We had at breakfast Thomas Shilletoe, to meet an Indian, who is a Methodist minister,
and was interpreter for Thomas when he was among the natives.
He is intelligent, and speaks English well; dresses much as Methodists usually do,
excepting that he is decorated around his waist with a red belt or sash.

Be particularly careful, dear, of your health.
To this end use exercise; two or three times a day run or walk in the open air.
I would rather see you restored to us in good health, not knowing quite so much,
than that your attention to your studies should undermine your health.

--

+++[+++In the Fifth month of this year, Thomas Kite attended the Yearly Meeting of Virginia.
The service was performed to the peace of his own mind.
His minute was obtained in the Fourth and returned to
his Monthly Meeting in the Fifth month.

At Philadelphia Monthly Meeting, held Fourth month 29th, 1830,
he obtained a minute to visit the meetings of
Friends in Cain and Western Quarterly Meetings.
Of this journey little account is preserved.
He left home on the 12th of the Fifth month,
and having passed rapidly through the Eastern meetings in Cain Quarterly Meeting,
he passed into the Western, beginning at London Grove,
Fifth-day the 20th. Daring this journey he was in a low state of mind.

In writing to his wife, he says: "`I have very little to say of our meetings,
for I think, notwithstanding Friends are very kind,
I have seldom known a time when I thought myself more
in need of the sympathy of those who can feel.
I am desirous of being preserved, wholly given up to do or suffer the Divine Will.`"

On Second-day, Fourth month 19th, of this year,
Dr. John D. Godman was buried in Friends`' Western ground.
His funeral was largely attended by the scientific portion of the community,
and men of more than ordinary pretensions to knowledge and literature.
On this occasion Thomas Kite was remarkably drawn forth in the ministry,
setting forth the excellency of true religion as compared with knowledge and science;
and calling on all the men of exalted minds and great
attainments to cast their crowns at the feet of Jesus.]

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his sister Mary.

[.signed-section-context-open]
Philadelphia, Seventh month 1st, 1830.

[.salutation]
Dear Sister:

The ties of natural affection
which bind the children of one family together,
are strong;
but the ties of spiritual love which unite the redeemed
children of the heavenly Father`'s family,
are stronger.
May our fellowship be increasingly of this latter kind,
which does not obliterate the former, but exalts and purifies it.
Encompassed as I am with frailties, feeling myself an unprofitable servant,
I nevertheless greatly desire for you that you may be faithful;
that having put your hand to the plough, you may not dare to look back,
and through unfaithfulness unfit yourself for the Heavenly kingdom.
As a sincere desire to stand approved in the Divine Sight is cherished,
and as we centre down in humility and stillness before the Lord,
he will not fail in his own time to show what he would have us to do,
nor to afford strength to perform it.
He sends no one a warfare at their own charges;
though he sends his poor disciples out without purse or scrip,
yet depending in faith on Him, they lack nothing.
Yield not unprofitably to discouragement;
at the same time be careful to try all openings or presentations of a
religious nature in the balance of the sanctuary:
and though many baptisms and exercises for the Lord`'s sake,
and for the working out of your own soul`'s salvation, may attend,
you will know at seasons from the evidence of
Divine life in your silent waiting on the Lord,
that he has not given us the spirit of fear,--that is slavish fear, which has torment,
nor of the fear of man, which brings a snare--but of power, of love, and of a sound mind.

We have heard from Nathan and William,^
footnote:[His brother and son, who had taken a pedestrian tour to Susquehanna County,
to visit John L. Kite.]
who stood their journey out admirably.
They accomplished +++[+++it]
in five days and a half, which is nearly thirty-two miles a day on an average.

--

+++[+++Joshua, the second son of Thomas Kite, towards the close of this year,
began to suffer much pain in the hip,
supposed to have arisen from a hurt received by falls while skating.
Whatever the cause, he never recovered from the effect,
but for several years was quite a cripple.

Thomas Kite, Jr., the third and youngest son, commenced as a scholar at Westtown,
Seventh month, 1830.
His father`'s first letter to him is dated First month 7th, 1831.]

[.embedded-content-document.letter]
--

[.salutation]
Dear Son:

I hope you do not forget to read over the
letter of advice you carried with you to Westtown.
It may serve to remind you of me, when I am too busy to write to you.
Whether I write or not, I am at all times your deeply interested parent,
anxious that all the pains taken with you may produce their desired effect,
and that you may grow up intelligent, well-behaved, and, above all, pious;
remembering your Creator in the days of your youth, fearing to offend Him,
endeavouring to love and serve Him, that He may preserve you from temptation,
support you in trouble, conduct you in safety through the wilderness of this world,
and finally receive you to his own blessed abode.
That, at last, when the journey of life is over, this may be your happy experience,
is the desire of your loving father,

[.signed-section-signature]
Thomas Kite.

--

+++[+++He attended the Yearly Meeting held in New York in the Fifth month,
with a minute of his Monthly Meeting, from which he wrote a letter to his wife,
dated Fifth month 24th, 1831, in which,
after mentioning having the company of Hannah Warrington, Jr.,
and his cousin Anne Warrington, wife of Henry Warrington, of Westfield,
on the journey to New York, and being accommodated at Samuel Wood`'s,
he notes that Samuel and Jane Bettle were lodging at John R. Willis`'s, and then says:]

[.embedded-content-document.letter]
--

Among the strangers attending are Daniel Wood, J. and E. Meader, J. Patterson,
Abigail Barker, Granville Woolman, J. and H. C. Backhouse.
So far, it has been to me very much a time of suffering,
which I desire patiently to endure,
because the blessed Master`'s cause is worthy to be suffered for, and because I know,
if I am favoured rightly to bear the trials dispensed, they will tend to purification,
which I greatly need.

Please remember me affectionately to the family circle, my parents especially,
and my dear Joshua.
I have heard what has befallen my dear friend Sarah Morris,
and sympathize much with her in this personal affliction.
But she is in the hands of a merciful Father, who will enable her to bear up under all,
as she looks unto Him in child-like dependence.
He is our only refuge in the hour of trial.
May you and I, my love, so live in his fear,
that we may experience Him to support us in the hour of need,
is at this time the prevalent desire of your affectionate,

[.signed-section-signature]
Thomas Kite

--

+++[+++On the 28th of the Seventh month, Thomas Kite was set at liberty by his Monthly Meeting,
to attend the meetings composing Concord Quarterly Meeting,
and appoint meetings for those not members.
His invalid son, Joshua, being at his grandmother Sharpless`'s, in East Bradford,
he addressed him a letter,
dated Seventh month 29th. It begins with a description of a destructive fire,
which he knew would interest the boy, and then adds:]

[.embedded-content-document.letter]
--

This is not the only instance of the uncertainty of all things here.
Our dear friends Samuel and Jane Bettle,
have had the affliction of losing their son Thomas, by a sudden death.
He went on a journey to Easton, Pennsylvania, hoping it might benefit his health.
He was staying there with his cousin Martha Sinton and her family.
After tea on Second-day evening, he walked out into the yard,
and was soon found there entirely dead.
The afflicted parents have this alleviation to their sufferings,
that for some time Thomas has appeared more seriously disposed.
At the house at the time of the funeral, and in the grave-yard,
much quietness and solemnity were felt.
His widow appears overwhelmed with affliction.
But we may hope that our Heavenly Parent,
who has promised to be a father to the fatherless, and a husband to the widow,
will care for her and her babes.
In her late husband`'s parents she will find tender and sympathizing friends.

--

+++[+++After attending Concord Quarterly Meeting,
Thomas Kite proceeded to fulfill his prospect of visiting the subordinate meetings, etc.]

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his Wife.

[.signed-section-context-open]
Middletown, Eighth month 25th, 1831.

I was particularly affected with the account of dear Abigail Folwell`'s sudden removal;
at a time when we are anxiously looking forward for a succession of
testimony-bearers from among our dedicated youth,
to have one of the most exemplary of that class called away, is no small trial.
Yet we dare not murmur.
The Lord is perfect in wisdom as well as goodness,
and can raise up others to bear his testimonies,
and bless to survivors these stripping dispensations.

With regard to dear Abigail, the testimony lives in my heart,
"`There is now no condemnation to them that are in Christ Jesus.`"
She is safe,
where no storms or tempests can ever assail her,--
landed on the peaceful shores of immortality,
and permitted to mingle with the ransomed of the Lord,
returned to heavenly Zion with everlasting joy upon their heads.

My prospect is to attend Middletown Meeting today, Darby tomorrow,
and return home in the afternoon; remain there until Seventh-day evening,
or First-day morning; then attend Springfield Meeting on First-day.
Your expressions of affectionate sympathy are very grateful to me.
May we ever be preserved in a disposition to "`bear one another`'s burdens,
and so fulfill the law of Christ.`"

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to Thomas Kite, Jr.

[.signed-section-context-open]
Philadelphia, Tenth month 29th, 1831.

[.salutation]
Dear Son:

As usual, I feel anxious you should be diligent in your studies;
but far more I wish your conduct may be such as to gain your teacher`'s esteem.
Do not be light or trifling, but remember your Creator in the days of your youth.
Remember Him to fear Him, to love Him.
It is those only who are truly religious,--that is,
who fear and love God,--who are truly happy in this world,
and have a hope of being happy in the world to come.
Oh! my dear son,
I feel ardently desirous that you may be of the
number of those who follow the Lord Jesus Christ,
and are his faithful disciples.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To the Same

[.signed-section-context-open]
Twelfth month 27th

Citizen, Stephen Girard, died yesterday.
His wealth could not save him from the common lot.
Great curiosity, is no doubt, felt, to know how he has left his immense wealth.
A few days will probably disclose the secret.

My dear son, be attentive to your learning,
and circumspect in all things in your conduct,
that so your affectionate mother and myself may have comfort in you;
for it is written in the good Book, '`A wise son makes a glad father;
but a foolish son is the heaviness of his mother.`'

--

+++[+++On the 29th of Twelfth month,
he obtained a minute of his Monthly Meeting to visit the
families of Friends composing Radnor Monthly Meeting.
This service he performed during the First and Second months, 1832,
to the peace of his own mind, and "`much to the satisfaction of that meeting.`"

A concern having arisen in the Yearly Meeting of 1832,
respecting the situation of its subordinate meetings,
a committee was appointed to visit them, as way might open, to feel with and for them,
and as ability might be afforded, to offer counsel and encouragement.
The committee consisted of the following Friends: Samuel Bettle, Joseph Whitall,
Thomas Wistar, Thomas Kite, Thomas Stewardson, John Comfort, Ezra Comfort, Thomas Evans,
Benjamin Cooper, Hinchman Haines, William Evans, Samuel Craft, David Cope,
Robert Scotton, Ruth Ely, Abigail Barker, Elizabeth Pitfield, Mary Allinson, Hannah Paul,
Jane Bettle, Regina Shober, Martha Jefferis, Hannah Gibbons,
Mercy Ellis and Hannah Warrington, Jr.

On Sixth-day, the 4th of Fifth month, Thomas Kite was bowed in awful, vocal supplication.
The matter continuing with him, he afterwards believed it right to reduce it to writing.]

[.embedded-content-document.prayer]
--

[.letter-heading]
Substance of a Prayer,

[.signed-section-context-open]
Fifth month 4th, 1832.

It is, O Lord! under a sense that none of us can keep his own soul alive,
that no man can redeem his brother, or give to you a ransom for his soul;
that though Noah, Job or Daniel stood before you,
they could save neither son nor daughter;
it is under a sense of the entire inability of man, that we are engaged to look unto you,
the Fountain of everlasting life, and to ask of you that you will minister,
by your abiding Word, to the various states now assembled before you.
Grant us, O Lord,
a fresh visitation of your mercy--the influence
of the law of the Spirit of Life in Christ Jesus,
which alone sets free from the law of sin and death--that thus
those who have been halting between two opinions,
may be convinced that you, the God who answers by fire, are the true God,
worthy to be worshipped, served and obeyed,
and may be strengthened to cast their idols to the moles and to the bats;
and those who have once known your power, but who have settled upon their lees,
may be stirred up and animated to give all diligence to
lay up a good foundation against the time to come,
that they may lay hold on eternal life.

May those who are endeavouring to bear the ark of your testimony upon their shoulders,
often in great weakness--their hands hanging down, and their knees smiting together,
be strengthened with might by your Spirit in their inner man,
and afresh feel the consoling assurance that you are God, and changes not,
therefore the sons of Jacob are not consumed.
Oh!
Heavenly Father! may the children be gathered! allured from the world,
and turned unto you, who only can preserve through the slippery paths of youth.
By submitting to your power, may each of them be enabled to say, the Lord is my shepherd,
therefore I shall not want.
We are afresh humbled into a sense of our own unworthiness.

But we remember your love and mercy,
which gave your Son to be a propitiation for our sins.
We remember that He, our glorified Redeemer, ever stands in your presence,
to make intercession for us.
For his sake we ask you to heal our backslidings, to blot out our transgressions,
to pardon our iniquities, and through the renewed extendings of your Holy Spirit,
to prepare our minds, not only to worship you in your courts below, but also,
O Lord! for your heavenly kingdom,
that at length we may join those who have gone before--your ransomed
and redeemed ones--in ascribing unto you salvation and praise!
uniting together in that worship which will know no end.

--

+++[+++Thomas Kite made a few notes of the proceedings
of that branch of the Yearly Meeting`'s committee,
of which he was one; consisting of Joseph Whitall, Thomas Kite, Thomas Stewardson,
Thomas Wistar, Hannah Warrington, Jr., Martha Jefferis and Hannah Paul.
Portions of his memoranda follow:]

[.small-break]
'''

Fifth month 9th. Attended the Select Quarterly Meeting of Abington.
Beside the committee and Hannah C. Backhouse, eight men and thirteen women were present.
Some evidence of a right concern among them.
The mourners were encouraged.

10th. Quarterly.
Meeting.
About 90 men and boys.
The business was harmoniously attended to; and it was thought to be a solid opportunity.
The young people behaved with great solidity.

28th. Were at Abington Monthly Meeting.
Fourteen or fifteen of their own members attended.
Beside the Yearly Meeting`'s committee,
a committee from the Quarterly Meeting on the subject of education, was present.
There is great weakness and lack of skill in the discipline;
yet some hoverings of the wing of Ancient Goodness were prevalent.

29th. Frankford Monthly Meeting.
About 30 members, exclusive of strangers.
A lively concern for the maintenance of order,
and a more judicious exercise of the discipline appeared.
The meeting was favoured.

30th. Select Quarterly Meeting of Bucks.
The meeting small, several of the members being absent.
+++[+++Christopher Healy was in England]. Towards the
close a little revival of light and intelligence;
and Friends were encouraged to submit to baptisms
necessary to qualify for service in the church.

31st. Quarterly Meeting for business.
About 90 persons present.
Great openness toward the committee appeared, and ability to labour was vouchsafed.
The meeting was satisfactory.

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his Wife.

[.signed-section-context-open]
Whitemarsh, Sixth month 1st, 1832.

[.salutation]
My Dear,

We attended +++[+++Frankford]
Monthly Meeting at Gerroantown on Third-day; dined at Thomas Megargee`'s;
and had Asa Walmesly for a pilot to Byberry.
We, that is Joseph Whitall and myself, with the two women Friends +++[+++Hannah Warrington,
Jr., and Hannah Paul], lodged at his house.
We four have been together at every place,
and my two name-sakes have been accommodated elsewhere.
On Fourth-day we attended Bucks Quarterly Meeting of Ministers and Elders,
where sister Martha met us;
with whom we went to Moses Comfort Jr.`'s. The
next day was the Quarterly Meeting of business.
Sister M. went home with Mercy Hulme;^
footnote:[An Elder]
we went to James Moon`'s to dine and lodge.
Today we have had a wearisome journey to Ezra Comfort`'s,
where we now are waiting to attend Gwynedd Monthly Meeting tomorrow.
We have been favoured to get along in much unity;
and Friends have manifested an agreeable openness towards the committee.

--

Sixth month 2nd. Gwynedd Monthly Meeting.
About twenty of their own members.
A few concerned Friends; but as a meeting, in a weak state.

4th. Buckingham Monthly Meeting.
About thirty-three members present.
A larger number of concerned Friends.
Yet a danger manifest in respect to taking an active part in the discipline,
without taking up the cross, or being rightly engaged to set a consistent example.

5th. Wrightstown.
Nine or ten members present.
Much weakness.
The mourners had a word of consolation offered them.

6th. Middletown Monthly Meeting.
Thirteen or fourteen.
A concerned remnant present.
Perhaps the most comfortable covering of solemnity we have yet experienced.

7th. Falls Monthly Meeting.
Nearly fifty present.
An honestly concerned number among them, but rather deficient in skill.
Judicious fathers lacking.
A prospect among the youth somewhat hopeful.

[.small-break]
'''

+++[+++After the return of the committee from this visit,
they were ready for a trip to Stroudsburg and Friendsville,
the most distant meeting of Abington Quarterly Meeting.
They left Philadelphia on Third-day, the of Seventh month.
It was a serious parting.
The Asiatic, or spasmodic cholera had just broken out in New York,
and from the rapidity of its progress, no doubt could be reasonably entertained,
but that it #would reach Philadelphia before their return.
No account of this visit has been found among Thomas Kite`'s papers.
It was, however, performed to their satisfaction.

During the prevalence of the cholera in Philadelphia, Thomas Kite was in the city,
except a few excursions to meetings in the neighbourhood.]

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his son Thomas.

[.signed-section-context-open]
Philadelphia, Ninth month 4th, 1832.

[.salutation]
My Dear Son:

It is a considerable time since I
manifested in this way my interest in your welfare,
which, notwithstanding, remains unabated.
While my principal wish for my children is, that they may become the Lord`'s children,
which can only be their happy experience by living in his fear,
I am not indifferent about their welfare and prosperity in the world.
Hence I desire that you, in particular, may apply yourself diligently to your studies,
that your talents may be so improved,
that you may be qualified for whatever business it may be found expedient to put you to.
The habit of industrious application formed in early life, is of incalculable advantage;
therefore, strive to form and to preserve this habit.
Whatever your hands find to do, do it with all your might.
To be lazy is a reproachful character, and yet some boys deserve it.
Your mother and I went to Burlington Quarterly Meeting last week.
The cholera has nearly disappeared.

--

+++[+++On Sixth-day, Eighth month 31st, 1832,
William Kite went to spend a few days in the neighbourhood of Medford,
where he had taught school.
The day he left home, his father addressed this letter to him:]

[.embedded-content-document.letter]
--

[.salutation]
Dear Son:

Whether you go abroad or stay at home,
my thoughts are often turned towards you,
with much solicitude for your present and everlasting happiness.
With your conduct towards me as an obedient son, I am fully satisfied.
What I wish is, that you may not rest short of the experience of regeneration;
that you may be in truth a follower of Jesus Christ,
and may know redemption through his blood, the forgiveness of sins,
the sanctification of your nature, fellowship with the Father and with the Son,
and a consequent qualification to maintain a
lively exercise of spirit in public assemblies,
and private retirement.
Thus will you know, not only the restraints of religion, but also the comforts of it;
and as you are engaged to wait for heavenly direction, you will, I trust,
receive it on all needful occasions,
so as to be conducted safely through the wilderness of this world,
and receive at last a peaceful settlement in the promised land.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his son Thomas.

[.signed-section-context-open]
Philadelphia, Tenth month 20th, 1832.

[.salutation]
Dear Son:

I expect to go to Baltimore Yearly Meeting.
You, have heard, I presume, of the death of Edward Bettle.
He had been a dutiful son to his father, and being of good talents,
well improved by education, he was not only useful in civil and religious society,
but had become the companion and counsellor of his father,
who now mourns the loss of a valuable son.
Yet he must have the consolation of knowing that he was a religious man,
a follower of the Lord Jesus Christ, and, therefore,
that there is ground to hope he is now in a happy state,
in which he will be forever with the Lord.

While my desires are undoubtedly strong for your mental improvement,
for the proper and diligent cultivation of your natural powers,
I yet more earnestly desire that you may become my friend and counsellor.
May you inherit the blessing one of old enjoyed,
of whom the Almighty thus speaks in the Holy Scriptures:
"`My covenant was with him of life and peace,
and I gave it him for the fear wherewith he feared me, and was afraid before my name.`"
Then, whether you live to old age, or your life should terminate in youth,
all will be well;
your example will be salutary to survivors,--your prospects for eternity will be bright.
Ah! my son,
is not the hope of everlasting happiness a glorious hope! sufficient to animate and
encourage us under the difficulties we must expect to meet with in the present life.

--

+++[+++Thomas Kite having a minute of the unity of his Monthly Meeting,
attended Baltimore Yearly Meeting; his wife bore him company.
The meeting was smaller than usual,
owing to the fears many were in respecting the cholera.

1833+++.+++ Philadelphia Yearly Meeting`'s Committee continued its labours,
but Thomas Kite has left no account of its visits from place to place.

Edith Kite, having accompanied Gulielma Widdifield to New England Yearly Meeting,
her husband thus wrote to her:]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Philadelphia, Sixth month 21st, 1833.

[.salutation]
My Love:

I was glad to receive your letter this morning, and to hear of your welfare.
It was pleasant to find you had met with so many of my dear friends.
I sincerely desire your visit may prove not only agreeable, but profitable,
so that you may bring home a little good to me, for I feel, and have long felt,
very poor, indeed.
Yet I do not mention it in a murmuring spirit.
I desire patiently to wait, and quietly to hope, for the arisings of Divine Life.
And oh! that neither you nor I may rest satisfied without this experience,
which will sanctify the comfort we have in each other,
and enable us to bear up under whatever portion of sorrow may be in
reserve for us in our future steppings through this vale of tears.

Give my love to our dear friend Jacob Green.
I know not how to think of his leaving this country without seeing him again.
Tell him our Monthly Meetings are next week, and if he comes here on Second-day with you,
he may have the opportunity of attending them,
of taking leave of many who feel closely bound to him in the fellowship of the gospel,
and may be back to New York in time for the ship.

--

+++[+++In the Tenth month of this year,
the Monthly Meeting of Philadelphia set Thomas Kite at liberty
to visit the meetings of Salem Quarterly Meeting,
New Jersey.
This service he performed in the Eleventh month.

In the Twelfth month, Edith Jefferis was taken ill at the house of her uncle,
Thomas Kite, and was for a long period hardly expected to live.
She, however, gradually recovered during the spring of 1834,
and was enabled to go to the residence of her mother, near West Chester,
soon after the Yearly Meeting.
An interesting account of this illness will be found in a memoir, published of her life.

At an adjournment of Philadelphia Monthly Meeting, held Fifth month 8th, 1834,
Thomas Kite received a minute "`to pay a religious visit to the
meetings composing Shrewsbury and Eahway Quarterly Meeting,
and also a few meetings within the limits of
Burlington and Haddonfield Quarterly Meetings,
particularly those near the sea shore.`"
Soon after the Monthly Meeting, he started to fulfill this prospect.

His first meeting was at Plainfield, his second at Eahway;
after which he proceeded to Shrewsbury,
where the Quarterly Meeting for business was held,
on the 15th. On that day he addressed a letter to his invalid son Joshua,
which contained the following paragraph to his wife:]

[.embedded-content-document.letter]
--

[.salutation]
My Dear:

I never remember parting with you with more
tender emotions of regard and affection.
I much desire we may both live so near the Heavenly Fountain,
as to experience an increase of that gospel fellowship which, I trust,
we have each known something of.
I feel my own weakness, and desire your secret sympathy and prayers,
that I may be preserved in the line of duty; and when at liberty to return.
I shall be glad again to be favoured with your company.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Susanna, then at East Bradford.

[.signed-section-context-open]
Philadelphia, Fifth month 24th, 1834.

I returned on Fifth-day, before meeting.
My route was through New Hope, Somersville, and to Plainfield,
which was the first meeting; then to Rahway;
afterwards through New Brunswick to Shrewsbury, where I attended the Quarterly Meeting.
From there through Squankum to Barnegat, Tuckerton, Galloway and Egg Harbor,
which was the last meeting.

At Plainfield I climbed to the top of a mountain,
and had a magnificent view of an extensive landscape, including New York in the distance.
The country through which I travelled from New Brunswick to Shrewsbury is mostly dreary.
Heavy sand and pine forests, occasionally interspersed with poor farms.
Shrewsbury is a beautiful village, and Margaret Parker, late Allinson,
seems quite at home, in a pleasant house, with a kind husband.
+++[+++The house]
is surrounded with beautiful fields and trees.
The Quarterly Meeting was small, and no young Friends belonging to it dress plainly.
A lamentable case! which prompts a sigh,
in considering where the standard-bearers of a
succeeding generation are to be looked for.
Oh! how fervently I wish that my children may be of the
number of the few who are willing to bear the cross,
and to be thoroughly crucified to the world.

From Shrewsbury to Barnegat is a poor country; yet the various rivers,
opening to the ocean, and numerous birds, diversified our ride.
From there to Tuckerton the country appears better.
The meeting at Tuckerton being on a First-day, was large,
and some of the young people belonging to it looked like Friends.
I thought the good Master was near to bless us.

We left our chair and horse near this place, and took passage by water to Leed`'s Point.
The meeting is very small, yet contains some concerned friends.

--

+++[+++William Kite had been in weak health for many months,
and having gone into Chester County for the purpose of recruiting his energies,
his father wrote to him:]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Philadelphia, Sixth month 18th, 1834.

[.salutation]
Dear Son:

I was in hopes you would have written,
to let us know how the country agrees with you.
I feel a strong desire, not only for the restoration of your health,
if it please our Heavenly Father to permit it, but more so for your spiritual strength;
that you may be enabled to shake yourself from all hindering things,
and press toward the mark for the prize of the heavenly calling.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Rebecca.

[.signed-section-context-open]
Philadelphia, Eighth month 27th, 1834.

Hannah C. Backhouse, we suppose, met Jonathan at Burlington Quarterly Meeting,
held yesterday.
A number of citizens went up,
principally attracted by the hope of hearing Stephen
Grellett give an account of his European journey.
Farewell!
May this retirement from business be blessed to you;
and a renewal of desire and prayer be felt,
for more entire dedication and conformity to the Divine Will!

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Susanna.

[.signed-section-context-open]
Philadelphia, Ninth month 20th, 1834.

Our dear young friend, Beulah Maule, was buried on Second-day last.
Though long in declining health, and her complaint of a pulmonary character,
a bilious fever was at last the instrument of
her release from the conflicts of mortality.
I was at the funeral, and dined with the relatives.
A comfortable feeling predominated in the assurance
that she was one of our Saviour`'s adopted lambs,
whom He has gathered to the heavenly sheepfold.

Dr. Porter, our old friend, has also deceased.
Some of us attended the funeral yesterday.
Thus old and young are passing away,
admonishing all ages to be ready when our Lord shall
call upon us to give an account of our stewardship.
May you, and I, dear child, increase in devotion to our Lord and Master,
submitting to the purifying operations of his holy hand, until we are prepared,
through his unmerited mercy, not having spot, or wrinkle, or any such thing,
to join the company of his redeemed.

--

+++[+++On Fifth-day, the 6th of Eleventh month,
Thomas Kite attended the marriage of James R. Greeves and Abigail Sharpless, his niece;
and on the following Second-day, with his wife, Rachel Bartram^
footnote:[An overseer of Northern District Monthly Meeting.]
and Israel W. Morris,--they being under appointment of
Philadelphia Quarterly Meeting--started for Muncy.
In allusion to this journey, he wrote:
"`It will require in all of us much self-reduction, and humble reliance on Divine aid,
to get through with it to profit.`"

Being in New Bedford on business in the Tenth month, he thus wrote to his wife:]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
New Bedford, Tenth month 14th, 1834.

I yesterday rode out a few miles into the country to see our friend Sarah Tucker.^
footnote:[Of this visit, Sarah Tucker`'s Journal says,
"`We had a sweet visit yesterday from dear Thomas Kite, of Philadelphia; it was, indeed,
comforting and reviving to my drooping mind.`"
Page 148.]
Her health is very delicate: but she appears to be alive in the Truth.
Her husband seems a valuable, solid Friend.
I feel inclined to go to Fall River Week-day Meeting on Fourth-day,
and so on to Providence; visit, once more, my aged friend, Moses Brown,
and return here on Sixth or Seventh-day.

On First-day afternoon, Thomas Arnott attended this meeting,
and was to have a meeting yesterday at an adjacent village called Padan aram.
The meeting here is not a small one.
I suppose from 250 to 300 persons attended on First-day, of whom, I understood,
a number were not members.
They have a large and convenient brick meeting-house.
The whole town is so changed,
it is difficult to recognize in it the New Bedford I once before saw.
It is now a beautiful place,
many very splendid mansions adorning the higher parts of the town,
Great wealth has produced its usual effect, as regards luxury and extravagance, though,
as yet, it is an industrious community which inhabits it.
One house is now erecting which, it is supposed, will cost $70,000,
and there are many which have cost a large proportion of that sum.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his Niece Edith Jefferis.

[.signed-section-context-open]
Philadelphia, Twelfth month 21st, 1834.

I am not very partial to letter-writing, but your communication, my dear cousin,
seemed to call for some acknowledgement, and therefore I have taken up the pen.
I needed not such a remembrance as your letter
to awaken sympathetic feelings with yourself,
your dear mother and sister.
Your valued parent can adopt the language of David Barclay, the father of the Apologist,
"`The perfect discovery of the Dayspring from on high,
how great a blessing has it been to me, and to my family.`"
Although her trials have been many, and she may yet have some bitter cups to drink of,
she knows in whom she has believed; she yet feels the gracious Shepherd to be near,
and his power and love, as felt in the day of early visitation, is still her consolation.
To her I have no doubt, notwithstanding her bereavement,
the declaration will apply "`Your Maker is your husband, the Lord of Hosts is his name.`"
May she be strengthened then to lean on Him, and commit, not only her own soul,
and all her concerns, spiritual and temporal, but her children also,
to his holy care and keeping.

And you, dear cousin, have, through unutterable mercy,
experienced the operation of that living Word, by which we are born again,
and in the experience of the child`'s state, a very precious state,
as a new-born babe you have desired the sincere
milk of the Word that you might grow thereby.
Often in secret, in days that are past, have your desires been gratified,
and you sustained and nourished.
But if we experience a growth, we shall in the Heavenly Parent`'s time,
know the weaning state; and sometimes, as we advance, a state of fasting;
which is all in wisdom, to keep us sensible of our dependence on the Good Shepherd,
who takes his lambs, carries them in his bosom,
and feeds them with the food convenient for them--of which He is the judge.

Now, as these operations are often painful, the weanings and the fastings,
it is important that the child should neither murmur,
nor look out for forbidden gratifications, which the enemy will not fail to present,
in one shape or another, and sometimes he may in degree take the mind captive,
when the holy watch is not rightly maintained.
Yet the reproofs of instruction will follow; and as the child bows under the rod,
reconciliation and forgiveness will be known.
Thus led along and instructed,
the knowledge of its own weakness keeps pace with its
discoveries where strength is to be obtained,
and gradually the young man`'s state is obtained,
who is strong because the Word of God abides in him,
and because he has in a good degree overcome the wicked one.
And now the Lord expects, in his own way, and in his own time,
his children to labour for Him--to endure hardness as
good soldiers--not to be ashamed of the cross;
for they that are with the Lamb, are called, and chosen, and faithful.
I feel desirous, dear Edith, that you may become of this dedicated number,
so that whether few or many days are allotted you,
or whether your prospects as to this world be adverse or prosperous,
you may stand for the cause of the holy Redeemer in your generation,
and at length be permitted to join the innumerable multitude
whose robes are made white in the blood of the Lamb!
Salute in my name your dear sister Ann: tell her to keep near the Truth in her own heart,
and to choose the friends of Truth for her friends.
I know that in faithfully bearing the cross she will meet with many mortifications;
but may she be willing to confess the Lord Jesus in life and conduct,
and then these mortifications will prove blessings;
and she will be strengthened not only to be a comfort to her exercised parent,
who can have no greater joy than to see her children walking in the Truth,
but she will also be enabled to unite with you,
so that you can bear one another`'s burdens, and so fulfill the law of Christ.
And above all she will experience that peace which is
the portion of the followers of Jesus Christ.

--
