== Chapter X.

[.chapter-synopsis]
* 1835.
* Edith Jefferis`' appearance in the ministry
* Death of Thomas Kite`'s son Joshua
* Marriage of Aaron Sharpless to Susanna Kite.

+++[+++In the First month, 1835, with the unity of his Monthly Meeting,
Thomas Kite visited the meetings constituting
Burlington and Haddonfield Quarterly Meetings,
except the few on the sea coast which he had so recently attended.
The journey was performed during the continuance of a very remarkably severe frost.]

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Rebecca.

[.signed-section-context-open]
Philadelphia, Second month 20th, 1835.

You will see in tomorrow`'s "`Friend`" an obituary notice of Lydia S. Rogers;
you may easily guess from whose pen.
Much more might have been said with truth;
but perhaps what is given will suffice to give evidence
that she is added to the "`cloud of witnesses`" of the
effect of the Gospel in preparing for the close of life.
Her last expressions I think peculiarly striking.^
footnote:[See [.book-title]#Youthful Piety#, p. 197, 1st ed+++.+++; 229, 2nd ed+++.+++,
for an account of her by Thomas Kite.]

Since your absence I have thought of you with earnest desires,
that nothing may turn you aside from attention to the one thing needful.
I want you to live not unto yourself, but unto your God and Saviour.
I want you to watch unto prayer; and taking no mortal for your standard,
aspire after purity of heart and dedication of life.
That our Society has need of faithful labourers is very evident.
Oh, that the visited children, may keep under the forming hand of the heavenly Potter,
and be made into vessels for his use,
that his power may be made manifest in the faithfulness
of those who are now coming on the stage of action;
and that to our poor, but still highly favoured Society, the language may be addressed,
"`Arise, shine, for your light is come, and the glory of the Lord is risen upon you.`"

Love to dear aunt Martha and the girls.
I hear cousin Ann is coming with you; she will be welcome to us.
Don`'t forget to mention me in affectionate terms to cousin T. +++[+++Tamasine Morris]
and her companion.
I hope they will set out right, by giving religion the first place.
The things of the world will prosper better by this means with them, I am well assured.

--

+++[+++Having received from his sister-in-law, Martha Jefferis,
information that her daughter Edith had appeared
in a public meeting in the line of the ministry,
Thomas Kite thus wrote to her.]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Philadelphia, Third month 7th, 1835.

[.salutation]
Dear Sister:

Your letter of the 22nd of last month was very acceptable to us,
and was the means of renewedly quickening in our minds that sympathy which those,
who are in measure baptized by one spirit into one body,
are at times favoured to experience,
and by which they become as epistles written in each other`'s hearts.
Such varied and important circumstances as have of late happened in your domestic circle,
have no doubt called into action all that is capable of feeling within you.
Dear sister, may you not forget the privilege of the believer,
but endeavour to cast your burden upon the holy High Priest;
touched with the feeling of our infirmities, and commend yourself,
your children and all your concerns, to his Father and your Father,
to his God and your God.
It is always interesting to those who have themselves passed through the
exercises attendant on coming forth as soldiers in the Lamb`'s Army,
to be informed that any are publicly manifesting their attachment to his glorious cause.

They know by experience the hearts of these--their fears,
anxieties and baptisms of spirit.
This interest is of course heightened in the case mentioned in your letter,
by strong natural affection, by long and intimate acquaintance,
and relationship almost paternal.
I need not say how much I have felt,
nor that my desires are strong for dear Edith`'s preservation,
and that in simplicity and godly sincerity she may
follow in the clear unfoldings of the Master`'s will.
If the work be of Him, He will own it, by the incomes of peace in her own breast,
and by opening the hearts of his children to receive her testimony.
But exercises she must expect to meet with; they are the lot of all.
She must learn to endure hardness as a good soldier of Jesus Christ.
She must know how to be abased, as well as how to abound.
But if the Gospel has its tribulations, it has also its consolations;
and may no unfaithfulness on her part deprive my dear
cousin of access to that "`pure river of water of life,
clear as crystal,`" which is given no less for refreshment than for purification.

Much depends, I have thought, dear sister, in the present state of the church,
on our all, younger and elder, keeping our places.
Though we may seem to be individually of little account, yet in a firm, united exercise,
there is strength; and there is a call for all who feel for the cause of Zion,
to stand in their respective allotments, labouring as fresh ability is given,
for the removal of wrong things,
for strengthening the things which remain which are ready to die,
and for exalting the standard of Truth.
For Zion`'s sake not holding their peace,
until the righteousness thereof go forth as brightness,
and the salvation thereof as a lamp that burns.

Dear cousin Ann has been pleasantly with us.
I cannot but think her improving;
and many times have I wished for her that her intelligent mind,
her quick and lively abilities, were all sanctified and made fit for the Master`'s use.
Though nature may be reluctant to yield, when once willingly submitted to, she will find,
as many have found to their humble admiration,
that "`his yoke is easy and his burden light.`"

--

+++[+++In the Sixth month, 1835, Thomas Kite attended New England Yearly Meeting.
It was a deeply proving prospect, for his son Joshua was very ill,
yet believing that his Master called him there,
and having the consent and unity of his Meeting in the concern, he gave up in submission.
It was a trying meeting;
some of the principles of Isaac Crewdson^
footnote:[Isaac Crewdson was the author of __The Beacon__,
a booklet published at this time by a member of the society,
which strongly criticized and attempted to undermine
several of the fundamental principles and practices
of the Society of Friends.
In a supposed attempt to avoid the errors promulgated
by Elias Hicks and his followers, Crewdson took aim at the
long held belief in the light of Christ inwardly revealed,
calling it a "`delusive notion,`" and denying any true
knowledge of God, or of His salvation, except through
the Scriptures.--F.L.P.]
had found
advocates within the borders of that Yearly Meeting,
and their spirits were to be felt.

On one of the days of the Yearly Meeting an individual, standing high with some Friends,
commenced a regular attack upon Philadelphia Yearly Meeting,
and ended by proposing the discontinuing any correspondence with it.

Thomas Kite believed it his duty to reply to the charges;
confuting one after another in the order in which they had been made.
Elisha Bates was present,
and active in endeavouring by his ministry to uphold
the unsound sentiments he had imbibed in England,
or which having been imbibed before, received there nourishment and strength.^
footnote:[Elisha Bates had formerly been a minister
in unity with Friends, but, through unwatchfulness,
joined with some who openly repudiated many of the
fundamental principles of the society, and was
eventually disowned.--F.L.P.]
Hearing more unfavourable accounts respecting the health of his son,
Thomas Kite hurried home as fast as was practicable.
The poor sufferer was still living when his father returned.]

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to Nathan Sharpless and Wife.

[.signed-section-context-open]
Philadelphia, Sixth month 24th, 1835.

[.salutation]
Dear Brother and Sister:

Our poor sufferer has been released, and rather unexpectedly,
at last.
He ceased to breathe seventeen minutes past 12 +++[+++this day]. It
is cause of thankfulness that I was permitted to see him,
and be present at his departure.
I reached home on Seventh-day afternoon.
The Yearly Meeting closed with one sitting on Sixth-day.

--

[.embedded-content-document.letter]
--

[.letter-heading]
J+++.+++ W. to Thomas Kite.

[.signed-section-context-open]
Hopkinton, Seventh month 20th, 1835.

You are not without some in New England, my dear friend,
to sympathize with you and family in the loss of your dear son, whose sickness did,
undoubtedly, make your absence while with us, very trying both to you and them.
I hope an assurance of his preparation for such an event, has been witnessed,
and proved a healing balm to his bereaved and afflicted relatives.
I hope also you will not be induced to repine
that you were so much away during his sickness,
for many of us were truly glad of your company and help at our late Annual Meeting.
A confirmation was not lacking,
that it was in the ordering of Wisdom that you were with us at so trying a time,
when mourning and secret suffering was so prevalently our lot.
At times the hour and power of darkness was permitted
to overshadow the feast of our solemnities,
and so to becloud many innocent minds,
that good discernment seemed lacking to distinguish between that which is,
and that which is not bread.
Nevertheless,
there were a few seasons in which there was truly a
little living bread broken and distributed.
How lamentable it was to see the attempts--I believe as regards some,
successful attempts--to take this living bread out of the children`'s mouths,
and to offer a fair show of that which is not bread, and I fear contained poison.
Please accept my tender love, my dear friend, for yourself, your wife and children.

--

[.embedded-content-document.testimony]
--

[.letter-heading]
Thomas Kite`'s testimony concerning his son Joshua.

In the Sixth month, 1835, my second son, Joshua, departed this life,
being in the 19th year of his age.
He had for a number of years endured much bodily suffering,
which I humbly trust was sanctified to him,
he being enabled to bear it with a good degree of patience.
In his last illness his diffident disposition prevented his saying much,
but the little of a serious nature he did express was very satisfactory;
and I have a consoling hope,
that his spirit has been permitted to join the
company seen by John in the opening of light,
who had come out of much tribulation,
and washed their robes and made them white in the blood of the Lamb.

--

+++[+++In the Ninth month, 1835, Susanna Kite, with the approbation of her parents,
was united in marriage to Aaron Sharpless.
Her home was thenceforward in East Bradford, Chester Co.,
and there the day after the wedding she accompanied her husband,
taking her sister Rebecca with her.]

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Rebecca.

I have seen nothing of Jane, but we all had a piece of wedding cake.
I wish her well; but my expectations of her future comfort are not very sanguine;
yet real religion will be to her, if she keeps under its influence,
as it is to every one who is so wise as to embrace it,
a regulating principle in prosperity, and a balm in affliction.
It has been pleasant to have your dear aunt Martha`'s company.
I went with her to infant school.
She seemed quite interested in the little creatures.
From there we went to see Sarah Gibbons, who is evidently declining.
The ties of nature cling around her heart,
but that Divine power under whose precious influence she evidently abides, can,
in his own time, strengthen her to let go her fondest attachments,
and prepare her to adopt the language, "`Come, Lord Jesus, come quickly,
your servant is ready.`"
Give my kindest, tenderest greeting to your dear sister.
I feel for her more than it is proper to express.
Her lot seems fixed, so far as we can perceive.
I have no doubt she will endeavour to discharge her new duties with Christian propriety;
and I trust she may be the instrument,
not merely of contributing to her husband`'s earthly comfort,
but also of promoting his religious welfare,
and strengthening his resolutions to walk worthy of Him
who has called us to his kingdom and glory.
Such I am sure she may be, if she is daily concerned to seek and to wait for holy help.

And may you, dear child, the child of many prayers,
keep near the Good Hand that visited you in early life,
that the promise of future usefulness may not be blighted, but that abiding in the Vine,
subjected to the power of the Holy Redeemer, you may, in due season,
bring forth fruits to his praise.
Married or single, I greatly desire for my children, that whether they eat or drink,
or whatever they do, they may do all to the glory of God.

--

[.offset]
+++[+++After visiting Susanna at her new home, her father wrote to her:]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Philadelphia, Tenth month 3rd, 1835.

[.salutation]
Dear Susanna:

You may remember I mentioned on Second-day,
that I heard a noise which I apprehended was the blowing up of a powder mill.
It turns out that Dupont`'s powder mill exploded, by which event two men lost their lives.

I find that our amiable cousin, Ezra Jones, has deceased.
He finished his earthly course on Seventh-day last.
He was out in the parlor every day until his last, as I have been informed.
I know nothing of the state of his mind,
excepting that he expected his disease to terminate as it did.
I think he was pious,
and therefore I trust his hope and expectation were placed on his Redeemer,
and that through Him, he found acceptance.
You see, dear, how brief his marriage life has been;
another instance of the uncertainty which attends our prospects of sublunary bliss;
by which we ought to be admonished to remember our Creator,
the design of our being brought into existence, the necessity of living unto Him,
so that we may be preserved, in the enjoyment of his gifts, from forgetting the Giver,
or seeking to have our Heaven here.
We cannot be heirs of two kingdoms.
I can speak the more feelingly, because, surrounded as I am with domestic comforts,
and favoured in my domestic relations,
I find the necessity of close watchfulness to keep my attachment to
created things in subordination to the love of uncreated purity.
I wish this may be your daily prayer to the Fountain of our mercies,
for yourself and your dear partner, that your mutual love may be sanctified,
and prove no hindrance to your journey towards the celestial city.
Our Society, in many places, is in a low state.
The lack of faithfulness to the cause of God is the reason of this.
Though the harvest is great, the field of labour extensive, the labourers are few.
My spirit intercedes for you, my dear children,
that by submission to the Grace which brings salvation
you may be prepared for usefulness in the Church,
that even now you may prefer Jerusalem above your chief joy,
and by acts of daily dedication be preparing more
conspicuously to display your devotion to the cause of Christ,
when the few faithful standard-bearers who yet remain in your
neighbourhood shall have entered their everlasting rest.

--

+++[+++With the approbation of his Monthly Meeting,
Thomas Kite attended Baltimore Yearly Meeting.
On his return he thus wrote to his daughter Susanna:]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Philadelphia, Eleventh month 7th, 1835.

[.salutation]
My Dear Daughter:

Before I set out for Baltimore I
could not make it suit to write to you,
and since my return I have been at a meeting of
one description or another every day until today.
I am now seated to converse a little with my absent child.
I made my home at Baltimore with Hugh Balderston, Samuel Bettle with Joseph King, Jr.,
and Stephen Grellett with Nicholas Popplin, a German Friend, who, like himself,
had formerly been a Roman Catholic.
Though lodging at different houses, we were much together,
and mostly dined and took tea at the same places.
We generally had the company of Hannah Paul, Sarah Hillman and Susan P. Smith,
who put up at the same place with Samuel Bettle.

Notwithstanding in meetings I met with trials of feelings, and inward exercises,
yet between which I had often rich enjoyment in the Society of Friends,
and sometimes our meetings were in degree favoured.
Though the state of things is low, in the general,
yet there are individual cases of dedication to the best of causes,
and a few young people seem under the preparing hand of
the Lord for future usefulness to the Church.
May they be kept humble and teachable,
and thus escape being taken in the snare of the enemy who will
seek to entangle them with the friendship of the world,
which is enmity with God.
Then, through the same Divine Power which raised up our predecessors in the Truth,
some of them may become burning and shining lights.

We have had the company of Joseph and Rebecca Batty, from Friendsville Meeting,
for several days at our house.
The latter is an approved minister, and seems a sweet and amiable friend.
They attended Abington Quarter this week, and have gone homeward.
Do you know that Elizabeth Fell, sister to Edith,
who is now a teacher in our Select School, is making her home with us?

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to Edith Jefferis.

[.signed-section-context-open]
Philadelphia, Eleventh month 21st, 1835.

Understanding that an opportunity will occur this afternoon, my dear Edith,
I feel a freedom to address you, desiring, as I do,
the preservation of all the Lord`'s children,
and more particularly of those who have demonstrated on whose side they are,
by making themselves, in obedience to apprehended duty, spectacles to angels and to men.
These have their natural dispositions, propensities, and peculiarities,
of which the enemy fails not to avail himself,
in endeavouring to withdraw them from that watchful state in which safety is experienced;
and when he has in some degree prevailed over them,
he is very artful in trying to prevent their return to the state in
which the gentle intimations of the Divine Will are witnessed.
Thus are they exercised at times; "`without are fightings,
within are fears`" and not feeling the same access as
at former seasons to the Fountain of living waters,
they are ready to fear that God has forgotten to be gracious.

It is important for such not to forget--I greatly desire for you that
you may not forget--that as a father pities his children,
so the Lord pities them that fear Him;
that He has made a rich provision for us in his dear Son,
the merciful and faithful High Priest; touched with a feeling of all our infirmities;
and that it is his will, if his dear children should at any time miss their way,
that they should return through Him, who is the way, the truth and the life,
our advocate with the Father, and the Propitiation for our sins.

I desire your encouragement, and, that having put your hand to the Gospel plow,
you may not look back, but that, pressing onward,
you may be led in the middle path out of all extremes.
It is a narrow but a safe way.
"`Its walls are salvation, and its gates praise.`"
If deep plungings and strippings should sometimes be your experience,
and the cause be hidden from you, perplex not yourself thereat,
nor open your inward state too freely to any mortal.
The Lord Almighty does all things well.
He has led his devoted servants in this way to
wean them from a dependence on any but himself,
who remains to be the saving strength of his anointed.
Even the dear Master, our example, trod the wine-press alone,
and of the people there was none with Him.
It is the privilege of his disciples, remembering his many gracious promises,
to lay aside every weight and the sin which doth so easily beset,
and to run with patience the race which is set before them, looking unto Jesus.
Let your eye be single unto Him, in heights and in depths, in poverty and in aboundings,
and you will then, in his own time,
witness the lifting up of the light of his countenance.
You will gradually learn to endure hardness as a good soldier
of Jesus Christ--learn clearly to distinguish his voice,
so as to "`preach the preaching that he bids you,`" and
keeping to this in child-like obedience,
the Word of the Lord will have free course and be glorified,
your own soul at times will be as a watered garden,
for "`He that waters shall be watered himself;
and the praise be ascribed where it is due.`"

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Susanna.

[.signed-section-context-open]
Philadelphia, Eleventh month 29th, 1835.

Your certificate was sent to Pennock Passmore by the Westtown stage, yesterday.
I feel an anxious solicitude, at times,
that in the meeting to which that document will join you,
you may be enabled to fill up your place with propriety,
giving evidence of the preference of the dear Master`'s cause to every earthly comfort;
choosing as first in importance the kingdom of Heaven and the righteousness thereof,
and patiently submitting to those humbling, cleansing baptisms of spirit,
which prepare us for the Lord`'s service.

Our respective Monthly Meetings in the city have concluded to
open an evening meeting at Arch Street House.
Many Friends have been desirous of such an opportunity of meeting their brethren
and sisters from all parts of the city in the exercise of social worship,
in the hope that it will strengthen the bond of religious fellowship,
as well as that these occasions may be useful to the younger branches of the Society.
Others have felt fears that they may prove of some disadvantage.
The experiment is to be tried.
May young and old attend them under a reverent sense of the weight
and importance of holding them in the authority and power of Truth,
and then we may humbly hope that through the condescending goodness of a gracious God,
they may tend to his honour, and the comfort and strength of his people.

You were probably aware that Elizabeth C. Mason has been in poor health lately.
She has so far recovered as to attend meeting last Fifth-day.
She went there in obedience to apprehended duty,
kneeled down and appeared vocally in solemn supplication.
You know my friendship for her, and are aware, it is likely,
of my belief that she is a solidly concerned Friend.
You can easily imagine my feelings are deeply interested in desire
for her preservation and encouragement in the path of dedication;
and also, that, seeing the harvest is great, and the labourers few,
the Lord of the harvest may be pleased to send forth more labourers.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Susanna.

[.signed-section-context-open]
Philadelphia, Twelfth month 11th, 1835.

[.salutation]
Dear Daughter:

I have been lately reading the life of James Macintosh,
written by his son.
I am partial to biography, where the character is fairly laid open;
and I think in this instance the author has succeeded well, neither wholly concealing,
nor indecently exposing, his father`'s errors.
James was an eminent political and literary character,
not long since flourishing in England.
First a physician, and afterwards a lawyer,
he filled for a number of years the station of a judge at Bombay.
After his return to England he was mostly in parliament during the remainder of his life.
He produced several important works, among which are a History of Ethical Philosophy,
several volumes of a general history of England,
and a minute account of the Revolution of 1685,
which placed William and Mary on the throne of England.
The last work was posthumous, and unfinished by him,
but has been completed by a very inferior hand.

One of the greatest faults of James Macintosh gently touched on by his son,
was his inordinate fondness for society,
in the indulgence of which propensity his most serious occupations were abandoned.
From an extract from his private Diary, given in the Memoir,
I infer that in younger life he was sensible of
religious impressions of a very tender character.
Such, I suppose, to be at one time or other, a universal experience,
though too often very much effaced in the commerce of the world,
which was probably in a great degree his case.
His last illness was occasioned by inadvertently swallowing a chicken bone.
The progress of his disease, and his closing scene is depicted by his daughter,
who appears from this sketch to have been a religious character,
in an interesting manner.
Serious reflection prevailed in those solemn moments.
Day after day found him more disengaged from interest in political affairs,
and more solicitous as regarded the awful after-scene.
There is ground to hope that his vigorous understanding was
brought to bow in child-like submission to the cross of Christ.

The packet of letters by sister Phebe met with a cordial reception.
We are always glad to hear from our absent one,
and all the details of domestic affairs were welcome.
The aspiration frequently ascends, that amidst these multiplied engagements,
the most important of all concerns may continue
to hold the chief place in your affections;
and that everything else, however proper in its place, may be subordinate.
When the current of our earthly concerns flows smoothly,
and everything is smiling around us, it is difficult to realize the truth,
that days of trial are in reserve for us,
notwithstanding all human experience proclaims it.
No language can set forth adequately the necessity and
advantage of living in the preserving fear of the Lord.
Then may we, if this be our blessed experience,
view all events as ordered by our heavenly Father,
and designed to contribute to our everlasting benefit,
in owning all things to work together for good, and having,
in the greatest afflictions that can befall us,
a sure refuge in those compassions which fail not.
May my beloved child so live in the sight of the Searcher of hearts,
so submit to the sanctifying operations of his Holy Spirit,
that she may always experience his protection, and the language be applicable to her,
"`He shall cover you with his feathers, and under his wings shall you trust;
his truth shall be your shield and buckler.`"

--
