== Chapter XI.

[.chapter-synopsis]
* 1836-1837.
* Death of Mary Yarnall
* Several letters
* Death of Othniel Alsop
* Ohio Yearly Meeting
* James Kite married to Lydia B. Rodman
* Abigail Greeve`'s death.

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Susanna.

[.signed-section-context-open]
Philadelphia, First month 23rd, 1836.

My letter turns out little more than a bulletin of
intelligence concerning our friends`' lack of health.
This may not be without its use in putting us in mind,
what we need often to be reminded of,
the uncertainty of health and other temporal blessings,
and ought to stir up to diligence in endeavouring to
secure an admittance into the house not made with hands,
not one of whose inhabitants can say they are sick.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to Martha Jefferis

[.signed-section-context-open]
Philadelphia, Third month 3rd, 1836.

[.salutation]
Dear Sister:

Uncle Ellis Yarnall has requested me to
give you an account of his most afflicting bereavement,
the removal of aunt Mary,
under circumstances of peculiar trial to the surviving members of their family,
and of solemn admonition to us all.
On Seventh-day morning last, she requested uncle to walk out with her,
intending to call and see two friends, one of whom had been sometime ill.
After going as far as Broad Street,
finding the walking unpleasant in consequence of the snow,
she concluded to return home without accomplishing her visits.
On her way +++[+++back], the near approach of a cart or wagon, somewhat agitated her,
so that she had to stop a minute to recover herself.
On reaching home, she went into cousin Amy`'s room, and sat down near the fire,
appearing fatigued, and mentioned that the air had been too keen for her.
Cousin Sarah handed her camphor, and then went, to see her brother Charles`' wife.

Cousin Amy asked her if she would have an egg beaten up for her; and on her assenting,
went down stairs to prepare it.
On returning, not having been absent more than five minutes,
she found her mother lying on the floor, with her head near the grate,
having fallen from her chair.
The cries of our afflicted cousin soon brought uncle and others into the room,
but life was gone.
It is supposed her death was caused by apoplexy, and that it was instantaneous.
The body was a little burnt about the head and face,
and a small portion of blood issued from the nose.
The alarm having been given, four physicians were soon present,
but their services were not needed.
Uncle seemed wonderfully supported through the trying scene; his daughters,
as might have been supposed, were greatly agitated.
The funeral was on Second-day.
The inclemency of the weather, and the absorbing nature of the event,
prevented invitations being sent into the country.
My wife and I attended the interment.
Yesterday I went to the house of mourning,
and found dear uncle preparing to go to the Week-day Meeting.
I stayed with Sarah and Amy, Benjamin and Charles`' wives, and two women friends.
The minds of our cousins appeared much tranquilized.
Cousin Amy seems favoured to take a just view of the subject.
I trust she will be preserved from sinking under this bereavement,
which the whole family appear to feel very keenly,
and which I ardently desire may be sanctified to them.

I have little room to speak of the interest we feel in your movements,
the sympathy we have in your trials,
the desire we feel that right direction may be vouchsafed,
and the confidence we have that in the path of duty,
"`as your day, so shall your strength be.`"

I might have added, that the sick friend aunt designed to call on,
died just about the same time she did.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Susanna.

[.signed-section-context-open]
Third month 7th.

On Seventh-day evening our neighbour, Griffith Edwards,
departed this life, aged nearly 83 years.
He has long been of a meek and quiet spirit;
and his hopes of future happiness being founded on a humble trust in redeeming mercy,
his family have good grounds of comfort concerning him.
He died of old age, the machine, apparently, worn out.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Rebecca.

[.signed-section-context-open]
Fifth month 14th.

Time but for a short note, just to show the continuance of that interest in your welfare,
and those desires for your establishment in the path of rectitude and peace,
which continually attend me, when my mind is drawn seriously to think of you.
There are many objects of pursuit which seem, in moderation, lawful,
some of which are decidedly agreeable, and add to innocent enjoyment;
but "`one thing is needful.`"
It is so; because if this be not secured, all is lost, and we have lived in vain!
I wish to impress upon your mind the importance of decision,
that the great object in your view may be to
live to the glory of your Creator and Redeemer.
Let this mind be in you which was also in Christ Jesus, who said,
"`My food is to do the will of Him that sent me, and to finish his work.`"
My heart is warmed towards you; and I could add more, but time admonishes me to close.

I have information that Stephen Grellett is also to be at New York Yearly Meeting.
Think of me when +++[+++I am]
there.

--

+++[+++Thomas Kite had been set at liberty by his Monthly Meeting, in the Fourth month,
to attend the Yearly Meeting of New York.]

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Rebecca.

[.signed-section-context-open]
Philadelphia, Fifth month 20th, 1836.

[.salutation]
Dear Rebecca:

I can hardly comply with your request at this time for
"`a long real letter,`" because I expect to take my departure this
morning in the ten o`'clock steamboat for New York,
and have yet some preparatory arrangements to make;
yet my letter shall be "`real,`" so far as to
convey the genuine feelings of a father`'s heart,
with which you are not unacquainted; but having them revived,
"`to stir up the pure mind by way of remembrance,`" may not be unattended with profit,
if you are renewedly led thereby to seek for counsel and
strength to walk worthy of the care of your parents,
and the distinguishing favour of your Heavenly Father.
You have been a child for whom many prayers have been offered,--on
whom much instruction in the way of righteousness has been bestowed;
nor has, I am persuaded, the immediate operation of the Holy Spirit,
"`by which we are sealed to the day of redemption,`" been lacking.
I wish the language of your heart to be,
"`What shall I render to the Lord for all his benefits?`"
I wish you to wait in retirement of spirit for the unfoldings of his will,
and that nothing may prevent from acting in conformity thereto.
You have by this time had sufficient experience to understand the weak points of
your character,--the manner in which the enemy has heretofore prevailed.
This ought to suggest where to set a double watch.
The Christian life is a warfare; the Christian soldier ought to be always armed,
always vigilant, lest Satan get an advantage over us,
for we are not ignorant of his devices.

The state of the Church is often the subject of my meditations, and, I have no doubt,
of yours, also.
We see the inroads made by the spirit of the world;
some of our members going into the earth, others into the air;
the trained servants few,--the veterans removing,--the ark tottering.
Is this a time for those who love the blessed cause to be amusing themselves,
--to be indulging even the amiable instincts of their natures,--cultivating
friendships and partialities,--indulging a refined taste,
and doing their own works, when the Lord has need of them?
There is nothing gloomy or morose in religion.
There is room enough in its paths for all the finest feelings of our nature to operate.
But still let us devote our best to the Great Proprietor of all,
and wait to experience those baptisms of spirit,
which will prepare us in the way designed by Infinite Wisdom to promote the cause
of truth and righteousness,--to manifest our devotion to the cause of Christ.
In this way the blessing of the Highest will rest upon us;
all lawful engagements will be sanctified; we shall answer the end of our creation,
serve the Lord in our generation, and receive "`the end of our faith,
even the salvation of our souls.`"
In haste I bid you farewell, remaining in the bonds, and, I hope I may say,
the fellowship of the Gospel, your affectionate father.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to E. S. F.

[.signed-section-context-open]
Philadelphia, Seventh month 21st, 1836.

[.salutation]
Dear Elizabeth:

Whatever things are honest, whatever things are just,
whatever things are pure, whatever things are lovely, whatever things are of good report:
if there be any virtue, and if there be any praise, think on these things;
and be not satisfied merely with thinking,
but let them be carried out into practice in your life and conduct.

You have, I believe, a love for Truth, a desire to flee from the wrath to come,
and to lay hold on eternal life.
May these desires, and every virtuous inclination, be strengthened.
One hint more: be very choice of your associates.
Admit none to your confidence, who are not, in your judgment,
aiming at consistency of life in the Christian calling.
Be courteous to all, intimate with few.
In conclusion, "`I commend you to God, and to the Word of his Grace,
which is able to build you up,
and give you an inheritance among those who are sanctified.`"

--

+++[+++Thomas Kite left Philadelphia on Second-day, the 22nd of Eighth month,
with a minute of his Monthly Meeting, to attend Ohio Yearly Meeting.
James R. Greeves was his companion on this journey.]

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Rebecca.

[.signed-section-context-open]
Blair`'s Gap, on the top of the Alleghany Mountains, Eighth month 24th, 1836.

[.salutation]
Dear Daughter:

Cousin James and I entered the car at Oakland Hotel about 11 o`'clock,
on Second-day,
and reached Columbia a little after 3 p. m. We were soon on
board the canal boat "`Virginia,`" small in dimensions,
but very comfortable; and passing up the canal, proceeded by Harrisburg,
which we did not reach till after dark.
In the morning we found ourselves five miles up the Juniata.
On Third-day we passed Newport, Mifflin, Lewistown, etc.
Night closed upon us near Waynesburg.
This morning, on rising, we found ourselves five miles west of Huntingdon.
We reached Hollidaysburg between 2 and 3 p. m., and ascended the Portage Railroad,
by horse-power and stationary engines, reaching this place by half-past 5,
where we propose sleeping, and descending the mountain at an early hour.
Our accommodations have been comfortable, and the`' two companies pretty well,
myself excepted.
+++[+++The other company contained Sarah Emlen, Esther Levis, Jesse J. Maris,
Rebecca S. Leeds.]
Cousin J. has been much gratified, with fine prospects.
R+++.+++ S. L. the same;
nor have the rest of us been indifferent spectators of the Creator`'s works,
nor of the efforts of man.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his Wife.

[.signed-section-context-open]
At Dr. Parker`'s, near Mt. Pleasant, Ohio, Ninth month 5th, 1836.

[.salutation]
Dear Wife:

I wrote to Rebecca from the summit of the Alleghany Mountain,
where we slept on Fourth-day night.
On Sixth-day we arrived at Pittsburg.
On the same evening J. and I started for Sewickly; lodged at a tavern;
and the next morning hired a conveyance,
which took us to Benjamin Gilbert`'s. Second-day we returned to Pittsburg.
Third-day went to Steubenville.
Fourth-day to Smithfield, to B. W. Ladd`'s; and remained there until Sixth-day,
when we came to this place.
Dr. Parker`'s, where we make our home, is pleasantly situated,
about half a mile from Mount Pleasant.
At the Select Meeting, on Seventh-day,
certificates and minutes were produced for seven ministers, beside myself, namely,
Elizabeth Coggeshall, Phebe Field, of Scipio, Daniel Wood, Sarah Emlen, William Evans,
William Pierson, belonging to Indiana Yearly Meeting, and Jeremiah Hubbard.
John Meader arrived in the evening, having been unable to reach the meeting in time.
Indeed, the Ohio River being too low at Pittsburg for steamboat navigation,
and many travellers wishing to go west, has exposed most of us to difficulty and expense.

This is a very pleasant country, so much changed since I was here twenty-eight years ago,
that I can scarcely recognize anything I then saw.
The morning meeting at Mount Pleasant was exceedingly large, very irregular in gathering,
and, owing to the kind of persons who attended, very unquiet.
Yet some feelings of solemnity were spread over us.
J+++.+++ Hubbard and J. Meader had the public service.
In the afternoon I attended at Short Creek Meeting-house.
A small and quiet meeting, and, with the exception of a few words near the close,
held in silence.
Since coming into this State, I have mostly felt pretty well.

--

+++[+++In the Tenth month of this year,
the Monthly Meeting of Philadelphia appointed a committee to visit such of
their members as were not diligent in the attendance of religious meetings.
Thomas Kite was one of that committee, which had much acceptable service.
Its labours were of singular use to some,
and for a time many were stirred up to greater zeal in assembling with their friends.]

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Susanna.

[.signed-section-context-open]
Philadelphia, Twelfth month 9th, 1836.

[.salutation]
Dear Daughter:

+++[+++After speaking of the postponement of a visit to her,
and the reason for it]. Among these,
the increasing indisposition and death of my friend, Othniel Alsop, may be included.
He appeared to have the prevailing cold, attended with difficulty of breathing,
and was confined a few weeks to his house.
He rapidly grew worse,
and at length his physicians believed his complicated complaints were,
abscess of the lungs, aneurism of the heart, dropsy of the chest,
and the same disease in the extremities.
Nature sunk under these united attacks, and he deceased yesterday,
about 1 o`'clock p. m. He will be much missed in his family,
and in the Northern District Monthly Meeting,
as well as more extensively in religious society.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to E. S. F.

[.signed-section-context-open]
Philadelphia, Third month 30th, 1837.

[.salutation]
Dear Friend:

Your letter,
giving an account of the last illness and death of my much respected and beloved friend,
Philip Price, was very acceptable.
It is a privilege to be with those who feel at such a
solemn period the consolations of the Gospel of Christ.
Nature shrinks from death; and even to the pious it is a solemn thing.
Samuel Emlen, eminently a disciple whom Jesus loved, said,
on his approach to the close of life, "`It is a serious thing to die;
the invisible world--how awful!`"
It is not principally the suffering attending the parting of soul and body,
though that is often hard to bear, nor the separation from all we have loved,
though that be trying to the affectionate feelings of our nature,
but it is the thought of a state of fixedness, of appearing before that Judge,
who knows the secrets of all hearts; and who has "`set oar iniquities before Him,
our secret sins in the light of his countenance.`"
There is but one remedy--repentance towards God, and faith in our Lord Jesus Christ.
That faith which enables us to accept Him in all his offices,--to deny
ourselves,--take up his cross and follow Him in the regeneration,--
submitting to those baptisms by which He purges away our defilements,
and makes us a holy people to Himself.
These are they who have hope in their death,
because they trust in Him who has conquered death, hell and the grave.
Having witnessed such a deathbed, dear Elizabeth,
let it incite you to count nothing too near to part with,
in order that you may be prepared to finish your course with joy.

We have met with a loss in the decease of dear Mary Elliott,
who died on Second-day morning last,
having left a good report behind her of her faith and faithfulness.
She also enjoyed the consolations of the Gospel in her hour of need.
Uncle John Letchworth is very unwell.
We fear his departure is not far distant.
Our aged friend Edward Randolph`'s close is hourly looked for.
Thus a stripping time is experienced; and w e must,
if our testimonies are to be supported,
look to the younger ranks for a succession of standard bearers.
May they submit to the power, that can alone prepare for the Lord`'s work.

--

+++[+++At Yearly Meeting time Thomas Kite`'s house was generally thronged with Friends;
and many religious opportunities occurred at such seasons,
beside instructive and animating conversation.
I find some notes of one or two such conversations and religious sittings.
On Seventh-day the 10th of Fourth month, 1837, Joseph Whitall being there at dinner,
was largely engaged in pleasant, sociable conversation, all, however,
having an instructive bearing.
One anecdote he related was to this effect.
A worthy Friend, who had been very useful in the church and family,
by giving way to discouragement, became depressed in spirit,
seemed to lose his Christian zeal, and sunk into a state of melancholy,
out of which he did not appear to seek to be rescued.
One morning he noticed one of his daughters looked unusually sad,
and he inquired of her the cause.
She was evidently embarrassed, and hesitated as if unwilling to tell him.
But on his insisting, she at length said,
that in her sleep the previous night she had dreamed
that she had had an encounter with the devil,
who told her he had been trying in vain for many years to overcome her father,
but that now he was giving way to melancholy, and he should certainly have him.
Startled as if he had suddenly found himself on the brink of a
precipice towards which he had been heedlessly walking,
the father exclaimed with awakened energy, "`He shall have a hard struggle then.`"
In earnestly seeking for strength where it alone can be found,
the parent was enabled to shake off his gloom and despondency,
and again through the mercy of a watchful Providence, to escape the snare of the devil.

Joseph also related that when a young man,
he travelled in New York State in company with Comfort Collins.
She was then about 87 years old.
He supposed that having been so long faithful,
she might have become so redeemed as to be released from temptation.
She, however,
told him she found it as needful to watch against the
attacks of the devil as at any period of her life.

In the evening of that day, Smith Upton, Sarah M. his wife, Sarah C. Hull, Isaac Hayes,
his daughter Mary, and many other Friends, took tea with Thomas Kite.
In the course of conversation,
Sarah M. Upton gave a pleasant little anecdote of Thomas Shilletoe.
He was travelling, perhaps somewhere in New York State,
when a concern arose to visit some one, but who it was he did not know.
His companion was in a hurry to be going on;
but Thomas said there was some one confined to their chamber in that neighbourhood,
to whom he must pay a visit.
He added, that his companion might go on and leave him to attend to his apprehended duty,
and he would get along as he could.
On inquiring among Friends in the place,
if there was any one there of that description,
they mentioned a woman Friend who had been confined for several years to her chamber.
Thomas after a pause said, "`She is the one I want to see.`"
He was taken to her house, and found her in her chamber,
so wrapped up as to keep the fresh air, which might be admitted through the door,
entirely from her.
Close by her was a stand or small table,
on which were a variety of different kinds of medicine,
of which she was almost continually taking some, a sup from one,
and anon from another cup.
Thomas was soon dipped into her state, and told her,
that her being confined there was all the work of the devil; bid her put away her stand,
lay aside all her medicines, and arouse herself.

Pointing to the shovel and tongs in the corner, he said,
"`If those are not scoured occasionally, they will become rusty;
and you have become rusty; and it is necessary you should be scoured.`"
So forcibly, and with such a prevailing effect, did Thomas speak,
that she was completely cured of all her imaginary ailments.
She left her chamber, rode out the next day,
and had continued in pretty good health up to the time of the narrative.

After a time of social converse,
in which several other interesting circumstances were related,
silence fell upon the company assembled in Thomas Kite`'s parlor.
Pretty soon, in allusion to the presence of his friend and fellow-labourer in the Gospel,
Sarah M. Upton, Thomas Kite broke forth, "`God who comforts those who are cast down,
has comforted us by the coming of Titus.`"
He said he had been comforted;
and endeavoured to encourage Sarah to a faithful discharge of every apprehended duty.
He said that though she might have come weeping,
not conscious of bearing any precious seed, yet, if faithful, she would, doubtless,
return rejoicing bearing her sheaves with her.
He then addressed Sarah C. Hull, +++[+++widow of Henry],
desiring her to trust in that Arm that had supported her in six troubles,
and would not leave her in the seventh.
He believed that the Lord who had drawn her to Himself in early life,
had fixed the bounds of her habitation.
Adding he had had great unity with her dear husband,
whose praise was in all the churches, and who had now entered into everlasting rest.

After Thomas had ceased speaking, silence rested awhile on the tendered company,
until Sarah M. Upton commenced, "`I can say, it is good for us to be here.
I have laboured under many discouragements, and was almost ready to query,
whether it were not wrong that I had come.
But I can now adopt the language,
'`It is good for me that I am here.`'`" She spoke briefly, encouraging all to faithfulness,
that they might be bound together in Christian fellowship.]

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Susanna.

[.signed-section-context-open]
Lynn, (Mass.,) Fifth month 13th, 1837.

[.salutation]
Dear Susanna:

Yesterday, at an appointed meeting held at this place,
your uncle James +++[+++Kite]
accomplished his marriage with his amiable friend +++[+++Lydia B.
Rodman]. Many gaily dressed young women were present,
attracted, no doubt, by curiosity; but their behaviour in general was orderly.
The Friends concerned spoke audibly;
and the meeting was quite as satisfactory as could reasonably be expected.

We have been to Nahant and Salem,
and have been favoured with fine weather while travelling,
though several storms have occurred while we were resting with our friends.
The season is cold and backward.
We have seen some very stony farms,
and renewedly wondered how the farmers continue to live;
but we have been into one farming district where the land is good.
It is Danvers, near Salem.

It is now near 10 o`'clock, and an easterly storm is setting in,
and the rain has just commenced.
From the door I can hear the roaring of the billows of the Atlantic,
but a little eminence intervening, prevents the ocean being seen.

[.signed-section-context-open]
Philadelphia, Fifth month 18th.

After writing the above, my pen was laid aside,
to be resumed at my own beloved home.
On First-day we went to Salem, attended morning meeting,
and returned to Lynn to afternoon meeting.
'`On Second-day morning, we set out for Boston, so early,
that we were in time for the morning train of cars
which start at 7. We arrived in Providence before 10,
and had six hours to devote to seeing the city, visiting the Boarding School, etc.
We embarked in the steamboat "`Rhode Island,`" joining
the newly-married pair and Hannah Bassitt,
who has borne her sister company to her new habitation.
The clouds were gathering up for a storm,
which fairly set in soon after we passed Newport,
and our large and excellent boat was sadly tossed, affecting us with that unpleasant,
but not commonly dangerous complaint, sea-sickness.
Your mother and I were sick, and many others of our fellow-passengers;
but I had a pretty comfortable night`'s rest notwithstanding, for when in bed,
I felt pretty much free from nausea.
The tempest and darkness caused the vessel to be several times anchored,
and protracted our voyage,
so that we barely reached New York in time to take the second morning boat,
which leaves at 9 o`'clock.
We arrived at home about 5, on Third-day afternoon,
having had cause gratefully to acknowledge the protection of that merciful Power,
without whom not a sparrow falls to the ground.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to E. S. F.

[.signed-section-context-open]
Philadelphia, Seventh month 24th, 1837.

If, however,
I could say anything that would encourage you to hold fast what you have attained,
and to press forward towards greater degrees of resignation to the Divine will,
and bearing the daily cross, I would willingly do it.
The world, and all that engrosses the attention of the worldly-minded, is vanity.
Solid satisfaction can only be found in a life of holiness.
Be this, then, the great object in your view, to stand approved in the Divine sight.
The friendship of the pious, and many social comforts, our Heavenly Parent affords us,
are to be duly prized, and ought to be received with thankful hearts.
Yet, after all, but one thing is needful.
It is so, because without it we can never enter the pearl gates.
Part with everything that obstructs your participation in this all-essential,
ever-enduring, that so it may be said of you, as of one formerly,
"`She has chosen that good part, which shall never be taken from her.`"

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his Son-in-Law, Aaron Sharpless.

[.salutation]
Dear Aaron:

We feel much obliged by your attention in sending
us an account of your uncle`'s +++[+++Benjamin Sharpless`']
sickness.
We wish to hear from time to time, how it fares with him,
particularly should his disorder increase upon him.

In the present reduced state, of your meeting, he would be much missed,
should he be taken from you, and no less so by his own family.
But we must leave all in his hands who disposes of us and our affairs in perfect wisdom.
Happy they who are habitually looking forward to the
solemn period of giving an account of their stewardship,
and are daily preparing, under the guidance of the Holy Spirit,
to give up their accounts with joy.
Tell Susan that her friend Rachel Morris continues quite ill;
she has been removed to her mother`'s. Stephen is also ill at his own house.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Sarah Scull to Thomas Kite.

[.signed-section-context-open]
Eighth month 10th, 1337.

[.salutation]
Dear Friend:

Though I have been tardy in acknowledgment,
yet I trust my heart has not been insensible of your kindness in forwarding the books,
and especially the feeling that prompted your very acceptable brotherly salutation.
I was pleased to learn that a visit, so particularly grateful to my feelings,
afforded a comfortable, peaceful retrospect to your own mind.
There was truly a precious serenity attending it, and a covering, not at our command.
How very desirable, even in our interactions with each other,
to witness something like a seal of Divine approbation.
Oh! it is an inestimable privilege thus to mingle together,
and partake from a source from which springs some of
the purest enjoyments which await us below,
the comfort and benefit that flows from true Christian fellowship,
through the influence of his Spirit, which unites in near feeling,
the very child in experience, to the strong man in Christ.

Ah! my dear friend, I do feel while I am writing,
that there is abundant cause for humble,
heartfelt gratitude to the merciful Disposer of events, who,
though it has pleased Him to take away my dearest earthly treasure and delight,
has not entirely cut off the consolations which arise from Christian friendship.
It is, indeed, through his unmerited goodness, that I am permitted to enjoy the belief,
that there are those left who care for my soul, and pray for its redemption.
These are comfortable considerations, under any circumstances, but particularly so,
when the spirit is sadly musing on the removal of faithful, devoted labourers,
under a sense of its own shortcomings and weakness.

I must just mention, as to one interested in the proceedings of the Church,
wherever situated, and concerning which, I believe,
we had some conversation when together, that at our last Monthly Meeting,
an appointment was made, if way should open,
to select from men`'s meeting some suitable Friend to fill the station of elder.
This, at all times, and in all places, a very important movement, appears to me,
in the reduced state of that meeting,
to involve unusually serious and weighty deliberation.
Oh, how needful is it, both for the honour of Truth,
and the spiritual advantage of the individual who may be chosen,
that the minds of the committee be clothed with heavenly wisdom.

I should be glad sometimes to have your company at our little meeting, but, nevertheless,
desire to be content with the portion afforded us,
and endeavour to rest satisfied under the comfortable persuasion,
that however widely separated, there is, or may be, a communion of spirit,
and that those qualified to feel and pray for such as sit in lonely places, may,
through the blessing of our Holy Head and compassionate High Priest, availingly help us.
While I am sensible that an individual and
living engagement of heart must be experienced,
if ever any spiritual benefit is enjoyed from assembling together for Divine worship,
I do also earnestly crave the continued intercession of
those who travail in soul for the welfare of Zion.

--

+++[+++In the Eleventh month,
Thomas Kite paid a religious visit to the meetings
composing Cain and Western Quarterly Meetings.
Of this journey he kept a brief account.]

[.small-break]
'''

Eleventh month 7th, Third-day.
"`Left home; a very unpleasant morning.
In the course of a few hours the wind began to rise, causing much dust,
so that it was quite trying.
I stopped at Robert Garrett`'s to dine; then went to Westtown.
After remaining a short time,
passed on to Aaron Sharpless`'s. Found them all as well as usual,
unless A. Greeves is a little weaker.

Fourth-day.
I rose early, and, after breakfast, set off over the hills to Cain; a delightful morning,
and fine prospects.
Attended +++[+++Bradford]
Monthly Meeting.
In the first meeting the testimony was to the character of the true Church,
and its living members, from the passage in Revelations, '`I, John, saw the holy city,
New Jerusalem, coming down from God, out of heaven,`' etc.
About forty men and lads attended; several Friends being absent.
Dined at Richard Pirn`'s, and went on to Jabez Jenkins`' to lodge.

Fifth-day.
Walked to William Trimble`'s; from there went to Uwchlan Monthly Meeting.
From the language, '`Fear not, little flock,
it is your Heavenly Father`'s good pleasure to give you the kingdom,`'
it was endeavoured to show the nature of Christ`'s kingdom,
and who they are who are entitled to that gracious declaration,
with various cautions and warnings to the worldly-minded,
and encouragement to the mourners in Zion.
About twenty persons in the meeting for business.
Things appear, among the members of this meeting, in a declining state.
Dined at Mordecai Larkin`'s, and lodged at Jesse Meredith`'s.

Sixth-day.
Rose early and started for Ephraim Scarlett`'s at Robeson.
Attended Monthly Meeting.
The subject spoken to was, the impossibility of attaining settlement of mind,
and certainty in religion, on any other ground than that of immediate Divine revelation,
from the question of Christ to his disciples, and their answer, '`Whom do men say that I,
the son of man, am?`'
etc. The danger of a formal, lifeless, traditional profession of religion, was spoken to;
and the language of affectionate entreaty addressed to the visited children,
encouraging them to abide under the Power that can enable, from living experience,
to say, '`You are the Christ, the Son of the living God!`' etc.
Lodged at Ephraim Scarlett`'s.

Seventh-day.
Rode to Lampeter, and put up at Hannah Gibbons`'. First-day, Eleventh month 12th,
attended Lampeter Meeting,
and treated on the necessity of manifesting in our lives and conduct,
the fruits of true religion, thus manifesting a preparation for the life to come, etc.
Rode to Ferree Brinton`'s, with Abraham Gibbons for pilot.

Second-day.
Rode to Bart, and attended an appointed meeting.
A+++.+++ G. still with us.
I apprehend this to have been the most favoured meeting I. have been at.
The subjects spoken to were, the wickedness of man and the mercy of God;
the state of man in paradise,--his apostacy,--its sorrowful effects,--
the general condition of man in a state of alienation from God,--the
means of recovery by Jesus Christ,--the necessity of the new birth,
and of leading self-denying, holy lives;
addresses to various classes of our fellow members,
with something in particular for those not of our Society,
several being present who did not profess with us
called in the afternoon to see William Kirkwood,
who has settled within the limits of this meeting.
Went to Robert Moore`'s to lodge.
A+++.+++ G. here left us, and William Baily took charge of us.
He lives at present with his son-in-law, Robert Moore.

Third-day.
Attended Sadsbury Meeting.
A more labourious time; yet was strengthened to advocate the cause of Truth.
Went to Isaac Phillips`' to lodge, and had a comfortable,
religious opportunity with this interesting family.

Fourth-day, called pleasantly at William Coale`'s, on our way to East Sadsbury Meeting.
+++[+++This meeting]
was to my comfort, dear Hannah Gibbons being present,
and participating in the public labour.
My concern was to open the spiritual nature of the Gospel dispensation,
and the necessity of renewed qualification from
the immediate operation of the Holy Spirit,
to discharge our varied religious obligations.
Dined at James Smith`'s, and came in the evening to Joshua Edge`'s, at Coatesville,
to lodge.

Fifth-day, to Downingtown, to Select Quarterly Meeting.
Dined and lodged at George G. Ashbridge`'s.

[.offset]
+++[+++From this place Thomas Kite wrote to his wife thus:]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Eleventh month 16th.

I have been closely engaged, body and mind, but have had the sympathy of some feeling,
valuable Friends, which has been consoling; particularly Hannah Gibbons.
In company with her, I visited Charity Baldwin,
who is now confined to her chamber by indisposition, and is in her eighty-fourth year.
She is in a comfortable state of mind.

--

Sixth-day.
At Quarterly Meeting at Cain.
I suppose the largest I have attended there since the separation.
Though there are some valuable Friends, the state of things is rather low.
Went to uncle Isaac Hayes`' +++[+++in East Fallowfield]
to lodge.

Seventh-day,
18th. After a favoured opportunity with the
united families of my uncle and cousin +++[+++Isaac],
in which Isaac, Jr.`'s, mother-in-law, Hannah Harlan, was present,
went to an appointed meeting.
The meeting was small, and it was a low time.
I had very little to say, but a Friend from a neighbouring meeting spoke twice.
Went to Samuel Swayne`'s to lodge.

First-day, 19th. Had opportunities with Samuel Swayne`'s wife and daughter,
both remarkably afflicted women.
Went to London Grove Meeting.
Very small.
A neat, new meeting house has been built.
Took tea with Edith Edge, and lodged at Isaac Pusey`'s.

Second-day, 20th. At an appointed meeting at West Grove.
More encouraging than the two last.
I was largely opened, and the opportunity ended well.
Went to Joshua Sharpless`'.

Third-day, 21st. A favoured appointed meeting at London Britain,
in which I was helped to open the ground and nature of Christian redemption;
to treat of the mercy of the Most High to his fallen creatures in different ages,
after the fall of our first parents;
at the deluge--when Israel was captive in Egypt--at the birth of Christ, etc,
and to speak to various states with openness and freedom.
The meeting ended with prayer and praise.
Dined at Eli Thompson`'s, and lodged again at Joshua Sharpless`'.

Fourth-day, 22nd. After a religious opportunity, set off for New Garden,
to an appointed meeting, which was held to a good degree of satisfaction.
The nature of the true Church, and the qualification for membership, was set forth,
and various states addressed.
Dined at Daniel Thompson`'s; visited W. Hicks, and went to Joseph Chambers`' to lodge.

Fifth-day, 23rd. After a religious opportunity, set off for London Grove,
calling at Benjamin Hoopes`', whose wife is indisposed.
Had a time of retirement with her and some other members of the family,
in which the language of encouragement was handed forth.
Then proceeded to the Select Quarterly Meeting.
There met with Hannah Warrington, Jr., and company.
Dined at Samuel Swayne`'s, and lodge at Isaac Pusey`'s.`"

[.small-break]
'''

+++[+++In a letter written to his wife from this place, he says,
"`I ought to have mentioned that William Cole joined me at Fallowfield,
and continues with me.]

[.small-break]
'''

Sixth-day, 24th. Attended Quarterly Meeting.
A favoured, solemn meeting.
Awakening calls were extended to the youth and others.
Several Friends engaged in labour in the meeting for discipline,
towards the close of which prayer and thanksgiving were
offered up to the Author of all our mercies.
In the morning a religious opportunity in E. Edge`'s family.
I dined at Isaac Pusey`'s,
and lodged at Thomas Lamborn`'s. Walked to his married son`'s house in the evening,
and had a sitting.

Seventh-day, 25th. After a religious opportunity in the family where we lodged,
proceeded to Thomas Jackson`'s,
calling at Enoch Lewis`'. Walked over to T. Walker`'s. Dined at T. Jackson`'s,
went to meeting +++[+++at Okesson]
at two o`'clock.
It was quite a satisfactory opportunity,
in which the invitations of the Gospel were freely extended to a serious auditory.
Towards the close a solemn covering spread over the assembly.
Lodged at Evan Phillip`'s.

First-day, 26th. Attended Kennett Meeting.
Had the most close and alarming testimony I have delivered in the present journey.
The principal Scripture passage was the first Psalm,
'`Blessed is the man that walks not in the counsel of the ungodly`' etc.
I believe I was helped to relieve myself to the satisfaction of the livingly exercised.
There appeared to be those present who have little feeling of right exercise,
whose lukewarmness and worldly-mindedness make the labour hard for the burden bearers.
Dined at Edward Temple`'s; paid a hasty visit at D. Temple`'s,
and went to Aaron Sharpless`' to lodge.
My prospect there closing; parted with William Coale at Kennett,
who expected to reach home to night.
He has been a kind, sympathizing and agreeable companion.

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his Wife.

[.signed-section-context-open]
Westtown School, Twelfth month 26th, 1837.

[.salutation]
My Dear:

You will probably have heard of the decease of our dear niece, Abigail Greeves,
before this letter reaches you.
She had been perceptibly growing weaker for several days,
and on Seventh-day afternoon I took sister Lydia Sharpless to see her.
I returned in the morning and attended both the meetings here on First-day,
and went again to Aaron`'s in the evening,
designing to return to the school on Second-day morning;
but our niece was so low that I did not feel willing to leave her,
and accordingly waited until the close, which took place at twenty minutes before two,
in the afternoon.
When awake, she appeared sensible to the last.
Her sufferings were great, particularly the last night but two, I think it was,
when they appeared to be agonizing.
She had been, during most of the early period of her illness,
much shut up from communicating her feelings on religious subjects; but towards the last,
her mouth was opened, not only in supplication at different times,
but also in remarks in relation to her circumstances,
manifesting that her dependence was on the Lord alone.
Perhaps two hours before her departure, she appeared in prayer,
commending her spirit to her Saviour`'s care.
Nearly the last articulate words were to this effect, "`I believe I am almost gone!`"
At the period when the spirit appeared to leave its clay tenement,
a sweet and heavenly solemnity seemed to spread
over our minds who were privileged to be present,
and thanksgivings were raised in our hearts to Him
whose mercy is from everlasting to everlasting,
and his righteousness to children`'s children,
of those who remember his commandments to do them,
in that we could believe her immortal part was gathered to join with
the redeemed of all generations in worshipping before the Throne of
the Most High in a state of endless felicity.
May surviving relations experience renewed preparation of heart for the Master`'s service,
and through increasing dedication, not only serve him in their generation,
but receive at last the end of their faith and righteousness,
even the salvation of their souls.
The interment is to be on Fourth-day afternoon, at three o`'clock.
Such of you as may come out in the morning car, will, I suppose,
meet with a conveyance at West Chester.

--
