== Chapter XIII.

[.chapter-synopsis]
* 1839.
* Letters
* Jonathan Evan`'s death
* Thomas Evans appears as a minister
* Diary
* Thomas Kite Jr. Removes to Cincinnati
* Letters

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Rebecca.

[.signed-section-context-open]
Philadelphia, Second month 8th, 1839.

[.salutation]
Dear Rebecca:

A prince and a great man has fallen this day in Israel.
Jonathan Evans departed this life this morning, in great tranquillity,
in apparently the full possession of his mental powers,
and without giving evidence of bodily suffering.
Not a sigh was heard, not a muscle observed to quiver as the spirit took its flight.
At the commencement of his illness, which he believed would prove his last,
he underwent some conflict of mind, but it was soon over, and he felt quiet and composed,
and the Everlasting Arm seemed underneath to the last.
The funeral is to be on Second-day morning.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to Aaron Sharpless

[.signed-section-context-open]
Second month 8th.

[.salutation]
Dear Son:

We have had quite a pleasant visit from Daniel Wheeler;
he seemed quite at liberty for social converse,
and his extensive travels and remarkable life furnished abundant topics of interest.
He has had a cold which has confined him to the house for a few days past.
It is likely Rebecca mentioned that Thomas and Elizabeth Robson, as well as Daniel Wheeler,
were at our Quarterly Meeting.
It was large and interesting.
Your mother and I hope to make you a visit after our +++[+++next]
Monthly Meeting; perhaps we may take Chichester and Concord in our way.
We quite wish to be with you,
but circumstances have induced us to postpone it for the present.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Rebecca.

[.signed-section-context-open]
Second month 16th.

I was at the funeral of our Friend Jonathan Evans,
and was invited into the room where the family were assembled, where also Ezra Comfort,
Christopher Healy, Elizabeth Pitfield and Sarah Hillman were.
A very precious solemnity prevailed,
and some brief testimonies were delivered to magnify
that grace which made our departed Friend what he was,
a firm and upright pillar in the Church.
The first-named Friend particularly addressed his grandchildren.
At the grave his son Thomas spoke a few words.
The attendance of Friends was very large, some from the country,
and a number of those who had separated from us.

Daniel Wheeler has taken tea and spent an evening at our Friend`'s late residence,
in company with a number of his children.
Our Friend Abigail Nicholson deceased on Third-day night, and the funeral is this day.
On Fourth-day morning I went to Woodbury, to attend Salem Quarterly Meeting.
I found Thomas and Elizabeth Robson at Joseph Whitall`'s.

It was a comfortable meeting.
In the meeting preceding that for business on Fifth-day,
the Wing of Ancient Goodness was memorably spread over us.
I dined at W. Tatum`'s;
the cars started before I had finished +++[+++my dinner]. Being thus left,
I went to George Mickle`'s, and spent the evening with some very interesting Friends.
Among these were John E. Sheppard and his sister Mary,
his mother and his cousin Richard Sheppard and his wife Amy,
who is Elizabeth Evan`'s sister.
Mary Mickle, the wife of George, has quite lately been acknowledged as a minister,
and is a tender, sweet-spirited Friend.
She appeared in the morning +++[+++in the ministry]
among us, which satisfied me with my detention for the night.
I had a passage to Camden with T. Warrington, who had been at the Quarterly Meeting.

--

[.offset]
+++[+++From Thomas Kite`'s Diary:]

Third month 5th. Calling on Anne S., wife of Robert Pearsall,
who appears to be afflicted with pulmonary consumption,
I was drawn into sympathy with her, and a short testimony to Christ Jesus,
the Light of the World, and the life of men, was delivered.
She was encouraged to submit to his power,
which is able to prepare for an admission to the realms of everlasting peace.

Third month 6th. Going to the residence of Elizabeth, the widow of Thomas B.,
to inquire after her sister Mary, now ill,
an unexpected opportunity offered of entering into sympathy with Elizabeth,
and of imparting encouragement to her,
to continue her trust in the Father of the fatherless, and Judge of the widow.
The same morning, from a secret drawing, attended the Western Meeting,
and was favoured with an opening on the passage,
'`Keep your foot when you go to the house of God,`' etc.;
and strength was afforded to enlarge upon it,
and afterwards to hand out consolation to the mourners,
particularly those who have been deprived of their companions,
and feel the sorrows of the widowed heart.
After meeting, accompanied by a young Friend, I visited a daughter of affliction,
to whom the consolations of the Gospel were offered.

10th. In the afternoon meeting, instances of the efficacy of living faith were adduced,
as encouragement to the Lord`'s tribulated children to trust in Him.
The circumstance of the famine in Samaria,
and the plenty predicted by the prophet Elisha, which so soon followed, was mentioned,
as also his preservation when the King of Syria sent a band of men to take him;
each of these cases being spiritually applied.

11th. Visited, in company with other Friends,
one of the departments of the Select School, by appointment.
A comfortable feeling prevailed, and the dear children were spoken to,
and the language of encouragement addressed to their teacher.

12th. Being brought under a concern to attend the North Meeting, I gave up to it.
An opening presented on the subject of the prophet`'s visit to the potter`'s house,
with which I stood up and was favoured to speak to some states in the love of Truth.
Dear Elizabeth Pitfield afterwards was acceptably engaged in supplication;
and it appeared to be a solemn opportunity.

Third month 13th. Believed it my duty to attend Haddonfield Quarterly Meeting.
I went to the meeting of Ministers and Elders this day,
which was owned of our gracious Shepherd; several Friends ministered acceptably,
and it seemed to be proper for me to bring into view
the character and faithfulness of departed worthies,
formerly members of that meeting.
A precious covering prevailed during great part of the meeting.

14th. At the Quarterly Meeting for business.
The united opportunity previous to entering upon the concerns of the Society,
was a favoured season.
The testimony I believed it right for me to deliver,
was on the prophecy of Jacob concerning the coming of Shiloh,
and the gathering of the people to Him.
Elizabeth Evans afterwards spoke very closely to the present state of our Society,
with a good degree of Gospel authority.
Both yesterday and to day,
my dear friends Simon Gillam and Joseph Whitall were present to my comfort.

17th. In the afternoon meeting,
being drawn into a feeling of compassion with the miserable,
those made so by rebellion and transgression against the light, some words were spoken,
remaining such of the unfailing mercies of God in Christ Jesus,
and of our Lord`'s compassion of the man leaving the ninety and nine sheep,
and going into the wilderness after the one which had gone astray,
and setting forth the compassionate regard of Him who
came to seek and to save that which was lost.

19th. Rebuking a friend for improper conduct, I spoke with too great asperity,
for which I was soon sorry, but not, perhaps, sufficiently so.
Lord! put on me the armament of a meek and quiet spirit.

20th. At the Western Meeting.
Our Friend Daniel Wheeler present, but silent.
I spoke on the language of Isaiah the prophet, personating the Lord Jesus Christ;
'`I have trodden the wine-press alone,
and of the people there was none with me;`' in sympathy with
those who are now enduring tribulation for the Gospel`'s sake.
Before the meeting closed, I was sensible of an impression pointing to vocal prayer,
but waiting for the motion to be more deeply felt, the meeting ended.
If any suffered loss by my withholding, I regret it,
but should much more regret appearing in that solemn
service without the requisite qualification.

21st. At our week-day meeting, we had the company of Elizabeth Robson, in silence.
The meeting appeared in a good degree favoured, and my mouth was opened in prayer.
In the afternoon went a few miles into the State of New Jersey,
to visit the family of my kinsman, Henry Warrington.

22nd. In company with H. Warrington, called on a few Friends,
and visited one who was sick; a religious opportunity took place in his chamber;
his wife and daughter, as well as his wife`'s aged mother, being present,
to each of whom the language of encouragement was imparted.

23rd. Before taking leave of my relations,
I found an impression of duty to have the family collected.
The opportunity seemed to be solid, and several states were spoken to;
the dear young people were encouraged to bear the cross of Christ,
and to yield obedience to every manifestation of the heavenly Father`'s will.

24th. First-day morning meeting.
An opening on the words of our Lord, '`My food is to do the will of Him that sent me,
and to finish his work.`'

Third month 30th to Fourth month 5th. At Westtown Boarding School,
attending an examination of the scholars,
and a meeting of the Committee having charge of that seminary.
I was at three meetings occurring in course, which were in degree favoured.
I had some little public labour,
and some more privately with scholars towards whom my mind was drawn;
and a hope attends that it was not altogether in vain.
I feel a renewed belief that this institution is under the care of our heavenly Parent,
and strong desires that all who are entrusted with its oversight,
may act under a weighty sense of their accountability to Him;
that thus it may be preserved in a situation to answer the design of its
establishment--the preservation of the dear children from evil example,
and their growth in virtue and piety, as well as their instruction in useful learning.

Fourth month 10th. The state of our religious Society, from various causes,
affords at present a sorrowful prospect.
Diversity of sentiment prevails, even on very momentous subjects;
and the fruits of love in many cases are blasted.
My present prayer is, that I may be preserved inward to the Lord;
and that He may be pleased not only to be merciful to the remnant of his heritage,
but by his mighty power to open the blind eyes among us,
and restore those who have in any degree lost the unity of the spirit--the bond of peace.

13th to 19th. The Yearly Meeting for Ministers and Elders commenced the 13th,
that for business the 15th. Many Friends had
looked forward to the meeting with much anxiety,
in consequence of the present state of society; yet, through Divine mercy, it proved,
on the whole, a favoured season.
A great weight of exercise attended, on many accounts,
yet the Lord was near his dependent children; his power at times was felt to be over all,
and the meeting separated under a feeling sense impressed on many minds,
that God is good to Israel.

[.small-break]
'''

+++[+++At this Yearly Meeting the following public Friends were present--Daniel Wheeler,
Elizabeth Robson, Joseph John Gurney, Anne Thornburgh, Joseph Edgerton,
Richard H. Thomas, Elizabeth Peckham, Anne A. Jenkins, Phebe Haines, late Cobb.]

[.small-break]
'''

30th. Attended Frankford Monthly Meeting.
Silence was my portion in the meeting for worship,
attended with thankfulness that I felt no desire to speak, unless divinely required.
I visited a young person in the afternoon, who appears to be in a decline,
and offered what appeared to be given, me for her encouragement.

Fifth month 1st. Finding K. D. had not left the city, I felt drawn to see her,
and in a religious opportunity apprehended myself made sensible of her present state,
and authorized to speak in a line of caution, counsel and encouragement,
which seemed to be suitably received.`"

In this month Thomas Kite attended the Quarterly Meeting of Salem and Western.
His daughter Rebecca being in New England, visiting some of his friends,
Thomas Kite wrote to her frequently.
Under date of Sixth month 22nd, after family information, etc, he concludes:

[.embedded-content-document.letter]
--

In conclusion, I desire, as perhaps I have written before, your preservation,
not only from evil, but from its appearance,
that your light may so shine through your watchful
attention to the intimations of the Divine Will,
that others may have evidence that you belong to the family of Christ; of Him who said,
'`My kingdom is not of this world;`' and who also said, '`If any man will be my disciple,
and come after me, let him take up his cross daily, and follow me.`'

Seventh month 3rd. Your uncle James, I believe, has not quite decided when to go to Lynn,
but I presume it will be in a few days.
He will be under the necessity of making his stay short,
and I suppose you will be glad of the opportunity of returning with him.
We shall rejoice to receive you safe after all your journeyings,
especially if we perceive that, like Paul the Apostle, everywhere and in all things,
you have been instructed, and that you return with the disposition strengthened,
which can say with him,
'`Herein do I exercise myself to have always a conscience void of offence,
both towards God and towards man.`'
With a heart full of tender greetings, and affectionate desires for your welfare,
every way, I remain your father and friend.

--

[.offset]
+++[+++On the 17th of the preceding month he wrote to her:]

[.embedded-content-document.letter]
--

I have nothing remaining but to express the desire which often accompanies my mind,
that you may experience preservation from evil; cultivate retirement of mind,
and spiritual fellowship with the '`Friend who sticks
closer than a brother`' that thus the present journey,
notwithstanding the danger which attends on such association with mankind,
may not in your case produce unhappy results; but rather beneficial effects.
And that your absence from home may prove a time
of renewal of covenant to serve the Lord,
and to dedicate to his service your future days,
that the resolution may be written in your heart by the finger of divine love and mercy,
to perfect holiness in the fear of the Lord,
being enabled to breathe the language of adoption, '`Abba,
Father!`' to take the exhortation of the Lord by his prophet,
'`Will you not from this time say unto me, my Father, you are the guide of my youth?`'

--

+++[+++Thomas Kite, Jr., in the Seventh month of this year,
went to the West to establish himself in business.
He had served his apprenticeship as a machinist;
and that trade being under temporary depression in Philadelphia,
he sought an opening where the prospect seemed more encouraging.]

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Rebecca, then again at Westtown as a teacher.

[.signed-section-context-open]
Eighth month 19th, 1839.

I can scarcely lay down my pen without expressing some desires
which arise warm from a heart overflowing with affection.
May the Lord preserve you, not only from evil, but from the least appearance of it.
Cultivate retirement, and an inward acquaintance with your Creator and Redeemer;
and when this little service at the institution is accomplished,
may you be restored to us in peace,
established in the holy resolution not to live henceforth unto yourself,
but unto Him who died for you and rose again.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To the Same.

[.signed-section-context-open]
Ninth month 9th.

Your sister had a letter from her husband, dated at Mount Pleasant, on First-day evening,
the first inst., after attending two meetings there.
In the first John Wood and Elizabeth Evans spoke remarkably.
In the afternoon the meeting was thought to have been favoured,
though I forget who was stated to have ministered.

I have from other quarters heard that the Yearly Meeting got on comfortably.
On Fifth-day, Daniel Wheeler was very remarkably engaged in testimony.
And now my dear child,
while I rejoice in believing the time approaches
when you will be restored to us in peace,
I feel some anxiety that you may not relax that holy
vigilance--that state of watching unto prayer,
without which preservation will hardly be witnessed.
Be circumspect; shun the appearance of swerving from the line of rectitude.
Rather debar yourself of gratifications that might perhaps be lawfully indulged,
than give occasion to critical observers to make their unfeeling remarks.
Remember,
that those in Daniel`'s time who sought occasion against
him were convinced they should not find it,
"`excepting concerning the Jaw of his God.`"
Accept these few remarks in the love in which they are written
by him who feels himself your affectionate father.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his son Thomas.

Religious parents can have no greater consolation in regard to
their children than to know of their walking in the Truth.
I do greatly desire this separation from us for a
season may prove a time of spiritual improvement to you.
It was when Jacob had left his father`'s house, on a solitary journey,
he was favoured with a heavenly visitation,
and entered into covenant with his father`'s God.
Should this be your happy experience, I shall not regret our temporary separation.
May the Lord bless you, and keep you from evil, and if it be his blessed will,
restore you to us in peace.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To the Same.

[.signed-section-context-open]
Tenth month 5th.

I suppose you are now at Richmond, attending the Yearly Meeting,
and that I shall soon have the satisfaction of receiving from you an account of it,
as also of our particular friends whom you may meet with.
We had, last night a serious fire in the neighbourhood of the wharf--Chestnut Street,
Water and Front Streets--supposed to have been
the greatest which ever happened in this city.
Perhaps forty houses are injured or destroyed.
Your sister Rebecca is at home.
Aaron`'s neighbour, William Osbourn`'s family have met with an affecting bereavement.
As his eldest son, David, who is married, but not commenced house-keeping,
attempted to mount his horse on Fifth-day week, the animal started and threw him.
He was much injured, and languished until Second-day, when he died,
without its being certain that he had ever roused up to perfect consciousness.

Uncle John Letchworth obtained a minute at our last Monthly Meeting
to visit the Monthly Meeting of Abington Quarterly Meeting,
and accomplished it last week.
Samuel B. Morris, of Germantown, bore him company.
'`Did I mention that your brother William had a daughter named Esther,
who will be four weeks old tomorrow?
Our anxiety for your welfare every way, continues;
not merely desiring you may keep out of the way of evil communications,
but that you may really experience a growth in grace; bearing the cross daily;
submitting to the baptisms of the Holy Spirit; having your citizenship in heaven;
seeking first the kingdom of God and the righteousness thereof,
and keeping the most allowable of worldly comforts in their proper places.
Thus will you become increasingly, if our lives be spared, a comfort to your parents,
and to other affectionate friends.

--

+++[+++John L. Kite had been for some time practising as a physician in Susquehanna County,
where his children could not have the benefits of mingling in
social interaction with the members of the Society of Friends.
This became a subject of much concern to Thomas Kite,
and at his suggestion his brother removed to the city.
Shortly after his arrival, several of his children were taken ill with scarlet fever,
and his third son, Alban, a lovely youth of seventeen years of age,
sunk beneath the attack.
In a letter written to an absent member of the family, by one of his cousins,
this passage occurs:]

[.embedded-content-document.letter]
--

I think I never saw a more beautiful corpse than his was.
His fine high forehead, his sweet and placid countenance looked so lovely,
we could scarce resign him to the cold earth.
William and Elizabeth Evans sat with the family.
Elizabeth spoke very sweetly to the bereaved parents, and the young relations.
She thought some were in a peculiar manner
called on to improve by the present dispensation.
'`We had a very interesting time in the evening.
Father +++[+++Thomas Kite]
expressed his sympathy for uncle and aunt,
and his desire for the rest of us that we might walk in the straight and narrow way.
He commenced with saying he had been thinking of innocent Abel,
whose offering was accepted through faith.
So it was through faith that the ornament of a meek and
quiet spirit was so conspicuously set upon him;
desiring that we might follow him as he followed Christ.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to Martha Jefferis

[.signed-section-context-open]
Philadelphia, Eleventh month 25th, 1839.

[.salutation]
Dear Sister:

I thought I might as well inform you,
although probably you have heard it already,
that our banks generally do not consider themselves at liberty
to declare dividends during the suspension of specie payments.
'`On Fourth-day night, last, I was aroused from my first slumber,
by the ringing of our bell.
On putting my head out of the window, Joseph Edgerton answered to my call.
He and his companion, William Dewees, were at the door, and I soon admitted them.
After attending all the meetings of New England Yearly Meeting,
and some out of the Society,
he found a release from the remainder of his prospect for the present,
and a liberty to return home.
He seemed very pleasant and cheerful, and William no less so.
After attending our meeting on Fifth-day, they started homeward on Sixth-day,
expecting to be at their own Quarterly Meeting tomorrow and next day.

Notwithstanding the causes of depression which abound among us,
I have been at a number of meetings of late, which have been attended, in a good degree,
with the solemnizing power of Truth.
This is certainly a token for good;
and it is evidence that the Holy Head of his church and people is still mindful of us.
I cannot but believe that a larger number of
young Friends are disposed to take up the cross,
than has usually been found among us.
May they be preserved.

Jacob Green was at Carolina Yearly Meeting.
Thomas and Elizabeth Robson have been visiting families at Lynn, Massachusetts,
and making their home at Isaac Bassett`'s. J. J. Gurney
was to sail on Sixth-day for the West Indies.
I understand he expects to be at our Yearly Meeting in the Spring,
and also at those of New York and Rhode Island.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Susanna.

[.signed-section-context-open]
Twelfth month 25th, 1839.

You are very near to my best feelings,
together with your beloved companion and your precious babes.
I believe the dear Master has need of you; need of your services in his church;
and though nature may shrink from it, and you may count yourself unworthy,
yet remember he is able to fit and prepare for his own work, and will do it,
as there is a giving up the heart to him,
and humbly abiding under the purifying baptisms of his Holy Spirit.
I want you to be encouraged, and also dear Aaron;
although the prospect of a succession of upright-hearted,
clean-spirited standard-bearers in your Monthly Meeting may not be very encouraging,
yet the Lord is as able as ever He was to raise up children unto Abraham.
Then trust in Him who can cause the very dust of Zion to arise and praise Him.
Jacob Green is again in the city, attending our Monthly Meetings, which occur this week.
His prospect is to be at those of your Quarterly Meeting in the week ensuing.
There is also here, or was yesterday, a member from Canada, his last name Knowles,
accompanied by his wife, bound for Indiana,
and to visit some Indians west of the Mississippi.
He is to be felt for, being lame, and having but one horse and a dearborn,
the season trying to travel,
and the mountains being often covered to a considerable depth with snow.

--
