== Chapter XIV.

[.chapter-synopsis]
* 1839-1840.
* Joseph John Gurney
* Letter to Joseph J. Gurney
* Letters
* Yearly Meeting
* Last letter of his mother
* Her death.

+++[+++Joseph John Gurney, late of Norwich, England,
will long be remembered on account of the extensive distress
and disunity produced throughout the Society of Friends,
by his doctrinal writings.
He was a man of intellect, highly cultivated,
and having devoted himself to literary pursuits, he acquired facility in composition,
and his style was not without force and elegance.
Having studied the doctrines of the Christian religion
as he found them unfolded in the Scriptures of Truth,
aided in his researches by the writings of eminent biblical critics and commentators,
he came to a judgment as to what they were, and undertook to defend them by his pen.
He had read the writings of Robert Barclay, and other early Friends,
and though his views did in many points differ from theirs,
yet he endeavoured to persuade himself and others, that he was one with them,
in what he understood to be the meaning of their "`unhappy`" choice of words.^
footnote:[For more information on the writings of Joseph John Gurney, and their devastating effect upon the Society of Friends, see [.book-title]#An Examination of the Memoirs and Writings of Joseph John Gurney# by William Hodgson. See also Hodgson`'s [.book-title]#The Society of Friends in the Nineteenth Century#, and [.book-title]#The Journal of the Life of John Wilbur#.]

He was a member of the Society of Friends,
and was acknowledged as a "`minister`" in it by Norwich Monthly Meeting.
Soon his activity with his tongue and pen caused
him to be considered as a prominent leader,
not only in the Society of Friends,
but among the various benevolent associations throughout England,
and also among the defenders of what is called "`Orthodox`"
doctrine against Unitarianism,
and other grades of infidelity.

About the close of the year 1839, or beginning of 1840, Thomas Kite,
under a sense of religious duty, addressed him the following letter.]

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to Joseph John Gurney

I have at different times taken occasion to express to you
my uneasiness with your writings as containing sentiments not
in unison with the doctrines of our early Friends;
I have thought I perceived at least a tendency
towards the same views in your public preaching.
My motive in writing now is,
to desire you calmly to consider what has been the effect of your writings,
and more particularly of your present visit, on our Society in this country.
You found us generally in unity.
That unity to a great extent has been broken; and I believe your coming among us,
under the accompanying circumstances, has been the principal cause,
and the means of producing that extensive distress which, within the last three years,
has overspread many parts of the Society in this land.
Some members appear to have been inclined to embrace your views;
others consider them fraught with danger to the best interests of the Society;
hence a conflict of feeling has occurred, which partiality, prejudice, misconception,
and other causes have probably contributed to heighten.
If you have been the occasion of this sorrowful state of things,
might it not be best to leave us,
that without any fresh cause of uneasiness administered,
we may have leisure to feel after our situation, make explanations to each other,
and endeavour to seek for the healing balm of Gilead.

I would tenderly entreat you to turn your attention inward,
and humbly wait for the discoveries of that Light which makes manifest,
that thus your own state and condition may be discovered by you,
and through the mercy of a gracious God,
the enemy in all his transformations may be detected and cast out, and you,
being brought to rely on Him alone who is the Way, the Truth, and the Life,
may be brought into, and preserved in fellowship with his living members.

If this should be your happy experience,
I believe secret and open acknowledgment will be called for from you,
because of the offence given to many little ones who believe in the Lord Jesus,
not only as to his outward appearance,
and all that He did and suffered for us in the flesh,
but also as to his inward and spiritual appearance as the true
Light which enlightens every man that comes into the world,
and the only principle of Divine Life to the soul.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his son Thomas.

[.signed-section-context-open]
First month 2nd, 1840.

I feel, my dear son, much for you, separated so far from us,
and knowing how liable youth is to be tempted.
The subject has been brought home to my feelings, by the circumstance of a Friend`'s son,
nearly of your own age, having disgraced himself,
and brought deep affliction on his family and friends, by an act of immorality.
I do not mention it as supposing his will be your unhappy condition,
but as a case coming home to my feelings, in remembering that I am a father,
and in sympathizing with a distressed parent.
I cannot but trust, that He who was my father`'s God,
and has condescended to take care of me, will bless my absent son,
and preserve him in that fear which keeps the heart clean.
I hope that every day you may read a portion of the Holy Scripture,
with your mind seriously turned to feel after that spiritual influence which
can open the meaning of the holy penman to the understanding,
and impress it on the heart;
and also have some seasons of private retirement for waiting
on your Heavenly Father for the renewal of your strength;
besides being diligent in assembling with your Friends on
First and week days for the essential duty of public worship.
Your care in these various respects and in endeavouring never to act
in contradiction to the discoveries of Divine Light in your own heart,
will doubtless draw down the blessing of Heaven upon you.
The warmest wish of my heart for you is,
that you may be prepared by the operation of the Lord`'s holy power,
to live to his honour and glory, and your own peace;
and live to take the place of pillars in his house who have been removed to
that heavenly habitation where the morning stars sing together,
and the sons of God forever shout for joy.

We have had Jacob Green in the city lately.
He dined with us a week ago today, and had a religious opportunity in the family afterwards,
to our comfort.
Cousin Edith Jefferis has been with us very pleasantly; and went home on Third-day last.
At our evening meeting on First-day she was with us,
and after some expressions of religious concern by your father,
she knelt down and petitioned for spiritual blessings.
I feel a hope she is likely to be made a pillar in the Lord`'s house,
if she is faithful to Divine requirings.
Commending you to the guidance and protection of Israel`'s Shepherd,
who sleeps not by day, nor slumbers by night,
I remain your anxiously concerned and truly affectionate father.

--

+++[+++During this First month, at one of the sittings in his family,
Thomas Kite was led to address several of those gathered,
in a sweetly affectionate and solemn manner.
He commenced with addressing +++_______+++; said he thought it was a critical time with her,
and expressed the earnest desire he felt,
that she might improve by the opportunities which were presented to her.
Then came something for +++_______+++, encouraging her to persevere.
Next was a message for John L. Smith, desiring he might seek first the kingdom of heaven,
then all things necessary would be added;
impressing the necessity of a complete surrender.
If this is not the case a blessing may not accompany our labours.]

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his son Thomas.

[.signed-section-context-open]
Second month 11th, 1840.

I am not yet prepared to give a decided sentiment on
the subject of your locating yourself at Cincinnati.
I fear that Cincinnati is not so eligible as this city for fostering religious interests,
which are of more value than temporal ones;
besides the painful thought of having you fixed at so great a distance from us.
I desire what may be for the best may take place.
Notwithstanding the anxiety I manifest for your welfare,
I wish not to show a lack of confidence in your principles or
your disposition to act in conformity with my wishes:
above all I wish not to distrust the providential care of the Most High,
who is mighty to save, and able to redeem.
If it be his will that you should abide for a time in a
state of separation from your immediate connections,
He can bless and sanctify this separation to you.
He can protect his dependent children in every state, and preserve from every evil,
and enable them to glorify Him.
Look up to Him for direction, consult his Witness in your heart,
which is given for a Counsellor and Leader; follow its dictates,
and grieve not the Holy Spirit of God,
by which the disciples of the Lord Jesus are sealed unto the day of redemption.
So shall your life be happy,
and the work of preparation be going on for another state of being, where,
having fulfilled your course of service to your great Lord and Master on earth,
you may forever enjoy the sweet society of pure
and blessed spirits in the paradise of God.

--

+++[+++In the Second month, Thomas Kite attended Concord Quarterly Meeting.
Writing to his daughter Rebecca after his return
he said:]

[.embedded-content-document.letter]
--

You probably heard by cousin James,
that the two carriage loads of Philadelphians started together on Fourth-day morning.
Thomas Scattergood with his company took the lead, and we quickly lost sight of them in the fog.
It was agreed that we should dine at George Allen`'s at Springfield,
but when we arrived there we could get no tidings of our friends.
Charles and I reached home in the evening.
I have since heard that Thomas Scattergood missed his way and went from Middletown towards Chester.
On discovering his mistake he was about to turn back,
but the women +++[+++Sarah Hillman and her companion]
prevented him, finding their minds drawn towards Chester Meeting,
which they attended and came home in the evening.
I understand there was cause to believe they were rightly at the meeting.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his son Thomas.

[.signed-section-context-open]
Third month 25th.

Dr. Parrish deceased a few days ago.
He has been declining in health several months, but was not long confined to his bed.
There has been considerable eulogy of his character as a physician and a man,
in the public papers.

30th. Since my last date above, we have had a time of trial in the family.
Brother John`'s daughter Sarah`'s indisposition increased,
the cold settled on her lungs and liver, and on Sixth-day morning, about two o`'clock,
she ceased to be an inhabitant of this world.
It is a great affliction to her parents, particularly the dear mother,
to whom she was much of a companion.
She was aged nearly thirteen years.
I think about four months had elapsed since the death of Alban.
I feel desirous that the parents may apply to the only sure source of consolation;
and that all the connections of the dear child may take this renewed warning,
and seek to be ready for an hour which we cannot tell how soon may come,
when it will be said, "`Give an account of your stewardship,
for you may be steward no longer.`"

Our minds are now looking forward to the approaching Yearly Meeting,
which commences three weeks from today.
As usual, our feelings are of a mingled character.
While we anticipate some pleasant emotions from meeting old and valued friends,
and near relatives,
we are brought under feelings of exercise and
concern that the good cause may not lose ground;
and prayers are raised to the Father of mercies, that He may be pleased to be near,
and comfort the hearts of the mourners in Zion, confirm the weak,
and bring home wanderers from the path of rectitude to himself, that so his great name,
and the name of his dear Son, our holy Redeemer, may be magnified and glorified.

[.postscript]
====

P+++.+++ S.--Thomas and Elizabeth Robson, who have been much of late in New England,
are expected at our Yearly Meeting; Jacob Green is also looked for; he was,
at last accounts, in New York State.
Mildred Ratcliffe and Benjamin Hoyle, ministers belonging to Ohio Yearly Meeting,
are also expected; and no doubt we shall have others, of whom we have not yet heard.

====

--

+++[+++On Seventh-day the 18th,
Christopher Healy called in the morning at Thomas Kite`'s to see John Wilbur,
who made his home there.
He appeared happy to meet with him, and taking him by the hand, kissed him.
He said, "`John and I were members of the same meeting in early life,
and we have been drinking out of the same cup ever since.`"
Ellen McCarthy was present, and many other Friends.
A lively conversation ensued,
at first turning on the difficulties many had to pass
through in remote places in getting to meetings.
This was particularly the case with females in low circumstances, who had young children.
Ellen spoke feelingly of her trials in that respect, in years past,
when she had generally to walk twice a week to the meeting,
several miles distant from her residence, and carry a baby in her arms.

Christopher also gave his experience in the line of walking to meeting,
and carrying babies, having followed the concern pretty diligently for many years.
He spoke of the hardness of heart of some persons who
were unwilling to sit in meeting with babies,
and who would condemn all mothers to stay at home while the children were small,
if they had no person to leave at home with them.
The conversation then turned on the various testimonies
of our Society to plainness in dress and address.
Christopher, in earnestly setting forth the necessity of keeping to them,
quoted Judge Jay,
then member of Congress--the ambassador to England--the humble-minded Christian.
"`I admire your Society.
The principle contains all of Christianity that I have any idea of;
but I am sorry to see that some of you are losing your badge;
and I don`'t see how you can retain your principles, and forego your little peculiarities,
your marks of moderation, self-denial, and difference from the spirit of the world.
You are lights.
The world should come to you; but you are not to go to the world.
You may gather them; but they will scatter you.`"

Thomas Kite then quoted Samuel Neale`'s account
of his two visits to the Bishop of Cloghen,
in the first of which he balked his religious testimony,
and was treated with contempt by the Bishop, and felt reproved by the spirit of Truth,
and ashamed of his cowardice.
In the second, having spoken as a Quaker, he was treated with great civility,
and felt comfortable and happy.
He thought, however,
the principle of Truth should govern throughout--temper
as well as dress--telling the following anecdote.
A Friend in plain attire, having in an excited manner,
rebuked severely a young person in gay apparel,
for speaking in meeting in favour of the admission of a
colored man into the Society of Friends,
James Simpson spoke out, "`I had rather hear truth from a lapell,
than see indignation under a plain coat.`"
+++[+++James had previously said, as soon as the young man sat down, "`Well done, lapells.`"]

Christopher then mentioned that soon after he became plain,
having business with Elisha Potter, a great lawyer and member of Congress,
in company with one of his brothers, he called upon him.
Christopher found he must address this great man in the plain way,
although it was no small trial to do so.
Elisha received him and his friendly salutations kindly,
and they transacted the business which took him there.
When it was over, Elisha; addressing the brother, said,
he perceived that Christopher was determined to keep to
the peculiarities of the Society of Friends,
and he was glad of it.
He liked to see consistency.
He then strongly condemned those Quakers, who on occasion,
put off their testimonies and appear like the world; saying,
"`There are many that do so.`"
His wife, who was sitting by, here interposed and said, "`You wrong the Society,
Mr. Potter, by attributing to them the conduct of such members.
They are a burden to them.`"
The opportunity was a very interesting one to Christopher,
and the parties all separated in friendship.
In process of years,
sometime after Christopher had received a gift in the ministry of the gospel,
he found a concern raised in his mind to hold a meeting
in the neighbourhood where this lawyer resided.
Elisha, on being informed of it, was very active in procuring a suitable place,
and in preserving order in the company which assembled.

During the Yearly Meeting week, commencing Fourth month 19th, this year,
Thomas Kite`'s house was thronged with strangers.
Almost every evening a religious opportunity was had in the family,
some of which were peculiarly striking and instructive.
On First-day evening, the Westtown teachers--the females--were gathered there;
and Thomas Kite was much favoured in near access to the Throne of mercy,
interceding that those assembled might unreservedly
obey and serve the Lord in full dedication of heart.
On Fifth-day evening Benjamin Hoyle spoke in a very
feeling manner to a large company who were assembled.
On Sixth-day evening Jacob Green was opened in a
very lively and encouraging communication.
He spoke of the goodness and mercy of a gracious God, extended to all the obedient.
He addressed the young particularly,
opening in the counsel of Light what they were called to,
and their services in the Gospel of Christ; if they closed in with the divine requirings,
and bowed thereto in perfect submission.
Edith Jefferis then knelt in supplication.
She prayed for our dear friend Jacob,
that he might be strengthened to hand forth all the
Master`'s counsel to those among whom he was sent,
and that he might be preserved through every
height and depth through which he might be led.

During the time of answering the Queries on Third-day, the 21st,
Thomas Kite had an opportunity of relieving his mind of
a concern he had long felt on the subject of books.
He adverted to the increased necessity there was for Friends
to examine the publications they admitted into their houses.
Objectionable matter was issuing in great abundance from the press,
particularly in the periodicals of the day.
Beside these, there were many books found on the tables of Friends,
and read in their families, which, containing some excellent sentiments,
had mixed up with them in intimate connection,
views adverse to the doctrines and testimonies which, as a religious Society,
we bear to the world.
He felt a concern to caution Friends on the subject of the
indiscriminate reading of books professedly religious.]

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his son Thomas.

[.signed-section-context-open]
Fifth month 2nd.

Our family are in usual health, except for your grandmother.
On Third-day she had an operation performed on her face;
the lump which she had so long borne, and which has latterly much increased in size,
was then removed.
Dr. Darrach and your uncle John were present; the former held the knife.
The patient behaved with great firmness, and is now doing well.
I believe you have heard of your sister Susan`'s indisposition.
She continues unwell, and may probably have to lie in bed some weeks.

I suppose some of the family have written to you about our late Yearly Meeting.
It was large and much valuable counsel was communicated in it.
We had +++[+++at our house]
the acceptable company of John Wilbur, also of George F. Reed,
classical teacher at Providence Boarding School;
who was convinced of Friends`' principles by the immediate operation of the Holy Spirit,
when he was a preacher among the Baptists, We found him quite intelligent and agreeable.
We had beside, your aunt Martha, her two daughters, and son Joshua,
your uncle and aunt Middleton, Susan Taber, (Elizabeth`'s aunt,) of New Bedford,
and Elizabeth S. Fell.

Our friend Daniel Wheeler arrived the early part of the week at New York,
but quite in poor health.
He is so much indisposed, that his continuance in this life is thought doubtful.

With respect to the important subject of where you are to settle,
I have not been able fully to make up my mind.
Outward prospects of gain ought to be subordinate to your best interests;
and I wish that to take place which will be for your good.

Before I close,
I will just give you a few particulars of the proceedings of our Yearly Meeting.
When we met on Second-day morning,
Jacob Green expressed how comforting to him was
the awful silence into which we were drawn,
and in which the wing of Ancient Goodness was felt to be extended over us.
There were many of us who would never meet again in this capacity;
and some dear elderly Friends present, who felt they should be of that number.
He wanted such encouraged.
He believed there was a precious seed preserved among the ancients,
the middle aged and the youth, and that better days were at hand for this Society.
By the minutes of the Meeting for Sufferings,
a sorrowful account of the slave trade was laid before us;
it appears to be increasing in extent, and attended with greater horrors than ever;
upwards of one thousand per day are the victims of it; separated from their native land,
a large portion of whom perish in the voyage to the land of bondage.

A memorial concerning our late Friend, Jonathan Evans, was read;
by which it appeared he was convinced by incidently looking into Penn`'s [.book-title]#"`No Cross,
No Crown`"# and seeing there a testimony to the Light of Christ in men.
The reading the answers to the Queries,
introduced the meeting into exercise on account of the continued
neglect of our members in attending religious meetings,
it being evident that the love of other things
is stealing away the heart from the love of God,
and that in this state there neither can be a growth in the life and power of religion,
nor a right qualification to fulfill the obligations we all owe to Him,
and parents owe to their offspring.
A desire was felt that the negligent might again be
laboured with in the restoring love of the gospel.
The introduction into Friends`' families of improper books, was also adverted to,
not only the light and frothy productions of the periodical press,
but also books on religious subjects, which contain along with much that is excellent,
sentiments at variance with our doctrines and testimonies.

We were much affected with hearing the report of the Committee on Indian Affairs.
It appears that the plans of avaricious men to drive
away those natives who have been under our care,
beyond the Mississippi, are likely to take effect,
in consequence of a pretended treaty obtained by unfair means,
having been lately confirmed in the Senate of the United States,
by the casting vote of the presiding officer.
The business +++[+++of the Yearly Meeting]
having been finished on Sixth-day afternoon, a solemn silence covered the assembly,
when Jacob Green broke forth with the voice of thanksgiving, "`Oh,
give thanks unto the Lord, for He is good;
for his mercy endures forever,`" with more to the same effect.

--

+++[+++In the Sixth month of this year Thomas Kite went to Cincinnati to visit his son,
and to see about establishing him in business there.
He left Philadelphia on the 15th, and thus wrote from Pittsburg on the 19th:]

[.embedded-content-document.letter]
--

I arrived at this dusky, smoky city last evening, about half-past eight o`'clock,
having been three nights and four days on my way here.
My fellow passengers were mostly agreeable people, and I have been but little fatigued.
I put up last night at the United States Hotel, where I am now waiting for breakfast,
intending immediately afterwards to visit the steamboats lying at the riverside,
to select one out of three which advertise to start for Cincinnati today.
I had provided myself with books for reading, but got very little of it attended to.
Between the striking and magnificent scenery,
and the conversation of many of my fellow passengers,
I could scarcely obtain the quiet attention to read with profit.
Though it is rather tedious to be so long on the way,
yet I still give the preference to the canal route.`"

[.signed-section-context-open]
Cincinnati, Sixth month, 24th.

I reached this place last evening about dark.
We had much detention, partly from grounding, because the river was very low,
and one night because the darkness was so great the pilot could not see the channel.
We had also to stop for wood and coal, to deliver freight and passengers,
and on several occasions to take in a fresh supply of the latter.
Several of those who went in the canal boat to Pittsburg with me,
continued in company to this place.
Two Presbyterian ministers were of the number,
who had been to the General Assembly and taken their wives with them.
They were quite agreeable, affable men,
as was also an elder of the same society who came on board at Wheeling,
and had been on the same errand.
Five days and a little more than a half,
was occupied in the passage down the river and the numerous detentions.
The weather was warm, yet we had mostly an agreeable breeze.
I was much occupied with looking at the banks of the river,
which have suffered much from unusually high flooding this season,
and in noticing the various towns which are scattered on either side of it.
The city is certainly a pleasant one for situation and general appearance;
and is surrounded by handsome eminences,
on which are a number of good looking country-seats.
The prospect into Kentucky, which seems close at hand,
(the river being low is sometimes not seen,) is very fine, two handsome villages,
one on each side of the Licking, being situated directly opposite this place.

When near the Ohio, the long paved slope down to the water, presents a singular spectacle.
Low as the water is, the bank is crowded with steamboats, taking in or delivering freight.
Some coming-to, from below, or from above;
others giving notice of their intended departure;
while many people are running to and fro.
As it presents so much activity now, I can readily imagine, that when business is brisk,
it must present a scene of great bustle.
I was in the market this morning.
Some kinds of provision were plenty,--beef for instance, and some good-looking mutton;
but I was disappointed in finding things higher in price,
and less neatly put up than I expected.
In some instances the warm, soft butter, was ladled out of a pot and weighed in scales.
Fruit was scarce.
A few watermelons from New Orleans were to be seen; some Morella cherries,
a few raspberries, very poor currants and about a quart of gooseberries,
being the principal fresh fruit I saw.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his son Thomas.

[.signed-section-context-open]
Philadelphia, Seventh month 14th, 1840.

I arrived in safety at home on Fourth-day afternoon last.
I suppose you felt somewhat surprised at finding that the
captain of the Boston kept so nearly to his last-named hour.
About six o`'clock the boat drew off and was soon under way.
In the morning we found ourselves at Maysville.
An alarm was given that two gold watches were missing,
and as two passengers had left us at that place,
it seemed to be settled in the minds of others, that they had stolen them.
But though this unpleasant circumstance occurred,
I had great reason to be satisfied with my choice of a boat.
We had a very respectable and orderly company,
no sign of a playing card having been made use of;
while on board "`The Flying Dutchman,`" we were afterwards informed,
four card tables were in use every night.
The passengers of the latter boat were discharged at Wheeling,
while our boat continued to Pittsburg,
where we arrived about eleven o`'clock on Sixth-day morning.

I dined at Pittsburg with a friend of Rachel Sheppard`'s,
and took tea with R. L. At nine o`'clock took the canal boat,
which was full to an unpleasant degree.
In the morning I stopped at Judge Breckenridge`'s, near Tarentum,
to pay his wife Caroline, a visit.
She was from home at a pleasant little village called Freeport, where I followed her,
and spent an agreeable day, taking my place in the next packet boat,
by which I had my passage in one not so much crowded.

On reaching home, I found my family as well as usual, excepting your dear grandmother,
whose health continues feeble.
She and your cousin Mary Walton, who is also an invalid, are gone to Frankford on a visit.
Very striking was the proof I received of the uncertainty of human life,
on finding no less than seven of my friends had departed this life during my absence.
Mary Gardner, a widow, belonging to Evesham Meeting; William Needles,
Elizabeth Kaighn and John North, of the Northern District; Elizabeth Archer,
Rebecca Peirce and Mary W. Brown, of ours.
The latter, our neighbour, lost a darling and only daughter a few months since,
and grieved much for her.
Her own illness was short.
When she died, your aunt Mary was sent for, but as she was absent at Ann Dowry`'s,
your mother went instead,
and with a relation of the deceased prepared the body for burial.
John North`'s case is very striking.
He had just been preaching in the first meeting on the
day of the Northern District Monthly Meeting;
on sitting down he was perceived to be gently falling over.
On being taken up and carried into the entry he quickly breathed his last.
The meeting continued, with scarcely any interruption, but with great solemnity,
until the time to go to business.
Friends then made an opening minute and adjourned for one week.
How needful always to live in such a state of submission to our Heavenly Father`'s will,
as to witness a preparation for our final change, whether it come early or late,
gradually or suddenly.

Several friends in Cincinnati spoke to me favourably of your correct deportment,
and particularly of your diligence in attending religious meetings.
This was a comfort to me, for every degree of preservation from evil is a blessing,
and every instance of dedication is to be encouraged;
but I want you to press forward after a perfect victory over the flesh, the world,
and the devil.
I long for you, that you may obtain the testimony of Divine approbation,
even as holy Enoch, who walked with God and had the testimony that he pleased God.
One remark you made and one only that I recollect gave me uneasiness.
It was what you said in favour of music.
I think if you should be tempted to become the owner of a musical instrument,
of any kind, or to attend at any place where music was practised,
and give way to temptation, it would be to yourself a source of weakness,
and to me of sorrow, if I knew it.
The consistent members of our Society,
have always been led by the Holy Spirit to give up these things, when they became such,
though in the days of their ignorance of the precious Truth,
they may have practised them.
John Thorp, a valuable minister in England, who deceased in 1817, thus expresses himself:
"`When a boy about fourteen years of age, my attachment to music and singing was such,
that when walking in the lanes and fields in an evening,
I frequently gratified myself by singing aloud,
and indulged therein even after my mind became uneasy with the practice,
until in one of my solitary evening walks, and when in the act of singing, I heard,
as it were, a voice distinctly say, '`If you will discontinue that gratification,
you shall be made partaker of a much more perfect harmony.`'
John Churchman says in his Journal:
"`I had taken great delight from a child to play with whistles
and pipes made of the bark of small branches of trees,
and of straws of wheat and rye,
but now it grieved me to observe children to delight therein;
and I ventured to tell my mind to some concerning these things.`"
The same Friend says he considered it a base consumption of precious time,
which man must be accountable for, which, if enough regarded, instead of music,
whistling, and singing many foolish and profane songs,
many would have occasion to lament and weep for their misspent time.
He cautions parents to beware of indulging their children in anything
which may impress their tender minds with a desire after music,
etc.:
and to direct the minds of their offspring to attend to the
voice of Him who called to Samuel in the days of old,
and remains to be the same Teacher of his people in this age.
I have enlarged upon this subject,
because I wish your sentiments on all points to be correct,
knowing that sound sentiments have an important bearing on sound practice.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Rebecca, then at East Bradford.

[.signed-section-context-open]
Seventh month 24th.

+++_______+++`'s son H. was buried yesterday.
He looked like a strong, healthy young man.
He had been rather unwell for some weeks, but his last illness continued about ten days.

He was mostly delirious.
He had one lucid interval, and on the expressions he then made use of,
hopes are entertained of his peaceful close.
Happy for surviving relatives, when they can look back after such bereavements,
not merely on deathbed expressions, but on a life of dedication.
Your grandmother has gone to Fallowfield, accompanied by your aunt Mary and little John.
By a letter received by W. B. F. from cousin James R. Greeves,
it appears that he has written to Aaron.
Of course I suppose you have the particulars of his voyage out.
+++[+++James R. Greeves accompanied Jacob Green to Ireland,
where he paid a visit among his own relations.]

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his son Thomas.

[.signed-section-context-open]
Seventh month 27th.

Your grandmother`'s health continues poor.
She went on Fourth-day to Fallowfield, accompanied by your aunt Mary and John L. Kite.
I do not know that I have more to say than to add your mother`'s love and mine,
and our continued desire for your preservation from evil, and growth in the Truth;
that whatever things are just, pure, lovely, and of good report,
may be meditated on by you, and may be exemplified in your life.
Then will the work of righteousness in your experience be peace,
and the effect thereof quietness and assurance forever.

--

+++[+++In the Eighth month, Thomas Kite attended Concord Quarterly Meeting,
visiting his relations in Chester and Delaware counties,
and then Bucks Quarterly Meeting.
His mother, whose health had long been declining, was now sinking fast.
She returned about the close of summer from Fallowfield, desiring as she expressed it,
to die at home.
She had been all her life a diligent letter-writer,
and even now that death seemed so near, and weakness was so great,
she made some efforts that way.
The last attempt was to greet her granddaughter Susanna and her husband;
she was not able to finish it.
We are willing to insert it as a mark of her manner,
and the spirit in which she was waiting for her close.
It was written about the beginning of the Tenth month.]

[.embedded-content-document.letter]
--

[.salutation]
My dear grandchildren:

From my sick chamber,
I might say my sick bed +++[+++I write]. I am propped
up in bed and find it hard work to breathe;
yet mostly get some relief after waiting a time.
My limbs are much swollen, and I find much difficulty in getting to bed.
Food I take in small quantities,--a soft boiled egg for breakfast,
a little thin broth for dinner, and a few oysters for supper.

I do not expect ever to be much better,
but try to endure all with as much patience as I can,
knowing that it is the lot of all that live to take a share of suffering.
I do not think mine will be so heavy but that the Good Hand will help me to bear it.
A week or two back, I did not feel so comfortable,--I seemed to have lost my way;
I could not see where the good land lay.
I often looked out for some sign or token, but all seemed like the fading autumn.
Then it came into my mind,
that the good land was not among the briars
and thorns of this world--I must look ahead!
Since then I try to be content with the share that comes to my lot.

We hear of many sick and suffering.
I expect you have heard of the sudden death of Sarah E., and since then of her sister.
One night last week Mary Ann was taken somewhat in the same way,
but is now better,--quite recruited.

It would be very pleasant to see either of you!
What a great undertaking to scribble a little!
Mary Walton is with me; our family mostly gone to meeting.

Second-day morning.
I had a more comfortable night.
William smiles to see his grandmother, pen in hand.
He and his wife are very kind in bringing me little nice tidbits,
such as they think I can eat.
Indeed all are kind, and willing to visit me and make me comfortable.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Mary Kite to Sarah Sharpless.

[.signed-section-context-open]
Eleventh month 14th.

Your grandmother has been much as for many weeks past, until the last three days;
since which she has had more oppression, and her limbs much more swollen,
so that it is difficult for her to move them.
She does not appear to look forward with dread to the future,
or to anticipate the coming trial, leaving all with the Good Physician,
who knows what is best for her.
She sometimes says, when asked how she is, "`Gradually going.`"
Sometimes she says, "`It takes time for nature to wear out.`"

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Susanna.

[.signed-section-context-open]
Eleventh month 26th.

William was kind enough to impart the contents of your epistle to himself and wife;
and cousin Edith and Ann have entertained us with some account of your domestic events.
They are very pleasantly with us.
We had them at our Monthly Meeting today.
Cousin Edith was concerned to say a little in the meeting for worship.
I was yesterday at the Monthly Meeting for the Southern District,
and Lydia Deane was there,
a friend whom you may have heard of as having attended the Yearly Meeting last spring.
Her residence is in New York,
and she is here with a prospect of visiting the
families which compose Orange Street Monthly Meeting.
Her concern met with the approbation of the meeting,
and I suppose she commenced her labours this morning.
Elizabeth Evans is absent on a similar concern for the
two Monthly Meetings of Haddonfield and Chester,
(New Jersey). William
Evans has lately returned from a religious visit to the
meetings of Purchase and Westberry Quarterly Meetings,
in the State of New York.
Thus you may perceive the Lord`'s servants are not wholly unemployed.

You have probably heard your mother and I have been to Greenwich.
We understood that our friends George and Mary Mickle had such a visit in prospect,
and were willing to take us in their carriage.
We accordingly went to Woodbury +++[+++Eleventh month 6th],
the Sixth-day before Salem Quarterly Meeting, lodged at George`'s,
and the next day went to Greenwich.
A very unpleasant occurrence marked the evening of our arrival.
One of our horses had exhibited marks of indisposition before we reached Greenwich,
and died about an hour after our arrival.
On First-day we attended Greenwich Meeting; dined at John Sheppard`'s,
where we made our home, and in the evening took tea with John E. and Margaret.
On Second-day our kind friends George and Mary left us,
and returned home to be at the funeral of James Saunders, who died of consumption.

We stayed at Greenwich until Third-day, paying some agreeable visits,
and in the afternoon accompanied John and Mary to Mannington, near Salem,
making our home at Jonathan Freedland`'s, while we continued in that neighbourhood.
Ann Eliza Yarnall seemed truly glad to see us.
I attended Select Quarterly Meeting on Fourth-day,
and both of us that for business on the day following.
We dined at Elizabeth Miller`'s after the first, and Rhoda Denn`'s after the second.

On Fifth-day afternoon George and Mary Mickle took us to Sculltown on our way home.
Our visit to A. and S. Scull was very agreeable.
We dined with our kind friends George and Mary at their farm-house near Woodbury,
and came home in the evening car.
But for the loss of the horse, our whole excursion would have been peculiarly pleasant,
as affording the opportunity of renewing our interaction with
many Friends to whom we are closely united,
and particularly in noticing in some of them an increase of
those fruits of righteousness which are to the glory of our
Heavenly Father when brought forth in his obedient children.
May such fruits abundantly appear in the case of my dear child and her companion in life!

--

[.offset]
+++[+++On the decease of his mother, Rebecca Kite, Thomas Kite made the following memorandum:]

[.embedded-content-document.testimony]
--

My dear mother departed this life Twelfth month 20th, 1840,
in the seventy-sixth year of her age.
Her piety was of a cheerful character; although she had many trials to endure,
her faith did not fail; and near her close she spoke of the bright pathway before her.
At another time she repeated the substance of the
Psalmist`'s expression '`a broken and a contrite heart,
O God,
you will not despise!`' It was a satisfaction to me to have had my
parents to reside with me for several years before their departure,
and a great comfort to believe that, through the mercy of God in Christ Jesus,
they each found acceptance with Him, and have been joined to the company John saw,
of whom it was said, '`These are they which have come out of great tribulation,
and have washed their robes and made them white in the blood of the Lamb.`'

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to Joseph Edgerton

[.signed-section-context-open]
Philadelphia. Twelfth month 16th, 1840.

[.salutation]
Dear Friend, Joseph Edgerton:

I have frequently of late remembered that I am in your
debt for a very acceptable letter dated Tenth month 29th. It not only
strengthened the feelings of brotherly affection I entertain for you,
but communicated interesting information concerning the
late Yearly Meetings of Ohio and Indiana;
so that I ought in common justice to endeavour to make some return,
which I shall endeavour to do by giving you some
little hint of how we are getting along here.
The Apostle James says "`The fruit of righteousness is sown in peace of them
that make peace,`" but if it be true that the tree is known by its fruit,
something of a very different nature has been sown among us,
and what that has been you are well aware.
But little change has recently occurred; yet I hope that little is favourable,
and that some Friends are less unkind in their feelings than they were;
but there are others whose minds continue uncomfortable.

One effect of the present state of things I particularly regret.
Most of our elders are quite aged,
and there are no doubt gifted men and women in younger life,
who might usefully be placed in that important station, if it could be done in the unity,
of which at present there seems no certainty.
But the cause is the Lord`'s, and He can make a way where no way appears, in his own time,
and enable his dependent children so to wait upon Him,
that patience in them may have its perfect work.
We are not, however, forsaken;
the dear Master frequently is graciously pleased in our
solemn assemblies to afford us a token for good,
by the manifestation of his immediate life-giving presence,
as well as by qualifying his servants and
handmaidens to speak well of his excellent name.
He has also, as I believe,
been turning his hand upon the little ones to prepare them for his own service;
and several of these in different parts of our Yearly Meeting
have recently come forth in a public testimony to the Truth.

Our friend Elizabeth Evans has gone to pay a religious visit to the
families of Haddonfield and Chester Monthly Meetings in New Jersey.
Lydia Dean, of the City of New York,
is engaged in a similar visit to the families of the Southern District Monthly Meeting.
Thomas and Elizabeth Robson were lately heard of at Charleston, South Carolina.

John Warren and Samuel Taylor passed through
this place lately on their way to North Carolina.
Our boarding school at Westtown is largely supplied with scholars for the present session.
It has 131 boys and 121 girls.
We are favoured with suitable teachers, not only as regards literary acquirements, but,
we hope, they mostly are concerned for the religious welfare of the pupils;
and a comfortable hope is entertained,
that the institution is fulfilling what our friend
Thomas Scattergood had a prophetic foresight of,
many years ago: "`This,`" he said, "`is a plantation that the Lord will water.`"
May the Divine blessing rest upon it and upon your similar undertaking.
We are making efforts to have our select school for boys, in this city,
more thoroughly what is desirable.
That for girls, has for several years very much answered our desires.
My dear mother has for some time been in a declining state of health.
She appears to be drawing towards her close.
I mentioned to her that I was writing to you, and she said,
"`Give my love affectionately to him, and tell him I expect to see him no more!`"
She seems in a clear, calm and resigned state;
waiting for the summons that shall call her hence.
Her sufferings have been great from a disease of the heart,
combined with dropsy and erysipelas; but she has been mercifully preserved in patience.
My wife also desires her love, as does my sister Mary and daughter Rebecca.

Sarah Hillman, the daughter of the widow mentioned in your letter,
was at my house yesterday.
Her health is delicate, yet she is alive in the Truth,
and at times much favoured in her public ministry.
My nephew by marriage, James R. Greeves,
who accompanied our dear friend Jacob Green to his own habitation, has returned;
and gives a pleasant account of the peaceful state of his (Jacob`'s) mind.
Yet he is not eating the bread of idleness,
having commenced a visit to the families of six Particular Meetings,
composing the Monthly Meeting of which he is a member.

With love to dear Benjamin Hoyle, your respected companions,
William Green and his daughter, who was at our select school,
I remain in the fellowship of the Gospel, your friend,

[.signed-section-signature]
Thomas Kite

[.postscript]
====

The death of John Comfort is felt as a great loss,
he being in the prime of his usefulness; also Josiah Reeve, although he was much older.
They were each substantial elders.

====

--
