== Chapter XVII.

[.chapter-synopsis]
* 1842.
* Letters
* Visit to Nottingham Quarterly Meeting
* Thomas Kite, Jr.`'s long absence from home
* Visits Bucks Quarterly Meeting.

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Rebecca.

[.signed-section-context-open]
Second month 7th, 1842.

Though I have been fatigued with a long Quarterly Meeting,
which brought on a considerable headache, yet feeling somewhat relieved this evening,
I take my pen to give you some account of things that I suppose will interest you.
First, your little nephew +++[+++William`'s son Thomas]
is very poorly, and his parents seem much discouraged about him.
I know not what they call the complaint, but at present he seems to be sinking under it.
Your aunt Mary has gone to spend the night with him.
There have been several affecting instances of the
uncertainty of human life among our friends lately:
On Fifth-day morning, about 3 o`'clock, Joseph Ely died suddenly.
He was awake and conversing with his wife a few minutes before.
She heard him take a long breath, and he was at once insensible;
and before Charles Roberts, who was immediately sent for +++[+++a few doors off]
could get to his house, he was dead.
The afternoon of the same day, Asa Walmsley`'s daughter Ann, died almost as suddenly.
She had been in poor health, was on a visit to the city,
and had just parted with a friend, who had called on her,
when she passed away to another state of being.
And lastly, on Seventh-day afternoon, our friend, Peter Thomson, was called away.
His health had been declining for some weeks, but he mostly went into his office,
and spent a part of the last day in it, transacting business.
I understood, that in signing his name he remarked,
that he thought it was the last time he should do it.
He walked into his chamber, and was about to prepare to undress, when he died,
sitting in his chair.
Both Elizabeth and her daughter Hannah have been unwell,
and this unexpected stroke is a close trial.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Same to Same.

[.signed-section-context-open]
Second month 11th.

From the tenor of a part of your letter, which we received by yesterday`'s stage,
I infer you will not be surprised to hear of your little nephew`'s decease,
which took place on Fourth-day morning, a few minutes after six o`'clock.

After being laid out, in order for interment, the corpse looked very sweet,
and like one asleep; a smile seemed settled on the countenance,
as if he had a pleasant dream.
The funeral took place yesterday afternoon in the Arch street ground.
Your brother and sister seem affected with the loss of their little darling;
but there are so many considerations to alleviate
sorrow in the case of a child dying in infancy,
that I have no doubt they will become reconciled to the stroke.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to Rebecca Walton.

[.signed-section-context-open]
Mount Pleasant, Ohio, last of 2nd month, 1842.

I hope when you are joined in outward membership to the Monthly Meeting of Short Creek,
you may become a true burden-bearer,
and be increasingly joined to the living among them in Gospel fellowship,
and in concern for the advancement of the cause of Truth,
and the support of our Christian testimonies and discipline.
Also that your whole spirit, conduct and conversation,
may evince you to belong to the dear Saviour, that thus,
whether a long or short life should be allotted you, in our Heavenly Father`'s providence,
you may be prepared for the everlasting inheritance.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Rebecca.

About going to the wedding;
I leave it entirely to your uncle Nathan Sharpless +++[+++Superintendent at Westtown,]
and yourself to settle; only suggesting my wish, that wherever you go,
your concern may be unabated to stand approved in his sight,
of whom it is said "`The Lord is a God of knowledge, by Him actions are weighed.`"

Fourth-day noon.
I heard yesterday that Sarah Emlen and cousin Edith were to
have a meeting at a factory near Leiperville this afternoon
and would probably be at Chester Meeting tomorrow.
+++[+++They had a minute to appoint meetings in their Quarter.]
I notice what you say of your spiritual state, but have little to say on that subject.
I believe your Heavenly Father designs you for his own use,
but many humiliating baptisms are needful to break down your own will,
and bring all within into conformity to his.
Keep inward to Him, and He will turn his hand upon you, and purely purge away the dross,
and take away all your tin.

In the process of effecting this, much anguish of spirit may be your portion,
but endeavour patiently to bear it; meanwhile whatever seems to be required,
whether it be in the way of doing or forbearing, endeavour to be an obedient child.
While it is profitable to feel our weakness,
yet it is not so to plead our consciousness thereof as an excuse for disobedience.
To sum up all in a few words, remember the promise, "`Be faithful unto death,
and I will give you a crown of life.`"

--

[.embedded-content-document.letter]
--

[.letter-heading]
Same to Same.

[.signed-section-context-open]
Third month 23rd, 1842.

I went on Seventh-day, in company with Mary R. Carpenter and her daughter Rachel,
to the funeral of our friend Rachel Bullock.
It was largely attended, and I believe was satisfactory.
She will be much missed, not only in her family, but in the meeting and neighbourhood.
She was favoured with a calm and composed mind near her close,
and could see nothing in her way in looking towards the everlasting state of happiness.
Elizabeth Pitfield and Sarah Hillman have concluded their visit,
with the exception of one family, in which there is sickness.
They appear to have been helped through their arduous service.
In sitting with Sarah yesterday,
I remembered the dear Master`'s question to some of his earlier labourers,
and their reply, believing she could unite with them therein;
"`When I sent you forth without purse or scrip, did you lack anything?
and they answered, Nothing, Lord.`"

The Yearly Meeting seems near at hand;
and some exercise begins to be felt by concerned Friends,
that everything may be conducted at that season,
to the praise of the Great Helper of his people.
With the salutation of my love,
and the renewed desire that you may be kept
faithful to the discoveries of the blessed Truth,
and that all things may work together for your good, through the Divine blessing,
I conclude.

--

+++[+++About this date, Thomas Kite received a letter from his daughter Susanna,
containing the following passages:]

[.embedded-content-document.letter]
--

Although contented in our allotment,
we cannot but feel anxiety in regard to the disturbed state of public affairs;
and many thoughts are sent towards my dear friends in the city,
whom I fear may be involved in difficulty; particularly you, my dear parents,
whose days for active exertion seem to be drawing to a close.
It will seem very trying, if your means for a comfortable subsistence should fail.
It is a day of perplexity and trouble, but perhaps for the salt`'s sake,
a preserving Hand may be outstretched still;
may He overrule these troublesome times for good!

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Susanna.

[.signed-section-context-open]
Third month 25th.

We received your letter by David Garrett last evening.
It is always pleasant to hear from our children,
and your expression of solicitude on our account, in these remarkable times,
was satisfactory.
Another bank has closed its doors, in which I own a number of shares;
yet I do not feel cast down.
A merciful Providence has hitherto sustained and protected me,
and I endeavour peacefully to rely upon Him, trusting that He will make a way for me.
Our men in business find many difficulties to encounter.
The banks which have resumed payments in coin appear to be sustaining themselves.
So much for worldly matters.
This morning your cousin R. Walton had a letter from your brother Thomas,
containing the first intimations of his movements we have had since he left home.^
footnote:[He had left Cincinnati to go to New Orleans to collect a debt.]
It was dated the twelfth of last month on board
a steamer bound down the river Mississippi.

He seems to have been much interested with his voyage,
but we are anxious for later intelligence.
Three of the elders +++[+++of our Yearly Meeting]
have deceased within a short time, Margaret Shoemaker, widow of Charles, of Abington;
Rachel Bullock, of Wilmington; and Elizabeth Cooper, wife of Benjamin,
who was buried yesterday at Newton, near Camden.
Such removals often awaken the desire that younger
Friends might be favoured to bow to the Power that,
as submitted to, "`would purely purge away their dross,
and take away all their tin,`" and prepare them as successors in the Church militant,
to those who have finished their work,
and are safely landed in the realms of light and everlasting peace.

--

[.offset]
+++[+++Extracts from Thomas Kite`'s Diary]

Fifth month, 1842.
I obtained a minute in the Fourth month to visit the
meetings composing Nottingham Quarterly Meeting.
I set off on Third-day, Fifth month 10th, and went to the house of my son-in-law,
Aaron Sharpless, where I lodged.
The next day attended Birmingham Meeting, where my wife`'s nephew, Joshua Jefferis,
was married to Rachel Hoopes.
Way opened to set forth the nature of the Gospel dispensation,
in contradistinction to the outward ceremonies and observances of the law.
I had to treat of the Lord`'s supper, as being altogether inward and spiritual.
I was told after meeting,
that a person was present who had joined in membership with the Roman Catholics.
In the afternoon I went to London Britain, where my brother-in-law, Joshua Sharpless,
readily agreed to accompany me to the meetings I had in prospect.

On Fifth-day the 12th, we rode to the house of Joseph Balance, Little Britain.
That afternoon we attended the Select Quarterly Meeting, which began at three o`'clock.
I went home with a friend, who is a widow,
and had a religious opportunity with her and her two daughters.
On Sixth-day +++[+++13th], we attended the Quarterly Meeting.
It is composed of very few members.
Best Help was near, strengthening to extend an invitation to the various classes present,
to gather to the place of waiting,
that they might be favoured to experience a renewed
qualification to engage in the Lord`'s work.
On Seventh-day morning +++[+++14th], we visited one,
who on some offence taken at members of the meeting, wholly declined attending it,
and had resigned his right in Society.

We had an opportunity with him, in the presence of his wife and children,
the latter being young.
The same day attended an appointed meeting at Little Britain,
for the members of that meeting--some professors with us, and a few others,
being present.
The subject principally treated of was, the doctrines of the Gospel,
and the means employed by Divine Wisdom to bring mankind to the experience of that
state of true poverty of spirit which is pronounced blessed by our Lord.
After an opportunity at Joseph Balance`'s, where we had lodged, we set off for Deer Creek,
crossing the river Susquehanna at Connewingo bridge.
At Darlington we found Elisha Cook, waiting to conduct us to his house, where we lodged.

On First-day +++[+++the 15th], we attended Deer Creek Meeting,
where the doctrines of the Christian religion as held by us,
were opened to a mixed auditory.
After a religious opportunity in the family of Dr. T. Worthington, where we dined,
we set off for Nottingham, passing the river over a bridge near Port Deposite.
We lodged at William Waring`'s; and the next day +++[+++16th]
attended an appointed meeting at West Nottingham, made up of Friends and others,
wherein spiritual worship, and true Gospel ministry, were set forth,
and various states spoken to,
principally some who were in a disposition to put off to a
more convenient season their obedience to manifested duty.
We dined at T. Levering`'s, and had an opportunity in his family,
his married son and wife being present.
In the afternoon we went to see a friend,
who had indulged a spirit of hardness towards some of his fellow-members,
until it had induced him very much to decline the attendance of religious meetings.
We had a heart-tendering opportunity with him, his family being present.
Among his children is a tender-spirited, religiously-concerned daughter,
who seems likely to become a useful member of our Society.

We returned to William Waring`'s to lodge, and the next morning +++[+++17th],
after a parting opportunity with the family, we set off homewards.
We called on a family who had separated from Friends at the time of the great division;
after leaving them,
I was constrained to return and submit to have a religious opportunity.
They willingly made way for it;
and the way of salvation by Jesus Christ was preached to them.
Reached Joshua Sharpless`'s to dinner, and paid some social visits in the afternoon.
Had a family sitting with Edward Sharpless and wife.
Lodged at his father`'s. The next day +++[+++18th]
paid several visits; and on Fifth-day morning +++[+++the 19th],
had an opportunity with George Sharpless and his wife,
in which counsel and encouragement were offered to them.
Then proceeded to London Grove to attend the Western
Quarterly Meeting for Ministers and Elders.

At our first sitting down it was a low, suffering season, which continued for a time;
but a little light springing up, strength was afforded to comfort the mourners.
Our friend Caleb Pennock, aged about ninety-one years,
and green and lively in his old age, was enabled to speak to edification,
and the meeting ended well.
Dined at Samuel Swayne`'s, and lodged at Joshua B. Pusey`'s;
the house lately occupied by his kinsman, Isaac Pusey,
whose recent loss is severely felt in this part of the Society.
I had a religious opportunity with the family in the morning,
before proceeding to the Quarterly Meeting +++[+++20th]. It
was a time of depression in the first meeting;
but at length an opening presented; and standing up with it,
I was enlarged beyond expectation.
I went to Aaron Sharpless`'s to lodge; and the next day +++[+++21st]
reached home, thankful for the preservations and help extended to me during this journey.
Elizabeth C. Mason, Edith Kite, Thomas Evans and William Hodgson, Jr.,
under appointment of the Quarterly Meeting, paid a visit in this month +++[+++Fifth]
to the meetings of Muncy Monthly Meeting, and many of the families composing it.

[.offset]
+++[+++While the committee was absent on this labour of love,
Thomas Kite thus wrote to his wife:]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Fifth month 24th, 1842.

Elizabeth Hodgson kindly called on me yesterday with a message from you,
received in her husband`'s letter,
which also gave information of the committee`'s attending Muncy Monthly Meeting.
I was glad to hear of your proceedings, and of your health.
I hope whatever your hands find to do, in the clear unfoldings of Divine Wisdom,
you may do it with your might, not consulting with flesh and blood,
but giving up to the heavenly vision.
I feel for you, believing the service you are upon to be arduous and important,
and much desire that by keeping close to the safe Director and Preserver of his people,
each one of you may return with the answer of peace.
I feel particularly for dear Elizabeth,
and hope this journey may prove strengthening to her, mentally and bodily;
and that henceforth she may do, as Paul says he was enabled to do,
'`forgetting those things which are behind,
and reaching forth unto those things which are before,
I press toward the mark for the prize of the high calling of God in Christ Jesus.`'

--

[.embedded-content-document.letter]
--

[.letter-heading]
Same to Same.

[.signed-section-context-open]
Fifth month 27th.

I received your acceptable letter.
I am truly glad to hear of yourself and company;
and desire the blessing of the Lord may rest upon you and upon your labours.
In my absence, and probably before you left home, brother Nathan wrote to Jabez Reynolds,
inquiring what he had heard of Thomas.
Today he has an answer,
by which it appears that Jabez Reynolds had a letter dated Fourth month 16th,
about a month later than we had previously been made acquainted with his proceedings.
He was then well, and in good spirits.
A man indebted to him, but without other means of payment,
prepared two vessels loaded with lumber, which our son accompanied,
and the proceeds of which, when sold, was to be paid to him.
He was on the Mississippi, near the mouth of the Arkansas river.
He may have written to us and his letters miscarried.
There seems no other way, than to commit him to the protection of our Heavenly Father,
whom we have each proved to be good and gracious.
We understand William Brinton, and his more aged sister Mary Moore,
deceased within two days of each other, and that their brother Moses Brinton, who is,
I think, also older than William, was lately considered to be near the close of life.

At our Monthly Meeting on Fifth-day, we had our friend William Evans very acceptably.
He was afresh anointed to preach the everlasting Gospel in the first meeting,
and in the second he made some suitable remarks.
There was nothing of a very particular character in the business of our apartment,
and we transacted what we had to a good degree of satisfaction.
The minute of the Quarterly Meeting of Ministers and Elders,
on the subject of the nominated elders, was with us, and as a matter of course,
placed upon record.

I have seen a copy of the charge exhibited against our friend John Wilbur,
and am surprised, not only at the course taken,
but at the grounds upon which the charge rests.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Same to Same.

[.signed-section-context-open]
Sixth month 3rd.

On Second-day I went to the Select Quarterly Meeting at Burlington.
John Cox was not well enough to be present.
I returned in the evening,
and the next morning went there again to attend the Meeting for Business.
Our aged friend was at meeting, but did not sit to the close.
The concern of S. Craft`'s wife to attend Ohio and Indiana Yearly Meeting,
and some meetings within their limits, was united with, and she liberated to the service.
I was satisfied with being there, believing I was in my right place.
I lodged at Elizabeth Coleman`'s, and came home on Fourth-day.
Having drawings to be at Gwynned Monthly Meeting, I went there yesterday,
accompanied by Jeremiah Hacker.
Ezra Comfort was engaged in the ministry, and I had something to communicate.
We dined at Hannah Williams`'s; visited Ezra Comfort`'s in the afternoon,
and came to Jeremiah Hacker`'s place to lodge.
On returning home this morning,
I found an invitation to the funeral of Dr. Joshua Whitall`'s wife.
I was much attached to Sarah Ann, and propose going to her funeral,
which takes place this afternoon.
She died of inflammation of the lungs, as I understand, with only three days`' illness.
Another solemn warning is thus communicated,
that we be found endeavouring to be prepared for our final summons.

--

+++[+++In a letter to his daughter Rebecca, of Sixth month 7th, Thomas Kite,
speaking of his visit to Burlington Quarterly Meeting, says:]

[.embedded-content-document.letter]
--

I walked out in company with my relation, Robert Thomas, to Hickory Grove,
the late residence of the poet Samuel Smith, but now occupied by his sister, Hannah Mott,
whose only son, Richard, being designed for a farmer,
is there engaged in learning that business.
It is a perfect wilderness of plants, flowers and trees,
having been neglected since the owner`'s death.
Hannah and her son will have employment enough in reducing it to order.
'`I found an invitation to the funeral of Doctor Whitall`'s wife, whom, perhaps,
you remember as Sarah Ann Rogers.
I had a friendship for her,
believing her to be one of the travellers towards the heavenly Jerusalem;
and being inclined to attend at the interment of her remains,
I accompanied her relatives +++[+++John]
Mickle and Mary Whitall, with their sister Hannah, there.
She was ill but three days, her disease, inflammation of the lungs.
The day of her death was better to her than the day of her birth.
The trials of life had been sanctified to her, and she found her merciful Saviour,
in whom she was early taught to believe,
was able to keep that she had committed unto Him against that day.
She died triumphing in the faith.

I have been reading a pleasant memoir of a young Friend, Mary Ann Gilpin,
who died at about twenty-five years of age.
Part of her time was occupied in teaching;
and she seemed to dwell under a deep sense of the importance
of making right impressions on the objects of her care.
I have also the account of John Barclay,
with copious extracts from his diary and from his letters.
He was a lovely character; and appears to have ripened fast in religious experience.
He was a minister fifteen years,
and closed his earthly course at forty-one--having been a bright example of
Christian simplicity and devotedness--a burning and a shining light.

--

+++[+++The anxiety of Thomas Kite and family respecting his son Thomas,
continued to increase during the Sixth month.
No information was received from him,
and his friends at Cincinnati had almost lost all expectation of ever seeing him again,
fearing he had fallen a victim to the unhealthiness of the climate about New Orleans,
or to some of the casualties so common on the Mississippi river.
The uneasiness of his friends was, however, happily dispelled.]

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Rebecca.

[.signed-section-context-open]
Seventh month 4th, 1842.

We were comforted this morning by receiving a letter from your brother Thomas,
announcing his safe return to Cincinnati.
He speaks of having had a troublesome time,
but thinks he was as successful in the business he went on,
as could reasonably have been expected.
He seems thankful that he is among his friends once more;
and we feel emotions of the same character.
I have written in order to relieve your anxiety.
With affectionate desires for your preservation from evil,
and for your growth and establishment in the everlasting Truth, I remain your father, etc.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to son Thomas.

[.signed-section-context-open]
Seventh month 10th, 1842.

We have cause gratefully to acknowledge our Heavenly Father`'s care over you,
and to say with the patriarch, "`It is enough; Joseph, my son, is yet alive.`"
May we join you in endeavouring to evince a proper sense of this, and every other mercy,
by striving to live more entirely to the Lord;
and then we shall experience the truth of the declaration,
"`In all your ways acknowledge Him, and He shall direct your paths.`"
Uncle John Letchworth was at our meeting on Fifth-day and dined with us.
Many of our Friends who sympathized with us in our anxious solicitude about you,
seem to rejoice in our glad tidings.
With strong desires for your future welfare every way,
but more especially for your growth in religious experience,
through obedience to the manifestations of Divine Light in your heart,
I remain your affectionate father.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Rebecca.

[.signed-section-context-open]
Seventh month 19th.

A member of the Hicksite Meeting at Salem,
who has for some time been attending that of Friends, came a few weeks ago to this city,
for medical aid, being much indisposed,
yet not so as to prevent his attending our meeting,
which he did diligently until last Fifth-day, inclusive.
On First-day morning he was not well enough to go.
In the evening I was sent for to see him;
on going I found that a sudden attack had deprived him of the power of speech,
and probably of consciousness.
I remained with him until his close, which took place twenty-two minutes past eight.
From his anxiety to know his salvation wrought out, his diligence at meeting,
his intention to condemn his joining with the Hicksites,
the childlike simplicity of his mind,
and the quiet he was favoured to feel near the solemn winding up,
I feel a comfortable hope that all is well with his immortal spirit.

--

[.offset]
+++[+++Of the Quarterly Meeting, held Eighth mo.
1st, 1842,
one of the family thus writes:]

[.embedded-content-document.letter]
--

Our Quarterly Meeting
was rather remarkably comfortable for these times.
Elizabeth Evans was soon on her feet with the language,
'`Let not the mighty man glory in his might, let not the rich man,
etc.,`' showing that the true rejoicing of the Christian
was not to be for the increase of wealth,
knowledge, power, or any earthly good; but in the Lord alone.
She spoke of earthly possessions as fleeting,
and that the enjoyment derived from them must fail.
She had been reminded of two circumstances recorded in Scripture;
the first of which was that of the man whose idols of gold,
and his priests on whom he depended, had been taken from him,
'`They have taken away my gods and my priests, and what have I more.`'
This man`'s condition she contrasted with that of Habakkuk when he could say,
'`Although the fig tree shall not blossom, neither shall fruit be in the vine;
the labour of the olive shall fail, and the fields shall yield no crop;
the flock shall be cut off from the fold, and there shall be no herd in the stall;
yet I will rejoice in the Lord, I will joy in the God of my salvation.`'
Hannah Gibbons followed in an affectionate exhortation
to the youth to be willing to take the yoke of Christ,
and become his followers.
William Evans then powerfully addressed the youth, particularly the young men,
on the necessity of bearing the cross,
and becoming prepared to take the places of those who had been removed,
or were about being removed from the Church militant.
Thomas Kite addressed the aged, exhorted to faithfulness and perseverance to the last;
mentioning the cases of Simeon and Anna, who having waited for the Lord Jesus,
were permitted in old age to speak of Him to all that looked for Him in Jerusalem.
H+++.+++ L. S. united with the last communication,
and Mercy Ellis closed the opportunity with supplication.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Rebecca.

[.signed-section-context-open]
Eighth month 9th, 1842.

I got home comfortably on Fourth-day evening.
Finding ourselves in time for Chester Meeting, T. E. and I stopped there and attended it;
and afterwards dined at J. J. Maris`'. The railroad car
brought me to the city in the evening.
Your mother and I, and A. N., attended Merion Meeting on First-day,
where I saw our relation Ann Wetherill, who said she had been at Westtown,
and that you were in bed with an inflamed eye.
Please get some one to write us by Fifth-day`'s stage, and let us know how you are.
Thomas and Elizabeth Robson are in the vicinity of the city,
paying leave-taking visits to their particular friends.
I believe they were on First-day at Woodbury.
S+++.+++ Grellet continues very ill, although his symptoms are perhaps somewhat less alarming.
My dear child; may every trial, bodily or mental, less or greater, be sanctified to you.
The great business of our lives, is to bring glory to our Creator and Redeemer,
and to become prepared by the purifying operations of the Holy Spirit,
for a blessed and happy immortality.
That this may be your experience, is the earnest desire of your truly affectionate father.

--

[.offset]
+++[+++Extract from Thomas Kite`'s Diary:]

Having for some time felt a concern to visit the meetings of Bucks Quarterly Meeting,
I acquainted our Monthly Meeting therewith, in the Seventh month,
and obtained a minute of its unity.
Benjamin Albertson also had a minute to accompany me.
We set off on Third-day, Eighth month 23rd, and went to James Moon`'s to lodge.
The next day +++[+++24th,]
we attended the Quarterly Meeting for Ministers and Elders.
The language of the Psalmist was revived, '`In the multitude of my thoughts within me,
your comforts delight my soul;`' and the language of
encouragement was handed to the Lord`'s exercised children.

Lodged at James Moon`'s; and on Fifth-day +++[+++25th,]
attended the Quarterly Meeting for business.
In the first meeting, B. Cadwalader appeared in a short testimony,
followed by my aged relative, John Letchworth: after which,
out of a state of great weakness,
I was enabled to set forth the necessity of bearing the yoke and cross of Christ.
Elizabeth Evans followed in a well adapted communication.
Towards the close of the second meeting,
William Evans was excellently engaged in pointing out
the danger of degenerating into a form of religion,
without life and power.

Lodged at Samuel Comfort`'s; and on Sixth-day +++[+++26th;]
we had an appointed meeting at Middletown,
having before meeting paid religious visits to the
families of Mercy Stackhouse and Jonathan Stackhouse,
the latter not a member.
In the meeting I laboured according to the ability
received for the everlasting welfare of those assembled.
Here our young friend, Mahlon Moon, joined us,
having a prospect of going with us to all the meetings, as a guide.
We went to Mary Hulme`'s to lodge;
and had a religious opportunity in the family in the evening.

On Seventh-day +++[+++27th,]
we were at an appointed meeting at Bristol.
I was engaged to open the state of man in the fall,
with the means of his deliverance and redemption out of it,
speaking also to various states and conditions.
Dined at the widow Newbold`'s,
who is much afflicted and nearly helpless with inflammatory rheumatism.
Had a sitting with her,
in which the language of sympathy and encouragement was addressed to her.
Lodged at George W. Brown`'s; and on Fifth-day morning +++[+++28th,]
had a religious opportunity in his family and that of his father David Brown,
and made two short visits beside.
Then attended the Falls Meeting, which was largely attended by Friends and others.
I felt a concern for various states, and expressed as way opened;
and was led in a line of very close communication to
some of the youth of our own Society,
who are living above the cross of Christ.
Dined at B. Cadwalader`'s, and took tea with the wife of my dear friend Christopher Healy,
now absent in the service of the Gospel.
She has lately had pleasant intelligence from him, and from others,
of his labours among the Indians near Green Bay.
Lodged at James Moon`'s.

On Second-day +++[+++29th,]
attended an appointed meeting at Wrightstown; calling on the way there at John Buckman`'s,
in whose family we had a religious opportunity.
Dined at Dr. Chapman`'s; and was drawn into silence before leaving the family,
in which I felt particularly for two of the sons in declining health, who are both,
I believe, concerned for their everlasting welfare.
I had to address them and others present.
I rode with my aged friend, John Scholfield, as far as his house;
and on the way he pointed out the house of that worthy minister of Christ, Thomas Boss.
We took tea with my before-mentioned friend;
and afterwards went to lodge at the habitation of that mother in Israel, Ruth Ely,
whose company and conversation were very agreeable.
On Third-day +++[+++30th,]
attended Solebury Meeting, it being the day of their Preparative Meeting.
It was rather a low time, yet I felt an engagement to labor in weakness.
Dined at Aaron Eastburn`'s, and had a religious opportunity with his family,
in which my mind was particularly drawn to his wife, who has been long confined at home,
being entirely deprived of sight.
Went to Ezra Comfort, Jr.`'s, to lodge;
where resides the widow and two daughters of my late much esteemed friend, John Comfort.

On Fourth-day morning +++[+++31st,]
had a solemn opportunity with the family, in which our hearts were tendered and united,
and the language of encouragement was freely offered.
Attended Buckingham Preparative Meeting.
In the meeting for worship my heart was enlarged to preach the glad tidings of the Gospel.
Dined at B. Gillingham`'s, and paid a family visit to two young Friends,
William Balderston and wife; also another to the widow and family of his late father,
John W. Balderston.
Then went to Dr. Fell`'s to lodge.

Fifth-day, Ninth month 1st. Went to the Preparative Meeting at Plumsted,
previous to attending which, I called to see my aged friends Daniel Carlisle and wife.
Had an opportunity with them;
and it seems probable their time on earth is drawing towards its close.
The meeting proved a low and exercising season; yet I had some communication;
and afterwards a short one on the manner of attending religious meetings.
In the meeting for business some remarks were made to my younger brethren on
the necessity of submitting to the operation of that Power that would
prepare them to take the places of faithful labourers,
soon to enter their everlasting rest.
Dined at John Fell`'s and had a religious opportunity with his family,
and several Friends who were present, to a good degree of satisfaction,
parting under a sense of our Heavenly Father`'s love and goodness.

Came to James Moon`'s to lodge; and the next day parting with his son M.,
who had been acceptably with us, we returned home.
After remaining at home a few days, and not feeling released from my concern,
I again set off on Fourth-day, the 7th, to attend the Falls Monthly Meeting,
and to visit a few families.
On this occasion, my nephew, James R. Greeves, bore me company.
We reached Mahlon S. Kirkbride`'s and lodged there.
In the morning +++[+++the 8th]
we had a family sitting,
in which I had to offer encouragement to my young friend and his wife.
Afterwards had an opportunity at Daniel Burgess`'s with himself, his sister, and a niece,
who resides with them.

A family visit was also paid at John Price`'s, in which his wife,
and several of his children were present.
The wife is in poor health.
The eldest daughter seems to be a very promising young woman.
In the first meeting I was prostrated before the Lord in vocal supplication.
Although some valuable Friends belong to this meeting,
there seems to be a lack of depth and experience in managing its concerns,
and too much backwardness among some of the middle-aged, and a few younger Friends,
on whom a concern rests for the welfare of the Church.
I was concerned to go into the women`'s meeting,
and laboured to encourage them in the work of reformation, so much needed in our Society;
speaking of the manner in which some Friends permit their children to
associate with light and airy young persons in large parties,
to their own serious injury, and that of others, in the way of example.
Such things, when found in the families of active Friends,
will prove as stumbling blocks in the way of honest inquirers.
Dined at Mahlon Kirkbride`'s, and had an opportunity there.
Went to Joseph Satterthwait`'s to tea,
and had an opportunity of expressing my concern
for the religious welfare of himself and family.
Then to James Moon`'s to lodge.
Way opened in the evening for a religious opportunity, which was relieving to my mind,
having for some time felt a close exercise of spirit on account of this family.
In the morning +++[+++the 9th]
another sitting took place, in which the solemnizing power of Truth was felt,
so that I could leave them with an easy mind.
Called at Asa Walmsley`'s on my way home, and had a sitting with himself and children,
feeling sympathy with him under the loss of his companion.
On reaching my own habitation,
I felt a degree of thankfulness in having been enabled to
accomplish this religious engagement to my own peace of mind;
sensible at the same time of my own great unworthiness,
and desiring that I may be strengthened to abide
under the purifying baptisms of the Holy Spirit,
which can alone prepare for future usefulness in the Church.

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his son Thomas.

[.signed-section-context-open]
Ninth month 16th.

Your sister Susanna has a daughter about three weeks old, called after her own mother,
Elizabeth.
I have been a little journey on a religious account;
it was to attend the meetings of Bucks Quarterly Meeting.
I had to regret in some neighbourhoods that the young
Friends were not consistent in their appearance;
and that too many of them were fond of light company and conversation,
which is a sad hindrance to the growth of true religion.
Yet there are some who are bowing to the cross, and, in a few instances,
very remarkable changes have been effected by a submission to the Gospel,
which is the power of God unto salvation to every one that believes.
I feel solicitous that our youth may become devoted followers of the Lord Jesus,
and be prepared to take the place of faithful labourers gone to their everlasting reward.

May you, my dear son, bow to the appearance of that Divine Grace,
which manifests what is evil, and reproves for it, and as it is heeded,
strengthens to come out of everything that the Lord`'s controversy is
against. We were not sent into the world to amuse ourselves,
nor to accumulate earthly treasures, nor to gratify our own wills,
nor the will of others, but to work out our own salvation with fear and trembling,
and to stand devoted to the Lord`'s cause in our day and generation.
You live where, I fear, there are few instances of entire dedication; but the Lord,
as you rely upon Him, can enable you to become an example of deep self-denial;
and if you seek first the kingdom of God, and the righteousness thereof, He will,
I doubt not, provide things honest in the sight of men, and by his blessing,
which gives contentment in a moderate way of living,
add all things needful for your temporal accommodation;
and penetrate your heart with gratitude to Him, both for outward and spiritual benefits.
You are now nearly arrived at the age I was when my mouth was
first opened as a preacher in public assemblies.
It was a time of great humiliation, and ever to be had in remembrance by me.
What the Lord would make of you, if faithful, I cannot tell;
but I ardently desire He may be pleased powerfully to visit your soul with
renewed discoveries of the excellency of his everlasting Truth,--enamour
your mind therewith,--prostrate all within you in resignation to his holy
will,--show you with indubitable clearness what He would have you to be,
and to do, and give you from season to season, strength to perform all that He requires.
Then will your peace flow as a river, and your righteousness as the waves of the sea,
and you will be a preacher in life and conduct.
It matters little what station may be assigned you in the Church.
If faithful in the lowest, it will insure the Divine approbation.
"`I had rather,`" said the Psalmist, "`be a door-keeper in the house of my God,
than to dwell in the tents of wickedness.`"

In one of your late letters you intimate that you have
no present prospect of changing your condition.
I believe you are aware that marriage is one of
the most important events of a man`'s life;
and much of his comfort in this life depends upon the choice he makes
of a companion,--and it may influence his everlasting state.
I hope you will be preserved from choosing one whose mind is on earthly things,
the decoration of the poor body, or those things which perish with the using;
but that you may be directed to one who fears the Lord,
has entered into covenant with Him,
upon whom He has put the ornament of a meek and quiet spirit, which is, in his sight,
of great price.
Such a one, instead of being a snare and a hindrance,
would be a helper to you in your way to the kingdom of rest and peace.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his daughter Susanna.

[.signed-section-context-open]
Ninth month 30th.

I have been to Greenwich, and had a pleasant visit.
I went on Sixth-day +++[+++23rd]
to Salem in the steamboat,
and found that Richard Acton and wife were contemplating a
visit at some time to their Greenwich friends,
and they concluded to bear me company.
On Seventh-day morning +++[+++24th]
we went, arriving at Moses Sheppard`'s in time for dinner.
We took tea at John Sheppard`'s, separating afterwards, they going to Joseph Miller`'s,
and I returning to Moses`'s. The next day we were at their meeting,
and dined at George Bacon`'s; took tea again at John Sheppard`'s;
visited John E. in the evening, and lodged at the father`'s.

On Second-day left for Salem, calling at Moses Sheppards`'s again,
and paying a visit to Joseph Miller`'s. Richard had some business at Shiloh,
the settlement of a religious community, called the Seventh-day Baptists,
and in consequence we went through that neighbourhood,
which is considerably out of the direct route to Salem.
These people have a good reputation for integrity.
They have settled on poor land, which they are improving.
Keeping the Seventh, instead of the First-day of the week,
as a day of cessation from business is, as their name imports,
their distinguishing peculiarity.
I saw evidence that the spirit of the world has made some inroads upon them,
as is sorrowfully the case with other societies, our own not excepted.
I expect to attend the Examination at Westtown,
and would gladly avail myself of the opportunity of being so near my dear children,
to pay them a visit, and yet circumstances at this time, seem to forbid it;
but whether I come frequently to see you, or other duties prevent, I am at all times,
your truly affectionate father.

--
