== Chapter XVIII.

[.chapter-synopsis]
* 1842.
* Diary
* Visits Muncy with Quarterly Meeting Committee
* Catharine Sheppard`'s death.

[.offset]
+++[+++Diary continued:]

Our Quarterly Meeting having appointed me one of a committee
to aid and assist Friends of Muncy Monthly Meeting,
and several visits having previously been made by other members of
the committee in pursuance of the object of our appointment,
way appeared to open for me to engage in similar service, in company with Joseph Snowden,
Sarah Hillman, and Elizabeth Pierson, also members of the committee.

We commenced our journey on Seventh-day, Tenth month 8th,
and lodged at the house of Hannah Williams, Plymouth.
In the evening we had a religious opportunity with the family,
in which Sarah Hillman was my fellow-labourer.
On First-day morning +++[+++the 9th]
we set off for Pottstown, and arrived in time for meeting,
at which were six persons beside ourselves;
yet to this little company the language of encouragement was offered;
both Sarah Hillman and I having something to communicate.
Dined at Sarah Potts`'s, and went on to Exeter to Ellis Lee`'s to lodge.

The next morning +++[+++10th]
we all walked to the next house, the residence of John Lee,
and had a time of retirement in his family.
Sarah Hillman addressed our aged friend and his wife appropriately,
after which I was drawn forth in supplication on their behalf,--for their children,
the members of that meeting,
and for us who were going forth under feelings of great weakness.
Went to Maiden Creek, to Sybilla Starr`'s to dinner; and to Enos Lee`'s to lodge.
On Third-day +++[+++11th]
we pursued our journey, and lodged at J. Spohn`'s, on the summit of the Broad Mountain.

On Fourth-day evening +++[+++12th], we reached Andrew Eve`'s, Fishing Creek, and lodged.
Fifth-day +++[+++13th], attended Greenwood Preparative Meeting,
in which labour was extended in weakness.
We arrived in the evening at Mercy Ellis`'s, Muncy.
Sixth day +++[+++14th]
attended Muncy Preparative Meeting,
which was held by appointment at this time for our accommodation.
The meeting was favoured, Sarah Hillman participating in the public service.

[.offset]
+++[+++In a letter to his wife, written on the 14th, Thomas Kite says:]

[.embedded-content-document.letter]
--

I write at Henry Ecroyd`'s, Joseph and I having walked here this morning,
after calling at Jacob Haines`'s. Jacob got home last evening.
His father seems pretty well, excepting a cold.
He and Mercy Ellis have commenced a family visit;
have generally visited Friends of Fishing Creek,
and propose beginning those of this meeting soon.
I have been glad to hear that these aged Friends seem bound to this service.
Afternoon: The meeting is over.
It was in good degree favoured.
Sarah was enabled to address various classes in the love of the Gospel.
I followed her; and Mercy Ellis had a short testimony.
After the Preparative Meeting, we had an opportunity with the Overseers,
as we had yesterday, at Fishing Creek.
There seems a hopeful prospect at both the meetings,
that some of the young people are preparing for usefulness;
but there are others that do not appear to have submitted to the power of the cross.

--

+++[+++Diary:] On Seventh-day morning +++[+++15th,]
we had a religious opportunity in the family of John Ecroyd--a close, searching time.
Dined at Jacob Haines`', and paid a religious visit in the afternoon to the widow Warner,
daughter of our late friend Elizabeth Kitely, accompanied by our friend, Mercy Ellis:
the widow was addressed, and also an afflicted daughter,
who had long been confined to her bed, and appears to have lost the power of speech;
yet her understanding seems clear,
and she appears to be favoured with religious sensibility.

On First-day morning +++[+++16th,]
we paid a religious visit to the family of John Warner,
and afterwards attended Muncy Meeting, in which ability was renewed to labour.
In the afternoon went to Pine Grove,
and lodged at Isaac Winner`'s. His daughter Sarah appears to be a valuable young Friend.
On Second-day +++[+++17th,]
we had an appointed meeting, in which some capacity for public labour was granted,
Sarah Hillman participating therein.
The members were requested to remain together when the meeting for worship closed;
and they were exhorted to be more diligent and faithful
in the discharge of their religious duties.

On Third-day +++[+++18th,]
Joseph Snowden, Sarah Hillman and I, attended Muncy Preparative Meeting for Ministers and Elders.
It was a close, searching time.
In the evening, a time of silent retirement occurred at our friend Mercy Ellis`',
several Friends being present, who had come to attend the Monthly Meeting.

On this occasion Ellen McCarthy was drawn forth in testimony, nor was I wholly excused.
On Fourth-day +++[+++19th,]
we attended Muncy Monthly Meeting.
In the first meeting Sarah Hillman, Ellen McCarty and I,
respectively appeared in testimony, and Mercy Ellis in supplication.
Notwithstanding there are a few valuable Friends here,
the meeting appears to be in a weak state,
and there is great lack of faithfulness and consistency in maintaining our principles.
In the afternoon we paid a religious visit to the family of Benjamin Evans:
it was a time of tenderness and favour.
On Fifth-day +++[+++20th,]
after a solemn opportunity, in which Mercy Ellis, Martha Parker, Jacob and Rachel Haines,
and several of the children of the last-named Friends were present,
we set off for Greenwood and lodged at David Masters`'. I went alone towards evening,
and had an opportunity with a daughter of David`'s, who married out, but is now a member,
and seems under much religious exercise.
Sixth-day +++[+++21st,]
reached John Spohn`'s tavern, on the Broad Mountain, to lodge.

Seventh-day +++[+++22nd,]
to Enos Lee`'s. On First-day +++[+++23rd,]
after a religious opportunity, we set forward for Exeter Meeting.
I was silent;
but near the close Sarah Hillman was engaged in vocal supplication
for the renewed extension of Divine mercy and regard.
After dinner at Daniel Lee`'s, Joseph Snowden and I walked to Amos Lee`'s,
and had a tendering religious opportunity in his family.
Proceeded to Pottstown,
and lodged at Sarah Potts`'. In the evening a family visit was paid to Harriet Brooks,
and her daughter Rebecca J. Potts, several of the children of the latter being present.
On Second-day +++[+++the 24th,]
we reached home.
We have been favoured with good roads and agreeable weather.
We went forth in weakness, have been kept in a low, dependent state,
yet favoured at times with renewed ability to labour for the help of our fellow members;
and in returning feel the quiet assurance that we endeavoured to do what we could.

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his son Thomas.

[.signed-section-context-open]
Eleventh month 2nd, 1842.

+++[+++After mentioning his visit to Muncy.]
The situation of our Friends in some of the
Particular Meetings was such as to cause sorrow,
and abate the satisfaction we might otherwise have taken in our excursion.
In too many parts the professors of Truth have imbibed the spirit of the world,
and become light and airy, or dry and formal.
What can awaken them from their supineness?
The Lord has striven with them by his Spirit, and visited them with his judgments,
and if not reclaimed, it may be,
that He will deal with them by terrible things in righteousness.

I often feel anxiety about you, and desire for your preservation, not only from evil,
but from the appearance of it.
A close attention to the Heavenly Monitor within,
will restrain from all that is improper, either in kind or in degree,
and teach that "`whether we eat or drink,
or whatever we do,`" we should be aiming "`to do all to the glory of God.`"
May you, my beloved son, get deep enough in your mind,
seriously to consider what in your conduct or conversation,
falls short of the standard of purity held up by our worthy predecessors,
and their faithful successors.
And even if there should not be another young person in your city to join you,
I want you to endeavour to bear a firm and consistent testimony for our principles,
in your life and conduct, and by submitting to those baptisms which cleanse inwardly,
be gradually prepared to be rightly engaged in advocating those
doctrines for which the primitive Friends so nobly suffered.

--

+++[+++In the Eleventh month, 1842, Thomas Kite visited Concord Quarterly Meeting,
and his daughter at Westtown.
In the beginning of the Twelfth month he recommenced his Diary,
with the following observations:]

[.small-break]
'''

Some little attempt was made, in the Third and Fourth months, 1839,
towards keeping a Diary; it has since been suspended,
excepting while absent from home on religious service.
I renew the effort, designing occasionally to make an entry,
which may serve to remind me of the Lord`'s gracious dealings with me;
and with the desire that I may increase in diligence and dedication to my Divine Master,
that so in the conclusion of my time here,
I may be permitted to enter his undefiled rest.

Twelfth month 4th. First-day.
At morning meeting I was silent.
After dinner I went with my wife to the funeral of Henry, son of Richard Williams,
who died at Westtown, in his fifteenth year.
At the house, the goodness and mercy of our Heavenly Father was commemorated,
as manifested even in afflictive dispensations.
Sympathy with the mourners was expressed;
and those present were admonished to improve by the present instance of mortality.
At our afternoon meeting,
encouragement was handed to an honest-hearted but deeply tried remnant.
At evening meeting,
largely opened in expression upon the past and present state of our Society,
as well as its future prospects.
A good degree of solemnity seemed to attend.
After meeting, I accompanied my daughter +++[+++Rebecca]
to the house of mourning,
and way opened to address the brothers and sisters of the deceased youth.

5th. Second-day.
I have had fresh occasion to remember Paul`'s concern,
with desire that it may always be mine: '`I keep under my body,
and bring it into subjection; lest that by any means, when I have preached to others,
I myself should be a castaway.`'

6th. Third-day.
Attended the funeral of Rebecca, daughter of William and Elizabeth Biddle.
She was a scholar at the select school, and died in the twelfth year of her age.
I sat with the family, and had to speak, commencing with the passage,
'`Whom the Lord loves He chastens, and scourges every son whom He receives.`'
At the place of interment, Rebecca`'s school-fellows were addressed,
a number of them being present.

7th. Fourth-day.
Feeling drawings to attend Orange Street Meeting, I went there.
A sweet solemnity spread over the assembly,
and I was helped to minister to various states, to my own peace.
After which Elizabeth Evans was largely engaged in thanksgiving and supplication.

8th. Fifth-day.
In our week-day meeting I was opened on some important doctrines of the Christian faith,
from Ezekiel`'s vision of the holy waters, and from the pure river of water of life,
which John saw.
My desire is, that I may experience what I have borne testimony of to others.

Twelfth month 10th. Seventh-day.
In conference with a sweet-spirited friend,
felt the precious cementing influence of Gospel love.
Afterwards, a season of silent waiting, and the language of encouragement was given.
I felt drawn to go to the girls`' school in James Street;
and during the silent pause at the close,
I was prostrated in vocal prayer for the children, and all who were then present.
Afterwards had a brief exhortation for the children.

11th. First-day.
At the breakfast table access seemed mercifully granted to the Throne of Grace,
and I was enabled to plead for forgiveness of sin,
and future preservation on behalf of my family,--a circumstance unusual with me.
Silent in the morning meeting.
In the afternoon,
had to express the language of sympathy for those who are walking in darkness,
with encouragement to believe there would be a change of dispensation.
In the evening meeting, an address to parents from the words,
'`Then David returned to bless his household.`'
Sarah Hillman ministered acceptably.

13th. Third-day.
I believed it right to attend the North Meeting.
A precious solemnity was felt,
and I stood up with the language of our Lord to the woman at Jacob`'s well,
"`If you had known the gift of God,`" etc., with caution and encouragement.
My dear friend Elizabeth Pitfield,
was afterwards drawn forth in much the same line of communication.
The solemnity continued afterwards in silence, and I was comforted in being there.

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Kite to his son Thomas.

[.signed-section-context-open]
Twelfth month 14th.

+++[+++After mentioning the death of Henry Williams, as before mentioned.]
His mother was with him,
and three of the teachers came to the city to manifest their sympathy with her,
and to attend the funeral, namely, Joseph Walton, Jr., Abigail Williams,
and your sister Rebecca.
Though your sister`'s visit was short, and the occasion sorrowful,
yet it was pleasant to us to have her with us.
She had the opportunity of attending one of the evening meetings,
which this winter are regularly held on First-days.
Our friends William Biddie and wife, have met with two close trials.
In the first place, their son Samuel, perhaps fourteen years old, took the scarlet fever;
it was an aggravated case, and he survived the attack but about one day.
Three other children, all they had, have had the same disease, and one of them,
their only daughter, aged about eleven, has also died.
The parents were strongly attached to their children,
and this bereavement proves very afflictive.
I hope it may be overruled for their good, by loosening their affections from this world,
and settling them on that world, and the things of it, which is everlastingly glorious.
Our uncle, John Letchworth, is again ill.
He has passed through so many sicknesses, in which he was brought very low,
that it is difficult to decide, yet one of our intimate friends thinks,
this will prove his last.
It is a comfort to believe, as we do, that if it should prove so, he is prepared.
He has diligently served the best of Masters,
who now "`makes his bed in sickness,`" and will, no doubt,
receive him to Himself when the few remaining days of his pilgrimage are accomplished.

--

[.offset]
+++[+++Extract of a letter from one of Thomas Kite`'s family:]

[.embedded-content-document.letter]
--

On Second-day morning +++[+++12th], died the oldest female member of our meeting, Mary Coates.
On Third-day night, Catharine Sheppard was taken with gout in the stomach;
suffered extremely on Fourth-day; towards evening was better,
and seemed to pass an easier night.
Fifth-day morning, 15th, she was taken ill with a sinking spell;
Elizabeth Pitfield went into the room with the daughter, and by rubbing her with camphor,
she seemed to revive.
She spoke to Elizabeth; said she was aged, and would not last long;
that she had been looking around, and felt nothing in her way.
Spoke of her dear Redeemer.
She conversed a little about John Wilbur, showing her interest in him.
Elizabeth then withdrew, and Catharine appeared to doze; she roused up, and said,
'`This seems like the sleep of death.`'
She then soon expired.

--

[.offset]
+++[+++Thomas Kite`'s Diary, continued.]

Twelfth month 15th. Fifth-day.
Attended the funeral of our aged friend, Mary Coates, who died in her ninetieth year.
At the grave, under a sense that it was well with the deceased,
the language of our Lord was revived, '`Daughters of Jerusalem, weep not for me,
but weep for yourselves and for your children.`'
My exercise of soul was for those who remain in this mutable state,
exposed to the assaults and temptations of the enemy.

17th. Seventh-day.
Visited Ann Richards and several of her children.
It was the first time of my entering the house since
the interment of her sister Rachel C. Bartram,
who was run over and killed by a horse about a year ago.
In a religious communication,
I had to express my belief that this awful dispensation had been permitted in mercy.^
footnote:[She subsequently was received into membership.]
Most of the children seemed tender; and one of them, a grown-up daughter,
appears to be under a precious visitation of Divine love and mercy.

18th. First-day.
In the morning meeting considerable enlargement was witnessed in word and doctrine.
The experience of the Apostle Paul was brought into view, and several states addressed.
Attended the funeral of our friend Catharine Sheppard,
who departed this life on the 15th. Although unwell,
she had been at meeting on the 13th. She occupied the station of an elder,
was a woman of integrity, and will be much missed in her Monthly Meeting.
A short testimony to the way of life and salvation, was delivered at the grave,
and the belief expressed,
that though the summons to our departed friend might seem to be somewhat sudden, she was,
through Divine Mercy, found with her loins girt about and her light burning,
waiting for the coming of her Lord.
Silent in the afternoon and evening meeting;
but had particularly to address my nephew and nieces, who are under my care,
after our evening reading of the Scriptures.
The seed sown in weakness, may hereafter be raised in power, if our heavenly Parent,
be pleased graciously to extend an awakening visitation.
So be it, says my soul.

19th. Second-day.
Occupied a part of the morning in visiting my afflicted friends,
William and Elizabeth Biddle.
I was comforted in the belief that they have attained a good
degree of resignation respecting their late bereavement.
In the opportunity I had to encourage them to stand in dedication of
heart to what the Lord may be pleased to call them to.
It was measurably a favoured season.

20th. Third-day.
Sat with Margaret and Catharine, daughters of my late friend, Catharine Sheppard,
their married sister Rebecca Warder, being also present.
The overshadowing of the Wing of Ancient Goodness was experienced.
I felt sympathy for my friends, in a sense of their and the Church`'s loss,
and had to hand forth the language of encouragement.
Afterwards I had a religious opportunity in the family of our late friend Mary Coates;
her widowed daughter Mary Horner, and two of her grand-daughters, being present.

22nd. Fifth-day.
Felt deeply conscious of my own deficiencies,
and not destitute of aspirations for deliverance.
Went to meeting with no expectation of being heard;
yet an opening presented on the spiritual nature of the baptisms of Christ.
I sat sometime under it; and at length arose with John the Baptist`'s declaration,
'`There stands one among you whom you know not;
He shall baptize you with the Holy Spirit and with fire.`'
May I experimentally know the cleansing operation of his power,
'`whose fan is in his hand.`'
In the afternoon, my wife and I went to Woodbury,
principally to visit our dear friend Joseph Whitall.
Lodged at George Mickle`'s.

23rd. Sixth-day.
We went early in the morning to Joseph Whitall`'s, and found him in a very weak state of body,
but lively in spirit, and deeply interested in the cause of Truth and righteousness.
We accompanied him to the week-day meeting.
It seemed a low time; yet towards the close, a short communication was delivered,
on the case of Saul,
who had been '`a choice young man and goodly;`' yet by
unfaithfulness to his God he lost his favour,
and at length his kingdom and his life.

Twelfth month 25th. First-day.
The morning and evening meetings were silent.
In the afternoon meeting, Paul`'s address to the Philippians was revived,
'`I would you should understand, brethren,
that the things which happened unto me have fallen out
rather for the furtherance of the Gospel.`'
The tempted and tried were encouraged to believe this would be their
experience as they held fast their faith in the Good Shepherd,
who cares for the sheep.

26th. Second-day.
Dipped into sympathy with an exercised friend,
whom I addressed with expressions of encouragement.

27th. Third-day.
Much depressed with a sense that I am far from being thoroughly purified.
Feeling an impulse thereto, I went to the North Meeting.
A covering of solemnity prevailed,
under which access to the Throne of Grace in vocal supplication was vouchsafed.
Petitions were presented for various classes; and that as the Lord in his wisdom,
has removed faithful labourers,
He would raise up and qualify others to fill their places.
In the evening, at her request,
I accompanied my wife to Timothy Abbott`'s. Before we left his house,
the company were drawn into silence, and I was concerned, in vocal supplication,
for a widow present; also for a fatherless young woman, who is, as I apprehend,
exposed to danger; and for us all, that at the solemn hour of death,
we might be found prepared for the mansions of rest and peace.
