== Chapter XXI.

1843-1844.

Attends Indiana Yearly Meeting--Letters--Illness of daughter,
Susanna Sharpless--Sarah Emlen to Thomas Kite--Death of
Susanna Sharpless--Sarah Emlen to Thomas Kite.

On Sixth-day afternoon, the 15th of the Ninth month,
Thomas Kite left Philadelphia in the four o`'clock boat
for Baltimore on his way to Indiana Yearly Meeting,
having a minute from his Monthly and a certificate from his Quarterly Meeting.
His friends William Evans and Henry Cope were in company.
They reached Baltimore early next morning, and took the rail road cars for Cumberland.
In a letter describing this journey he says:
"`A most remarkable freshet was in the Potomac,
and I expect much damage has been done by it.
People were passing about in boats or flats in the street,
and we had to pass over a temporary scaffold to get to the house where we dined.`"
Owing to fogs in the Ohio river,
the travellers did not reach Cincinnati until Fifth-day morning.
They were in season to attend the usual week-day meeting there,
which was a labourious time.
Thomas Kite says: "`William Evans had very close and suitable service; and after him,
something fell to my lot.`"
"`Our kind, young friend, James Taylor,
took us in the afternoon to Harrison Alderson`'s to tea.
His place is three and a-half miles from the city, and is a most beautiful spot.
If he can but feel satisfied that he is in his proper place, he will, no doubt,
be well suited.
His wife is quite contented, so far as appears.`"
"`We returned in the morning to the city; visited our aged friend Ann Shipley,
with whom and her daughter we had a satisfactory religious opportunity.
They are both in improving health.`"
"`In the afternoon we went to see Ann Townsend, the Friend whom Thomas +++[+++Kite, Jr.,]
has mentioned as appearing acceptably in the ministry.
She has been recently recommended.
We had a religious opportunity with her, I believe, to her comfort,
in which William was opened instructively to speak to her situation.`"

Extract from Diary: "`We arrived at Richmond, Indiana, on Seventh-day evening,
and the next morning went sixteen miles to Milton to meeting.
It proved a low, heavy time,
yet William was enabled to labour amongst Friends with pertinency.
We returned to Richmond in the evening.

Second-day, the 25th, we attended the Meeting for Sufferings;
Third-day the Yearly Meeting of Ministers and Elders;
Fourth-day a large public meeting for worship,
in which both William and I appeared in testimony,
and it seemed in a good degree a favoured season; Fifth-day, the 28th,
the meeting for business opened, and was continued on Sixth and Seventh-days.
On First-day, Tenth month 1st, two large meetings for worship were held.
I had the principal service in the morning, and William in the afternoon;
and I trust we were favoured to preach the everlasting
Gospel in a degree of its owm demonstration.
The business was continued on Second and Third-days, on the last of which it concluded,
a season of precious solemnity being vouchsafed.

Besides the meetings mentioned,
we attended various other sittings of the Yearly Meeting of Ministers and Elders,
the Meeting for Sufferings, committees on Indian affairs,
and on the concerns of the people of color, and had some service in private.
The sittings were often long and fatiguing to the body,
but the comfortable feeling attended,
that we were in our proper places in being with our Friends,
who have been brought under great exercise in
consequence of the secession of some of their members,
who have set up and held what they call '`The Indiana Yearly Meeting
of Anti-Slavery Friends an event deeply to be regretted,
and which calls for patience and forbearance, as well as Christian firmness,
on the part of those who remain.
On Fourth-day William and Henry set off from Richmond
to attend a few meetings not far distant,
and I, accompanied by my son, went into Ohio to visit my kinswoman, Rebecca,
the wife of Abel Thomas.
We passed through Springboro`' and Waynesville to Lebanon, where she resides.`"

On Fifth-day evening on their way to Lebanon,
Thomas Kite and son reached the house of Thomas Evans, of Waynesville, where they lodged.
Of this Friend`'s house Thomas Kite in a letter says:
"`He occupies the brow of a lofty hill, overlooking the Little Miami River,
which is here, a beautiful stream,
with a range of hills on each side and narrow
strips of bottom land between it and the hills.`"

Thomas Kite reached Cincinnati early on Seventh-day morning,
where in the evening he was joined by his friends William Evans and Henry Cope.
His Diary continues: "`On First-day, the 8th of the present month,
we attended the meeting in that city.
The public labour in the ministry devolved on William Evans,
yet I was engaged in supplication.
The members were invited to come together in the afternoon,
when William was again introduced into exercise,
and much close searching and pertinent counsel was administered.

On Second-day morning we had a favoured religious
opportunity in the family of our aged friend,
Ann Shipley; after which taking leave of our friends,
we went on board a steamboat bound for Wheeling,
and returned homeward by the same route we took in going out,
and were favoured to arrive in safety, at three o`'clock in the morning of Seventh-day,
the 14th of Tenth month, having been absent about twenty-eight and a-half days.
I travelled in this journey 1778 miles,
and was permitted to feel much tranquillity of mind in the retrospect.`"
In a letter written while in Cincinnati, he thus speaks:

"`I have been unwell ever since I arrived in Ohio,
during the time of the Yearly Meeting,--ever since,
and suppose I shall be so until I leave this region.
It is probably in part owing to the water, which out of this city is limestone.
Here they drink the water of the river.
I do not regret, however, having come on this journey.
I have felt as if I have been in my proper place.
There is much to deplore in the situation of our Society in this wide-spread region,
and many trials seem in store for the faithful members; yet merciful,
loving kindness was near, at times, during their Annual Assembly,
and best help seemed offered to them.
One cause of sorrow to me,
is the departure of the youth in appearance and
manners from consistency with our profession.
It seems more remarkably so with the females.
Parents I should think, must be, in some measure to blame.
Indeed, family discipline seems to be at a low ebb.
Yet there are very large numbers of plain Friends of middle age, and elder,
who seem concerned for the cause of Truth.
Deeply experienced fathers and mothers seem very few indeed.
Yet there are preserved a few judicious elderly Friends upon
whom a living concern seems to rest for Truth`'s prosperity.
The great amount of business to be done in a limited time,
causes it to be hurried in the Yearly Meeting in a manner not pleasant to us,
and which has a tendency to abate the solemnity of such occasions.
Your family letter was very pleasant except the
part which announced dear aunt Sarah`'s death.^
footnote:[Sarah Hayes, a valuable elder of Fallowfield Monthly Meeting,
and sister of Thomas Kite`'s mother.
Her death occurred Ninth month 16th, 1843.]
But I trust her end was peace.`"

Diary: "`Tenth month 18th. First-day.
In the afternoon meeting a testimony was delivered concerning the faith of Abraham.`"

Extract of a letter to his daughter Susanna, dated Tenth month 27th:
"`After the Yearly Meeting was over, your brother Thomas accompanied me into Ohio,
to seek for our m cousin, Rebecca Thomas, whom we found at Lebanon.
Her children were with her, but her husband was absent.
Neither she nor I were at that time aware of her mother`'s decease.
This excursion gave me the opportunity of seeing a
considerable part of the celebrated Miami country,
as I passed through Springboro, Waynesville, etc.
It is very rich land, and some of it quite beautiful,
undulating like the hills of Chester county, but with less elevation.
Other parts are very flat, and I should suppose not so healthy.
The water in Indiana and Ohio where I have visited, is limestone,
and appears to disagree with me.
The fruits in general were fine, apples and pears particularly so, free from blemishes,
of a large size and finely flavored.
The peaches are not superior to our own.
The Yearly Meeting was very large,
and much unanimity prevailed on all subjects excepting the boarding school.
Qn education some diversity of opinion exists.
Those who have separated are not much missed out of the meeting;
yet it is a source of deep regret, that such a movement has taken place,
and that Charles Osborne, a man once so favoured, should be a leader in it.
I did not see him.
Circumstanced as the Society is in Cincinnati, with a strong worldly bias,
and few substantial Friends,
the younger part are under many difficulties with respect to a
firm and upright support of our testimonies.
I do earnestly desire your brother may become one of a band,
who may stand in that place for the cause and testimony of Truth.`"

During the Tenth month,
Rebecca Kite spent a short time during her Westtown vacation at her father`'s house.
Almost immediately after her return to the school, her father thus addressed her:

Philadelphia, Tenth month 28th, 1843.

My Dear Rebecca,

You will probably feel some surprise at seeing my
well-known hand-writing so soon after parting with me.
The fact is, that various things were pressing on my mind,
and my attention was so engrossed, that I hardly feel as if I had taken leave of you.
So you may consider this letter as my farewell at the
termination of your semi-annual visit to your father`'s house.
I need not say, because I believe you feel it,
that your presence beneath our roof was truly grateful to me,
and your departure left a void which, though natural, is still painful.
This was alleviated by the reflection that, for the present,
your proper sphere of action is elsewhere.
I fully believe you are usefully engaged in your station,
and are desiring to become increasingly so.
I am persuaded if your eye be single to Divine direction,
you will be enabled to discharge the responsibilities which rest upon you,
to the advantage of the dear children,
and to your own furtherance in the way cast up for the redeemed of the Lord to walk in.
A gracious God condescended to visit your mind in early
life with the convictions of his Holy Spirit,
and to enlighten you to perceive the transcendent beauty and excellency of a
life devoted to the pursuit of durable riches and righteousness.
I believe you often mourn over yourself,
that you have not made more advances in the way of holiness; but, my dear child,
I wish your encouragement.

To see wherein we have fallen short, is a great favour;
to feel that we have no might of our own, is not less so.
Wait then on Him who gives power to the faint, and you will find by blessed experience,
that to those who have no might He increases strength.
Be encouraged then, to make use of the ability which the Lord alone gives,
and He will enable you to overcome temptation, to resist evil,
to submit to those baptisms which purify the heart.
He will, I believe, show you with increasing clearness, in his own time,
in what He designs you should promote his blessed cause in the earth;
and with the discovery, the power to comply with his will, will be offered.
If obedient to his requirings,
you will feel the truth of the declaration of the faithful and true Witness,
'`Blessed are they that do his commandments,
that they may have a right to the tree of life,
and may enter in through the gates into the city.`'

In the warmth of natural affection,
as well as of religious desire for your growth in the Truth, I bid you farewell,
and am your sympathizing father,

Thomas Kite.

Diary: "`Tenth Month 29th. First-day.
In the morning meeting, Uzzah`'s attempt to steady the ark was brought before me,
and a testimony delivered on that and other subjects.
A good degree of solemnity seemed to attend.

30th. Second-day.
Went to Woodbury to visit my esteemed friend, Joseph Whitall, and wife.
I found that the Select Preparative Meeting was to be held next morning, and attended it,
to my comfort, as also the Monthly Meeting, which was held afterwards.
In the meeting for worship, preceding the latter, I was enabled to preach the Gospel,
commencing with the words of our Saviour to Nicodemus, "`The wind blows where it wishes,
and you hear the sound thereof, but cannot tell where it comes and where it goes;
so is every one that is born of the Spirit.`'

Eleventh month 1st. Fourth-day.
Went with my wife to Germantown, to attend the funeral of my aged relative, Lydia Jones.
At the ground I had a short testimony to deliver in much weakness.
The inward feeling of corruption has of late much attended me,
and the need of forgiveness,
together with the washing of regeneration and the renewing of the Holy Spirit.

2nd. Fifth-day.
A large assembly at our week-day meeting, by reason of a marriage.
Best help was near, quieting and settling the minds of many;
so that unexpectedly we had a good meeting,
and testimony was borne to the sufficiency of the immediate
teaching of the Lord Jesus Christ by his Spirit.

9th. Fifth-day.
My wife being under appointment,
and I invited to attend the marriage of Lloyd Balderston and Catharine Canby,
we were present on the occasion.
The deportment of my young friends, and their manner of speaking, were satisfactory.
We had a religious opportunity in the evening, in which something was communicated.
The glorious condition of the redeemed,
who have been prepared to stand before the Throne, and to sing the new song,
was the principal theme.`"

Thomas Kite to his daughter Rebecca.

Eleventh month 6th.

This has been the day of our Quarterly Meeting;
of course a day of exercise and anxiety to me.
I understand the women had a trying time.
We had also one rather of suffering.
But it is nothing new for those who are honestly endeavouring to fill
up the measure of duty to have to partake of sufferings.
If we can but be favoured to bear it in a proper spirit,
it will assuredly be sanctified to us,
and tend to our advancement towards that kingdom where
sorrow and suffering are no more experienced.

To the Same.

Eleventh month 18th.

The occurrences at Westtown strikingly illustrate the uncertainty of temporal things;
the school opened under favourable auspices and looked smiling; in a few days,
indisposition was common with teachers and scholars, and since,
a few cases of a dreadful disease +++[+++scarlet fever]
has appeared.
But however changeable the events which happened in our lot, the Lord reigns,
and in his boundless goodness He can bless every dispensation to his dear children,
and will do it?
as He is rightly sought unto.
That this may be the effect of my dear daughter`'s share of the present affliction,
and of all others, is the desire of her affectionate father.

Diary: "`Eleventh month 21st. I attended the North Meeting from a secret impulse.
It proved through Divine favour a comfortable time.
I stood up and recited the Apostle Peter`'s petition for the believers,
as contained in his first general epistle, '`The God of all grace,
who has called us unto his eternal glory by Christ Jesus,
after that you have suffered awhile, make you perfect, stablish, strengthen, settle you;
to Him be glory and dominion forever and ever.
Amen.`'
I had an open and relieving time in testimony,
and was followed by Elizabeth Pitfield in a lively communication,
after which Sarah Hillman was solemnly engaged in supplication.

25th. Seventh-day.
This day I was remarkably engaged in private labour,
having had four religious opportunities, two with individuals,
one with a Friend and his wife, and the other with a mother and her daughter,
all to good satisfaction, being enabled to enter into sympathy with deeply-tried minds,
and strengthened to offer them encouragement, as well as to extend counsel to others.

26th. First-day.
The morning meeting was silent.
In the afternoon I had a testimony to bear, reviving this passage from Ecclesiasticus,
'`My son, if you come to serve the Lord, prepare your soul for temptation.`'
The discouraged were addressed, and various promises revived of a consoling character.
The evening meeting was large, and William Evans ministered therein acceptably.

28th. Third-day.
At Frankford Monthly Meeting.
I was drawn forth in supplication.

Twelfth month 3rd. First-day.
I was engaged in testimony in the morning and again in the afternoon,
on each occasion to the relief of my mind.
My concern of the morning was of a more general nature;
in the afternoon a tried and afflicted state was much before me;
such were encouraged to trust in the Lord;
and the passage from one of the Apochryphal books was rehearsed,
'`Look at the generations of old, and see,
did ever any trust in the Lord and was confounded?
or did any abide in his fear and was forsaken?
or whom did He ever despise that called upon Him?`'
In the evening our friend, John Pease, ministered to a very large and, apparently,
a very attentive auditory.`"

In writing to his son in Cincinnati, a few days previous to the last date,
Thomas Kite thus unfolds the earnest concern that dwelt upon his mind:
"`If anything interesting should occur in your Monthly Meeting, please let me know of it.
I feel much solicitude for Friends of your city, that they may be sound in principle,
consistent in practice, and witness a growth in vital religion.
For none of them am I '`more concerned than for you, my beloved son.
May you be strengthened to bear the cross of Christ faithfully,
and follow the Captain of salvation in the way of his own blessed leadings.
Then, I am satisfied, He would guide you by his counsel even in the things of this life,
but eminently so as regards those things which pertain to the spiritual life.
Though eternal life be the great promise of the Gospel,
yet temporal blessings are not excluded.
'`Seek first the kingdom of Heaven and the righteousness thereof,`' said our Holy Redeemer,
'`and all these things,`' alluding to what we need
for the comfort and support of our bodies,
'`shall be added unto you.`'

Diary: "`Twelfth month 6th. Fourth-day.
Much depressed under a sense of my unworthiness;
nevertheless feeling a gentle drawing to attend the meeting for the Southern District,
I went to it, and was somewhat refreshed.
A circumstance related in chapter 13th of the second book of Kings,
was brought before me, '`And Elisha died, and they buried him.
And the bands of the Moabites invaded the land at the coming in of the year;
and it came to pass, as they were burying a man, that behold, they spied a band of men;
and they cast the man in the sepulchre of Elisha;
and when the man was let down and touched the bones of Elisha, he revived,
and stood up on his feet.`'
A communication was delivered on the subject, with some enlargement of heart,
and to a degree of comfort.
Our friend, Lydia Dean, afterwards ministered acceptably.

24th. First-day.
Since the last record I have been occasionally engaged in small religious services,
but there has not been an openness to note them down.
My prevailing feelings have been those of depression,
under a deep consciousness of having fallen short,
and a conviction of the need of experiencing the
further operation of the baptism which cleanses.
This day, however, I appeared in testimony in our morning meeting,
commencing with the words of the apostle, '`There remains, therefore,
a rest to the people of God.`'`"

Thomas Kite to his daughter Susanna.

Twelfth month 22nd, 1843.

My Dear Daughter:--By a letter from your sister to her aunt Mary,
we have heard today of the sickness of your little Elizabeth.
We sympathize with you in this renewed call upon your maternal solicitude,
but hope you will be strengthened to confide in the goodness
and superintending care of your heavenly Parent.
How many are the anxieties and troubles through which we have to pass,
and yet bow consoling to believe that they all
are designed to work together for our good.
"`These light afflictions, which are but for a moment,
shall work out for us a far more exceeding and eternal weight of glory.`"
Such is the testimony of that dignified apostle,
who had learned in whatever state he was,
"`therewith to be content,`" and who exhorted others "`to rejoice evermore,
and in everything give thanks.`"
This is what I believe my clear Susanna is aiming at;
yet it is sometimes difficult to come to, but through Divine aid, not unattainable.
How striking is the trust and confidence displayed by the prophet, when he said,
"`Although the fig tree shall not blossom, neither shall fruit be in the vine:
the labour of the olive shall fail, and the fields shall yield no crop;
the flock shall be cut off from the fold, and there shall be no herd in the stall;
yet I will rejoice in the Lord, I will joy in the God of my salvation.`"

Diary: "`Twelfth month 27th. Fourth-day.
At the Western Meeting I was enabled to approach
the Throne of Grace in vocal supplication.

30th. Seventh-day.
Attended the funeral of Amy, a daughter of my friends, B. and A. Albertson,
who died of scarlet fever, aged three and a half years.
In the evening my wife and I were with the family,
and an opportunity of religious retirement occurred, in which I had service,
both in ministry and prayer.

31st. First-day.
I was silent at the three meetings.
In the evening my wife and I sat awhile with our friends, Joseph and Hannah Snowdon,
whose daughter Jane died in the morning of scarlet fever.
I had to address the bereaved parents with words of comfort.

First month 1st, 1844.
Second-day.
I attended the funeral of the dear child mentioned above.
Sitting with the parents and a few friends, preparatory to removing the body,
a sweet solemnity prevailed, and our friend, Elizabeth Evans, ministered acceptably;
after which I revived the case of the disciples, when they were assembled,
the doors being shut, for fear of the Jews.
It is recorded, '`that then came Jesus and stood in the midst, and says unto them,
Peace be unto you; and when He had so said, He showed them his hands and his side.

2nd. Third-day.
At the North Meeting, where was a marriage.
I had to speak of the calling of Nathanael.
Afterwards our friend, Samuel Bettle, appeared in testimony.
It seemed a favoured meeting.`"

Thomas Kite to his daughter Rebecca.

First month 5th, 1844.

There are many cases of scarlet fever in the city, I believe, as well as in the country.
On Seventh-day last I was at the funeral of little Amy Albertson;
on Second-day that of Jane Snowdon; on Fourth-day, that of a child of Levi B. Stokes,
each having died with that disease.
T+++.+++ F. Scattergood`'s daughter is low with it, and B. A.`'s son Charles, has been taken sick.
Samuel Leeds`' wife died a few nights since; she had a cold,
but her removal was sudden and unexpected.
Many are the warnings the living have, and yet too few seem to take it to heart.
A preparation for the everlasting kingdom of
righteousness and peace is the one thing needful,
yet how many are passing along without earnestly seeking it!
May you and I, my daughter, be of the number of the wise in heart,
who are taking the counsel of Him who is the way, the truth, and the life,
as well as the Light of men.
"`Walk while you have the light, lest darkness come upon you;
for he that walks in darkness knows not where he goes.
While you have the light, believe in the light,
that you may be the children of the light.`"

I have been pleasantly engaged today.
John Jones`' legacy was divided amongst the members of the school corporation,
to distribute to necessitous individuals.
I obtained some for your aunt Mary`'s friend, A. D., for Susan K., E. H.,
your grandmother`'s acquaintance, R. Y., and several others.

To the Same.

First month 13th.

I take a small piece of paper because I have little to say,
yet was unwilling to permit the stage to depart without some testimonial of my regard.
My desire for you, as for myself is, that as we grow in years,
we may experience a greater willingness to bear the cross of our Holy Redeemer,
and become qualified by experience to say, with a devoted follower of the Lord Jesus,
"`I am crucified with Christ, nevertheless I live; yet, not I, but Christ lives in me;
and the life which I now live in the flesh, is by faith in the Son of man, who loved me,
and gave himself for me.`"

Diary: Same date.
"`Seventh-day.
For many days past, I have felt, to my humiliation, the prevalence of the carnal mind;
but this day I have, through mercy, been renewed with some sensations of the Divine life,
so that I was enabled in some degree, to enter into sympathy with, and minister to,
a friend, who has many temptations and trials to endure.

14th. First-day.
I was once more enabled to bear a public testimony in our morning meeting,
in sympathy with some sincere-hearted travellers, who are under discouragement,
because of the withdrawing of the light of their dear Master`'s countenance.
I commenced with the words of our Lord, '`Can the children of the bride-chamber fast,
while the bridegroom is with them?
the days will come when the bridegroom shall be taken away from them,
and then shall they fast in those days.`'
Silence was my lot in the other meetings,
and aspirations arose in them to the Fountain of Purity,
that I may be washed and purified,
and made fit for the inheritance of the saints in light.

16th. Third-day.
My friend, Samuel Spencer, has come to town for medical advice, and is very ill.
Calling at the house where he is confined, I was invited to see him.
He seemed clear in his mind.
I apprehended the time of his dismissal from this state of being was near, and felt,
and had to express my trust, that all would be well;
'`not by works of righteousness which we have done, but of his mercy He saves us,
by the washing of regeneration, and the renewing of the Holy Spirit.`'
19th. Sixth-day.
I was permitted to dip into feeling with an exercised traveller towards the city of God,
and to hand forth a word of encouragement.

20th. Seventh-day.
This morning I met with two dear friends,
who had been passing through deep conflict of spirit,
of which I was renewedly made sensible, and to whom way opened to minister.

22nd. Second-day.
I went to Moreland, and attended the funeral of Samuel Spencer,
who deceased the night of the 19th inst.
His death is a great loss to the meeting he belonged to,
as well as to his near connections.
A sweet feeling of the blessedness of the everlasting rest of the righteous attended;
and a firm belief that he had been through redeeming love and mercy,
prepared to enter into it.
I had to express the substance of these feelings, as did also our friend, Alice Knight.

26th. Sixth-day.
A day of deep depression and mental conflict; yet,
calling on business at a friend`'s house in the evening, my mind became tranquillized,
and I was enabled to minister, to my comfort, to some present,
who were no strangers to hidden exercises and baptisms unto death.

28th. First-day.
The states were respectively addressed of such as such
as think themselves rich while they are poor,
being destitute of the true riches; and of such as feel themselves poor,
yet being the Lord`'s poor, and trusting in Him, may be considered to be rich in faith,
and heirs of the kingdom which He has promised to them that love Him.`"

Thomas Kite to his daughter Rebecca.

Second month 3rd.

In conclusion,
the desire again arises that you may give yourself without reserve to the Lord.
"`You are not your own, but are bought with a price;
wherefore glorify God with your bodies and with your spirits which are his.`"
Salute in my name dear Abby Williams;
tell her that "`all things shall work together for good to them that love
God;`" and "`He that keeps Israel shall neither slumber nor sleep.`"

Diary: Second month 15th. Fifth-day.
During the interval since the last record,
I have passed through some seasons of deep depression.
In our mid-week meeting on the 8th inst., I was raised up to minister,
which afforded a peaceful feeling to my mind.
Again I was permitted to sympathize with the mourners on First-day afternoon the 11th,
and have of late had some service in private opportunities.
In our meeting today I arose with a sweet impression,
and was helped to open doctrine and counsel from the words of the apostle,
'`I beseech you brethren, by the mercies of God,
that you present your bodies a living sacrifice, holy and acceptable unto God,
which is your reasonable service; and be not conformed to this world,
but be transformed in the spirit of your mind,
that you may prove what is that good and acceptable and
perfect will of God concerning you.`'

Second month.
On the morning of one of the First-days of the week this month,
(probably the 11th,) Thomas Kite was led sweetly to address his family.
He said he remembered that the Saviour said to his disciples,
"`You are the Light of the world;`" and again He said, "`I am the Light of the world.`"
He then expressed his earnest desire that those present
might so partake of the Light of the Saviour,
as to shine in their respective places, and be as lights in the world.

On the 18th he wrote to a young friend;
"`The work of the soul`'s redemption is a great work;
and many conflicts of spirit we must all pass through in whom this work is going on.
If the Great Master has any special service for you in his Church,
beyond being a preacher of righteousness in life and conduct,
which every follower of Christ is called to, He will not fail to manifest it to you,
and in his own time endue with strength and clearness for his own work.
Be you faithful in a little, and He will make you ruler over more.`"

Diary: Second month 22nd. Fifth-day.
"`Having for a considerable time felt drawings to visit
Friends of Salem Quarterly Meeting in their different meetings,
I obtained a minute for that purpose from our Monthly Meeting held this day.
Dougan and Asenath Clark were with us,
being about to embark for Great Britain on a religious visit.

25th. First-day.
In the afternoon I was drawn into sympathy with the afflicted of various classes.
I was engaged in communication, beginning with the words of our Lord,
'`Blessed are they that mourn, for they shall be comforted.`'

26th. Second-day.
My brother James and his wife having heard this day of the death of their daughter Eliza,
aged a few months, at the house of her uncle, Samuel Boyce, in Lynn, Massachusetts,
my wife and I went to visit them in the evening.
A religious opportunity occurred,
in which I was concerned to address them on the afflicting occasion.

Third month 1st. Sixth-day.
Set out on my visit to the meetings of Salem Quarter,
accompanied by my kinsman James E. Greeves.
Lodged at George Mickle`'s, near Woodbury.
Previous to leaving the family, the next morning,
(2nd,) a religious opportunity took place,
in which I was concerned to address the heads of the family and the children.
Dear Mary Mickle expressed a few words at the close.
Went to Greenwich, and lodged at cousin Moses Sheppard`'s.

3rd. First-day.
At Greenwich Meeting I was helped to relieve my mind towards various states;
close things were said to some, and consolation offered to others.
Dined with my aged friend, John Sheppard.
He and his daughter Mary, accompanied us to his son Clarkson`'s to tea.
An opportunity of religious retirement took place in the evening,
and I had to address an individual present from the words of Christ to Nathanael,
'`Before that Philip called you, when you were under the fig tree, I saw you.`'
Mary Sheppard had a short communication.

6th. Fourth-day.
After a sitting in the family where we lodged,
in which ability was granted to address the heads of it, we went to Salem Meeting.
Here I was again enabled to preach the Gospel of Christ,
and to divide the Word to various states; leaving the meeting-house in peace.
Went to the house of Hope, the widow of Paul Scull, who has lately departed this life.

7th. Fifth-day.
Again this morning, the widow, her only son, her married daughter and son-in-law,
being together, I had to address the three last in Gospel love.
Went to Pilesgrove Meeting,
and had cause to acknowledge the renewed extension of
Divine regard in qualifying to plead with the people.
Returned to the widow`'s to dine.
When about leaving the house, the covering of silence overspread us,
under which my mouth was opened in prayer for the various members of the family,
that the afflictive dispensation of late meted out, might be blessed to them.
Went to my beloved aged friend, Joseph Whitall`'s, to lodge.

8th. Sixth-day.
At Woodbury Meeting.
I had an open time in communication,
commencing with the language of the Most High by the Psalmist,
'`Gather my saints together unto me,
those that have made a covenant with me by sacrifice.`'
In the afternoon returned home in a state of peaceful poverty.`"

In reference to this visit, he writes to his daughter Rebecca: "`On the whole,
I feel glad I have been out, and that this debt of Gospel love has been paid.`"

Diary: "`Third month 10th. First-day.
Our morning meeting seemed favoured.
It was mostly held in silence, yet towards the close,
I was engaged in the solemn service of supplication.
The afternoon meeting seemed to me a low time.
S+++.+++ Biddle appeared in the evening, and Elizabeth Evans was engaged in prayer.

13th. Fourth-day.
Feeling a draft thereto, I attended the meeting for the Southern District.
The prophet Ezekiel`'s vision of the holy waters being before me,
something was spoken relative thereto, and also on other subjects which presented.
I felt calm and peaceful after the meeting,
which I esteem a renewed instance of merciful regard from Him whom,
however unworthy I am, I desire to serve in the Gospel of his Son.

14th. Fifth-day.
Openings attended at our week-day meeting concerning John`'s baptism and that of Christ;
they were both spoken to;
and those addressed who are now under the administration of the latter,
feeling it operating upon their pride, impurity, earthly affections,
and whatever in them the Lord`'s controversy is against.
These were counselled patiently to endure until the Heavenly Refiner has done his office,
and the soul is prepared rightly to rejoice.
The same day a friend whom I much love,
spoke to me incautiously in commendation of my service,
which introduced me into exercise and fear:
'`Lord preserve me in self-abasedness before you;
and grant that all I do may be with a single eye to your glory.`'

17th. First-day.
In the morning I attended the North Meeting from a secret impulse, and was silent therein.
In the afternoon, at our own meeting,
laboured a little to encourage the '`prisoners of hope.`'
In the evening I had a testimony to bear to the nature of spiritual worship;
after which Hannah Gibbons and Samuel Cope were engaged in Gospel communications.
I believe the meeting closed too soon.

20th. Fourth-day.
The remains of Deborah Hutton, daughter of Richard and Ann Wetherall,
were interred yesterday in the burying-ground belonging
to Friends of Chester Meeting (Pennsylvania).
Way did not open for my attendance; but today I went to that meeting,
and there met with the husband, parents, and other relations of the deceased;
and we were favoured with a solemn season,
in which ability was furnished to preach the Gospel of life and salvation,
and to comfort the mourners.

21st, Fifth-day.
Unexpectedly it seemed to be my duty to sit with Friends of Newtown Meeting;
accordingly I went there.
It proved a low time,
yet some capacity seemed furnished to set forth
the necessity of our experiencing regeneration,
and also that there is a '`needs be`' for the afflictions
which our merciful Father permits to befall us.

Fourth month 1st. Second-day.
I went to the funeral of Rest, the wife of my brother-in-law, Benjamin Cope.
During the opportunity before the removal of the corpse,
it appeared to be my place to bend the knee in vocal supplication.
At the grave Sarah Emlen addressed an individual present in a very close manner,
yet under the influence of Gospel love.

4th. Fifth-day.
At Westtown.
In the morning meeting Sarah Emlen commenced the vocal service,
followed by William Scattergood and William Evans,
after which I had a communication from the Scripture passage,
£ He that being often reproved hardens his neck, shall suddenly be destroyed,
and that without remedy.`'
Some who had often been reproved, both immediately and instrumentally,
were reasoned with; and others who had entered into covenant with the Lord,
were encouraged.
The examination closed in the evening.

7th. First-day.
I had a testimony to bear in the afternoon meeting, and in the evening +++[+++had]
a private opportunity with a valuable young friend.

8th. Second-day.
Much oppressed with the prevalence of the earthly nature.
Our Preparative Meeting of Ministers and Elders was to me a low time.

9th. Third-day.
Felt somewhat relieved of the deep depression I have laboured under for several days,
and my mind was turned to the North Meeting.
After our friend, John Pease, had appeared in testimony,
I had to speak of the excellency of that living
faith which is the substance of things hoped for,
and the evidence of things not seen, by which the holy ancients obtained a good report.
The subject was illustrated by bringing into view the case of the prophet Elisha,
when the King of Syria sent an army to apprehend him.
The meeting seemed to be in a good degree favoured.

B+++.+++ Hoyle to Thomas Kite

Mount Pleasant, Fourth month 20th, 1844.

Dear Friend:--Feeling under obligation for your two last acceptable communications,
and also, I trust, an inclination to salute you under feelings of brotherly love,
I cannot easily let the present opportunity of
conveyance pass without dropping you a few lines.
I noticed in your last an intimation not to remain in any present engagement,^
footnote:[Superintendent of Mount Pleasant Boarding School.]
to the hindrance of more important concerns.
For this token of the kind remembrance of my distant friend,
I hope to feel gratitude to that Almighty Caretaker,
who at times puts into the hearts of fellow travellers to remember one another for good.
I desire to be continued in your remembrance.
I have had, if I may be permitted to unbosom my feelings,
some descendings into low places for several months past,
yet not without an evidence now and then afforded,
that I am under the protecting care of the Shepherd of Israel.
Believing that these dispensations are profitable,
I dare not wish for it to be otherwise ordered, but am bound to acknowledge that,
'`Good is the Lord, and worthy to be praised.`'
'`His will is our sanctification;`' and that work
is completed in us as we are found doing it,
or permitting it to be done in us.
May the Lord enable us more fully to drink of the cup that He drank of,
and to be baptized with the baptism that He was baptized with;
for hereby are we kept in our proper allotments.

Your annual assembly is perhaps by this time over.
Has the ministry been of that description which tends to bring '`under
the cross of Christ '`? The accounts from your side latterly have been,
so far as I have seen them, favourable, and heartily do I wish it may prove so.
I am not without fears that there may be that among us,
which may be likened to £ wine mixed with water.`'
Unless the Blessed Head of the Church interposes
for his cause`' sake and for his honour`'s sake,
there may be those liberated by some of the Yearly Meetings, even to cross the sea,
whom He has not sent.
These cannot profit the people at all,
but must add affliction to the true burden-bearers where they may travel.
These remarks do not apply to any such cases
that may have been before your Yearly Meeting;
but surely there is a lack of true discerning in some directions.

Fifth month 13th. Sixth-day.
Our Yearly Meeting has been held, which was upon the whole a favoured season;
the Meeting for Ministers and Elders particularly so.
Our friend, Sarah Emlen,
was set at liberty to visit the churches in Great Britain and Ireland.
We had the company of John Pease, Isabel Casson, and Rachel Priestman,
the latter of whom obtained a returning certificate.
Yesterday in our Monthly Meeting I was drawn forth in vocal supplication,
and had afterwards a short communication.
Isabel Casson and Rachel Priestman appeared in testimony.`"

During the spring of this year symptoms of a pulmonary
affection appeared in Susanna Sharpless.

Fifth month 5th, her sister Rebecca writing of her then condition, says:
"`Dear uncle +++[+++Thomas Kite,]
I cannot but feel sad when I call to mind the suffering,
emaciated frame of a sister so tenderly beloved,
and feel that before long she may be taken from us.
She is very sensible of her situation, and is, I believe,
desiring to be prepared either for life or death.
She told me she had not asked to be restored,
though she felt keenly the prospect of parting from her husband and children.
May we all seek for resignation to the Divine will,
and urn murmuringly drink of whatever cup He may see fit to hand us.`"

On the 11th the doctor said she seemed better.
There was more to hope but much to fear.
The invalid that day, after a hard spell of coughing,
(alluding to the idea of some that the fine summer weather would improve her health),
said, "`It wall take more than pure air to cure that cough.`"

About the middle of the Fifth month, Thomas Kite visited his sick daughter,
and attended Cain Quarterly Meeting.
Fifth month 24th he writes to his daughter Rebecca:

"`I propose sending this letter by a young Friend of Ohio,
and a member of Indiana Yearly Meetiug, who is about to become a scholar at Westtown.
Her mother spoke to W. E. and me at Richmond last fall concerning her,
and has since by letter commended her to our care.
She seems amiable and intelligent,
and I wish you to pay some attention to her as a stranger.
I should think her health would be benefitted by frequent walking.
Above the desire I feel for her improvement in useful knowledge, the prevalent one is,
that religious impressions may be deepened,
and she favoured to return to her friends a decided
lover of the cross of our Lord Jesus Christ,
which crucifies the world with every evil affection.

We feel anxiously solicitous respecting your dear sister.
When we consider what she has been, and is to us,
and what she is to her dear husband and children, it is natural that we should feel.
I have not, however, yet given up all hope that she may be restored to us for a season,
but I wish to endeavour to stand resigned to the dispensations of our heavenly Father,
fully believing the Judge of all the earth will do right,
and that He can make up to bereaved ones every loss, sanctify every affliction,
and prepare his children to join the innumerable company,
who had not only "`come out of great tribulation,`" but also "`washed
their robes and made them white in the blood of the Lamb.`"

Our friend, Lydia Dean, seems gradually declining.
I have been to see her several times since her confinement to her room.

Your mother and I have just returned from Sarah E. Oresson`'s,
where we went to say farewell to Sarah Emlen.^
footnote:[About to embark to Europe on a religious visit.]
A time of religious retirement took place,
in which some precious feelings were experienced,
and some expressions of sympathy with our dear friend,
and also with her companion who remained at home.

Thomas Kite to his son Thomas.

Fifth month 27th. 1844.

My Dear Son:--Your sister Rebecca`'s letter has, no doubt,
apprised you of our dear Susan`'s illness.
It will be eight weeks tomorrow since she was taken sick.
She was at the time, as well as her husband,
under appointment to attend the Yearly Meeting,
and we were anticipating the satisfaction of having them in the city,
but it was otherwise ordered; and we have had a time of great anxiety.
The disease was at first a catarrh fever, afterwards it turned to bronchitis,
attended with severe cough and other distressing symptoms.
However desirous your mother was of paying you her long talked of visit,
of course she could not positively decide on anything
while your sister remained in this critical state,
and for that reason we have forborne writing until some change should take place.

Your uncle Nathan and your mother returned from East Bradford last evening,
and report the dear invalid better, so that the prospect now is, should she continue so,
for your mother to be at Pittsburg in time to take the steamer
Majestic on Seventh-day the 29th of the Sixth month.
But as Susan is still very weak, and a relapse may take place,
I wish you not to be too sanguine in expecting your mother,
and endeavour to bear it with fortitude should you meet with a disappointment.

To the Same.

Fifth month 29th.

Cousin Rebecca Haverstick`'s funeral was largely attended, and was a solemn time.
A testimony was delivered at the house,
in which the confidence was expressed that she had known the washing of regeneration,
and was safely landed in the realms of bliss.
R+++.+++ Collins appeared in prayer.
At the grave Sarah Hillman had a testimony to bear, commencing with,
"`They shall hunger no more, neither thirst any more;
neither shall the sun light on them, nor any heat,
for the Lamb which is in the midst of the throne shall feed them,
and shall lead them unto living fountains of water;
and God himself shall wipe away all tears from their eyes.`"
It seemed to be her belief that our kinswoman had been admitted to
participate in the blessedness enjoyed by the redeemed.

It seems as if I could scarcely let any letter depart without the expression of the wish,
that, with respect to you, lies nearest to my heart, which is,
that as you are growing in years, you may be growing in grace;
not on]y avoiding the very appearance of evil, but that,
cheerfully taking up the cross of Christ, the dear Redeemer,
you may be found following Him in the regeneration.
In our dear cousin`'s case we see how uncertain is time;
may it be increasingly your concern to be found ready when the call is issued, "`Steward,
give an account of your stewardship, for you may be no longer steward.`"

Thomas Kite to his daughter Rebecca.

Fifth month 31st, 1844.

The accounts we receive of your sister`'s state in various ways,
seem rather more encouraging.
I am aware, however, that she remains much indisposed.
There is sympathy due to her and her valuable companion, as well as to other dear friends.
I feel for you, my dear daughter;
between your school duties and your natural desire to be with your sister,
I suppose you have some struggles.
However,
by this time you have learned that many trying things
have to be borne in our journey through life.
I observed in one of your letters a remark, to the effect,
that you had been enabled to attend with cheerfulness to your classes.
I am glad of it, and hope you will continue,
while Westtown remains to be your proper place,
to discharge your engagements there with fidelity.
Catharine W. Morris is quite unwell, also Rebecca Folwell; the latter, it is thought,
can hardly recover.
Our aged friend, Gulielma Widdifield, is confined to the house with indisposition,
and Jane Peirce was absent from Monthly Meeting yesterday, from the same cause.

We have had an intimation that Joseph Edgerton will probably soon be here,
having in view to attend some meetings within the limits of our Yearly Meeting,
and also to be at that held for New England.
The latter part of his prospect I should think would not be very pleasant to him.

In the beginning of the Sixth month, Thomas Kite,
whose heart was closely drawn towards his suffering daughter, paid her another visit.
He found her not quite so well as she had previously been, the effect, it was thought,
of damp and rainy weather.

On the 10th, Rebecca Kite writing of her sister says:
"`The doctor thinks her disease has now assumed a decidedly consumptive form,
and notwithstanding an increase of strength, he does not feel at all encouraged.
I have watched her now week after week, and my mind but strengthens in the belief,
that before very long we will have to part with one whose uniform
kindness and loveliness has closely entwined her round our hearts.
On Seventh-day she said, alluding to the time when I should no longer have a sister,
'`I could remember how much we had loved each other and had enjoyed being together.
She had not indulged herself with thinking that
we should recognize our friends in another world;
she thought that would be a matter of little importance if she could only be
found worthy to obtain the lowest seat in the Heavenly Kingdom.`"

Thomas Kite to his daughter Rebecca.

Sixth month 18th.

Your mother and I are much obliged to you for
keeping us informed of the state of your sister;
her situation, we are aware, is critical,
and we cannot calculate on her being raised again to health,
unless such should be His determination to whom all things are possible.
Great as will be the trial to myself, and to others of my family,
to part with this long-cherished and beloved member of our circle,
it will no doubt be more keenly felt by her beloved partner.
To him and the children the loss will be great.
May our merciful Father in Heaven strengthen and comfort him, and care for them.

Ever since I saw you last, I have felt at times some solicitude on account of your health.
I wish you would make an effort to regain your former habits of walking,
particularly in the morning,
even if you have to omit some sewing and some
writing to obtain the time to accomplish it.

Sixth month 21st. Susanna Sharpless was a little stronger, but had a suffering day.
She said she did not think herself any better.
The disease was a flattering one,
and she thought the many changes were calculated to unsettle the mind.
A Friend (J. E.) who at this time visited her,
remarked afterward her "`bright and cheerful countenance`" and
"`the gathering of solemnity`" which was at times upon it.
He thought we need not say of such as she was, "`they would be blest,
they were blest already.`"

Thomas Kite to his son Thomas.

Sixth month 25th.

I received a letter from you a few days ago,
in which you speak of your mother`'s proposed visit.
She came home from Aaron`'s on First-day evening, and left your sister in a declining way,
so much so that she cannot feel easy to leave home,
for fear she should be called away in her absence.
Since I last wrote to you Susanna`'s disease has assumed
a more marked character of pulmonary consumption.
No calculation can be made as to how long she may last.
It is no doubt a great trial to your mother to give up her proposed visit,
and it will be so to you to be disappointed.
To you both and to us all,
it will be a severe affliction to part with our loved and cherished one,
whose amiable qualities, and faithful performance of her duties, as wife, mother,
child and sister, have won our affection in no ordinary degree.
It has seemed her great object to make those around her comfortable;
and she appeared to be prepared for greater usefulness in the Church.
But we are poor judges of what is best.
"`Shall not the Judge of all the earth do right?`"
was the question of faithful Abraham.
No doubt He will; and however we may feel, it is our duty to submit,
and look to the Lord alone for consolation, who in his own time, if we murmur not,
will comfort all that mourn.

With renewed desires for your preservation in the fear of the Lord,
in bearing your daily cross, and in obedience to all the dictates of the Holy Spirit,
I am your affectionate father.

A black boy, twelve years old, who died some time since, I think of consumption,
said near his close, "`God is my Creator, Christ is my Redeemer,
the Holy Spirit is my Sanctifier, and Heaven is my home.`"

Thomas Kite to his daughter Rebecca.

Seventh month 6th.

There are many circumstances in the present day of a serious aspect,
and many exercises for the Christian traveller to pass through.
The old, as well as the young, have their conflicts,
and there is but one Power can sustain and preserve any of us.
To a single attention to Him who is given as a Leader and Commander to his people,
I would recommend my dear children with a wish
to be their companion in this necessary concern.
I am your sympathizing and affectionate father.

Thomas Kite to his son Thomas.

Seventh month 15th.

As I have heard of a private conveyance for a letter,
I avail myself of it to give you further information respecting your sister Susanna.
Her disease seems to be gradually making its progress,
and although we sometimes hear that she seems more comfortable,
yet on the whole she is weaker, and wearing away.
Your mother and I expect to go to Aaron`'s tomorrow, to remain for some time.
We have no fixed plan, but must be governed by circumstances.
No doubt you have heard greatly exaggerated reports of the late riots.
The reality was truly sorrowful, not only from the loss of life,
but from the disposition of resistance to the lawful authorities manifested.
Many causes have contributed to bring about this state
of things amongst a portion of our community.
Religious and political animosity had a share, and injudicious publications,
particularly in the penny papers, have kept up an almost constant irritation.
Some of the editors have been called to account.
Many companies of country volunteers are here on military duty,
to their own inconvenience, and to the detriment of their farms and families.
I am as fully convinced as ever of the propriety of peace principles,
and desire all our members may not only keep out of the spirit of war,
but be preserved from that agitation of mind which results
from unprofitable discussions of the aspect of affairs.
Were we truly living under the government of the Prince of Peace,
our example would be of importance wherever we might live,
and our spirits would afford a practical illustration of the nature of his kingdom.

Same to Same.

Seventh month 31st.

Dear Susanna keeps very much indisposed.
Your mother and I spent about a week at Aaron`'s. She was in a state of much suffering.
We left to attend our own Monthly Meeting,
intending to return after the Quarterly Meeting.
We hear she has been somewhat easier since our return,
although there is no change that is likely to be permanent.
The doctor gives no expectation of her recovery.
Your sister Rebecca has been frequently to see her,
and through the kindness of the superintendent and her fellow teachers,
she has been permitted to remain with the dear sufferer about two weeks.

Thomas Kite to his daughter Susanna.

Eighth month 2nd, 1844.

My Dear Daughter:--I have not written to you lately,
but it has not proceeded from any diminution of affection.
On the contrary you were never more dear to me than now,
when you are under the discipline of affliction,
which sooner or later in one form or another, all the Lord`'s children have to partake of.
"`Whom the Lord loves He chastens, and scourges every son and daughter whom He receives.`"
I believe you are disposed to say, "`It is the Lord,
let Him do what seems Him good;`" and yet nature is weak;
and fears at times may arise whether you will be able to endure
protracted suffering with entire patience and resignation.
Ah! my dear child, our compassionate Father knows our frame,
and will not mingle more bitter ingredients in the cup of sorrow,
than He sees to be best.
Meanwhile He condescends to let his suffering children remember that his name is Love,
and that mercy is his attribute, and that his promises are all yes and amen forever.
His promises are of strength and support equal to the trials of our day,
and of an everlasting day of rest and comfort
when the afflictions of time have passed away.
The language of my heart is, "`The Lord hear you in the day of trouble,
the name of the God of Jacob defend you; send you help from his sanctuary,
and strengthen you out of Zion;`" giving you to experience the faith of the Psalmist,
"`Blessed is he that considers the poor, the Lord will deliver him in time of trouble.
The Lord will strengthen him upon the bed of languishing;
you will make all his bed in his sickness.`"
Then trust in Him with all your heart, and I believe He will be near,
giving you to see the greatness of his salvation, and that it is all of mere mercy;
"`Not by works of righteousness which we have done, but of his mercy He saves us,
by the washing of regeneration and the renewing of the Holy Spirit.`"

Thomas Kite to his daughter Rebecca.

(Same date.) Having written to your sister,
I seem to have little at present to say to you.
I understand you expect in a few days to return to your duties at the school.
I have left this subject to your own feelings, but as you have come to this conclusion,
it will not perhaps be improper to say, I am satisfied with it.
When there, endeavour as much as possible to give your mind to the service of each day,
without unprofitable anticipations.
I trust the time you have past with your suffering sister has
not been without its lessons of profit to you;
and I feel an earnest desire that every trial may be blessed and sanctified to you,
producing greater degrees of humility, tenderness and love;
and that your determination to devote yourself to the Lord and his cause,
may be strengthened through the renewings of holy help.

We sometimes notice what we deem to be inconsistencies in
those whom we nevertheless believe to be on the Lord`'s side.
It is seldom of advantage to the young to speak of these things to others.
Let them take warning as regards themselves,
and remember that none are safe unless the holy watch is maintained.

On the 8th of Eighth month, Thomas Kite attended Abington Quarterly Meeting.
Joseph Edgerton was first opened in Gospel power and authority,
and having closed his communication, Thomas Kite soon rose.
He said although we did not believe it to be right to eulogize the dead,
for their own sake,
yet the apostle exhorted the believers to "`Remember them that have the rule over you,
who have spoken unto you the word of God; whose faith follow,
considering the end of their conduct, Jesus Christ, the same yesterday,
today and forever.`"
He added we were both allowed and recommended to have the righteous in remembrance,
and he had been afresh reminded of a dear departed sister of that Quarterly
Meeting who had lately been removed from among them by death,
whose life, conduct, and labours, many of the present company had witnessed,
and whose faith had been of that kind which was worthy of being followed.
He stated his belief that there were some present for
whom this dear friend had been exercised,
that they might be turned from the error of their ways,
but who had not yielded to the reproofs of instruction.
To these she, as it was said of righteous Abel, "`being dead yet speaks.`"^
footnote:[Alice Knight who had deceased.]

During the Eighth month, Thomas Kite spent some time with his declining daughter.
On the 26th after his return he thus concludes a letter to his daughter Rebecca:
"`With affectionate desires for your preservation in the path of rectitude, in humility,
watchfulness, and filial fear of offending your Heavenly Father, either in thought,
word or deed, I remain your anxiously concerned parent.`"

Same to Same.

Eighth month 30th.

At our Monthly Meeting yesterday we had the company of Hannah Warrington,
who has been visiting some of the meetings of our Quarterly Meeting with a minute.
She had a good communication to deliver on the parable of the talents,
and on that of the wise and foolish virgins,
calculated to promote self-examination as to whether we were
rightly using the gifts and talents dispensed to us,
and were thus preparing to have oil in our vessels, with our lamps,
at the period when the solemn sound should be heard,
"`Behold the Bridegroom comes,`" etc.
Your mother thought she had acceptable service in the last meeting.
William Evans was also at the first meeting, and had a powerful testimony,
setting forth the nature and ground of true unity,
beginning with the Psalmist`'s declaration,
'`How good and how pleasant a thing it is for brethren
to dwell together in unity,`' with more of the passage.
Our men`'s meeting was comfortable,
much unity of feeling prevailing in relation to the business which came before us,
of which we had a considerable amount,
so that we did not get released until near two o`'clock.

Thomas Kite to Ann Eliza Yarnall.

Eighth month 31st.

Dear Cousin.
My daughter Susan mentioned to me that she thought the
volume of "`Memorials recently prepared,
would be acceptable to you.
I therefore present you with a copy, which accompanies this letter.
When we read of the self-denying lives and happy deaths of the servants of Christ,
it has an animating and encouraging effect, and under the Divine blessing,
sometimes renews in our hearts, fervent desires to follow them as they followed Christ.
I feel a wish that this may be the case with you in seriously perusing this little work,
in which is contained excellent testimonies to the power and
efficacy of the Grace of our Lord Jesus Christ.
I have no doubt you have for years felt the stirrings of the Holy Spirit,
and I believe you are sensible the Lord is calling you
to walk in the narrow way which leads to life;
let nothing discourage you, my dear cousin, from surrendering yourself without reserve,
to be what the Lord would have you to be.
Sometimes when young persons seriously disposed,
see those who make profession of being religious,
acting inconsistently with such a profession,
it has a tendency to produce reasonings of an unfavourable character,
and the enemy takes advantage of the miscarriages of others to
stumble those and turn their feet out of the way.
But we are to leave others to the Lord (unless when it
is our duty in meekness to plead with them),
and to let their faults prove warnings to us.
The call of the Lord to his visited children is, to come out of all that defiles,
all that stands opposed to purity and holiness,
and on the terms of obedience to his call, He will make them his adopted children;
"`Come out from among them and be separate; touch not the unclean thing,
and I will receive you, and will be a Father unto you;
and you shall be my sons and daughters, says the Lord Almighty.`"
I am your affectionate and sympathizing friend and cousin,

Thomas Kite.

Thomas Kite to his Daughter Rebecca

Ninth month 2nd.

There is no situation or station exempt from trial and temptation.
Hence the necessity of individually attending to our Lord`'s command;
"`What I say unto you I say unto all, Watch.`"
As we are rightly careful in this respect,
we shall see our weakness and various deficiencies,
the sense whereof should lead to secret prayer for deliverance from evil,
and that having put our hands to the plough, we may not look back,
and grow more indifferent about the things which accompany salvation,
than we were in former years.
If thus watching unto prayer, we shall experience an increasing fervency of spirit.
But we may take up no rest short of the true rest,
nor ever be contented short of the living experience
which Paul so forcibly describes as his own;
"`I am crucified with Christ, nevertheless I live; yet not I but Christ lives in me;
and the life which I now live in the flesh, I live by the faith of the Son of God,
who loved me, and gave himself for me.`"
May this be increasingly the case with my beloved daughter,
that thus amidst the trials and afflictions of the present life,
she may be preparing for another state of being,
where the ransomed and redeemed of our God, "`shall hunger no more,
neither thirst any more; neither shall the sun light on them nor any heat,
but the Lamb which is in the midst of the Throne shall feed them,
and lead them to living fountains of water,
and God shall wipe away all tears from their eyes; and there shall be no more death,
neither sorrow nor crying, neither shall there be any more pain;
for the former things are passed away.`"

Thomas Kite to his son Thomas.

Ninth month 5th.

By your mother`'s letter I suppose you have information
of your sister`'s continued indisposition,
and that there remains no probability of her recovery.
There seems no doubt with us that her end will be peace.

I often feel solicitous for the younger members of your Monthly Meeting,
that there may be a greater consistency amongst them with our profession.
It is hard to the strong will of man to be subject to the cross;
but unless this be faithfully borne it is vain to
expect firm and upright supporters of our testimonies.
May good Joshua`'s resolution be yours, "`As for me, I will serve the Lord.`"
Let everything else give way to the resolution to live for the cause of Truth.
Study to be quiet, and do your own business;
the first and most important part is to work out
your soul`'s salvation with fear and trembling.
Then will you be prepared rightly to discharge every relative duty,
and to fulfill such services in the church as may
be consistent with your age and experience,
ever remembering that godliness is profitable unto all things,
having the promise of the life that now is, and of that which is to come.
I have no doubt Truth would lead to a stricter administration
of the discipline than is common in some parts.
But the men to enforce this must be clean handed.

Thomas Kite to his daughter Rebecca

Ninth month 6th.

+++[+++After a little general information he concludes a short note thus:]
I cannot think of anything more, necessary to tell you at present.
So with desires for your stability, watchfulness and increasing dedication to the cross,
even until your own will shall be crucified and slain, I remain your affectionate father.

Ninth month 9th, Thomas Kite attended Haddonfield Monthly Meeting.
On the 10th, writing to his daughter Rebecca, he says:

"`We hear more unpleasant tidings from New England.
There have been some operations commenced in another
Monthly Meeting of Rhode Island Quarterly Meeting,
which, if we are rightly informed, are of an arbitrary character.
The prospect of what the issue may be seems gloomy and discouraging.
Yet everything of this kind, or any trials nearer home,
should incite us to individual faithfulness;
for whatever may be permitted to befall any of the children of men,
the sentence of the wise man will stand good,
'`Surely I know that it shall be well with them that fear God; that fear before Him.`'`"

Sarah Emlen to Thomas Kite

Belfast, Ninth month 15th, 1844.

My beloved friend, Thomas Kite,
has very many times been the companion of my mind since being in this land;
and I should have been glad to have known of this opportunity earlier,
that I might have written you to say, how glad I was of,
and how much good your kind and welcome letter did me,
which was handed me after we had been out at sea a week.
Indeed, it caused tears of gratitude to flow, that I had been so kindly remembered.

`'Tis now after ten o`'clock, and after the labour of attending,
two large meetings in this place, (which,
I think I may say were overspread as with Emanuel`'s wing), feeling spent,
and as if my little store was nearly exhausted,
I am too poor to have anything worth your notice.
But you are my interested friend, and will understand me, when I say,
that I have been many times a wonder to myself,
so marvellously has the Lord made my way where there seemed to be no way;
so that my heart has often been attuned, both secretly and openly, with living praises.
May all the praise and all the honour ever be
ascribed to the "`Lion of the tribe of Judah.`"
Please give my dear love to your E., sister Mary, Rebecca, William and wife, etc.
Ah! dear Aaron! how often have I thought of him.
How is it?
Is dear Susan with you yet?
or has she taken her flight to join the saints above?
How incomprehensible are the ways of Providence!
A letter addressed to the care of Isaac Hadwin, of Liverpool, would find your friend,
Sarah Emlen.

Thomas Kite to his son Thomas.

Ninth month 16th.

We are about in usual health, excepting your sister Susanna, who gradually declines.
Her limbs now swell towards night, but the swelling abates by morning.
Water also appears to accumulate on her chest.
She seems to be supported under her sufferings,
and her reliance is evidently on her Creator and Redeemer.
It is quite uncertain how long she may yet have to struggle with her afflictions.

On the 16th, Susanna Sharpless became alarmingly oppressed,
and in the belief that her end could not be very distant,
asked for her husband and then for her children.
When they came, she affectionately bade them farewell, and addressed some sweet,
parting counsel to two of the children.
She expressed that she felt peace.
After a time she alluded to her sister, then attending to her duties at Westtown.
Understanding that she desired to see her before the close,
a messenger was sent after her.
During this day (2nd), it seemed as if the struggle would suddenly end,
and death must come, she suffered such intense agony.
Towards night, however, she revived, and was easier.
Observing this, she remarked, "`What a disappointment.`"
That evening she said, "`I am ready to query:
why are his chariot wheels so long in coming?`"
On Third-day, the 17th, she lay gasping for breath,
and though apparently in the perfect possession of her senses, spoke little; yet,
during the afternoon, she at one time exclaimed, "`It is written;
suddenly,--in a moment,--in the twinkling of an eye, we shall be changed!
Oh! that the change would come to me!`"
She was very anxious to be gone, but, as her aunt P. wrote,
"`is a pattern of quiet submission.`"

During Fourth-day night the period came for her release.
A letter announcing the event to her connections in Philadelphia, (written on Fifth-day),
says: "`Since Second-day morning she was almost in a constant struggle for breath.
Several times they thought her going.
Last night, waking out of sleep, she seemed very feeble, and sat up in bed for a time.
They noticed a rattling in her throat, and cousin Aaron was called.
In a few minutes she passed away, very calmly and quietly.`"

The following account was penned by one present at the close and funeral:
"`It was my privilege to witness the closing scene,
and it was the first time I had ever been present on such an occasion.
Half propped up in bed, she gently drew her breath at short intervals, until all ceased.
A solemn silence prevailed over the room,
which was before long broken by the voice of supplication,
returning thanks to God that He had taken unto himself our beloved friend and relative.

Surely there is cause for thankfulness and rejoicing,
and however deeply we may feel our loss, when, as in this case,
we have reason to believe that those who have been removed
from us had through mercy experienced their natural affections
and propensities regulated by the standard of the cross,
their sins forgiven, and an entrance administered unto them into the celestial city.

Her funeral, which took place on Sixth-day, the 20th of the month,
was attended by many of those who had been attached to her during life,
by the ties of affection and relationship.
Her father spoke +++[+++in the ministry],
and appeared in supplication in the room where the family were collected together;
and the tender feeling which prevailed was very precious.
At the grave also his mouth was opened to express his own resignation,
and his sense of her worth, and to bear testimony, that by the grace of God,
she was what she was.

The sentences which follow, are believed to be nearly as they were uttered:

'`There is now no condemnation to them which are in Christ Jesus,
who walk not after the flesh, but after the Spirit;
for the law of the spirit of life in Christ Jesus has
made me free from the law of sin and death.`'
'`Blessed are the dead who die in the Lord from henceforth; yes, says the Spirit,
that they may rest from their labours; and their works do follow them.
Some experience their sins to go beforehand to judgment, and some they follow after.
What a blessed thing to know, a going beforehand to judgment!
That this was the experience of this, my firstborn and precious child,
I am thankfully made to believe.

By one stroke how many tender ties have been severed.
An obedient child,--a loving and faithful wife,--
a tender and watchful mother,--has been removed.

By the grace of God she was what she was;
and it may be for the encouragement of some present, that my voice is heard this day.
May you be enabled to give up all and follow Christ.
I am enabled to say, '`The Lord gave and the Lord has taken away;
blessed be the name of the Lord!`'

The following notice appeared in "`The Friend:`"

"`Died, Ninth month 19th, at the residence of her husband, in East Bradford,
Chester County, Pennsylvania, in the 36th year of her age, Susanna,
wife of Aaron Sharpless; a member of Birmingham Monthly Meeting.
During her last illness, which was of many months`' duration,
she was enabled to bear her acute sufferings with
patience and resignation to her heavenly Father`'s will.
Having from an early period of her sickness been
persuaded that it would terminate in death,
she was quietly yet earnestly engaged that her concerns, outwardly and inwardly,
might be found in order.
She appeared as a servant watching for her Lord, not knowing the moment of his coming,
but yet rejoicing in the belief that He would not tarry,
but through redeeming love and mercy would gather her into his mansions of rest.`"

Thomas Kite to his daughter Rebecca.

Ninth month 27th.

A notice of dear Susan`'s death is in "`The Friend.`"
It seems to me to be cautiously written, and I hope will not give uneasiness.
Much more might have been said with truth,
but this will give a hint to her distant friends
of the composed and resigned state of her mind.
It was written by your uncle N. When anything is said,
either in brief notices or longer memorials, of the pious life,
or happy death of a Christian, the object ought to be to magnify Divine Grace,
and to afford encouragement to survivors to submit to the Power which
can alone prepare for an admittance into the realms of bliss.

On a calm review of all the circumstances attending your sister`'s last illness,
notwithstanding we must keenly feel her loss,
I think we have great cause of thankfulness.
No doubt she suffered greatly; but her pains and sorrows were sanctified,
and the everlasting Arm was underneath; and they may have been permitted in part,
to make those who were united to her by the tenderest ties,
more willingly resign her to Divine disposal, fully believing, as they did,
that her release from the pains of an afflicted tabernacle,
would be succeeded by an entrance into never-ending happiness.
Her memory will be precious to us;
for her agreeable natural qualities being refined and sanctified by religion,
made her truly lovely.
She seemed, according to her measure and opportunities,
to be living up to the exhortation of the apostle,
"`To do good and to communicate forget not, for with such sacrifices God is well pleased.
"`But I must check myself.
By the grace of our Holy Redeemer, she was what she was,
and the praise is due to Him who loved her,
and washed her from her sins in his own blood,
and prepared her for a mansion of glory in his Father`'s house.
May we follow in the way cast up for the ransomed of the Lord to walk in;
and being strengthened to fight the good fight, and to keep the faith,
may we be permitted in the Lord`'s time to follow
her to the regions of light and everlasting joy.

Thomas Kite to his son Thomas.

Ninth month 29th.

Your brother William wrote announcing the death of your sister.
Your mother and I were not with her at the time,
not supposing it would take place so soon,
and I having very particular engagements in the city about the time it occurred.

We had both been considerably with her.
From an early part of her sickness she believed she should not recover.
The thought of parting with her husband and children was trying to nature,
especially the former, considering that his own nearest kindred had been removed.
She felt much sympathy for him.
But she was soon favoured with resignation to her heavenly Father`'s will;
and not only was earnestly engaged that the work of her
soul`'s salvation might be fully accomplished,
but was concerned that her outward affairs should be satisfactorily arranged,
being carried into different apartments, examining her clothing and that of her family,
putting things in order,
and giving directions concerning some articles she wished presented to individuals
of her acquaintance when she was gone as memorials of her affection.
She even gave directions respecting the manner
in which she wished the funeral to be conducted.
A short account for family use will probably be drawn up, mentioning some things,
which she expressed at various times, i just hint for the present at a few of them,
as I have received them from your aunt Mary, who continued with her to the last.
One evening she remarked, '`What a poor creature I am;
not worth all the trouble I occasion.`'
She then said she had been comforted with the communication of dear Joseph Edgerton,
in her chamber a few days before;
and how truly she felt herself '`a poor creature as he expressed it.
But she could say she loved the Truth, and desired to do nothing against it, adding,
'`How consoling the language,
that '`he believed the angel of the Lord`'s presence would attend,
and convey me safely through the dark valley.`'
She several times quoted the language of Job,
'`All the days of my appointed time will I wait until my change come.`'
At one time she remarked nearly in this wise, '`I often have sweet,
comfortable times in the night.
When I awakened last night, I had such a feeling as I never before experienced,
how full and sufficient the sacrifice of our Saviour was for us.`'
Her sufferings were very great throughout most of her illness,
which had a tendency to make her family more willing to part with her,
that she might be released from so much pain.
She received a letter, I believe, from her cousin, Anne S.,
which expressed sympathy with her, and offered encouragement.
On hearing it, she said, '`I hope it is so, that He is near to me;
though at times He hides his face, and I feel very much alone;
yet sometimes in the midst of severe suffering, I feel that He is love.`'
She afterwards observed, '`I have not as clear an evidence as I desire of acceptance,
but I am favoured at times with his presence;
and many times in the day my thoughts are turned towards my heavenly Father.`'
She also alluded in a feeling manner to the gradual weaning
from all earthly things her mind had experienced.
The same day she said to William, '`Dear brother, my days seem numbered,
and my life drawing to a close.`'
She was gradually and sweetly prepared for the solemn change.

On Fifth-day morning, about ten minutes before four o`'clock,
a gentle and peaceful dismission was granted her.
Of her last expressions, only the words, "`Lord Jesus,`" could be distinguished.
A solemn feeling covered the minds of those present at the time of her release.
At the time of her interment, we had a favoured season,
the evidence being granted that her immortal part was
safely landed in the realms of everlasting bliss.
On the whole, although sensible of the great loss we have sustained,
there is much cause for thankfulness, and to adopt the sentiment of Job, "`The Lord gave,
the Lord has taken away; blessed be the name of the Lord!`"

May we be concerned, my dear son,
to give all diligence to make our calling and election sure,
that so we may have the assurance that our names are written in the Lamb`'s book of life.
The fashion of this world passes away;
eternal things are those which should engage our most serious attention.
If the soul is lost, all that is worth living for is lost;
if immortal life is but gained, it matters little, comparatively, what else is lost.

To a friend of the family, residing at a distance,
who on hearing of the illness of Susanna Sharpless,
had written a sympathizing letter to the family, Thomas Kite thus replied:

Tenth month 18th.

You were truly informed as to the situation of our beloved daughter.
Her three children had the scarlet fever last winter, and Aaron was also unwell.
The care and fatigue of nursing had an unfavourable effect on her health.
In the Third month a catarrh fever commenced,
inflammation of the mucous membrane followed, and finally, consumption.
Her life closed on the 19th of last month.
She was early satisfied what the result would be, and with great composure,
prepared for the event, arranging her domestic affairs with admirable presence of mind,
and superintending her household long after her
debility was so great as to prevent her walking.
She was no less earnestly engaged with respect to her soul`'s welfare;
and He whom she had long loved, and desired to serve, her gracious Lord and Saviour,
condescended to give her a comfortable and sustaining hope,
that in the end all would be well.
She appeared to feel much more for her husband than for herself; her children, also,
had large claims on her sympathy.
She imparted her dying counsel to the two eldest in simple language;
gave advice to other members of her family;
had many seasons of sweet communion with Christian friends;
often was drawn forth in prayer and praise, and after enduring severe bodily affliction,
under which she was mercifully sustained, she was at length released,
leaving us the consoling evidence,
that her robes having been washed and made white in the blood of the Lamb,
her ransomed and redeemed spirit has been permitted to
join the multitude which no man can number,
who stand before the throne with palms in their hands.
We feel sensibly her loss, but endeavour to be resigned;
and Aaron is strengthened to support this afflictive bereavement with
proper submission to his heavenly Father`'s will.
Sister Mary went soon after Yearly Meeting, and continued with Susan to the close.
We expect her home next week.

During the time that Rebecca Kite was in Philadelphia
during the Westtown vacation this month,
a circumstance occurred which she thus narrates:
"`The last Fourth-day evening I was at home, all our uncles, aunts and cousins,
who could come, were collected at our house, and some account of dear sister was read.
After the reading, father spoke very sweetly from the text,
'`Behold how good and how pleasant it is for brethren to dwell together in unity.`'
He alluded to the love which united us as a family,
and then very feelingly to our recent bereavement, saying, '`My dear friends,
I have every proof which my heart could desire,
that the change was a happy one to the dear deceased.`'

In the same letter addressed to her brother Thomas, she says:

Have you ever looked back over those who have been taken from us,
and felt thankful in believing that so many of them were prepared for the final change.
Our eminently gifted grandmother +++[+++Edith Sharpless]
we never knew, and our worthy grandfather +++[+++Joshua Sharpless]
had so far passed his prime, that we could not appreciate the vigor of his early days,
when he stood a valiant soldier in the foremost ranks of the Church militant.
We can remember, however, the sweet spirit of his second partner, whom we dearly loved.
Our uncle Isaac Sharpless also was a devoted Christian.
We can remember the noble and generous spirit of our paternal grandfather +++[+++B. Kite]
and his strong love for the cause of Truth,
even though the decay of nature had somewhat impaired his intellectual powers.
In heavenly things there was no decay; he was green in old age,
and with his loins girded was found waiting when his Master
sent the gentle summons to '`enter into the joy of his Lord.`'
His tenderly beloved partner did not long survive him.

Through the course of a long life she had sought to promote the comfort of
others--was a frequent visitor in the abodes of sickness and poverty;
has faithfully performed the duties of a wife and mother;
had the comfort of seeing her sons and daughters useful in the Church;
saw even the third generation springing up around her, when she too,
having followed and faithfully eyed the '`bright star`' which she spoke of near her close,
found it to lead her to a happy home.

Very near her end, she dreamed her husband, arrayed in white,
had come to take her to the mansion prepared for her.
Though her dying agonies were hard to witness, the end was peace.
Our cousins whom we loved as sisters +++[+++Abby Greeves]
and +++[+++Edith Sharpless], our dear brother,
and now our most tenderly loved and cherished sister,
have one by one been summoned by the messenger on the pale horse,
and we trust have all been ready.

Tenth mouth.
In a letter from Rebecca Kite to her brother Thomas,
is some further information relative to Thomas Kite`'s movements this week.
Of the Fifth-day, at Westtown, she says: "`Our dear father was at meeting,
and spoke very interestingly.
'`Information having been received of the death of our uncle, Isaac Hayes,
father went +++[+++to Fallowfield]
on Seventh-day afternoon.
The next morning, before light, brother Aaron, aunt Mary, cousin Joseph and myself,
were on our way To the Same place.
We saw the placid remains of our venerable uncle,
and learned that his end was peace and joy.
Father`'s voice was heard both in the dwelling house and in the meeting.`"

Thomas Kite to his son Thomas.

Tenth month 29th.

I do not wish to fill my letters with repetitions of religious counsels,
the same in substance as I have often given,
yet I know not how peacefully to lay aside my pen
without adverting to the most important of all subjects.
It may suffice for the present to say,
that my feelings towards you are set forth in the language with which
Aaron and his sons were commanded to bless the children of Israel:
"`The Lord bless you and keep you;
the Lord make his face to shine upon you and be gracious unto you;
the Lord lift up his countenance upon you and give you peace.`"

Thomas Kite To the Same.

Eleventh month 6th.

I have been sorry to see so much excitement about the presidential
election and hope that men`'s minds will soon settle down,
and be at liberty to attend more closely to those concerns which are not bounded by time,
but reach forward into eternity, even the concerns of the immortal soul.

Thomas Kite to his daughter Rebecca.

Eleventh month 22nd.

I had occasion to call last evening at William Evan`'s,
and there found Elizabeth Pitfield, Elizabeth Pearson, Joseph Snowdon,
Charles Williams and others.
The covering of silent solemnity was spread over us,
and Elizabeth Pitfield addressed William on the
subject of his prospect of religious service,^
footnote:[Visit to Western New York and Canada.]
offering sympathetic encouragement.
After her, Elizabeth Evans offered comfort to those assembled in a general way;
then William followed, and alluding to the difficulties in the Society,
had counsel to impart to the elder portion of the company present.
The last-named Friend and his companion, Joseph Elkinton,
expect to leave home on their northern tour on Second-day.
I am reminded that Joseph and his wife took tea at my house on First-day evening last,
also Henrietta Woodward, James R. Greeves and E. G. Taber.

An affecting circumstance took place early in this week.
John Bacon, son of John, (of Bacon`'s neck,) near Greenwich, N. J.,
was going on a visit to a relation at Plymouth;
as he was passing near a limestone quarry,
on his way from the railroad depot to his destination,
at the moment the workmen were blasting a rock, a fragment of it struck him on the head.
He was much injured, has been insensible up to the last account we have heard,
and he is not expected to recover.
It will be a great affliction to his parents and to the family.

Sarah Emlen to Thomas Kite.

Exeter, Eng+++.+++, Twelfth month 1st, 1844.

My Beloved Friend:--Your very acceptable letter reached me at Bristol,
the 12th of last month, just four weeks from its date.
While I sympathize with you in the privation of so valued and worthy a child,
nevertheless, I do believe, that on her account, we may rejoice.
I can readily conceive the pangs it must have cost her natural
affections to be severed from her nearest earthly ties.
The struggle must have been great.
But oh! what a mercy to experience the work of
redemption and sanctification to be accomplished,
so that she could calmly and resignedly look on death,
waiting "`all the days of her appointed time,`" till He
should come who rides upon the wings of the wind,
to bear her precious spirit through the dark valley to the
mansions of eternal light and never-ending blessedness.
Doubtless,
she is now numbered with that innumerable company who
stand before the throne of God and of the Lamb,
where his servants shall serve Him and see his face;
and his name is upon their foreheads.

"`There shall be no night there, and they need no candle, neither light of the sun;
for the Lord God gives them light, and they shall reign forever and ever.`"
I feel her loss, both in the Church and as a neighbour to my child,
who felt her as a sister.
When you go into the neighbourhood, please give my dear love to Aaron,
and tell him I often think of him; and do try to spare a few moments for poor C. and M.,
and remember them for good.
They, doubtless, have heard the voice of the blessed Shepherd,
and oh! that they could be persuaded to follow Him.
Nothing in this life could so rejoice my heart,
as to see my precious offspring meekly and sweetly bending to the yoke of Christ.
I am sometimes ready to cry out:
what more shall I do for my children than to bear them
with my tears upon my heart before the throne of Grace?
They are naturally amiable and lovely; but I long to see them newly-born babes in Christ,
and not ashamed or afraid to confess Him before men.
Your account of my dear James, and of the children waiting on their friends,
with cheerfulness and alacrity, during committee time, was pleasant.
It is now more than five weeks since I was favoured to
accomplish my mission through Ireland,
and came over to Liverpool, with my little sheaf, but without daring to set it up,
because I still felt the sentence of death.
While I was waiting to see what might, in the ordering of a kind Providence, turn up,
in the way of a companion, Dugan and Asenath Clark, very unexpectedly and unthought of,
came.
I remembered Naomi and Ruth.
Indeed, we all wept.

While Asenath and I were more weak, being privileged,
Dugan turned his back to hide his tears.
Ah, indeed, it is sweet, when we are strangers in a strange land,
to meet with our dear countrymen and women.
Now it seemed that help had been sent,
and that it might be right for me to be banded with them.
After comparing our feelings and prospects,
we thought it best to consult the Select members of Liverpool Meeting,
about the propriety of such a move; and they uniting with it,
and giving us as much encouragement as we could ask, we set out on the railway,
the 16th of Tenth month, for Colebrookdale,
and reached the house of Bernard Dickinson that evening,
a distance of one hundred and twenty miles.
We had an appointed meeting the next evening, which was large and very quiet,
and favoured, I thought, with a little of the precious ointment.
We then set out for South Wales;
had a long journey over the "`barren mountains
and desolate hills,`" and saw plenty of heath.
How justly, I thought, might those who put their trust in the arm of flesh,
be compared to this dry heath, that knows not when good comes.

The mountains of Wales are quite a curiosity to the eye of an American.
Not a tree nor a shrub to be seen;
all look as clean as though they had been mown with a scythe.
A few cows here and there, and some sheep, were all that we saw grazing on them,
for hundreds of acres.
The road over the great hills was excellent.
To us who had been accustomed to much more uneven ways, it was a subject of inquiry,
why they hooked on another pair of horses?
We wondered at being told,
"`to drag you up the hills,`" when we thought the road was so fine.
We visited the few scattered ones of the tribes in that country, Pales and Hay,
and so on to Neath, in Glamorganshire.
From there we had a long two days`' journey to Milford, on the sea,
where are but two or three members of our Society.
We felt well rewarded for our journey,
and thought a little Benjamin was there,--a seed of the living faith,
that seemed crying for help.
Our public meetings were large and favoured, and the poor people,
or the "`common people,`" did appear to rejoice as the
dry and thirsty ground rejoices at the sound of rain.
Many of them could understand but very little English, and others that could, would ask,
"`Won`'t you come again?`"
and "`You must come again.`"
When they were reminded that if they had received any good,
they must give the honour and praise to the great Head of the Church,
and not to his poor servants, they with tears and sobs would exclaim, "`Yes!
Yes!
Yes!`" and it was really affecting and humbling to see them crowding round our carriage.
Dugan said, "`Well, I never saw the like.`"
