== Chapter XXII.

1844-1845.

Letters--Thomas Kite`'s last journey--Deborah Welsh--Thomas Kite`'s illness and death.

Thomas Kite to his daughter Rebecca.

Twelfth month 3rd.

Last Seventh-day my mind seemed to be turned towards Frankford,
and accordingly I went there in the evening stage.
'`In the morning I rode to meeting,
which was thought to be about as large as it commonly is, notwithstanding the rain.
Within a few months I had been twice before at this meeting,
and each time silent as to ministerial labour;
but now my way was open to communicate more largely than is common with me.
I took tea at home and went to the evening meeting,
where I heard the same passage of Scripture
commented on that I had spoken of in the morning,
namely,
that wherein we are told that Paul before Felix reasoned concerning righteousness,
temperance, and judgment to come.

Thomas Kite attended Haddonfield Monthly Meeting,
Chester Monthly and Haddonfield Quarterly Meetings, held on the 9th, 10th,
11th and 12th of the month.
The Quarterly Meeting was held at Moorestown.
In the meeting for worship, on Fifth-day, he was favoured in solemn supplication.

In this little town he had an opportunity of visiting some of his relations,
and many friends in the neighbourhood of Haddonfield, Moorestown and Westfield,
who little thought that this was the last time they should see their
much loved brother in the faith and patience of Jesus Christ.

Thomas Kite to his daughter Rebecca.

Twelfth month 16th.

We hear that your young friend, Mary Moore, has terminated her course on earth;
we know not many particulars,
but have been informed that she was married only about a month before her close.
She had been long engaged,
and it was thought desirable that the marriage should take effect,
although at the time it was expected she could not long survive.
I think her husband was a student of medicine.
'`Our friend, Mary Wistar, departed this life during last night.
She was yesterday about as well as she had been of late,
but seemed somewhat restless at going to bed.
About one she was taken ill, and soon expired.
'`Continue carefully to attend to the preservation of your health, but, above all,
of your peace of mind.
This last can only be experienced by watching unto prayer,
and yielding obedience to the restraining influence of Divine grace,
as well as the clear presentations of duty.

At the evening meeting on First-day, Twelfth month 22nd,
Thomas Kite was opened in the ministry with living authority,
and in an impressive manner.
His text was: "`There was silence in heaven for the space of half an hour.`"
In connection with this, he quoted the passage, "`The Lord is in his holy temple,
let all the earth keep silence before Him.`"
In the course of his communication,
he said that "`Although a living Gospel ministry was a great blessing to the Church,
yet to know the Lord to be in his holy temple, and keeping silence before him,
was worship.`"

The religiously-guarded education of the children of Friends,
had long been a subject of deep interest to the Yearly Meeting of Philadelphia.
It had in 1845 appointed a Committee on Education,
and of that committee Thomas Kite was an interested and working member.
Being with several others appointed by the committee to
visit Friends in Cain Quarterly Meeting,
in order to stir them up to greater carefulness in the
proper education and training of the children,
he left home on Seventh-day, the 4th of First month, 1845, to fulfil that duty.

On First-day, the 5th, he was at the morning meeting at West Chester.
On the Fourth-day of the previous week, S. C. had attended Birmingham Monthly Meeting,
held in that borough, and had been opened on the text, "`Quench not the Spirit,
despise not prophesying.
Prove all things; hold fast that which is good.
Abstain from all appearance of evil.
And the very God of peace sanctify you wholly: and I pray God your whole spirit,
and soul and body, be preserved blameless unto the coming of our Lord Jesus Christ.
Faithful is He that calls you, who also will do it.`"
After speaking in a very interesting manner on
these beautiful exhortations of the apostle, S. seemed rather abruptly to conclude.

Thomas Kite`'s daughter, Rebecca, in writing to her father before the close of the week,
mentioned this communication; but when about to tell the text,
she desisted from a sudden impression that it would not be best.
On First-day, Thomas Kite was led largely to comment on the same passage,
not '`knowing until afterwards, of the coincidence.
His nephew, Joseph Walton, Jr., after the meeting, took him to Westtown, where,
in the afternoon,
he was again clothed with Gospel power to preach glad tidings to those assembled.
He commented with great sweetness on the blessings
pronounced by our Saviour when on the Mount,
and closed his communication with an earnest query to some present,
whether their days`' work was keeping pace with the day.

That evening he suffered much from pain in the head, which he supposed was neuralgia,
yet he was cheerful and pleasant in conversation.
On Second-day morning the 6th, he went to his son-in-law, Aaron Sharpless`'s,
who was to accompany him to the meetings of Cain, being also a member of the committee.
That afternoon they rode to the house of Isaac Phillips, at Sadsbury,
where they met William Hodgson, Jr., under like appointment with them.
At that hospitable house Thomas Kite felt at ease, and seemed to enjoy being there.
In the evening, solemn silence covered the little company,
and he was again drawn forth in testimony, particularly addressing the daughter.
That night was a stormy one, and snow fell to the depth of several inches.
The next day (7th of the month), they were at Sadsbury Monthly Meeting,
and in the Meeting for Worship he was engaged for some time in testimony.
At the close of the meeting for business,
the committee had an opportunity of unfolding to a number of
the members of that meeting nominated to hear them,
the nature of the concern of the Yearly Meeting
and the best way of cooperating therewith,
In this conference Thomas Kite manifested the warm interest he took in the subject.

The committee dined with Joseph Cooper,
and then came to the dwelling of William Forsythe, near Cain Meetinghouse,
where Bradford Monthly Meeting was to be held that day.
The pain in Thomas Kite`'s face continued,
and this evening seemed so about one of his teeth,
as to induce him to attribute it to some defect in that organ.
At Bradford Monthly Meeting, he was again largely engaged in a living, baptizing ministry.
At the close of the meeting a conference was held with some of the members,
similar to the one at Sadsbury, and suitable counsel and advice was given them.

After dining with Davis Hoopes, the committee took Ann E., the wife of Jacob Edge,
into their carriage and went into Downingtown to visit E. Valentine, her mother.
They sat down with the pious mother and her daughters,
and the current of Gospel love sweetly flowed amongst them.
Thomas Kite was enabled with strength and authority to hold forth the
language of encouragement to the ancient Friend to hold on her way,
and an invitation as well as encouragement was extended to the daughters.
It was a heart-tendering opportunity, in which the little company were melted to tears,
and proved to the visitor as well as the visited, a brook by the way.
Lodging that night at W. Trimble`'s,
in the morning he called to see William Harry and family,
not far from Uwchlan Meeting-house.
Fifth-day the 9th, they attended Uwchlan Monthly Meeting,
where Thomas Kite was much enlarged, and spoke with more than usual force and authority.

After the second meeting, and the administering advice on education,
the committee went to the house of Mary Butler, where they dined.
Immediately after this meal, they started for Robeson,
having a son of their late kind entertainer for guide.
The road was difficult and rough and the pilot not acquainted with it;
so that it was after night before they reached the house of James Scarlet.
The pain in Thomas Kite`'s face still continued,
and it was probably increased by the exposure to which he was necessarily subjected.
The next day was Robeson Monthly Meeting, which was a small gathering,
but five women present.
Although there were rather more men,
yet several of them had not the appearance of Friends.
One of the committee thus described the meeting:
"`I was prepared to believe the outward appearance was
a fair representation of the hearts of those assembled,
and the thought passed through my mind, '`what can be said here, all seems so dead?
While such thoughts +++[+++engaged]
my mind, Thomas Kite rose to his feet,
and was largely and powerfully engaged in testimony,
so that at the conclusion I could acknowledge that he
had been strengthened like the good scribe,
to bring forth out of the treasury things new and old.`"

After dining with James Scarlet, the Friends returned to Mary Butler`'s to lodge,
where on the following morning, Seventh-day the 11th, they had a religious opportunity.
In this, Thomas Kite was much drawn to a little grand-daughter of their hostess,
and also to her youngest son, who was about being placed out as an apprentice.
At the railroad the Friends parted, Thomas Kite and W. H., Jr.,
returned by that route to Philadelphia, while A. S. proceeded home in his carriage.

Of this journey Aaron Sharpless says:
"`I have often looked back upon this little journey with satisfaction;
and the impression on my mind relative to dear father`'s services is,
that he was peculiarly favoured, and that his gift shone with unusual brilliancy.
Perhaps having recently partaken of the cup of affliction,
my heart was a little softened, and therefore more susceptible of feeling.`"

When Thomas Kite reached his own dwelling he was much unwell,
the pains in his face continued, and he seemed somewhat worn and wearied;
yet the next day he attended the three meetings held in the Arch Street House.
On Second and Third-days he paid several visits,
in some of which he was engaged in the ministry.
In one of these visits he spoke of his last journey, and said that while engaged in it,
much service and exercise had fallen to his lot,
and this not merely in relation to the matter on which he had been appointed.
He said that in most of the families and meetings the
committee had visited he had had religious service.
He added, it felt trying to him to be so frequently engaged in the line of the ministry,
but he could see no way, except in yielding himself to Divine requiring.
"`And now,`" he added, "`I have come home poor, and stripped, and empty.`"
He expressed this with great seriousness and deep feeling.

After a time he said with solemnity, that his mind had recurred to what the apostle says,
"`Let a man so account of us as the ministers of Christ,
and stewards of the mysteries of God.
Moreover it is required in stewards, that a man be found faithful,`" and also,
"`As every man has received the gift,
even so minister the same one to another as good stewards of the manifold grace of God.
'`If any man speak, let him speak as the oracles of God.
If any man minister let him do it as of the ability which God gives:
that God in all things may be glorified through Jesus Christ,
to whom be praise and dominion forever and ever.`"
He then expressed his belief that it was necessary for
all who were called to that great work,
deeply and seriously to consider the important meaning of these passages.

On Third-day he called to see Deborah Welsh, a poor cripple,
who for many years had suffered much acute pain,
and who for some time had been entirely confined to her bed.^
footnote:[Deborah Welsh was naturally of a docile and amiable disposition;
and having very early in life submitted to the heart-tendering
and heart-changing influences of her heavenly Father`'s love,
she was enabled to enter into covenant with Him, and through his blessed power,
she was supported through a life of great and varied suffering,
in a remarkable degree of patient, and even cheerful resignation,
to the end of her days.
{footnote-paragraph-split}
Her parents were Methodists,
and when quite a child, she also joined that Society.
So far as could be perceived by those around her, her mind was kept so steadfast,
as to be preserved from delighting in the vanities and allurements of the world.
Her very recreations in childhood seemed in good degree seasoned with salt.
At a very early age,
it was her desire--repeatedly expressed to her mother--that
her clothing should not be made after the tasty fashion,
nor of such gay material as her sisters and companions wore,
saying it was painful to her to wear such.
She was also known frequently to expostulate with her fellow-members,
much older than herself,
because of the inconsistency of their appearance with the profession
they made of being the followers of the meek and lowly Jesus.
This concern never left her,
and she endeavoured to be found faithful to her duty therein,
pleading for that simplicity and sobriety in dress and
deportment which becomes the followers of Christ.
After the fifteenth year of her life,
she never knew a day`'s exemption from bodily suffering;
and she was very often incapable of any active exertion.
{footnote-paragraph-split}
During the intervals between the paroxysms of acute pain,
she was ever busy, doing what she could towards maintaining herself;
her father being by rheumatism very much disabled from
labouring for the support of his family.
After her thirtieth year, she was entirely confined to her bed, on which,
for nine years afterwards, she endured sufferings which may safely be called agonizing.
During this period she never once stood upon her feet;
and during much of the time she was unable to use her needle or her pen,
two employments much prized by her,
and which had yielded her much pleasure.
{footnote-paragraph-split}
About twelve years before her death,
her mind began to turn towards Friends,
and she was evidently pleased with the visits of
such members of our Society as called upon her.
It is believed that their peculiar doctrines at that
time formed no part of her conversation with them,
yet she was evidently drawing nearer them in feeling;
and she afterwards spoke of the satisfaction she had
experienced in silent communion of spirit with some of them.
As she patiently abode under the operation of that Word of prophecy,
which was leading her in a way she had not fully known,
she in time felt a freedom to inquire concerning the doctrines
and Christian practices of Friends.
{footnote-paragraph-split}
She read "`Barclay`'s Apology,`" and found that,
with two or three exceptions,
she had herself been brought into the same views which she found there so ably advocated.
Those points in which she did not as yet see with Friends,
she did not make subjects of discussion, but quietly pondered them in her heart until,
in the Lord`'s time, she was enabled fully to unite with them.
She now believed it right to sever the connection which had
long subsisted between the Methodist Society and herself,
and, therefore,
applied for a certificate of dismissal from the congregation of which she was a member.
This certificate was granted her,
yet not before her loving classmates had earnestly laboured to
persuade her to continue her connection with them.
Her mind was now turned towards a union in membership with the Society of Friends.
She prepared an application to them,
but it was never carried to the Monthly Meeting of the Society,
on the ground that there was no human probability that
she would ever be able to meet with them.
This was a great trial to her, but supported by the presence of the Lord Jesus Christ,
and a consciousness of having endeavoured to act in his fear, and according to his will,
she endeavoured to bear all her portion of affliction without
repining.
{footnote-paragraph-split}
She lived several years after this,
cheered by the sympathy of a few valued friends,
who watched over her with tenderness and care, seeking to administer, as they were able,
to her comfort and support.
{footnote-paragraph-split}
Thus
sustained by the Master,--consoled by his disciples,
she patiently completed her measure of suffering;
and on the twenty-first day of the Fifth month, 1850,
she was released from her earthly afflictions.
{footnote-paragraph-split}
She was in the fortieth year of her age.
Twenty-five long years had been passed in bodily agony; but what mattered it then?
The rest which remains for the people of God, opened before her,
and an eternity of blessedness.]

After sitting by her in silence awhile, he addressed her in nearly the following words:
"`The very hairs of your head are all numbered.
I am well assured that nothing will be permitted to assail you,
but what is intended for your good.
I have at all times felt a tender regard for, and sympathy with you,
during your long affliction.
Recently I have felt more peculiarly so,
believing that you have considered your bodily infirmities of little account,
or as nothing in comparison to the mental, yes spiritual anguish, which you have endured.
Do not think there is anything strange in the fiery trial which is now proving you.
Our dear Lord and Saviour permits it all for your refinement.
Rejoice then, inasmuch as you are thus made a partaker of his sufferings,
that when his glory shall be revealed,
you also may be a partaker with Him in joy unspeakable.

Although that He requires of you may be as dear to you as your right eye, pluck it out;
or as your right hand, cut it off;
so that you may be able to say from the very bottom of your heart, '`Not my will,
but yours, be done.`'
If you are faithful and obedient to your Master`'s requisitions,
you will finally be found among those which have come out of great tribulation,
and have washed their robes and made them white in the blood of the Lamb;
therefore are they before the throne of God, and serve him day and night in his temple;
and He that sits On the throne shall dwell among them.
They shall hunger no more, neither thirst any more; neither shall the sun light on them,
nor any heat; for the Lamb, which is in the midst of the throne, shall feed them,
and lead them unto living fountains of waters,
and God shall wipe away all tears from their eyes.`"

On this afternoon he attended the Select School Committee for the last time.
On Fourth-day it was evident that the disease had made great progress,
and he was not out of his chamber that day.
By the next morning his upper lip was much enlarged,
and the disease about the head had put on an erysipelatous form;
some fever and violent suffering attended.

The symptoms after this grew more and more discouraging; the pain continued in the head;
and by First-day evening the swelled cheek opened and
began to discharge pus in small quantities.
During this day he asked his sister M.,
if she thought this sickness was to be the winding up of all things with him?
adding, "`It is hidden from me.`"
She replied, "`We hope to retain you many years with us.`"
On this he said, "`Jesse Kersey was very ill when he was about fifty years of age,
and if he had died then, it might have been said of him, as it was of Samuel,
"`All Israel mourned for him.`"
"`We would rather part with you,`" said his sister,--"`than I
should live to dishonour the Truth,`" he added,
finishing her intended remark.

On Second-day, the 20th,
when his brother N. returned from their Preparative Meeting of Ministers and Elders,
he inquired about the meeting,
evincing his continued interest in everything
which concerned the religious Society of Friends.
That evening his brother John, who was his physician,
wishing to have a consultation respecting him, brought Dr. Charles Evans to see him.
On Third-day, the 21st, he said to his sister M., "`We have been a favoured family,
and are all living except one sister, Sarah, and she died in innocency.
Our dear parents, we believe, were prepared to go, and my Elizabeth,
and Joshua and Susanna.`"

On Fourth-day, the 22nd, addressing the same sister, he said,
'`This is not a time for much conversation, but I have many thoughts on my sick bed.
I love to have you sit by me,
and have remembered the language of Thomas Scattergood to George Dillwyn,
"`that when they were boys, and went in to swim, and were under deep waters,
they could feel each other when they could not speak.`"
After a time, he said, "`Light is sweet; and a pleasant thing is it to behold the sun.`"
When Richard Jordan was on his deathbed, he said,
he "`had lived through one storm in the Society, and if it was his Master`'s will,
he was willing to live through another.`"

Although it was evident that he did not clearly
see that his sickness was to close his life,
yet he was very anxious that all his temporal concerns should be settled;
and was uneasy till his brother had attended to a trifling matter,
which would leave everything in comfortable order.
For months before the time, he had been engaged in closing unsettled accounts;
he had made a new will, and so arranged his affairs, that there were no debts to pay,
and no difficulties of any kind to trouble his executors.
He felt no evidence that he should die at this time,
but he had no assurance that he should recover; and feeling the possibility,
if not probability, of his decease, he said to his wife,
"`If this should prove my last sickness, I wish to be buried in a plain walnut coffin,
and laid in the Arch street ground.`"

As he lay patiently suffering, many sweet passages of Scripture passed through his mind,
and furnished him with subjects for thought.
At times he would repeat a text.
One morning he broke out with a clear voice,
as if he was deeply entering into the spirit of the passage, "`We are yours, David,
and on your side, you son of Jesse.`"

The disease had now in measure left his head, and had seated itself in one lung;
and on Seventh-day morning, the 25th, he was much oppressed in breathing.
His niece, Mary H. Walton came that morning to see him, and as she sat by his side,
his lips were opened to minister encouragement and counsel to her.
In this communication he pressed on her the necessity
of walking "`in the old-fashioned way of the cross.`"

Soon afterwards E. C. M. and R. S. came in.
They sat by his side in silence for a time, and then he said,
"`Notwithstanding there are many deep baptisms and trials to be endured,
in order that the work of cleansing may be thoroughly wrought in us,
yet it is a consolation to believe,
that there are some who are bound together in the covenant of love and life,--who
are made willing to suffer with Christ,--to be made conformable to his death,
that they may be partakers of his resurrection.`"
"`Friends, I have but little to express, for I am very weak.`"

When the friends retired, the doctor came in, and taking the patient by the hand,
immediately perceived by the fluttering pulse,
that the hour of death was fast approaching.
Of this he informed the family, and William, who was an invalid, was sent for.
About noon, his son-in-law, A. S., came,
and was received by him in a warmly affectionate manner.

It was thought best to inform him that his friends deemed his close near;
and his brother, the physician, said, taking him by the hand, "`Dear brother,
do you know that your labour is nearly over, and that you are going home?`"
He replied, "`Not certainly.`"
The doctor added, "`It has been in mercy hid from you; but it is plain to us.`"
He paused a moment, and then said with remarkable composure, "`Well.`"
After a short time he inquired, "`How long will I probably continue?`"
He was informed that it was uncertain, but that it could not be long.

His wife said, "`We all know it will be a blessed change to you,
for you have been diligently and faithfully engaged in your Master`'s service.`"
To this he replied with emphasis, "`Don`'t place it on that ground.
It is not by works of righteousness that we have done,
but according to his mercy He saves us,
by the washing of regeneration and the renewing of the Holy Spirit,
which is shed on us abundantly through Jesus Christ our Saviour.
I have no confidence in any outward performance whatever;
but now at the final conclusion and winding up of my life, I wish for myself,
and for all of us, that we may place our whole confidence in the mercy of God,
and thus be prepared for an admittance within the pearl gates,
there to join the blessed company, whom no man can number.`"
During the course of the afternoon, he many times repeated the text,
"`Not by works of righteousness which we have done,`" adding each time a few comments.
Several times he quoted the saying of a worthy minister, Samuel Emlen,
"`The soul is a serious thing; mind, you that hear me, it is a serious thing to die.
The invisible world,--how awful!`"

At one time, after a period of solemn silence, he said,
with reverent acquiescence to the Divine will,
"`The working out our soul`'s salvation is an important work.
If it should please my heavenly Father to take me within a few hours,
his blessed and holy will be done.`"

He inquired who were in the room.
On being informed that his wife and children, with the exception of one,
and that his brothers and sisters, with some of their children, were there,
he said that it was a great satisfaction to him to have them around him.

From time to time, as he lay growing weaker and weaker,
he gave utterance to the exercise and thoughts of his heart.
"`What a blessing, at the end and winding up of all things,
to feel an evidence of the sustaining presence round about.
It is an unspeakable favour to know our sins to go beforehand to judgment.`"

After a time of silence, he called John L. Smith to his side, and said,
"`Tell Rachel R. Sheppard that I am probably dying, or near it,
and if she inclines to come, she may.`"

This friend accordingly came; at first he seemed to take but little notice,
but after a time, gazing earnestly at her, he said, "`I have not much to communicate,
and particularly to you, dear R., because the work is going on,
and that is the greatest of all concerns.`"
He then raised his voice, and with great solemnity, added,
"`It is of great importance,--of the highest importance,
--to be altogether given up to the will of the Lord;
altogether given up.
I desire not to draw your attention, or fix my own on anything outward.
May we live in the fear of the Lord, and then He will give us his favour.
I have remembered the language of one, upon a similar occasion,
'`It is a serious thing to die;
the invisible world,--how awful!`' I wish to be preserved in
this feeling to the very last,--to the close of all things.`"

R+++.+++ Allen and her daughter Elizabeth came into the room.
He said to the mother, "`It is probable I shall not see the light of another day.`"
When they were retiring, he addressed the daughter,
"`Keep fast hold of the arm of your dear Saviour.
It matters not what are the trials and sufferings we meet with in this life,
if they are but sanctified, they will prepare us for a crown of righteousness.`"

The dear sufferer now said, "`I expect Samuel Settle would wish to see me once more.`"
Some one at this went for S., who immediately came.
The only words he addressed to the visitor were these, "`This is a serious moment,
Samuel.`"
The doctor inquired, "`Don`'t you feel very composed?`"
He replied, "`I feel quiet; very composed, is a strong term.`"
"`I wish to encourage the fainthearted among you; those that are fearing and trembling,
and feel themselves of no account.
The Lord`'s power is sufficient.
Oh, trust in the Lord, and don`'t be afraid.
We must all give an account of ourselves for ourselves.`"

Frequently alluding to his temporal, as well as spiritual affairs, he said,
"`they were all settled.`"

The weakness of death now came on him,
and he lay during the evening supported by two of his brothers,
in apparent unconsciousness of the things around.
A few words escaped his lips, which seemed to be,
"`Spiritual rest,`"--"`Going to the heavenly Jerusalem.`"
Soon afterwards, with no apparent pain, or bodily struggle,
the immortal spirit was released from its corruptible companion.

Many bereaved ones were there; yet in the holy quiet which covered those assembled,
and in the inward assurance of the holy translation which the husband, the brother,
the father, the uncle had experienced, a degree of resignation was felt,
and a desire to acquiesce in the Divine will, was experienced.
